Remove blog and Launchpad translation subpages
ethereum/ethereum-org-website pull request #10069
Opened 2023-04-25 18:09 UTC by lukassim

## Description

Remove Blog translations and Launchpad translations subpages from the Translation Program page
Remove What we're working on section from the Translation Program page

## Related Issue

No related issue

2023-04-25 18:15 UTC, nhsz requested changes
Thanks! We should also remove the links to the removed pages to avoid having dead links

2023-04-25 18:15 UTC, nhsz commented on src/content/contributing/translation-program/index.md
we should also remove all the links to `/contributing/translation-program/`

2023-04-25 18:15 UTC, nhsz commented on src/content/contributing/translation-program/launchpad-translations/index.md
we should also remove all the links to `/contributing/translation-program/launchpad-translations/`

2023-04-25 18:18 UTC, lukassim commented
> Thanks! We should also remove the links to the removed pages to avoid having dead links

For sure, thanks for raising this.
The links to these subpages from the main Translation Program page have been removed, and as far as I can see, we only link out to them on the content buckets page, which needs to be updated, and the translated versions of the Translation Program page.

Anywhere else we should remove these links from?

2023-04-26 14:52 UTC, nhsz approved these changes
LGTM

2023-04-26 14:52 UTC, merged