Add EnvWarningBanner PoC
ethereum/ethereum-org-website pull request #10127
Opened 2023-05-04 13:31 UTC by minimalsm

## Description

Proposing we remove individual warnings about `.env` safety in Tutorial files with a reusable component.

**Why?**

1. Reduces duplicate work for translators
2. More maintainable (allows us to refine component/message to increase effectiveness)
3. Can be dropped anywhere we're telling people to use `.env` files, increasing developer safety
4. Allows us to remove many HTML tags (`<code>` and `<a>` tags) across our tutorial markdown pages, improving maintenance during Crowdin import process

The current banner is used in many places, but really should be in more places to avoid people getting by poor env hygiene:

<img width="1168" alt="Screenshot 2023-05-04 at 14 30 29" src="https://user-images.githubusercontent.com/62268199/236219931-36f462d1-e8de-4304-83de-b5990e748ab1.png">

## Related Issue

#10126

2023-05-04 21:56 UTC, pettinarip requested changes
Hey @minimalsm I think this change makes total sense but the only _big_ downside I see is in adding more text (translations) in the intl JSON files.

I'm a bit worried about the impact in memory usage on build time.

What we have been trying to encourage recently is the opposite of this PR: to set translations in md files as much as we can, and leave translations in the JSON files just for the global components.

I'd love to explore more these types of abstractions in the future but I see the previous reason as a hard blocker.

LMK what do you think.

2023-05-08 17:11 UTC, pettinarip approved these changes

2023-05-09 15:04 UTC, nhsz requested changes
Thanks @minimalsm! Asking for a few changes

2023-05-09 15:52 UTC, minimalsm commented on src/components/EnvWarningBanner.tsx
> +export interface IProps extends FlexProps {}
Done, thanks.

2023-05-09 15:57 UTC, minimalsm commented on src/intl/en/page-developers-tutorials.json
> +  "page-tutorials-env-banner": "Don't commit <code>.env</code>! Please make sure never to share or expose your <code>.env</code> file with anyone, as you are compromising your secrets in doing so. If
I think we might get this automatically from our Link component @nhsz 🤔 

[In our templates, we use MDXProvider](https://github.com/ethereum/ethereum-org-website/blob/25ef0f8e8a1eb6a145114e30c74748a73a9e660d/src/templates/static.tsx#L171) to override the default the rendering of HTML elements.

In our Link, [we parse the href to determine if a link is internal/external](https://github.com/ethereum/ethereum-org-website/blob/25ef0f8e8a1eb6a145114e30c74748a73a9e660d/src/components/Link.tsx#L118).

Tested in dev, and looks like it is working as expected without the additional properties.

2023-05-09 16:28 UTC, merged