fix(orderedlist): list points in layer2 page
ethereum/ethereum-org-website pull request #10158
Opened 2023-05-09 16:15 UTC by SimardeepSingh1450

## Description
Made the points fit in center of the circle and fixed the oval shape to circular shape.

Earlier the numbers in points were not in center of the circle and circle was not in proper circle shape, it was in oval shape, fixed both of these problems.

## Related Issue
Bug report: L2 numbered list doesnt have aligned numbers: #9974

2023-05-09 23:34 UTC, nhsz requested changes
Hey @SimardeepSingh1450, thanks for the contribution! I left some suggestions to adjust some values to align the circles a bit better

2023-05-09 23:34 UTC, nhsz commented on src/components/OrderedList.tsx
> +  height: "1.5rem",
```suggestion
  height: "1.6rem",
```

2023-05-09 23:34 UTC, nhsz commented on src/components/OrderedList.tsx
> +  width: "32px",
```suggestion
  width: "34px",
```

2023-05-09 23:34 UTC, nhsz commented on src/components/OrderedList.tsx
> +  top: "-5px", // adjusts circle + number up and down
```suggestion
  top: "-3px", // adjusts circle + number up and down
```

2023-05-09 23:34 UTC, nhsz commented on src/components/OrderedList.tsx
> +  // aspectRatio: "1",
we should remove this property

2023-05-10 03:57 UTC, SimardeepSingh1450 commented
@nhsz thanks for the suggestions, I have commited them in the pr, please review and merge.

2023-05-10 13:39 UTC, nhsz approved these changes
Thanks @SimardeepSingh1450, LGTM!

2023-05-10 13:40 UTC, merged