Updated info about GitPOAPs
ethereum/ethereum-org-website pull request #10329
Opened 2023-05-25 14:34 UTC by bskrksyp9

Added info on GitPOAP and it's procedure to claim. Source as per official discord server.

## Description

## Related Issue

2023-06-29 16:17 UTC, clauBv23 commented on src/content/contributing/index.md
> +3. Search for your GitHub username, ETH address, ENS names or any GitPOAP to check if you're eligibile.
```suggestion
3. Search for your GitHub username, ETH address, ENS names or any GitPOAP to check if you're eligible.
```

2023-06-29 17:27 UTC, bskrksyp9 commented on src/content/contributing/index.md
> +3. Search for your GitHub username, ETH address, ENS names or any GitPOAP to check if you're eligibile.
thanks for correction 👍🏼

2023-09-12 21:37 UTC, wackerow requested changes
Hey @bskrksyp9... I see two PRs for this, #10328 and this one... can you help clarify which you're looking to use by closing the other? Assuming you wanted to go with this one since it came after and has more details.

Few notes on this one, I would put the information about GitPOAP after our note about "If your contribution gets merged...", and also we'll need to clean up the `{}` usage... would use bolded text or headers as needed.

2023-09-13 01:00 UTC, bskrksyp9 commented
Hello @wackerow !

Yes you could modify the info as you mentioned, but the 2 PRs are different, though the change in content is same

One appears on Contributing page of site, where the other is from the github Readme Page

2023-09-21 21:12 UTC, wackerow approved these changes
@bskrksyp9 Just pushed a patch to this... shifted it below our standard POAP explainer, removed what looked like an unfinished note about tiered POAPs which we should leave off. Bringing it in, thanks!

2023-09-21 21:13 UTC, merged