Added hover animations for nav icons
ethereum/ethereum-org-website pull request #10811
Opened 2023-07-28 16:20 UTC by rohan9024

## Description

I have used basic chakra ui hover animations

Here is the video of it-->

https://github.com/ethereum/ethereum-org-website/assets/64919642/0bd326d6-bd31-4795-a94c-c2c826d99aa6

This was the issue--> #10478

2023-07-31 21:12 UTC, corwintines commented
@nloureiro would like some input from you here. 

I know we initially wanted `language` to be there to make the button more explicit for users, so I do think that needs to be added back in. 

I'm not the biggest fan of the little rotation on the color mode. Don't think it fits much of whats on the site. But the hover effect making it larger seems fine to me. 

@rohan9024 I would also scope this outside of the homepage as this is specific to the nav. Open to other ideas you have for the homepage, but we have not spent time on redesigning the home page at the moment.

2023-08-01 16:03 UTC, rohan9024 commented
@corwintines removed the rotation animation. Are there any more changes to be made?

2023-08-03 19:16 UTC, nhsz commented
I'd push against using Framer for simple animations as it adds unnecesary complexity and JS code to the bundle we're aiming to reduce, otherwise we'll start to bloat the site. We could use CSS instead. @konopkja @corwintines @pettinarip

2023-08-04 06:53 UTC, pettinarip commented
> I'd push against using Framer for simple animations as it adds unnecesary complexity and JS code to the bundle we're aiming to reduce, otherwise we'll start to bloat the site. We could use CSS instead. @konopkja @corwintines @pettinarip

Agree. However, he is not using framer motion for these animations. Probably you were confused because there is an import of `motion` but is not being used xD

2023-08-04 06:56 UTC, konopkja commented
> @corwintines removed the rotation animation. Are there any more changes to be made?

so how does it look now with that change? can i see?

2023-08-04 07:09 UTC, pettinarip commented
> > @corwintines removed the rotation animation. Are there any more changes to be made?
> 
> so how does it look now with that change? can i see?

@konopkja you can access the preview deploy [here](https://ethereumorgwebsitedev01-rohan9024ethereumorgwebsitedev.gatsbyjs.io/en/) or by clicking in [this auto-generated comment](https://github.com/ethereum/ethereum-org-website/pull/10811#issuecomment-1656019336) by the GatsbyCloud bot
![image](https://github.com/ethereum/ethereum-org-website/assets/468158/16e9bfdf-88ef-410f-b9fc-5d7cfbcc06ab)

2023-08-04 08:11 UTC, konopkja commented
> * Deploy preview

Yes the language should be added back in, languages are important part of our website.

I am actually personally for the spin as its more visible and is more engaging (which is something in small doses we want to add to the website). But lets see what other think and also ping @nloureiro 

Already better than nothing as we have now.

2023-08-04 11:23 UTC, rohan9024 commented
@konopkja Thank you Jakub!!! Finally someone gets me🥰 I'll add the languages text back👍

2023-08-04 11:24 UTC, rohan9024 commented
> > I'd push against using Framer for simple animations as it adds unnecesary complexity and JS code to the bundle we're aiming to reduce, otherwise we'll start to bloat the site. We could use CSS instead. @konopkja @corwintines @pettinarip
> 
> Agree. However, he is not using framer motion for these animations. Probably you were confused because there is an import of `motion` but is not being used xD

Oops, sorry for that😂.  I'll remove that.....

2023-08-04 13:22 UTC, nloureiro commented
Hey, @rohan9024 thank you for this.

There are various considerations on this PR, and from my stand, I think CSS it's the best way to go, if possible, for animations. Simpler and lighter for the browser.

I would add the text we have in production now and rotate 10º to the globe to be the same type of animation as the moon/sun.

The timing and speed look good to me.

Something like this.

https://github.com/ethereum/ethereum-org-website/assets/1120748/05da15b4-d4bc-44ad-97a6-2b10ff138845

2023-08-05 15:53 UTC, rohan9024 commented
@nloureiro have you made a commit or should I?

2023-08-14 18:52 UTC, corwintines commented on .env.example
This shouldn't be deleted

2023-08-14 18:52 UTC, corwintines commented on yarn.lock
I don't think this needs to be added, we can update packages in a separate PR

2023-08-14 18:52 UTC, corwintines commented on src/components/Nav/index.tsx
> +                size="md"
We shouldn't be changing the size here

2023-08-14 19:05 UTC, corwintines requested changes
Thanks @rohan9024 

The following bugs need to be addressed here
- [ ] Icon sizes should go back to original
- [ ] The gap between icons increased, this should be the same as before
- [ ] Add the .env.example file back
- [ ] The highlight of the language icon and text should be in sync

https://github.com/ethereum/ethereum-org-website/assets/15589226/ebc00f0b-b132-4709-8a97-eb52cbdc079d

- [ ] When highlighting the language text, it should also apply the rotation of the icon


https://github.com/ethereum/ethereum-org-website/assets/15589226/08934f43-7c6c-4315-9fb9-79b0a239fae7

2023-08-24 18:10 UTC, corwintines commented
@rohan9024 we merged some changes into dev for the Nav. You'll need to merge dev into your branch here to resolve conflicts.

2023-08-25 14:17 UTC, rohan9024 commented
@corwintines Sure, I'll merge it 👍

2023-08-26 08:12 UTC, closed without merging