fix image and link on /refi/ page
ethereum/ethereum-org-website pull request #10912
Opened 2023-08-11 03:04 UTC by corwintines

## Description

- Reduce size of image
- Change link to https://capitalinstitute.org/8-principles-regenerative-economy/ in intro paragraph

2023-08-11 08:25 UTC, nloureiro commented
Besides the fine-tuning of the image, should we add a caption to the image with credits? Where does this image come from?

@jmcook1186 probably, you can help on this one. 😀

2023-08-11 10:25 UTC, nloureiro commented
@corwintines I change the image to 450x450px, but on the dev preview it's not showing. Can you take a look?

2023-08-28 17:00 UTC, wackerow requested changes

2023-08-28 17:00 UTC, wackerow commented on src/assets/use-cases/refi-regenerative-economy-diagram.png
<img width="1121" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/c54ade67-56fc-4bc7-a61e-9f63f2f19a7e">

![image](https://github.com/ethereum/ethereum-org-website/assets/54227730/2f166331-e4f9-4c75-a4d9-d5752596ec68)


This has lost image quality when previewing, which may be related to pixel ratios. Do we need to downsize the image file or could we just put a max size on it when rendered?

2023-10-14 08:24 UTC, corwintines commented on src/assets/use-cases/refi-regenerative-economy-diagram.png
I think since this is done through markdown, we might need to have it be 450px if that is our goal dimensions. Ill see if I can do this without losing quality.

2023-10-14 15:42 UTC, corwintines commented
I pushed a better res version of the 450x450px image. I think this is ready.

2023-10-15 17:16 UTC, wackerow approved these changes

2023-10-15 17:17 UTC, merged