[DRAFT] Update readme
ethereum/ethereum-org-website pull request #11131
Opened 2023-09-12 00:50 UTC by corwintines

## Description

## Related Issue

2023-09-18 15:50 UTC, rohan9024 commented
Hey @corwintines ! Just noticed some extra spacing on this url --> https://ethereumorgwebsitedev01-readmeupdate.gatsbyjs.io/en/contributing/testing/#user-experience

![image](https://github.com/ethereum/ethereum-org-website/assets/64919642/bcfa5e11-1ce4-45e8-aabc-6c033506aa54)


1. Is there any image to be rendered which is not being rendering ? 
2. On this link--> https://ethereumorgwebsitedev01-readmeupdate.gatsbyjs.io/en/contributing/code/#1.-submit-an-issue
The links on the right side are not functional

For reference, 
https://github.com/ethereum/ethereum-org-website/assets/64919642/2424fc75-9c92-4456-a5ef-ea1041132701

_In the above video, I'm trying to click the links which should navigate me to that part._

3. Feature Request: We can link the open issues on the contributing.md itself or have a separate page for it. Additionally, in order to let the developers gain confidence, we can have simple good first issues. 

For reference: https://appwrite.io/community

4. Adding New "Require Guidance Issue Template" and also label: When I click on create new issue, there are several templates like this-->
![image](https://github.com/ethereum/ethereum-org-website/assets/64919642/2576efc8-9df5-4644-830b-c40d4466bdf7)

We can add require guidance which can be helpful for developers who require assistance. Assistance can be related to setting up the project , problems related to codebase, structure, etc.


Lastly, I would love to work on these issues. Feel free to assign me.
Have a Great Day!😊

2023-09-25 14:50 UTC, konopkja commented
![Screenshot 2023-09-25 at 19 48 51](https://github.com/ethereum/ethereum-org-website/assets/100724231/c024aa6e-e8f6-461f-a7f5-5df198890766)
can this just be a link to the folder in our GH repo?
https://github.com/ethereum/ethereum-org-website/tree/dev/src/content

2023-09-25 14:52 UTC, konopkja commented
![Screenshot 2023-09-25 at 19 52 30](https://github.com/ethereum/ethereum-org-website/assets/100724231/562ecfdd-1669-47b9-9095-6b1db761c33c)

@corwintines  this should have been simple bullet points, not a lengthy paragraph :P

2023-09-25 14:54 UTC, konopkja commented
![Screenshot 2023-09-25 at 19 53 45](https://github.com/ethereum/ethereum-org-website/assets/100724231/c8daa56d-df99-4962-a15a-1db6d30348f8)

this should be under the headline, not at the end

2023-09-25 15:07 UTC, konopkja commented on src/content/contributing/testing/index.md
> +On Tuesdays we create a release candidate that goes into the staging branch. Information about the release candidate will be posted in the `👾 ｜ website-code` channel in our [Discord](https://discord.
```suggestion
 in the GitHub repository. The release candidate will be tagged as a `pre-release` until it has been merged into master. After QA testing, we deploy the release candidate into production if there are no release blocking bugs found on Thursday. More info on the deploy process for ethereum.org can be found [here](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/deploy-process.md).

- **Every Tuesday** we create a release candidate that goes into the staging branch.
- Info about the release candidate is posted in the `👾 ｜ website-code` channel in our [Discord](https://discord.gg/ethereum-org). 
-  Find the release notes for the release candidate on the [releases page](https://github.com/ethereum/ethereum-org-website/releases)
- The release candidate will be tagged as a `pre-release`
- **On Thursday** the release candidate is published on production.
- More info on the deploy process for ethereum.org can be found [here](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/deploy-process.md).

```

2023-10-15 00:33 UTC, corwintines commented on src/content/contributing/testing/index.md
> +There are a number of ways to get involved with testing. We are looking for any content, design, or user experience bugs or regressions that may have been introduced in the release candidate.
A bit. We currently don't offer anything, but I would like to see this as something we do for 2024.

2024-02-13 20:47 UTC, wackerow commented
Just updated with latest from `dev`... Just noting this PR does _not_ address the removal of Gatsby information; this is handled in #12041

2024-02-13 20:52 UTC, wackerow requested changes
Nice, left a few comments and suggestions

2024-02-13 20:52 UTC, wackerow commented on src/content/contributing/testing/index.md
This file needs custom header IDs still

2024-02-13 20:52 UTC, wackerow commented on src/content/contributing/code/index.md
This file needs custom header IDs still

2024-02-13 20:52 UTC, wackerow commented on public/content/contributing/index.md
This file needs custom header IDs still (on new items)

2024-02-13 20:52 UTC, wackerow commented on src/content/contributing/content/index.md
Might just suggest adding the programming language to the code blocks here

2024-02-13 20:52 UTC, wackerow commented on README.md
> +We have a space to discuss all things ethereum.org – share your ideas or just say hi over [on Discord](https://discord.gg/CetY6Y4).
```suggestion
We have a space to discuss all things ethereum.org – share your ideas or just say hi over [on Discord](https://discord.gg/ethereum-org).
```

2024-02-13 20:52 UTC, wackerow commented on src/content/contributing/code/index.md
> +- Why not say hi and draw attention to your PR in [our discord server](https://discord.gg/CetY6Y4)?
```suggestion
- Why not say hi and draw attention to your PR in [our discord server](https://discord.gg/ethereum-org)?
```

2024-09-16 18:48 UTC, closed without merging