Update index.md
ethereum/ethereum-org-website pull request #11278
Opened 2023-09-27 07:30 UTC by 0xObsidian

Included Reth in the execution client table, propose change.

## Description

## Related Issue

2023-09-27 23:02 UTC, RamanSB approved these changes

2023-09-27 23:02 UTC, RamanSB commented on src/content/developers/docs/nodes-and-clients/index.md
> +| [Reth](https://github.com/paradigmxyz/reth)     | Rust     | Linux, Windows, macOS | Mainnet, Sepolia, Goerli, and more | Full                               | Archive, Pruned |
```suggestion
| [Reth](https://github.com/paradigmxyz/reth)     | Rust     | Linux, Windows, macOS | Mainnet, Sepolia, Goerli, and more | Snap, Fast, Full                   | Archive, Pruned |
```

2023-09-27 23:04 UTC, RamanSB requested changes

2023-09-27 23:04 UTC, RamanSB commented on src/content/developers/docs/nodes-and-clients/index.md
> +| [Reth](https://github.com/paradigmxyz/reth)     | Rust     | Linux, Windows, macOS | Mainnet, Sepolia, Goerli, and more | Full                               | Archive, Pruned |
```suggestion
| [Reth](https://github.com/paradigmxyz/reth)     | Rust     | Linux, Windows, macOS | Mainnet, Sepolia, Goerli, and more | Snap, Fast, Full                   | Archive, Pruned |
```

2023-10-04 02:18 UTC, corwintines commented on src/content/developers/docs/nodes-and-clients/index.md
> +| [Reth](https://github.com/paradigmxyz/reth)     | Rust     | Linux, Windows, macOS | Mainnet, Sepolia, Goerli, and more | Snap, Fast, Full                   | Archive, Pruned |
```suggestion
| [Reth](https://github.com/paradigmxyz/reth)     | Rust     | Linux, Windows, macOS | Mainnet, Sepolia, Goerli, and more | Full                   | Archive, Pruned |
```

Couldn't find documentation on these other syncing strategies, so going to revert this back to just full

2023-10-04 02:18 UTC, corwintines approved these changes
Thanks @0xObsidian

2023-10-04 02:18 UTC, merged

2023-10-04 02:18 UTC, corwintines commented
@all-contributors can you add @0xObsidian for content