Nov 6 Spanish (Docs - tech stack pages)
ethereum/ethereum-org-website pull request #11610
Opened 2023-11-06 22:24 UTC by corwintines

## Description

- Nov 6 Spanish (Docs - tech stack pages)

2023-11-09 17:43 UTC, wackerow approved these changes

2023-11-09 17:44 UTC, merged

2023-11-11 13:00 UTC, nnnnnnsssss approved these changes

2023-11-11 13:01 UTC, nnnnnnsssss requested changes
Recheck

2023-11-11 17:12 UTC, nnnnnnsssss approved these changes