Add crossmint
ethereum/ethereum-org-website pull request #11685
Opened 2023-11-18 00:58 UTC by rohit-710

Adding Crossmint on Ethereum Docs

## Description

Updating Tools for Creating DAPPS to include Crossmint and Updating Ethereum Mainnet for enterprise doc to show Crossmint

## Related Issue
https://github.com/ethereum/ethereum-org-website/issues/11636

2023-11-18 00:58 UTC, rohit-710 commented
https://github.com/ethereum/ethereum-org-website/issues/11636

Issue link

2023-11-18 05:47 UTC, nnnnnnsssss approved these changes

2024-03-11 17:24 UTC, tasdienes commented
I think that Crossmint should only be listed under *one* category, not under multiple categories.

2024-04-22 20:24 UTC, wackerow requested changes
@rohit-710 Left a request. Also, we remove `utm_source` trackers from all links if you could please make that adjustment. Thanks!

2024-04-22 20:24 UTC, wackerow commented on src/content/enterprise/index.md
I'm not sure I see other products that we're listing multiple times on this page. The number of items to choose from throughout this page is already quite unwieldy...

Requesting we choose one category that best fits what Crossmint offers.

2024-04-22 20:53 UTC, rohit-710 commented on src/content/enterprise/index.md
Hey @wackerow 
I just updated this

2024-04-23 19:06 UTC, wackerow approved these changes

2024-04-23 19:16 UTC, merged