Fix feedback widget positioning + refactor to use popover
ethereum/ethereum-org-website pull request #12135
Opened 2024-02-08 12:52 UTC by pettinarip

![image](https://github.com/ethereum/ethereum-org-website/assets/468158/8a7f9399-5cd5-43c6-b3f7-e747a2868d6e)

## Description

To fix the FeedbackWidget positioning issue + fix the horizontal overflow #12035 + improve a11y aspects since we were using a wrong component (AlertDialog), this PR switches the base component to a Popover.

## Related Issue

#12035

2024-02-08 12:52 UTC, pettinarip commented on src/components/FeedbackWidget.tsx
> +        ref={ref}
Needed for the `PopoverTrigger` to work correctly.

2024-02-08 12:53 UTC, pettinarip commented on src/components/FeedbackWidget.tsx
> +        bottom={{ base: `${bottomOffset + 1}rem`, lg: 4 }}
Absolute position the button to the right inside the sticky container.

2024-02-08 12:53 UTC, pettinarip commented on src/components/FeedbackWidget.tsx
> +    <Box position="sticky" bottom="0">
Keep it at the bottom of the screen.

2024-02-14 20:49 UTC, corwintines requested changes
Nice, thanks @pettinarip 

Noticing that on mobile, there is an issue with this overflowing

![Screenshot 2024-02-14 at 1 47 55 PM](https://github.com/ethereum/ethereum-org-website/assets/15589226/7e47ab27-352b-4c15-9646-661f0dc024b8)

Ive created this issue for this: https://github.com/ethereum/ethereum-org-website/issues/12184

It currently exists still, but would be good to fix in this I think.

2024-02-15 09:27 UTC, pettinarip commented
@corwintines good catch! added a new variant to control the internal width of the popover.

2024-02-15 17:58 UTC, pettinarip commented
@corwintines closing this in favor of #10997.

2024-02-15 17:58 UTC, closed without merging