Added missing whitespace after numbered emojis in all languages [Fixe…
ethereum/ethereum-org-website pull request #12179
Opened 2024-02-13 23:21 UTC by RabihJabr29

…s #12173]

Added missing whitespace after numbered emojis in all languages [Fixes #12173 ]

## Description

Issue #12173 https://github.com/ethereum/ethereum-org-website/issues/12173

Missing space between emoji and text on design page

Added the missing whitespace by having the property me="2" in the <Emoji /> elements.
Done for all languages.

## Related Issue

2024-02-14 20:40 UTC, corwintines requested changes
Thanks @RabihJabr29!

Ive left some suggestions which I think will be a cleaner solution. Instead of using margins, we can use the the character code for a space instead to get this. HTML is removing the white spaces between the Emoji and text, but if we add this character code it will be included.

2024-02-14 20:40 UTC, corwintines commented on public/content/contributing/design/index.md
> +### <Emoji text=":one:" size={1} me="2" /> Provide feedback on early design prototypes {#design-critique}
```suggestion
### <Emoji text=":one:" size={1} /> &nbsp;Provide feedback on early design prototypes {#design-critique}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/contributing/design/index.md
> +### <Emoji text=":two:" size={1} me="2" /> Participate in survey research {#answer-surveys}
```suggestion
### <Emoji text=":two:" size={1} /> &nbsp;Participate in survey research {#answer-surveys}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/contributing/design/index.md
> +### <Emoji text=":three:" size={1} me="2" /> Find design related issues on the website and report them {#report-design-issues}
```suggestion
### <Emoji text=":three:" size={1} /> &nbsp;Find design related issues on the website and report them {#report-design-issues}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/contributing/design/index.md
> +### <Emoji text=":four:" size={1} me="2" /> Propose design changes {#propose-design-changes}
```suggestion
### <Emoji text=":four:" size={1} /> &nbsp;Propose design changes {#propose-design-changes}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/contributing/design/index.md
> +### <Emoji text=":five:" size={1} me="2" /> Build Design System together {#Contribute-to-design-system}
```suggestion
### <Emoji text=":five:" size={1} /> &nbsp;Build Design System together {#Contribute-to-design-system}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/contributing/design/index.md
> +### <Emoji text=":six:" size={1} me="2" /> Write design-related content on the website {#write-design-articles}
```suggestion
### <Emoji text=":six:" size={1} /> &nbsp;Write design-related content on the website {#write-design-articles}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/contributing/design/index.md
> +### <Emoji text=":seven:" size={1} me="2" /> Draw new illustrations {#prepare-illustrations}
```suggestion
### <Emoji text=":seven:" size={1} /> &nbsp;Draw new illustrations {#prepare-illustrations}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/de/contributing/design/index.md
> +### <Emoji text=":one:" size={1} me="2" /> Geben Sie Feedback zu frühen Design-Prototypen {#design-critique}
```suggestion
### <Emoji text=":one:" size={1} /> &nbsp;Geben Sie Feedback zu frühen Design-Prototypen {#design-critique}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/de/contributing/design/index.md
> +### <Emoji text=":two:" size={1} me="2" /> Teilnahme an Umfragen {#answer-surveys}
```suggestion
### <Emoji text=":two:" size={1} /> &nbsp;Teilnahme an Umfragen {#answer-surveys}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/de/contributing/design/index.md
> +### <Emoji text=":three:" size={1} me="2" /> Finden Sie designbezogene Probleme auf der Website und melden Sie diese. {#report-design-issues}
```suggestion
### <Emoji text=":three:" size={1} /> &nbsp;Finden Sie designbezogene Probleme auf der Website und melden Sie diese. {#report-design-issues}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/de/contributing/design/index.md
> +### <Emoji text=":four:" size={1} me="2" /> Designänderungen vorschlagen {#propose-design-changes}
```suggestion
### <Emoji text=":four:" size={1} /> &nbsp;Designänderungen vorschlagen {#propose-design-changes}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/de/contributing/design/index.md
> +### <Emoji text=":five:" size={1} me="2" /> Das Designsystem gemeinsam aufbauen {#Contribute-to-design-system}
```suggestion
### <Emoji text=":five:" size={1} /> &nbsp;Das Designsystem gemeinsam aufbauen {#Contribute-to-design-system}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/de/contributing/design/index.md
> +### <Emoji text=":six:" size={1} me="2" /> Verfassen Sie designbezogene Inhalte auf der Website. {#write-design-articles}
```suggestion
### <Emoji text=":six:" size={1} /> &nbsp;Verfassen Sie designbezogene Inhalte auf der Website. {#write-design-articles}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/de/contributing/design/index.md
> +### <Emoji text=":seven:" size={1} me="2" /> Gestalten Sie neue Illustrationen. {#prepare-illustrations}
```suggestion
### <Emoji text=":seven:" size={1} /> &nbsp;Gestalten Sie neue Illustrationen. {#prepare-illustrations}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/es/contributing/design/index.md
> +### <Emoji text=":one:" size={1} me="2" /> Proporciona opiniones en diseños tempranos de prototipos {#design-critique}
```suggestion
### <Emoji text=":one:" size={1} /> &nbsp;Proporciona opiniones en diseños tempranos de prototipos {#design-critique}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/es/contributing/design/index.md
> +### <Emoji text=":two:" size={1} me="2" /> Participa en las encuentas {#answer-surveys}
```suggestion
### <Emoji text=":two:" size={1} /> &nbsp;Participa en las encuentas {#answer-surveys}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/es/contributing/design/index.md
> +### <Emoji text=":three:" size={1} me="2" /> Si detecta errores de diseño en la página web, comuníquelos {#report-design-issues}
```suggestion
### <Emoji text=":three:" size={1} /> &nbsp;Si detecta errores de diseño en la página web, comuníquelos {#report-design-issues}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/pt-br/contributing/design/index.md
> +### <Emoji text=":seven:" size={1} me="2" /> Desenhe novas ilustrações {#prepare-illustrations}
```suggestion
### <Emoji text=":seven:" size={1} /> &nbsp;Desenhe novas ilustrações {#prepare-illustrations}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/tr/contributing/design/index.md
> +### <Emoji text=":one:" size={1} me="2" /> Erken tasarım prototipleri hakkında geribildirim sağlayın {#design-critique}
```suggestion
### <Emoji text=":one:" size={1} /> &nbsp;Erken tasarım prototipleri hakkında geribildirim sağlayın {#design-critique}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/tr/contributing/design/index.md
> +### <Emoji text=":two:" size={1} me="2" /> Anket araştırmasına katılın {#answer-surveys}
```suggestion
### <Emoji text=":two:" size={1} /> &nbsp;Anket araştırmasına katılın {#answer-surveys}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/tr/contributing/design/index.md
> +### <Emoji text=":three:" size={1} me="2" /> Web sitesindeki tasarımla ilgili sorunları bulun ve bildirin {#report-design-issues}
```suggestion
### <Emoji text=":three:" size={1} /> &nbsp;Web sitesindeki tasarımla ilgili sorunları bulun ve bildirin {#report-design-issues}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/tr/contributing/design/index.md
> +### <Emoji text=":four:" size={1} me="2" /> Tasarım değişiklikleri önerin {#propose-design-changes}
```suggestion
### <Emoji text=":four:" size={1} /> &nbsp;Tasarım değişiklikleri önerin {#propose-design-changes}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/tr/contributing/design/index.md
> +### <Emoji text=":five:" size={1} me="2" /> Tasarım Sistemini birlikte geliştirin {#Contribute-to-design-system}
```suggestion
### <Emoji text=":five:" size={1} /> &nbsp;Tasarım Sistemini birlikte geliştirin {#Contribute-to-design-system}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/tr/contributing/design/index.md
> +### <Emoji text=":six:" size={1} me="2" /> Web sitesinde tasarımla ilgili içerik yazın {#write-design-articles}
```suggestion
### <Emoji text=":six:" size={1} /> &nbsp;Web sitesinde tasarımla ilgili içerik yazın {#write-design-articles}
```

2024-02-14 20:40 UTC, corwintines commented on public/content/translations/tr/contributing/design/index.md
> +### <Emoji text=":seven:" size={1} me="2" /> Yeni illüstrasyonlar çizin {#prepare-illustrations}
```suggestion
### <Emoji text=":seven:" size={1} /> &nbsp;Yeni illüstrasyonlar çizin {#prepare-illustrations}
```

2024-02-15 10:19 UTC, RabihJabr29 commented
Hello again, @corwintines 
Adapted the new changes to your suggestions.

2024-02-15 17:52 UTC, corwintines approved these changes
Thanks @RabihJabr29!

2024-02-15 17:52 UTC, merged