docs: add Covalent Python and Typescript SDK info on docs page
ethereum/ethereum-org-website pull request #12585
Opened 2024-03-27 02:03 UTC by Dennayz

## Description

The PR intends to describe Covalent's SDK packages (Python and TypeScript) under the respectable documentation sections. This will go along with the recent covalent Golang SDK PR https://github.com/ethereum/ethereum-org-website/pull/12543.

## Related Issue

2024-04-08 22:13 UTC, wackerow commented
Thanks @Dennayz! Flagged for product review

2024-04-10 19:53 UTC, Dennayz commented
> Thanks @Dennayz! Flagged for product review

Thanks! I also fixed the merge conflict! :)

2024-04-17 06:07 UTC, Dennayz commented
@wackerow Hey! Just wondering if there are any updates on this? Thanks!

2024-05-07 20:03 UTC, wackerow commented
Hey @Dennayz, question.. was checking out https://www.npmjs.com/package/@covalenthq/client-sdk and tried to look at the repo but it 404's.. has it moved or is it closed?

2024-05-07 20:05 UTC, Dennayz commented
> Hey @Dennayz, question.. was checking out https://www.npmjs.com/package/@covalenthq/client-sdk and tried to look at the repo but it 404's.. has it moved or is it closed?

Hey @wackerow, thanks for the reply! I think the repo is private.

2024-05-25 15:56 UTC, wackerow commented
Thanks @Dennayz.. curious if you know if there are plans to open source the SDK in the future? To my knowledge the other JS and Python products on two of the pages here are all open source. We could probably add this to the frameworks page, but hesitant to open the others up to closed source.
cc: @minimalsm @corwintines curious if you have an opinion here

2024-05-27 18:10 UTC, Dennayz commented
> Thanks @Dennayz.. curious if you know if there are plans to open source the SDK in the future? To my knowledge the other JS and Python products on two of the pages here are all open source. We could probably add this to the frameworks page, but hesitant to open the others up to closed source. cc: @minimalsm @corwintines curious if you have an opinion here

Hey @wackerow, thanks for the message, I do not think these SDK's will be open sourced anytime soon.

2024-06-07 13:30 UTC, wackerow commented
@Dennayz Thoughts on starting with a listing on the Frameworks page only for this, given the open source aspect of the JS/Python lists?

2024-06-14 19:46 UTC, wackerow requested changes

2024-06-14 19:46 UTC, wackerow commented on public/content/developers/docs/programming-languages/python/index.md
> +- [Covalent Python SDK](https://pypi.org/project/covalent-api-sdk/) - _Efficient blockchain data access via Python SDK for 200+ blockchains_
```suggestion
```

2024-06-14 19:46 UTC, wackerow commented on public/content/developers/docs/apis/javascript/index.md
> +
```suggestion
```

2024-06-17 23:20 UTC, wackerow approved these changes
Removed from JS and Python pages at least for now, but left in for the frameworks page. Thanks @Dennayz! Bringing in

2024-06-17 23:21 UTC, merged

2024-06-17 23:22 UTC, wackerow commented
@all-contributors please add @Dennayz for tool