♻️ (apis/backend/index.md): Reorganize & update list of available libraries.
ethereum/ethereum-org-website pull request #12605
Opened 2024-03-30 11:00 UTC by Pedrojok01

## Description

According to the suggestion in the issue https://github.com/ethereum/ethereum-org-website/issues/12545, I have reorganized all libraries into 3 `h3` categories to make everything easier to digest. Since many libraries tend to overlap each other and offer similar services (node providers offering various APIs and vice-versa), I tried to stick to the "main" product offered. Also tried to keep each category balanced. 
```
1. Infrastructure and Node Services
2. Development Tools
3. Blockchain Services
```
Open to better suggestions if any. Worst case, we can default to an alphabetical order without category.
All links have been updated when needed.

Notes:
- `Figment.io/datahub` seems deprecated (404 links). Updated to `Figment.io`
- `Nodesmith` is dead. Removed.
- `Ethercluster` is dead. Removed.

## Related Issue

https://github.com/ethereum/ethereum-org-website/issues/12545

2024-03-30 11:12 UTC, Jacekdaa approved these changes

2024-04-08 17:29 UTC, wackerow requested changes
Great, thanks @Pedrojok01! I think this is a nice iterative step in the right direction and helps make this list a bit easier to navigate. Just left a couple small suggestions to use "sentence casing" for the headers [per our style guide](https://ethereum.org/en/contributing/style-guide/content-standardization/#header-casing) then this should be good

Thanks for removing the dead links/projects as well 🙏

2024-04-08 17:29 UTC, wackerow commented on public/content/developers/docs/apis/backend/index.md
> +### Infrastructure and Node Services {#infrastructure-and-node-services}
```suggestion
### Infrastructure and node services {#infrastructure-and-node-services}
```

2024-04-08 17:29 UTC, wackerow commented on public/content/developers/docs/apis/backend/index.md
> +### Development Tools {#development-tools}
```suggestion
### Development tools {#development-tools}
```

2024-04-08 17:29 UTC, wackerow commented on public/content/developers/docs/apis/backend/index.md
> +### Blockchain Services {#blockchain-services}
```suggestion
### Blockchain services {#blockchain-services}
```

2024-04-08 21:33 UTC, wackerow commented
Just merged in latest from `dev` and cleared the conflict where a new product was added here

2024-04-08 22:25 UTC, wackerow approved these changes
Went ahead and just made that small update with the header casing... Thanks @Pedrojok01! Pulling in

2024-04-08 22:25 UTC, merged

2024-04-08 22:26 UTC, wackerow commented
@all-contributors please add @Pedrojok01 for maintenance

2024-04-09 02:12 UTC, Pedrojok01 commented
Very welcome @wackerow. Happy to contribute. And thank you and the community for the great resources! I will try to help every now and then.