chore: import translations for hu (manual)
ethereum/ethereum-org-website pull request #13113
Opened 2024-06-06 15:02 UTC by wackerow

## Description
Import Crowdin translations.

Thank you to everyone contributing to translate ethereum.org ❤️

## Content buckets imported
3, 6, 7, 10, 11, 12, 13, 16, 21

## Preview link
- TBD

PR replaces #13085

2024-06-06 16:13 UTC, wackerow commented
Note to self: use `crowdin` in branch name for any manual imports to avoid unnecessary check failure

2024-06-07 14:29 UTC, nhsz requested changes
some terms are being translated but shouldn't

2024-06-07 14:29 UTC, nhsz commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `tanúsítások`        | a tanúsítók listája, akik ezt a blokkot támogatják                  |
seems these words shouldn't be translated

2024-06-07 14:29 UTC, nhsz commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `behelyezés`         | az új letétek listája a letéti szerződésbe                          |
seems these words shouldn't be translated

2024-06-07 14:29 UTC, nhsz commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `adat`             | konténer számos almezővel                                    |
seems these words shouldn't be translated

2024-06-07 14:29 UTC, nhsz commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `aláírás`          | az összes tanúsítást végző validátor aláírásának aggregátuma |
seems these words shouldn't be translated

2024-06-07 14:29 UTC, nhsz commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `időbélyeg`         | a blokk ideje                                                            |
seems these words shouldn't be translated

2024-06-07 14:29 UTC, nhsz commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `időbélyeg`        | a blokk ideje                                                            |
seems these words shouldn't be translated

2024-06-07 14:29 UTC, nhsz commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `kivételek`        | a visszavonásra kerülő objektumok listája                                |
seems these words shouldn't be translated

2024-06-07 17:35 UTC, wackerow commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `tanúsítások`        | a tanúsítók listája, akik ezt a blokkot támogatják                  |
```suggestion
| `attestations`        | a tanúsítók listája, akik ezt a blokkot támogatják                  |
```

2024-06-07 17:35 UTC, wackerow commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `behelyezés`         | az új letétek listája a letéti szerződésbe                          |
```suggestion
| `deposits`         | az új letétek listája a letéti szerződésbe                          |
```

2024-06-07 17:35 UTC, wackerow commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `aláírás`          | az összes tanúsítást végző validátor aláírásának aggregátuma |
```suggestion
| `data`             | konténer számos almezővel                                    |
| `signature`          | az összes tanúsítást végző validátor aláírásának aggregátuma |
```

2024-06-07 17:35 UTC, wackerow commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `időbélyeg`         | a blokk ideje                                                            |
```suggestion
| `timestamp`         | a blokk ideje                                                            |
```

2024-06-07 17:35 UTC, wackerow commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `időbélyeg`        | a blokk ideje                                                            |
```suggestion
| `timestamp`        | a blokk ideje                                                            |
```

2024-06-07 17:35 UTC, wackerow commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `kivételek`        | a visszavonásra kerülő objektumok listája                                |
```suggestion
| `withdrawals`        | a visszavonásra kerülő objektumok listája                                |
```

2024-06-07 17:42 UTC, nhsz commented on public/content/translations/hu/developers/docs/blocks/index.md
> +| `törzs`          | egy olyan objektum, amely számos mezőt tartalmaz, ahogy azt alább definiáljuk |
```suggestion
| `body`           | egy olyan objektum, amely számos mezőt tartalmaz, ahogy azt alább definiáljuk |
```

2024-06-07 17:43 UTC, nhsz approved these changes

2024-06-07 17:43 UTC, merged