Add sybil attack glossary item [Fixes #12096]
ethereum/ethereum-org-website pull request #13161
Opened 2024-06-13 14:36 UTC by aslikaya

## Description

[Fixes #12096]

I searched through the website and added this as a tooltip on the first occurrence of this term on pages.

## Related Issue

2024-06-14 02:52 UTC, wackerow requested changes
Overall looks good @aslikaya! But ["Sybil" should remain capitalized](https://en.wikipedia.org/wiki/Sybil_attack) throughout here

2024-06-14 13:38 UTC, aslikaya commented
I thought they were mistakes😅 changing back now

2024-06-14 14:45 UTC, aslikaya commented on public/content/developers/docs/consensus-mechanisms/index.md
> +**Sybil resistance** measures how a protocol fares against a Sybil attack. Resistance to this type of attack is essential for a decentralized blockchain and enables miners and validators to be reward
on the upper side of the page there is a tooltip explanation on the first occurrence of the term, shall I still put it here?

2024-06-19 03:31 UTC, wackerow commented on public/content/developers/docs/consensus-mechanisms/index.md
> +**Sybil resistance** measures how a protocol fares against a Sybil attack. Resistance to this type of attack is essential for a decentralized blockchain and enables miners and validators to be reward
@aslikaya Ah right, just once per page is fine... I see why you removed this now. 👍

2024-06-21 13:04 UTC, aslikaya commented on public/content/developers/docs/consensus-mechanisms/index.md
> +**Sybil resistance** measures how a protocol fares against a Sybil attack. Resistance to this type of attack is essential for a decentralized blockchain and enables miners and validators to be reward
@wackerow I can still add here too btw, no problem at all

2024-06-22 00:16 UTC, wackerow commented on public/content/developers/docs/consensus-mechanisms/index.md
> +**Sybil resistance** measures how a protocol fares against a Sybil attack. Resistance to this type of attack is essential for a decentralized blockchain and enables miners and validators to be reward
All good 👍, better to not overload with links

2024-06-22 00:21 UTC, wackerow approved these changes
Looks great! Thanks @aslikaya!

2024-06-22 00:21 UTC, merged