style(theme/Tag): set background style on close button hover
ethereum/ethereum-org-website pull request #13237
Opened 2024-06-25 04:57 UTC by TylerAPfledderer

## Description

Updates the close button style on hover to sync with the DS.

This is not a complete sync — see the "Normal" and "Tag" Solid variants. This provided additional complication that already exists in the theming.

## Related Issue

- Closes #10266

2024-06-25 05:01 UTC, TylerAPfledderer commented
@pettinarip and @nloureiro, I would like to try and review the tag styling with you, and present an alternative that I have made (Pablo has seen this).

What makes creating the styling in the code with all the variants is inconsistency in how all the different colors are being used. The generates a bloated set of styles that have to be hard-coded. I would like to present a solution that reduces the colors used to just the two different shades in the palette for each "status" type which would also improve a11y in the color contrast, especially with this hover styles of the close button.

2024-06-25 07:40 UTC, pettinarip requested changes
@TylerAPfledderer nice, lgtm. Once we revert the `yarn.lock` we could merge this.


=====
Not related to this PR but noted a bug on the Tags as links
![image](https://github.com/ethereum/ethereum-org-website/assets/468158/dc77a2e8-9f53-490f-8343-c9f42efc5538)

When hovered, it is displaying the text with the Link styles. Not a big deal because we are not currently using this case on the site.

2024-06-25 07:40 UTC, pettinarip commented on yarn.lock
we shouldn't have this file modified

2024-06-25 07:46 UTC, pettinarip commented
> @pettinarip and @nloureiro, I would like to try and review the tag styling with you, and present an alternative that I have made (Pablo has seen this).
> 
> What makes creating the styling in the code with all the variants is inconsistency in how all the different colors are being used. The generates a bloated set of styles that have to be hard-coded. I would like to present a solution that reduces the colors used to just the two different shades in the palette for each "status" type which would also improve a11y in the color contrast, especially with this hover styles of the close button.

Sounds good to me!

FYI new colors are coming to the DS. Just saying for context but I don't think it will affect what you're suggesting here.

2024-06-25 13:05 UTC, TylerAPfledderer commented on yarn.lock
@pettinarip The file modified when I brought in the latest changes from `dev` and ran `yarn install`

2024-06-25 20:01 UTC, TylerAPfledderer commented on yarn.lock
@pettinarip merging the latest `dev` still provided a diff for the lockfile

2024-06-26 12:16 UTC, pettinarip approved these changes
Fixed. The difference was added in your first commit, I added a revert for that file.

The rest looks good, approving 👍🏼

2024-06-26 23:50 UTC, merged