Refine data documentation in https://ethereum.org/en/developers/docs/data-and-analytics/
ethereum/ethereum-org-website pull request #13352
Opened 2024-07-08 00:30 UTC by andrewhong5297

Related to issue https://github.com/ethereum/ethereum-org-website/issues/9144

2025-07-16 19:34 UTC, wackerow requested changes
Hey @andrewhong5297! So sorry for the delays on this. Circling back, gave it a read and left my thoughts.... Most of my code suggestions are just clerical stuff, but a few that I'd like addressed before we pull this in.

- (Clerical fixes)
- "Recent" verbiage... would reword some stuff to be a bit more future-proof
- 2024->2025, anything critical we should add?
- Page length... split into two?
- Empty further reading
- Thoughts on repeating block explorer listings? Would prefer to have one list of these on their dedicated page and link to that

Otherwise I think this is great, and a really nice update to the page. Would love to get this in soon. Would you be available for any updates @andrewhong5297? Thanks again!

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +title: Data and Analytics
(We use sentence casing for all titles)
```suggestion
title: Data and analytics
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +As you get into crypto, you're likely to see stats, charts, and APIs across dozens of different websites (and github repos). This is a stark contrast from traditional tech or finance where there is j
```suggestion
As you get into crypto, you're likely to see stats, charts, and APIs across dozens of different websites (and GitHub repos). This is a stark contrast from traditional tech or finance where there is just one trusted source (i.e. Bloomberg). This is due to the open data nature of the industry, where all data can be freely downloaded from client nodes.
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +However, that data is stored in hex/binary form and is hardly legible or usable. As an ecosystem, we've had to work together to share queries, tools, tables, and labor to make crypto data accessible
Maybe just a note on how it's also not indexed by default or easily searchable?

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +In this overview page, we'll cover all the parts of the crypto data stack as they stand today (last updated in 2024).
@andrewhong5297 Certainly apologize for delays here... anything critical that has developed since that you'd like to add now that we're in 2025?

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +## Crypto Data Landscape
(Custom header ids needed for all headers—related to our translations)

```suggestion
## Crypto Data Landscape {#crypto-data-landscape}
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +Below is a diagram of the five parts of the crypto data stack, with some top example product logos called out. You can learn more about these products in the [tool descriptions page](public/content/d
```suggestion
Below is a diagram of the five parts of the crypto data stack, with some top example product logos called out. You can learn more about these products in the [tool descriptions page](/developers/docs/data-and-analytics/tool-descriptions/)
```

And similarly, that page should be at tool-descriptions/index.md, not tool-descriptions.md; we'll get it moved

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +![](/public/images/data/data_landscape.jpg)
(Alt text)

```suggestion
![Diagram showing the web3 data stack as represented in 2024](/public/images/data/data_landscape.jpg)
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +#### web2 counterparts
(Important not to skip heading levels)

```suggestion
### Web2 counterparts {#web2-counterparts)
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +- …and back onchain: this is just reverse ETL
Any proper names/brands should be capitalized here

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +### Index: Read raw data from the blockchain
```suggestion
### Index: Read raw data from the blockchain {#index}
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +However, that data is stored in hex/binary form and is hardly legible or usable. As an ecosystem, we've had to work together to share queries, tools, tables, and labor to make crypto data accessible
ah, see it's covered below, that'll do

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +- Forks-as-a-Service
```suggestion
**Forks-as-a-Service**
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +- Rollups-as-a-Service (RaaS):
```suggestion
**Rollups-as-a-Service (RaaS):**
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +  - The big theme of the year has been rollups, with Coinbase kicking it off by launching a rollup (Base) on the Optimism Stack (OP Stack) earlier this year.
As you can see, time passes fast... using terms like "earlier this year" quickly become dated. Ideally we rephrase to keep content a bit more future-proof, although I do appreciate the note at the top mentioning the timeframe we're discussing.

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +Alchemy and Quicknode have expanded further into crypto native infra and data engineering infra. Alchemy launched [account abstraction](https://www.alchemy.com/account-abstraction-infrastructure) and
Few updated links

```suggestion
Alchemy and Quicknode have expanded further into crypto native infra and data engineering infra. Alchemy launched [account abstraction](https://www.alchemy.com/bundler) and [subgraph services](https://www.alchemy.com/subgraphs). Quicknode has been busy with [alerts](https://www.quicknode.com/quickalerts), [data streaming](https://www.quicknode.com/stream), and [rollup services](https://blog.quicknode.com/introducing-quicknode-custom-chains).
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +We should see our first “intents” clients/services soon. Intents are a part of the modular stack, and are essentially transactions handled outside the mempool that have extra preferences attached. Un
```suggestion
We should see our first “intents” clients/services soon. Intents are a part of the modular stack, and are essentially transactions handled outside the mempool that have extra preferences attached. UniswapX and Cowswap both operate limit order intent pools, and should both release clients within the year. Account abstraction bundlers like [stackup](https://www.stackup.fi/) and [biconomy](https://www.biconomy.io/) should venture into intents as well. It’s unclear if data providers like Alchemy will index these “intents” clients, or if it will be like MEV where we have specialized providers like [Blocknative](https://www.blocknative.com/) and [Bloxroute](https://bloxroute.com/).
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +  - New startups like [Conduit](https://conduit.xyz/), [Caldera](https://caldera.xyz/), and [Astria](https://www.astria.org/) are offering full stack rollup services. Quicknode and Alchemy have launc
```suggestion
- The big theme of the year has been rollups, with Coinbase kicking it off by launching a rollup (Base) on the Optimism Stack (OP Stack) earlier this year.
- Teams are building products specifically for running the nodes and sequencer(s) for your own Rollup. We’ve already seen dozens of rollups launch.
- New startups like [Conduit](https://conduit.xyz/), [Caldera](https://caldera.xyz/), and [Astria](https://www.astria.org/) are offering full stack rollup services. Quicknode and Alchemy have launched similar RaaS offerings.
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +  - ilemi gave his thoughts on [shortcomings and difficulties](https://twitter.com/andrewhong5297/status/1732230186966413484) on this approach.
```suggestion
- Fork any contract and add events and calculations, and then pull this data from a new “forked” RPC/data service.
- Some of the main providers for this are [shadow.xyz](https://www.shadow.xyz/), [ghostlogs](https://ghostlogs.xyz/), and [smlXL](https://smlxl.io/).
- ilemi gave his thoughts on [shortcomings and difficulties](https://twitter.com/andrewhong5297/status/1732230186966413484) on this approach.
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +### Explore: Quickly look into addresses, transactions, protocols, and chains
```suggestion
### Explore: Quickly look into addresses, transactions, protocols, and chains {#explore}
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +Outside of etherscan, we now have this plethora of explorers to choose from:
```suggestion
Outside of Etherscan, we now have this plethora of explorers to choose from:
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +- Nansen launched a 2.0 of their token and wallet tracking product, with cool new features like “smart segments”
Noting we do already have a dedicated page for block explorers nested in this section: https://ethereum.org/en/developers/docs/data-and-analytics/block-explorers/

It's hard enough to maintain one list of these; I'd be hesitant to add a list with the same purpose to this page. cc: @konopkja

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +Marketing specific address explorers are on the rise. Teams like spindl and bello will lead the way here. Cross-chain explorers (and pre-chain like MEV/intents) will see expansion in development.
Capitalize team names? Only leave lower if they're branding indicates as such... kinda like `ethereum.org` =)

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +Across platforms, wallets are still poorly labelled and tracked, and it’s getting worse with intents/account abstraction now. We don’t mean static labels like “Coinbase” but instead more dynamic ones
https://walletlabels.xyz
<img width="454" height="183" alt="image" src="https://github.com/user-attachments/assets/636d506a-cbf8-404f-8115-eca96041548a" />

<img width="605" height="509" alt="image" src="https://github.com/user-attachments/assets/60c5193e-d321-4b9c-b528-a0b7564ba48b" />

sad panda..

```suggestion
Across platforms, wallets are still poorly labelled and tracked, and it’s getting worse with intents/account abstraction now. We don’t mean static labels like “Coinbase” but instead more dynamic ones like “Experienced Contract Deployer”. Some teams are trying to tackle this, such as [syve.ai](https://www.syve.ai/). It will also improve naturally alongside web3 social, which is growing mainly on [Farcaster](https://farcaster.xyz/).
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +### Query: Raw, decoded, and abstracted data that can be queried
```suggestion
### Query: Raw, decoded, and abstracted data that can be queried {#query}
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +Recent changes to existing products:
(Again, careful with "recent" language)

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +1. Query engines like [Dune](https://dune.com/) and [Flipside](https://flipsidecrypto.xyz/) have accepted there is more data than can possibly be ingested in custom data pipelines, and have launched
```suggestion
1. Query engines like [Dune](https://dune.com/) and [Flipside](https://flipsidecrypto.xyz/) have accepted there is more data than can possibly be ingested in custom data pipelines, and have launched products that allow the user to bring in that data instead. Flipside launched livequery (query an API in SQL) and Dune launched uploads/syncs (upload csv or api, or sync your database to Dune directly).

```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +2. Our favorite decentralized data child, [The Graph](https://thegraph.com/), has had to really beef up their infra to not lose market share to centralized subgraph players like goldsky and satsuma (
"Our favorite decentralized data child" -- I know it's colloquial, but may re-word this for a platform like ethereum.org

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +### Define and Store: Create and store aggregations that rely on heavy data transformations
```suggestion
### Define and Store: Create and store aggregations that rely on heavy data transformations {#define-and-store}
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +You can probably consider every 2-3 files to be a new protocol/table. So 200+ tables shifting around every month, and that number is only increasing with new chains and startups. If you’ve never work
Similar to above... "let me tell you that’s a ton of work to manage." would reword

Some general ethereum.org style guide tips: https://ethereum.org/en/contributing/style-guide/#best-practices

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
Seeing a word count around 1800

https://ethereum.org/en/contributing/style-guide/#best-practices

Generally try to keep things closer to 1000, 1500 max... perhaps we could split the content of this page into two separate pages?

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/index.md
> +### Back Onchain: Putting the data back into contracts using Zero Knowledge (ZK) tech
```suggestion
### Back onchain: Putting the data back into contracts using zero knowledge (ZK) tech {#back-onchain}
```

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/tool-descriptions.md
> +Developers can then process and transform this data to give their users unique insights and interactions with the [blockchain](/glossary/#blockchain). For example, [Etherscan](https://etherscan.io) p
As mentioned above; this would be the third place we talk about block explorers....  Glad we didn't place a list here, but I would also not link to Etherscan. We should direct to our [block-explorers page](https://ethereum.org/en/developers/docs/data-and-analytics/block-explorers/)

Would probably ditch the "blockchain" glossary link here as well... feels out-of-place for this deep in the docs.

2025-07-16 19:34 UTC, wackerow commented on public/content/developers/docs/data-and-analytics/tool-descriptions.md
> +- []()
✂️  if none

2025-07-16 19:36 UTC, wackerow commented
We'll also need to clear merge conflicts, but wouldn't worry about too much about that just yet; could make the existing comments harder to follow.

2026-07-06 11:46 UTC, nloureiro commented
Closing due to inactivity: review feedback from July 2025 went unanswered for ~12 months and the branch now conflicts with `dev`. The direction (refining the data-and-analytics docs) is still valuable — if you'd like to pick it back up against the current page, we'd welcome a fresh PR. Thanks for the work you put into this.

2026-07-06 11:46 UTC, closed without merging