fixed ui on find-wallet [Fixes #13421]
ethereum/ethereum-org-website pull request #13426
Opened 2024-07-18 19:14 UTC by nipunh

## Description
fixed ui on find-wallet Fixes #13421 

<img width="392" alt="Screenshot 2024-07-18 at 3 09 20 PM" src="https://github.com/user-attachments/assets/04958bb5-c6ea-40dd-bf9d-7b781d654a37">

1) Made changes in scroll-bar css to show it by default.
2) Increased the width of cards for overflowing on right size

We can also provide arrows like this indicating more items in the grid, clicking on arrow will scroll the cards
<img width="392" alt="Screenshot 2024-07-18 at 3 09 20 PM" src="https://github.com/user-attachments/assets/04958bb5-c6ea-40dd-bf9d-7b781d654a37">

2024-07-22 17:33 UTC, wackerow requested changes
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/a8a1eb7e-63a9-443e-9de5-c95bf9565f44">

> Production on left, PR on the right

Hey @nipunh, I'm not sure this is accomplishing what is needed here...

Looks like we've altered the card width itself, and how it's internal contents are handled... This is not what we want to change.

We need to adjust how these cards are displayed in the _parent container_ to remove the white space on the right edge (outside of the card itself) when there is more to scroll to.

From issue:

> overflow the wrapper till the end of the screen like this and have no empty space on the right side

Does this make sense?

2024-07-24 09:23 UTC, konopkja commented
ping @nipunh

2024-07-24 14:15 UTC, nipunh commented
> <img alt="image" width="1194" src="https://private-user-images.githubusercontent.com/54227730/351057329-a8a1eb7e-63a9-443e-9de5-c95bf9565f44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzA3OTgsIm5iZiI6MTcyMTgzMDQ5OCwicGF0aCI6Ii81NDIyNzczMC8zNTEwNTczMjktYThhMWViN2UtNjNhOS00NDNlLTlkZTUtYzk1YmY5NTY1ZjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE0MTQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMzc4MGMxM2RjNWVlMzU4YTMxMzcyMjc0YTE4YWFkNWZiMGMzMTIxOWJjOTE4NWUyYmZkMGVjZTA5N2UzNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h7lb1LG70v5Qa_Dx8kupfU4c1zFl60ASIR6mG9gI9dw">
> > Production on left, PR on the right
> 
> Hey @nipunh, I'm not sure this is accomplishing what is needed here...
> 
> Looks like we've altered the card width itself, and how it's internal contents are handled... This is not what we want to change.
> 
> We need to adjust how these cards are displayed in the _parent container_ to remove the white space on the right edge (outside of the card itself) when there is more to scroll to.
> 
> From issue:
> 
> > overflow the wrapper till the end of the screen like this and have no empty space on the right side
> 
> Does this make sense?

Yes, I will make the required changes

2024-08-18 09:01 UTC, konopkja commented
cc @corwintines

2024-09-16 16:33 UTC, corwintines approved these changes
Thanks @nipunh

2024-09-16 16:33 UTC, corwintines commented
@all-contributors can you add @nipunh for code

2024-09-16 16:46 UTC, merged