Shad feedback widget
ethereum/ethereum-org-website pull request #13456
Opened 2024-07-23 16:16 UTC by wackerow

## Description
- Migrates FeedbackWidget and associated components to shadcn, deprecating use of Chakra dependencies
- Adds custom `useDisclosure` hook, replacing Chakra import
- Adds shadcn base `popover` component via command line

## Related Issue

2024-07-24 15:21 UTC, konopkja commented
<img width="93" alt="Screenshot 2024-07-24 at 20 18 23" src="https://github.com/user-attachments/assets/4b3fdf30-e694-41db-8925-b3df85d99602">

 think the secondary background color isnt necessary and could be removed

2024-07-25 14:16 UTC, pettinarip requested changes
Looks good @wackerow 

One minor that I see on the preview is that the popover content moves a little bit when you hover the button and it scales.

https://github.com/user-attachments/assets/9989d4f0-7c48-440b-9b82-e987aeb49d50

We could fix this by disabling the scaling effect when the popover is opened. What do you think?

2024-07-25 14:16 UTC, pettinarip commented on src/components/FeedbackWidget/FixedDot.tsx
> +          isExpanded ? "lg:w-60 lg:gap-3" : `lg:w-12`,
```suggestion
          isExpanded ? "lg:w-60 lg:gap-3" : "lg:w-12",
```

2024-07-25 14:16 UTC, pettinarip commented on src/components/FeedbackWidget/index.tsx
> +          <div className="items-top flex gap-2">
`items-top` doesn't exist.

```suggestion
          <div className="flex items-start gap-2">
```

2024-07-25 19:53 UTC, wackerow commented on src/components/FeedbackWidget/index.tsx
> +          <div className="items-top flex gap-2">
But I want it to! 😉 Good catch

2024-07-25 20:20 UTC, wackerow commented
@konopkja Removed that shadow effect seen on hover

@pettinarip Conditionally paused the `scale` effect when open

Ready for re-review.

2024-07-26 07:38 UTC, pettinarip commented on src/components/FeedbackWidget/index.tsx
> +          <div className="items-top flex gap-2">
haha! is a good name though

2024-07-26 08:31 UTC, pettinarip approved these changes
LGTM @wackerow 

I've just pushed a commit to regenerate the yarn.lock file since it was installing an old version of `@netlify/plugin-nextjs`.

2024-07-26 11:42 UTC, merged