[HotFix] Translatathon updates
ethereum/ethereum-org-website pull request #13562
Opened 2024-08-01 18:16 UTC by corwintines

## Description

- Add prizes information
- Add /contributing/translation-program/translatathon/local-communities page
- Add hub information
- Small content updates

2024-08-02 10:15 UTC, isabelladebrito commented
@corwintines here's the copy for the Translatathon Hubs page [https://deploy-preview-13562--ethereumorg.netlify.app/en/contributing/translation-program/translatathon/local-communities/]

Local communities → `Translatathon Hubs`

copy - - - -

`Overview`
`The Translatathon brings together people from different expertise and cultures to collaborate on one goal: making Ethereum knowledge accessible in as many languages as possible. This year, with the support of local communities, we are bringing Translatathon Hubs to several cities worldwide, where people can get together, meet fellow Ethereum enthusiasts, and participate in the Translatathon.`

`Why do we do it`
`Translating is often a lonely task, but it doesn't have to be. By gathering participants in one place, they can enjoy the solitude of crafting the perfect translation while still taking breaks to socialize, have a coffee, and share the most challenging or funny terms they've encountered while translating.`

`How does it work`
`Check the list of Translatathon Hubs to see if there's one happening in your city! Remember, the Translatathon is an online competition, so you can always participate from the comfort of your couch.`


List of all local communities → `List of Translatathon Hubs`

**NOTE:** for each entry in this list, we only need city, country, emoji icon and a button to add the event URL; no "organiser" or description needed.

e.g.

Bucharest, Romania 
[emoji icon on the right]: 🇷🇴 

Button copy: 
Luma link → `Register here`

2024-08-02 10:18 UTC, isabelladebrito commented
**List of Translatathon Hubs**

Bucharest, Romania
[emoji icon on the right]: 🇷🇴
Register here [https://lu.ma/b7m1nyid]

Addis Ababa, Ethiopia
[emoji icon on the right]: 🇪🇹 
Register here [https://lu.ma/zi092c8v]

Belgrade, Serbia
[emoji icon on the right]: 🇷🇸 
Register here [https://lu.ma/ehd86ohx]

2024-08-02 11:50 UTC, lukassim commented
> Top translator in each language will win a 100$ bonus + Participation prizes ↓ `Top translator in each language: ` `100$ + participation prize`

Everything else I agree with Isabella, but this part is incorrect
These should specifically be 2 separate lines, where we can change the current text to `Top translator in each language: ` `100$` but the last line should be '+ Participation prizes' as these are 2 different categories of prizes

2024-08-05 11:57 UTC, isabelladebrito commented
@corwintines I just checked on [deploy-preview](https://deploy-preview-13562--ethereumorg.netlify.app/en/contributing/translation-program/translatathon/translatathon-hubs/) and there's one word missing in the Hub cities: `Addis Ababa, Ethiopia`

<img width="336" alt="Screenshot 2024-08-05 at 12 50 57" src="https://github.com/user-attachments/assets/9cfa574a-4254-47ea-b1f4-fac856f6eb5e">


.
.
and two more additions to the Translatathon Hubs' list:

Taipei, Taiwan
2024 ethereum.org Translatathon Hub - Taiwan
[emoji icon on the right]: 🇹🇼 
Register here [https://lu.ma/2i9fi2zi]

Lusaka, Zambia
Ethereum Translatathon - Hosted by ETHZambezi
[emoji icon on the right]: 🇿🇲 
Register here [https://lu.ma/4xyfdlz7]

2024-08-05 13:50 UTC, isabelladebrito commented
@corwintines aaand two more additions to the Translatathon Hubs' list!

Kaduna, Nigeria
Ethereum Hausa Translatathon
[emoji icon on the right]: 🇳🇬 
Register here [https://lu.ma/w00aw06a]

Lagos, Nigeria
Ethereum Yorùbá Translatathon
[emoji icon on the right]: 🇳🇬 
Register here [https://lu.ma/1vj9u4rj]

2024-08-05 14:56 UTC, pettinarip reviewed
Looking good on my local @corwintines 

Noting that the content is showing the last paragraph wrapped in a `pre` tag. I guess this is not desired.
![image](https://github.com/user-attachments/assets/d084d656-608a-4de5-9ef8-2f6305063a69)

2024-08-05 15:09 UTC, corwintines commented on public/content/contributing/translation-program/translatathon/translatathon-hubs/local-communities.png
Since its in markdown it doesnt reference it properly in other languages was what I was experiencing.

2024-08-05 15:20 UTC, wackerow requested changes

2024-08-05 15:20 UTC, wackerow commented on src/components/Translatathon/TranslatathonPrizes.tsx
> +            <p className="text-4xl font-bold">5000$</p>
If we don't want to use the Intl library to format this, I would use the dollar sign in front (throughout):

```suggestion
            <p className="text-4xl font-bold">$5000</p>
```

2024-08-05 15:20 UTC, wackerow commented on src/components/Translatathon/TranslatathonPrizes.tsx
> +            Top translator in each language: 100${" "}
```suggestion
            Top translator in each language: $100{" "}
```

2024-08-05 15:34 UTC, wackerow commented
> Looking good on my local @corwintines
> 
> Noting that the content is showing the last paragraph wrapped in a `pre` tag. I guess this is not desired. ![image](https://private-user-images.githubusercontent.com/468158/355147416-d084d656-608a-4de5-9ef8-2f6305063a69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NzIwOTcsIm5iZiI6MTcyMjg3MTc5NywicGF0aCI6Ii80NjgxNTgvMzU1MTQ3NDE2LWQwODRkNjU2LTYwOGEtNGRlNS05ZWY4LTJmNjMwNTA2M2E2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxNTI5NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmI4ZDVhNTNkMmQyMWFlZjgzZTMzZDg4MjY0NTAxN2NhYWUzNzMzNmI0MGQ0ZjY4ODU5MDhkYjlkNDhiNWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UV3bKcDxBOMA1fzjnezXWZOqsZoPOYSXB835yR7tp0U)

<img width="840" alt="image" src="https://github.com/user-attachments/assets/ff1b67e1-2895-4bc8-8176-c9581b57df93">

Posting a patch for this

2024-08-05 15:35 UTC, wackerow approved these changes
Looks good on my end. Can pull in when build passes.

2024-08-05 15:39 UTC, pettinarip approved these changes
LGTM

2024-08-05 17:40 UTC, merged