refactor(pages/what-is-ethereum): migrate to ShadCN
ethereum/ethereum-org-website pull request #13572
Opened 2024-08-04 04:26 UTC by TylerAPfledderer

## Description

Migrates the "What is Ethereum" page to remove direct Chakra imports and use ShadCN components and Tailwind.

Uses the custom ShadCN Link and ButtonLink, but leaves the import location at the tailwind directory.

2024-08-09 17:14 UTC, TylerAPfledderer commented
I would say that the [Learn Page PR](https://github.com/ethereum/ethereum-org-website/pull/13569) is a blocker here; it is establishing the import of the new buttons and links, which means movement of various files.

Once that is done and merged, then update this PR and those imports for the "What is Ethereum" page.

2024-08-14 00:23 UTC, Wachira3712 commented
Wachira3712

2024-08-15 01:31 UTC, TylerAPfledderer commented
@pettinarip should be good now

2024-08-15 14:39 UTC, pettinarip requested changes
@TylerAPfledderer looks good overall. Left a few comments to try to standarize some colors and spacing values. Didn't add a comment in all of the occurrences but you will get the point. Lets see if we can use the tw scale as much as we can.

2024-08-15 14:39 UTC, pettinarip commented on src/pages/what-is-ethereum.tsx
> +    className="text-sm font-medium uppercase leading-xs tracking-wider text-[#7f7f7f] dark:text-[hsla(0,0%,69.8%,.8)]"
Validated with Nuno, lets use `body` color for this
```suggestion
    className="text-sm font-medium uppercase leading-xs tracking-wider"
```

2024-08-15 14:39 UTC, pettinarip commented on src/pages/what-is-ethereum.tsx
> +    className="text-xl leading-xs text-[#666] dark:text-[#b2b2b2]"
same here
```suggestion
    className="text-xl leading-xs"
```

2024-08-15 14:39 UTC, pettinarip commented on src/pages/what-is-ethereum.tsx
> +              <div>
This was a missing space we needed to add
```suggestion
              <Stack className="gap-8">
```

2024-08-15 14:39 UTC, pettinarip commented on src/pages/what-is-ethereum.tsx
> +                <Stack className="gap-[1.45rem]">
```suggestion
                <Stack className="gap-6">
```

2024-08-15 14:39 UTC, pettinarip commented on src/pages/what-is-ethereum.tsx
> +                      <Stack className="mb-[1.45rem] gap-[1.45rem]">
```suggestion
                      <Stack className="mb-4 gap-6">
```

2024-08-15 14:39 UTC, pettinarip commented on src/pages/what-is-ethereum.tsx
> +                      <Stack className="mb-[1.45rem] gap-[1.45rem]">
```suggestion
                      <Stack className="mb-4 gap-6">
```

2024-08-15 14:39 UTC, pettinarip commented on src/pages/what-is-ethereum.tsx
> +                      <Stack className="mb-[1.45rem] gap-[1.45rem]">
```suggestion
                      <Stack className="mb-4 gap-6">
```

2024-08-15 14:39 UTC, pettinarip commented on src/pages/what-is-ethereum.tsx
> +                      <Stack className="mb-[1.45rem] gap-[1.45rem]">
```suggestion
                      <Stack className="mb-4 gap-6">
```

2024-08-15 14:39 UTC, pettinarip commented on src/pages/what-is-ethereum.tsx
> +                <Stack className="gap-[1.45rem]">
```suggestion
                <Stack className="gap-6">
```

2024-08-15 14:39 UTC, pettinarip commented on src/pages/what-is-ethereum.tsx
> +                <Stack className="gap-[1.45rem]">
```suggestion
                <Stack className="gap-6">
```

2024-08-21 10:34 UTC, pettinarip approved these changes
Nice job @TylerAPfledderer.

Will validate a few things with Nuno and then merge it.

2024-08-21 14:48 UTC, merged