Shadcn migration - tooltip
ethereum/ethereum-org-website pull request #13630
Opened 2024-08-13 14:48 UTC by pettinarip

## Description

Implement the Tooltip using the shadcn popover to be used in desktop and mobile devices.

2024-08-13 16:42 UTC, Wachira3712 commented on src/components/Glossary/GlossaryTooltip/index.tsx
> -import Heading from "@/components/Heading"
gatsby-node.js

2024-08-19 21:30 UTC, wackerow requested changes
https://github.com/user-attachments/assets/ec9c6c3a-0798-4df6-9a35-a3033570a4af

Looking good @pettinarip, but seeing this bug where we're unable to hover over the tooltip now without it closing on us.

2024-08-20 10:01 UTC, pettinarip commented
> Looking good @pettinarip, but seeing this bug where we're unable to hover over the tooltip now without it closing on us.

Uhmm good catch @wackerow, yes, that sucks. Trust me, I tested this before haha and it worked as expected. Will look into it soon. Thanks

2024-08-20 14:33 UTC, wackerow approved these changes
Looks good! Working just like production now, thanks @pettinarip!

2024-08-22 11:29 UTC, merged