Use `dark` class for color mode selector
ethereum/ethereum-org-website pull request #13661
Opened 2024-08-16 01:05 UTC by wackerow

## Description
- Refactors to use `.dark` class for color mode management
- Fixes syncing of color theme between in-app toggling and system color preference changes

## Related Issue
Tailwind migration

2024-08-16 01:15 UTC, wackerow commented on src/components/Nav/useNav.ts
> +  const { setTheme, resolvedTheme, systemTheme } = useTheme()
Removed usage of `theme` which was not always responding appropriately to system color preference changes.

In it's place, `resolvedTheme` is a more reliable "light" or "dark" string that the theme will resolve to. Also, `systemTheme` taps into the color mode preference of the system, and updates on change.

2024-08-16 01:15 UTC, wackerow commented on src/components/Nav/useNav.ts
> +    setTheme(lsTheme)
When observing this in the Application dev tools, the "system" is automatically parsed (by the embedded `next-theme` I believe*) to "light" or "dark". Using this approach seems to make sure the `html[class]` is updated by the NextThemeProvider.

<details><summary>*embedded `next-theme` script</summary>
<p>

```js
!(function () {
  try {
    var d = document.documentElement,
      c = d.classList;
    c.remove('light', 'dark');
    var e = localStorage.getItem('theme');
    if ('system' === e || (!e && true)) {
      var t = '(prefers-color-scheme: dark)',
        m = window.matchMedia(t);
      if (m.media !== t || m.matches) {
        d.style.colorScheme = 'dark';
        c.add('dark');
      } else {
        d.style.colorScheme = 'light';
        c.add('light');
      }
    } else if (e) {
      c.add(e || '');
    }
    if (e === 'light' || e === 'dark') d.style.colorScheme = e;
  } catch (e) {}
})();
```

</p>
</details>

2024-08-17 10:07 UTC, pettinarip requested changes
@wackerow a few things related to this PR and the color theme mechanism

1. I pushed a new PR https://github.com/ethereum/ethereum-org-website/pull/13676 to sync the color themes between chakra and next-themes. Maybe this PR will clarify a bit what is going on between the two color theme syncs.

2. Left a comment/question/opinion here about the manual system color selection.

3. On choosing the `class` method, would you explain again why we would prefer this over  the `data-` attr? question because chakra will automatically detect the latter but not the class and that might save us from manually sync the color themes.

=====
Saw this issue in the preview deploy
1. Load the page in incognito
2. Switch your system color mode
3. Visual diff
![image](https://github.com/user-attachments/assets/988ea87f-cd33-4384-9989-3d2204f8dbf4)

I guess this issue is related to the usage of  `theme` instead of `resolvedTheme` (fixed in #13663) as this branch is outdated.

2024-09-06 14:17 UTC, wackerow commented
Closing out; avoiding `.dark` solution at th time as it doesn't seem to provide benefit over existing selector. We'll also plan to add a "system" option for color modes instead of one-off-solutions.

2024-09-06 14:17 UTC, closed without merging