Adding Grandine to various pages
ethereum/ethereum-org-website pull request #13677
Opened 2024-08-17 17:06 UTC by arredr2

## Description

I updated the following pages by adding Grandine to any mention of CL clients.
    - Nodes and clients (https://ethereum.org/en/developers/docs/nodes-and-clients)
    - Client diversity (https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity/#consensus-clients)
    - Ethereum Support (https://ethereum.org/en/community/support/#consensus-clients)
    - Adding staking products or services (https://ethereum.org/en/contributing/adding-staking-products/#node-or-client-tooling)
    - Ethereum Governance (https://ethereum.org/en/governance/#who-is-involved)

## Related Issue

2024-08-19 16:49 UTC, wackerow requested changes
Thanks @arredr2! Correct me if I'm wrong, but Grandine appears to still be in beta, with release version <v1 still. Left some comments; don't see why we can't still list Grandine, but in the past we've marked those not yet fully in production as `(beta)` and graduate it over time when ready.

2024-08-19 16:49 UTC, wackerow commented on public/content/developers/docs/nodes-and-clients/index.md
> +| [Grandine](https://docs.grandine.io/)                         | Rust       | Linux, Windows, macOS | Beacon Chain, Goerli, Sepolia, and more                           |
Please move this to last and mark with `(beta)` at the end given we are not yet at a v1 production release.

2024-08-19 16:49 UTC, wackerow commented on public/content/developers/docs/nodes-and-clients/index.md
> +
Please move to end (below Teku)

2024-08-19 16:49 UTC, wackerow commented on public/content/developers/docs/nodes-and-clients/client-diversity/index.md
> +
Would avoid this listing until Grandine is out of beta with at least a v1 release

```suggestion
```

2024-08-19 16:49 UTC, wackerow commented on public/content/developers/docs/nodes-and-clients/index.md
> +
Would avoid phrasing such as "the latest consensus client" as this can change.

2024-08-26 13:43 UTC, arredr2 commented
@wackerow thanks for your comments! I have updated based on your suggestions.

2024-09-02 15:56 UTC, merged