[ShadCN] refactor(pages/staking): migrate page to ShadCN
ethereum/ethereum-org-website pull request #13675
Opened 2024-08-17 05:07 UTC by TylerAPfledderer

## Description

Migrate page to use ShadCN/Tailwind and import the new UI components used.

2024-08-19 17:54 UTC, pettinarip requested changes
@TylerAPfledderer nice!

Left a couple of comments for @nloureiro to confirm. Once we are ok there, this is ready to be merged 👍🏼

2024-08-20 08:06 UTC, nloureiro commented on src/pages/staking/index.tsx
> -    bg="layer2Gradient"
@TylerAPfledderer, great work. All looks great

@pettinarip, regarding the gradient, go for it! they look so similar that s hard to see the difference

2024-08-20 09:58 UTC, pettinarip approved these changes
LGMT now 🚀

2024-08-20 11:27 UTC, pettinarip approved these changes

2024-08-20 11:27 UTC, merged