Update index.md
ethereum/ethereum-org-website pull request #13758
Opened 2024-08-31 08:23 UTC by TakeASwing-420

### Description

Refactored the variable name `node` to `node_hash` to remove ambiguity. This change improves code clarity by explicitly indicating that the variable holds the hash of a node, not the node itself.

### Changes
- Replaced `node` with `node_hash` throughout the `update` and `delete` functions.

2024-08-31 08:36 UTC, TakeASwing-420 commented
@minimalsm, the code snippet should also comment a line saying that we need a  __17__ length array for `16 digit hexadecimal` + __1__ extra for `value store`...otherwise that part is also confusing. Although I did not add anything in my commit regarding this issue.

2024-09-04 04:35 UTC, corwintines approved these changes
Thanks @TakeASwing-420 

I fixes the areas where this update was missed in the codeblock. The parameters were changed, but not their use in the functions.

2024-09-04 04:35 UTC, corwintines commented
@all-contributors can you add @TakeASwing-420 for content

2024-09-04 04:38 UTC, corwintines requested changes
@TakeASwing-420 upon reviewing this file a bit more, I think this change is missing out throughout other code examples. Could you go through and fix this please :)

2024-09-04 08:19 UTC, TakeASwing-420 commented
@corwintines Please Check the updates and tell if it's okay.

2025-01-13 23:09 UTC, corwintines approved these changes

2025-01-13 23:09 UTC, merged