Tutorial: Using zero-knowledge for a secret state
ethereum/ethereum-org-website pull request #13783
Opened 2024-09-03 19:50 UTC by qbzzt

## Description

Onchain games are limited because they cannot keep any hidden information. After reading this tutorial, a reader will be able to combine zero-knowledge proofs and server components (see https://github.com/ethereum/ethereum-org-website/pull/13228) to create verifiable games with a secret state, offchain, component.

The technique to do this will be demonstrated by creating a [minesweeper](https://en.wikipedia.org/wiki/Minesweeper_(video_game)) game.

## Related Issue

Closing: #13234

2024-10-16 17:42 UTC, qbzzt commented
@corwintines , can I have a review on this? It's a very long article (probably the longest I've written), but I think it would be a valuable tutorial.

2024-11-04 19:02 UTC, qbzzt commented
Can I please have a review on this? It's a long and complex article, but it's a topic that can't be addressed in any other way.

2025-02-17 23:21 UTC, wackerow requested changes
Hey @qbzzt! Huge apologies for delay on this one, and apologies it slipped through. Super interesting topic, don't let the delay be confused with this not being very appreciated. 

I pushed a couple small adjustments and got the path to build.. left a couple other small comments, but most importantly:

I'm having trouble getting this to work... Following the instructions I'm not getting much when I run `pnpm dev`, just wondering if I'm missing something here.

Also a note about dependency versions that I personally hit a small snag on... unlikely something that would interfere with someone doing this advances a tutorial, but could be a nice touch to just mention the node and pnpm versions that are expected.

2025-02-17 23:21 UTC, wackerow commented on public/content/developers/tutorials/secret-state/index.md
> +   pnpm install
Personally encountered some node and pnpm version issues here. Looks like user will need node 18 and pnpm 8 or 9? I had issues above this.

2025-02-17 23:21 UTC, wackerow commented on public/content/developers/tutorials/secret-state/index.md
> +   Note that the startup takes a long time. To see the progress, first use the down arrow to scroll to the _contracts_ tab to see the MUD contracts being deployed. When you get the message _Waiting f
I'm not getting this personally.. I get something like this, and then the process finishes.

```sh
> mud-template-react@ dev .
> mprocs
```

Nothing ends up being served to `localhost:3000` when I do this.

2025-02-17 23:21 UTC, wackerow commented on public/content/developers/tutorials/secret-state/index.md
> +  - `gameId`: 32 byte value that is the hash of the map the player is playing on (the game identifier).
```suggestion
  - `gameId`: 32-byte value that is the hash of the map the player is playing on (the game identifier).
```

2025-02-17 23:21 UTC, wackerow commented on public/content/developers/tutorials/secret-state/index.md
> +  - `gameId`: 32 byte value that is the hash of the map the player is playing on (the game identifier).
```suggestion
  - `gameId`: 32-byte value that is the hash of the map the player is playing on (the game identifier).
```

2025-02-17 23:21 UTC, wackerow commented on public/content/developers/tutorials/secret-state/index.md
> +Additionally, we could use [a setup ceremony](https://zokrates.github.io/toolbox/trusted_setup.html#initializing-a-phase-2-ceremony). The advantage of a setup ceremony is that you need either the ent
```suggestion
Additionally, we could use [a setup ceremony](https://zokrates.github.io/toolbox/trusted_setup.html#initializing-a-phase-2-ceremony). The advantage of a setup ceremony is that you need either the entropy or some intermediate result from each participant to cheat on the zero-knowledge proof. If at least one ceremony participant is honest and deletes that information, the zero-knowledge proofs are safe from certain attacks. However, there is _no mechanism_ to verify that information has been deleted from everywhere. If zero-knowledge proofs are critically important, you want to participate in the setup ceremony.
```

2025-02-17 23:21 UTC, wackerow commented on public/content/developers/tutorials/secret-state/index.md
> +Zero-knowlege proofs use [arithmetic circuits](https://medium.com/web3studio/simple-explanations-of-arithmetic-circuits-and-zero-knowledge-proofs-806e59a79785), which don't have an easy equivalent to
```suggestion
Zero-knowledge proofs use [arithmetic circuits](https://medium.com/web3studio/simple-explanations-of-arithmetic-circuits-and-zero-knowledge-proofs-806e59a79785), which don't have an easy equivalent to an `if` statement. Instead, they use the equivalent of the [conditional operator](https://en.wikipedia.org/wiki/Ternary_conditional_operator). If `a` can be either zero or one, you can calculate `if a { b } else { c }` as `ab+(1-a)c`.
```

2025-02-17 23:21 UTC, wackerow commented on public/content/developers/tutorials/secret-state/index.md
> +### Why zero-knowlege {#why-zero-knowledge}
```suggestion
### Why zero-knowledge {#why-zero-knowledge}
```

2025-02-17 23:30 UTC, qbzzt commented
Thank you. I will replicate.

On Mon, Feb 17, 2025, 5:21 PM Paul Wackerow ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hey @qbzzt <https://github.com/qbzzt>! Huge apologies for delay on this
> one, and apologies it slipped through. Super interesting topic, don't let
> the delay be confused with this not being very appreciated.
>
> I pushed a couple small adjustments and got the path to build.. left a
> couple other small comments, but most importantly:
>
> I'm having trouble getting this to work... Following the instructions I'm
> not getting much when I run pnpm dev, just wondering if I'm missing
> something here.
>
> Also a note about dependency versions that I personally hit a small snag
> on... unlikely something that would interfere with someone doing this
> advances a tutorial, but could be a nice touch to just mention the node and
> pnpm versions that are expected.
> ------------------------------
>
> In public/content/developers/tutorials/secret-state/index.md
> <https://github.com/ethereum/ethereum-org-website/pull/13783#discussion_r1958845460>
> :
>
> > +
> +To run the minesweeper example:
> +
> +1. Make sure you [have the prerequisites installed](https://mud.dev/quickstart#prerequisites): [Node](https://mud.dev/quickstart#prerequisites), [Foundry](https://book.getfoundry.sh/getting-started/installation), [`git`](https://git-scm.com/downloads), and [`pnpm`](https://git-scm.com/downloads).
> +
> +2. Clone the repository.
> +
> +   ```sh copy
> +   git clone https://github.com/qbzzt/20240901-secret-state.git
> +   ```
> +
> +3. Install the packages.
> +
> +   ```sh copy
> +   cd 20240901-secret-state/
> +   pnpm install
>
> Personally encountered some node and pnpm version issues here. Looks like
> user will need node 18 and pnpm 8 or 9? I had issues above this.
> ------------------------------
>
> In public/content/developers/tutorials/secret-state/index.md
> <https://github.com/ethereum/ethereum-org-website/pull/13783#discussion_r1958846067>
> :
>
> > +   ```sh copy
> +   pnpm dev
> +   ```
> +
> +   Note that the startup takes a long time. To see the progress, first use the down arrow to scroll to the _contracts_ tab to see the MUD contracts being deployed. When you get the message _Waiting for file changes…_, the contracts are deployed and further progress will happen in the _server_ tab. There, you wait until you get the message _Verifier address: 0x...._.
>
> I'm not getting this personally.. I get something like this, and then the
> process finishes.
>
> > mud-template-react@ dev .> mprocs
>
> Nothing ends up being served to localhost:3000 when I do this.
> ------------------------------
>
> In public/content/developers/tutorials/secret-state/index.md
> <https://github.com/ethereum/ethereum-org-website/pull/13783#discussion_r1958846207>
> :
>
> > +
> +5. Now you can browse to [the client](http://localhost:3000), click **New Game**, and start playing.
> +
> +### Tables {#tables}
> +
> +We need [several tables](https://github.com/qbzzt/20240901-secret-state/blob/main/packages/contracts/mud.config.ts) onchain.
> +
> +- `Configuration`: This table is a singleton, it has no key and single record. It is used to hold game configuration information:
> +  - `height`: The height of a minefield
> +  - `width`: The width of a minefield
> +  - `numberOfBombs`: The number of bombs in each minefield
> +- `VerifierAddress`: This table is also a singleton. It is used to hold one part of the configuration, the address of the verifier contract (`verifier`). We could have put this information in the `Configuration` table, but it is set by a different component, the server, so it's easier to put it in a separate table.
> +
> +- `PlayerGame`: The key is the player's address. The data is:
> +
> +  - `gameId`: 32 byte value that is the hash of the map the player is playing on (the game identifier).
>
> ⬇️ Suggested change
>
> -  - `gameId`: 32 byte value that is the hash of the map the player is playing on (the game identifier).
> +  - `gameId`: 32-byte value that is the hash of the map the player is playing on (the game identifier).
>
> ------------------------------
>
> In public/content/developers/tutorials/secret-state/index.md
> <https://github.com/ethereum/ethereum-org-website/pull/13783#discussion_r1958846348>
> :
>
> > +  - `width`: The width of a minefield
> +  - `numberOfBombs`: The number of bombs in each minefield
> +- `VerifierAddress`: This table is also a singleton. It is used to hold one part of the configuration, the address of the verifier contract (`verifier`). We could have put this information in the `Configuration` table, but it is set by a different component, the server, so it's easier to put it in a separate table.
> +
> +- `PlayerGame`: The key is the player's address. The data is:
> +
> +  - `gameId`: 32 byte value that is the hash of the map the player is playing on (the game identifier).
> +  - `win`: a boolean that is whether the player won the game.
> +  - `lose`: a boolean that is whether the player lost the game.
> +  - `digNumber`: the number of successful digs in the game.
> +
> +- `GamePlayer`: This table holds the reverse mapping, from `gameId` to player address.
> +
> +- `Map`: The key is a tuple of three values:
> +
> +  - `gameId`: 32 byte value that is the hash of the map the player is playing on (the game identifier).
>
> ⬇️ Suggested change
>
> -  - `gameId`: 32 byte value that is the hash of the map the player is playing on (the game identifier).
> +  - `gameId`: 32-byte value that is the hash of the map the player is playing on (the game identifier).
>
> ------------------------------
>
> In public/content/developers/tutorials/secret-state/index.md
> <https://github.com/ethereum/ethereum-org-website/pull/13783#discussion_r1958847421>
> :
>
> > +
> +[Zokrates](https://zokrates.github.io/) isn't the only zero-knowledge library available, but it is similar to a normal, [imperative](https://en.wikipedia.org/wiki/Imperative_programming) programming language and supports boolean variables.
> +
> +For your application, with different requirements, you might prefer to use [Circum](https://docs.circom.io/getting-started/installation/) or [Cairo](https://www.cairo-lang.org/tutorials/getting-started-with-cairo/).
> +
> +### When to compile Zokrates {#when-compile-zokrates}
> +
> +In this program we compile the Zokrates programs [every time the server starts](https://github.com/qbzzt/20240901-secret-state/blob/main/packages/server/src/zero-knowledge.ts#L60-L61). This is clearly a waste of resources, but this is a tutorial, optimized for simplicity.
> +
> +If I were writing a production-level application, I'd check if I have a file with the compiled Zokrates programs at this minefield size, and if so use that. The same is true for deploying a verifier contract onchain.
> +
> +### Creating the verifier and prover keys {#key-creation}
> +
> +[Key creation](https://github.com/qbzzt/20240901-secret-state/blob/main/packages/server/src/zero-knowledge.ts#L63-L69) is another pure calculation that needn't be done more than once for a given minefield size. Again, it is done only once for the sake of simplicity.
> +
> +Additionally, we could use [a setup ceremony](https://zokrates.github.io/toolbox/trusted_setup.html#initializing-a-phase-2-ceremony). The advantage of a setup ceremony is that you need either the entropy or some intermediate result from each participant to cheat on the zero-knowlege proof. If at least one ceremony participant is honest and deletes that information, the zero-knowledge proofs are safe from certain attacks. However, there is _no mechanism_ to verify that information has been deleted from everywhere. If zero-knowledge proofs are critically important, you want to participate in the setup ceremony.
>
> ⬇️ Suggested change
>
> -Additionally, we could use [a setup ceremony](https://zokrates.github.io/toolbox/trusted_setup.html#initializing-a-phase-2-ceremony). The advantage of a [...]

2025-02-18 03:35 UTC, qbzzt commented on public/content/developers/tutorials/secret-state/index.md
> +   Note that the startup takes a long time. To see the progress, first use the down arrow to scroll to the _contracts_ tab to see the MUD contracts being deployed. When you get the message _Waiting f
I think it's because mprocs is not installed, at least for that version of node. I did two things that should fix it:

1. Removed the restriction on Node version
2. Suggested that people run `mprocs` directly rather than through `pnpm dev`.

2025-02-18 03:39 UTC, qbzzt commented on public/content/developers/tutorials/secret-state/index.md
> +   Note that the startup takes a long time. To see the progress, first use the down arrow to scroll to the _contracts_ tab to see the MUD contracts being deployed. When you get the message _Waiting f
BTW, thank you. I'm really glad to make progress on this.

2025-02-18 03:50 UTC, qbzzt commented on public/content/developers/tutorials/secret-state/index.md
> +   pnpm install
I tried with node 20 and pnpm 10, and it worked - after I removed the requirement from `package.json` ;-)

2025-02-18 21:40 UTC, wackerow requested changes
Awesome! Thanks a lot @qbzzt, this was a great read through. Definitely a topic I'm not as well versed in, so was nice to clone and see a real example and have the stack broken down like that.

Couple small polishes/patches and one suggestion then I think we're good to pull this in!

2025-02-18 21:40 UTC, wackerow commented on public/content/developers/tutorials/secret-state/index.md
> +
Awesome, this is working great now! I wonder if we should just show a "code-snippet" of the terminal one should expect here, since it's just text output:

```
┏Processes━━━━━━━━━━━━━━━━━━━┓┌Terminal────────────────────────────────────────┐
┃•client                  UP ┃│                                                │
┃ server                  UP ┃│  VITE v4.5.3  ready in 662 ms                  │
┃ contracts               UP ┃│                                                │
┃ anvil                   UP ┃│  ➜  Local:   http://localhost:3000/            │
┃                            ┃│  ➜  Network: use --host to expose              │
┃                            ┃│  ➜  press h to show help                       │
┃                            ┃│                                                │
┃                            ┃│                                                │
┃                            ┃│                                                │
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛└────────────────────────────────────────────────┘
┌Help──────────────────────────────────────────────────────────────────────────┐
│ <C-a: Toggle focus>  <q: Quit>  <j: Next>  <k: Prev>  <s: Start>  <x: Stop>  │
└──────────────────────────────────────────────────────────────────────────────┘
```

If it _doesn't_ work, the comment below doesn't make much sense, but this could at least give folks a visual to know they are, or are not on the right track.

2025-02-18 21:40 UTC, wackerow commented on public/content/developers/tutorials/secret-state/index.md
> +The math to verify Zokrates is beyond the scope of this tutorial (and my abilities). However, we can run various checks on the zero-knowledge code to verify that if it is not done correctly it fails.
```suggestion
The math to verify Zokrates is beyond the scope of this tutorial (and my abilities). However, we can run various checks on the zero-knowledge code to verify that if it is not done correctly it fails. All of these tests are going to require us to change [`zero-knowledge.ts`](https://github.com/qbzzt/20240901-secret-state/blob/main/packages/server/src/zero-knowledge.ts) and restart the entire application. It is not sufficient to restart the server process, because it puts the application in an impossible state (the player has a game in progress, but the game is no longer available to the server).
```

2025-02-18 21:40 UTC, wackerow commented on public/content/developers/tutorials/secret-state/index.md
> +## Conclusion: When is this the appropriate technique? {#conclusion}
```suggestion
## Conclusion: What is this the appropriate technique? {#conclusion}
```

2025-02-19 02:43 UTC, qbzzt commented on public/content/developers/tutorials/secret-state/index.md
> +
Done.

2025-02-20 00:04 UTC, wackerow approved these changes
Looks great, thanks so much @qbzzt! 🔥

2025-02-20 04:16 UTC, merged

2025-02-20 04:17 UTC, wackerow commented on public/content/developers/tutorials/secret-state/index.md
> +## Conclusion: When is this the appropriate technique? {#conclusion}
Ah sorry, my bad.. yeah, "when" is fine here