truncate long event description
ethereum/ethereum-org-website pull request #13919
Opened 2024-09-20 14:56 UTC by sumitvekariya

## Description

The event description had no text limitation and could have been too long. So now event description is limited to 230 characters, if longer than that it is truncated to 230 characters followed by `...`

## Related Issue

https://github.com/ethereum/ethereum-org-website/issues/13914

2024-09-23 16:11 UTC, wackerow requested changes
Hey @sumitvekariya! Thanks for the PR... Apologies if the issue may have been misleading, but I think we can get away with simply restricting the _line_ count here (instead of _word_ count), which we can use a simply TailwindCSS class for this: `line-clamp-x`... by default this has up to `line-clamp-6`, so I would suggest this )(just chatted with @konopkja as well who is in agreement)

Left a suggestion for how we can simplify to use this approach

![Screenshot2024_09_23_090716](https://github.com/user-attachments/assets/8f3ac3e8-1dba-4a2e-baca-0aff5dd80ee1)

2024-09-23 16:11 UTC, wackerow commented on src/components/EventCard.tsx
> +
```suggestion
```

2024-09-23 16:11 UTC, wackerow commented on src/components/EventCard.tsx
> +              <Text fontSize="sm">{truncatedDescription}</Text>
We'll just migrate this specific element so we can use tailwind:
```suggestion
              <p className="text-sm line-clamp-6">{description}</p>
```

2024-10-04 11:32 UTC, corwintines approved these changes
Thanks @sumitvekariya!

2024-10-04 11:56 UTC, merged