Shadcn migration - more components
ethereum/ethereum-org-website pull request #13951
Opened 2024-09-24 17:13 UTC by pettinarip

## Description

Migrate the following components to TW.

- Banners/UpgradeBannerNotification.tsx
- Banners/BugBountyBanner/index.tsx
- CopyToClipboard.tsx
- EnvWarningBanner.tsx
- EthVideo.tsx
- FeaturedText/index.tsx
- IdAnchor.tsx
- LearningToolsCardGrid.tsx
- MarkdownImage.tsx
- MergeArticleList.tsx
- StatErrorMessage.tsx
- TranslationChartImage/index.tsx
- YouTube.tsx

2024-09-26 20:25 UTC, wackerow requested changes
Overall looking good, just spotted the IdAnchor needed updating

2024-09-26 20:25 UTC, wackerow commented on src/components/IdAnchor.tsx
<img width="519" alt="image" src="https://github.com/user-attachments/assets/220a3566-fa52-4617-8f33-9f0925210eb1">

Looks like most of this was missed... Will post a sub-branch PR with a fix real quick

2024-09-26 20:59 UTC, wackerow commented on src/components/IdAnchor.tsx
#13980

2024-09-27 07:00 UTC, pettinarip commented on src/components/IdAnchor.tsx
Ahh nice! good catch @wackerow thanks for the PR!

2024-09-30 18:24 UTC, wackerow commented on src/components/MarkdownImage.tsx
> +      >
I'm not sure we need the `target` and `rel` any more.... we're using `ui/Link` now which should parse this with `const isExternal = url.isExternal(href)`

```suggestion
      <InlineLink href={transformedSrc} locale={false}>
```

2024-10-02 07:30 UTC, wackerow commented on src/components/MarkdownImage.tsx
> +      >
Never mind! I see we're feeding local images to this so this override is needed. Approving =)

2024-10-02 07:31 UTC, wackerow approved these changes
Looks good! Thanks @pettinarip!

2024-10-02 07:31 UTC, merged