Migrate layer 2 page to shadcn, and updates for layer 2 migration
ethereum/ethereum-org-website pull request #13987
Opened 2024-09-27 14:08 UTC by corwintines

** Description **

Migrates layer 2 page to shadcn
Move layer 2 page to /layer-2/learn
Updates for the layer 2 migration to this page

2024-09-30 16:53 UTC, wackerow requested changes
Nice @corwintines! Lookin good, just dropped an initial round of feedback and thoughts.

2024-09-30 16:53 UTC, wackerow commented on public/images/layer-2/learn-hero.png
<img width="1568" alt="image" src="https://github.com/user-attachments/assets/515e6654-b547-405d-98b4-57b1f422f287">

Noticing this is an image the chops on the top and bottom edges... looks a little strange having padding in the Y-direction here inside the hero cc: @nloureiro

2024-09-30 16:53 UTC, wackerow commented on src/components/Callout.tsx
> +        <div className="mt-[-10rem] self-center">
```suggestion
        <div className="-mt-40 self-center">
```

2024-09-30 16:53 UTC, wackerow commented on src/components/Callout.tsx
> +          )}
I'm a little unclear why we're opening up the props to optionally accept `title` and `description` or the keys for these:

<img width="531" alt="image" src="https://github.com/user-attachments/assets/ac96e70d-ec60-4239-8bf4-9193d120e208">

Is the plan to change these components to not have to handle the translation keys? As-is we not longer have any of the props as required.

2024-09-30 16:53 UTC, wackerow commented on src/lib/utils/translations.ts
>    }
Just noting that as-is the `page-layer-2` namespace will be loaded on `/layer-2/learn/`; is this what we want? If not, I'd change this one to not use `startsWith()`

2024-09-30 16:53 UTC, wackerow commented on src/intl/en/page-layer-2-learn.json
> +  "page-layer-2-learn-what-is-layer-2-title": "What is layer 2?",
Seeing 4 instances of "What is layer 2"... one of which has a question mark

1. Should we have a question mark at the end of this string? (I think we should)
2. Do we need to repeat this key, or can we simplify to just have one instance of "What is layer 2?"

2024-10-01 06:30 UTC, defihook reviewed
great work
thanks

2024-10-29 04:36 UTC, merged

2024-10-29 10:24 UTC, defihook reviewed
Looks good