Removed deprecated eth_coinbase from json-rpc docs[#13996]
ethereum/ethereum-org-website pull request #13997
Opened 2024-09-29 14:33 UTC by MaryNfs

## Description

As discussed in [ethereum/go-ethereum#29747](https://github.com/ethereum/go-ethereum/issues/29747), eth_coinbase no longer returns an address in v1.14.0+ and has been deprecated.
This PR removes the deprecated eth_coinbase RPC method from the JSON-RPC API list.

## Related Issue
#13996

2024-10-02 15:19 UTC, wackerow requested changes
Thanks @MaryNfs! Agree with the issue you posted, but am hesitant to remove this entirely for archival/historical purposes.

I might suggest something similar to what the playground we link out to does:

https://ethereum-json-rpc.com/?method=eth_coinbase

If you go here you'll see that the `eth_coinbase` method is still available, but executing shows `"details": "Method not supported"`.

I'd suggest we keep the h3 section and initial comment, and add a note that this method has been deprecated, and note as of when this occured. Something like this:

```
### eth_coinbase {#eth_coinbase}

Returns the client coinbase address.

**No longer supported (deprecated as of _____)**
```

2024-10-02 15:19 UTC, wackerow commented on public/content/developers/docs/apis/json-rpc/index.md
> +We can verify that the interface is running by retrieving the Coinbase address(by obtaining the first address from the array of accounts) and balance using [curl](https://curl.se). Please note that d
1. I know you didn't change this, but we should use lowercase `coinbase` here
2. Need a space

```suggestion
We can verify that the interface is running by retrieving the coinbase address (by obtaining the first address from the array of accounts) and balance using [curl](https://curl.se). Please note that data in these examples will differ on your local node. If you want to try these commands, replace the request params in the second curl request with the result returned from the first.
```

2024-10-03 01:29 UTC, MaryNfs commented
> I'd suggest we keep the h3 section and initial comment, and add a note that this method has been deprecated, and note as of when this occured. Something like this:
> 
> ```
> ### eth_coinbase {#eth_coinbase}
> 
> Returns the client coinbase address.
> 
> **No longer supported (deprecated as of _____)**
> ```

Hi @wackerow 
Thanks for the feedback!
I've made the changes as you suggested.
Let me know if there’s anything else you’d like me to adjust!

2024-10-04 11:38 UTC, wackerow approved these changes
Looks good, thanks @MaryNfs!

2024-10-04 11:38 UTC, wackerow commented on public/content/developers/docs/apis/json-rpc/index.md
> +> **Note:** This method has been deprecated as of **v1.14.0** and is no longer supported. Attempting to use this method will result in a "Method not supported" error.
> Attempting to use this method will result in a "Method not supported" error.

Should we consider replacing this sentence with a comment similar to below about using `eth_accounts` instead? Don't think it needs to block here, but curious thoughts for further iteration.

2024-10-04 11:39 UTC, merged

2024-10-04 11:39 UTC, wackerow commented
@all-contributors please add @MaryNfs for content bug patch