feat: migrate ExpandableCard component to shadcn
ethereum/ethereum-org-website pull request #14017
Opened 2024-10-01 18:44 UTC by kushagrasarathe

Migrates `ExpandableCard` component to ShadCN from Chakra

## Description
This PR updates the ExpandableCard to use ShadcnUI's accordion component instead of Chakra component. Styles have been updated for both light and dark version.

## Note
@pettinarip I've used the `accordion` from `/tailwind` directory and did not directly overwrite the classes in the primitives, instead added classes in the `ExpandableCard` component to keep the UI similar to how it was with Chakra.

Lemme know if this approach doesn't look good, happy to update it. 

Also the default behaviour on shadcn accordion doesn't allow the accordion it to be closed if clicked on content, I can add this using mouse events, thoughts?

## Related Issue
#13946

2024-10-02 17:22 UTC, pettinarip requested changes
Great start @kushagrasarathe! The approach you took is perfect. Left a few requests on color token changes to match the Design System.

This is how I see it on https://deploy-preview-14017--ethereumorg.netlify.app/en/contributing/style-guide/
![image](https://github.com/user-attachments/assets/4951781e-01ff-4b74-812a-74c3818c6f6e)

We would also need to align the text on the header texts to the left.

2024-10-02 17:22 UTC, pettinarip commented on src/components/ExpandableCard.tsx
> +          className="rounded-sm border border-gray-200/50 hover:bg-gray-100/50 dark:border-gray-600 dark:hover:bg-gray-800"
A few color changes to match the new colors we have in the Design System
```suggestion
          className="rounded-sm border hover:bg-background-highlight"
```

2024-10-02 17:22 UTC, pettinarip commented on src/components/ExpandableCard.tsx
> +            className="w-full p-6 transition-colors hover:bg-gray-50 hover:text-black md:p-6 dark:hover:bg-gray-800 dark:hover:text-white [&[data-state=open]]:bg-transparent [&[data-state=open]]:text
Similar case with colors, lets simplify this by using some of the DS colors.
```suggestion
            className="w-full p-6 transition-colors hover:bg-background-highlight hover:text-black md:p-6 dark:hover:text-white [&[data-state=open]]:bg-transparent [&[data-state=open]]:text-black dark:[&[data-state=open]]:text-white"
```

2024-10-02 17:22 UTC, pettinarip commented on src/components/ExpandableCard.tsx
> +                <p className="mb-0 w-fit text-sm text-gray-600">
color change and unnecessary margin class in this case
```suggestion
                <p className="w-fit text-sm text-body-medium">
```

2024-10-02 17:22 UTC, pettinarip commented on src/components/ExpandableCard.tsx
> +              <span className="my-auto text-md text-purple-600 sm:ml-auto dark:text-purple-400">
```suggestion
              <span className="my-auto text-md text-primary sm:ml-auto">
```

2024-10-02 17:22 UTC, pettinarip commented on src/components/ExpandableCard.tsx
> +          <AccordionContent className="cursor-pointer p-6 pt-0 md:p-6 md:pt-0">
Lets remove the cursor pointer now that we do not support that.
```suggestion
          <AccordionContent className="p-6 pt-0 md:p-6 md:pt-0">
```

2024-10-02 17:22 UTC, pettinarip commented on src/components/ExpandableCard.tsx
> +            <div className="border-t border-gray-200 pt-6 text-md text-gray-800 dark:border-gray-600 dark:text-white">
Lets go with our default color on border and body color.
```suggestion
            <div className="border-t pt-6 text-md text-body">
```

2024-10-03 18:38 UTC, kushagrasarathe commented
Hey @pettinarip pushed the changes requestd 🙌 

> Great start @kushagrasarathe! The approach you took is perfect. Left a few requests on color token changes to match the Design System.
> 
> This is how I see it on https://deploy-preview-14017--ethereumorg.netlify.app/en/contributing/style-guide/ ![image](https://private-user-images.githubusercontent.com/468158/372965111-4951781e-01ff-4b74-812a-74c3818c6f6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NzUzMTksIm5iZiI6MTcyNzk3NTAxOSwicGF0aCI6Ii80NjgxNTgvMzcyOTY1MTExLTQ5NTE3ODFlLTAxZmYtNGI3NC04MTJhLTc0YzM4MThjNmY2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNzAzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzFkMzMyNWRkNDNiNWU1N2M2MTMxYTdlNjU1Y2FjMzFmNTg4Zjg3ZDM4NzRlZTgxOWI2NmJhNmY4NzA3NWMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6EIf2gLxR0asNe0m3iySPfHCCq_auuljs3EaGJ94AdE)
> 
> We would also need to align the text on the header texts to the left.

2024-10-04 10:42 UTC, pettinarip approved these changes
Thanks @kushagrasarathe !

2024-10-04 10:42 UTC, merged