Migrate Gitstars component to shadcn/tailwind
ethereum/ethereum-org-website pull request #14073
Opened 2024-10-05 17:48 UTC by Baystef

## Description
Migrated the GitStars component styling to Tailwind/Shadcn

## Related Issue
#13946

2024-10-09 19:28 UTC, pettinarip requested changes
Good job @Baystef, left a few comments

2024-10-09 19:28 UTC, pettinarip commented on src/components/GitStars.tsx
> +      <Flex className="rounded border border-border bg-background-medium no-underline hover:fill-primary hover:shadow-table-item-box-hover">
removing as it is redundant, border will default to the `border` color.
```suggestion
      <Flex className="rounded border bg-background-medium no-underline hover:fill-primary hover:shadow-table-item-box-hover">
```

2024-10-15 13:40 UTC, pettinarip approved these changes
@Baystef i've polished a bit the styles for this component. Thanks for the PR

2024-10-15 14:31 UTC, Baystef commented
> @Baystef i've polished a bit the styles for this component. Thanks for the PR

Thanks. Is there a design you're following? @pettinarip

2024-10-15 14:31 UTC, merged