Migrate `DatesAndTimeline` component to Shadcn/Tailwind
ethereum/ethereum-org-website pull request #14071
Opened 2024-10-05 15:05 UTC by 0xgun

## Description
Migrate `DatesAndTimeline` component to Shadcn/Tailwind from Chakra

## Related Issue

https://github.com/ethereum/ethereum-org-website/issues/13946

2024-10-26 13:20 UTC, 0xgun commented
@pettinarip could you please review this PR

2024-10-28 12:38 UTC, pettinarip requested changes
@0xgun looks good visually but left a few comments to use the `cn` function and defined DS colors.

2024-10-28 12:38 UTC, pettinarip commented on src/components/Translatathon/DatesAndTimeline.tsx
> +            className={`flex border-l ${index === dates.length - 1 ? "border-transparent" : "border-purple-600 dark:border-purple-400"} px-4 ${index === dates.length - 1 ? "pb-0" : "pb-16"} gap-4`}
Let's take advantage of the `cn` function for conditional styles. https://github.com/ethereum/ethereum-org-website/blob/dev/src/lib/utils/cn.ts

In this case we could have something like this
```tsx
className={cn("flex border-l", index === dates.length - 1 ? "border-transparent" : "border-primary", ....)}
```

Also, use `border-primary` for the purple color. This is a color from the DS and is already included. You can check them out in this line https://github.com/0xgun/ethereum-org-website/blob/dev/tailwind.config.ts#L164

2024-10-28 12:38 UTC, pettinarip commented on src/components/Translatathon/DatesAndTimeline.tsx
> +                    : "bg-purple-100 dark:bg-purple-900"
`cn` funciton +
```suggestion
                  isLive
                    ? "bg-primary"
                    : "bg-primary-low-contrast"
```

2024-10-28 12:38 UTC, pettinarip commented on src/components/Translatathon/DatesAndTimeline.tsx
> +                    className={`mt-2 ${date.link === APPLICATION_URL && !isLive ? "pointer-events-none text-disabled" : ""}`}
Use `cn` function.

2024-10-29 07:48 UTC, 0xgun commented
Hey @pettinarip , I have made all the requested changes

2024-10-31 14:33 UTC, pettinarip commented on src/components/Translatathon/DatesAndTimeline.tsx
> +                    ? "dark:text-ButtonLinkack bg-purple-600 text-white dark:bg-purple-400"
```suggestion
                    ? "dark:text-back bg-purple-600 text-white dark:bg-purple-400"
```

2024-10-31 14:33 UTC, pettinarip commented on src/components/Translatathon/DatesAndTimeline.tsx
> +                    aria-disabled={date.link === APPLICATION_URL && !isLive}
👍🏼

2024-10-31 14:33 UTC, pettinarip approved these changes
🚀

2024-11-04 09:44 UTC, merged