Add smart contract quiz fixes #13776
ethereum/ethereum-org-website pull request #14162
Opened 2024-10-13 14:43 UTC by CryptoDelirium

Accidentally closed previous PR #13981. References issue #13776.

Quiz content added. Linked quiz to global counter

In collab with @JanetMo

2024-10-14 13:55 UTC, Shiva-Sai-ssb commented
Hey @TC1211 / @Qwerky7835, the smart contract quiz is working as expected on the quizzes page, but it is not functioning properly on the smart contracts page.

See the screenshot below to see how the quiz appears on the page, or you can view how the quiz appears in the deploy preview link (https://deploy-preview-14162--ethereumorg.netlify.app) provided by the Netlify bot. 

![smart-contracts](https://github.com/user-attachments/assets/c1d9b1b9-f440-412b-9228-ffc1c17a2980)


To fix this, refer to the suggestion provided here: https://github.com/ethereum/ethereum-org-website/pull/13704#issuecomment-2329448272.

Additionally, reference the issue number in the PR description you are referring to.

2024-10-19 09:39 UTC, TC1211 commented
Fixed the quiz widget on the smart contract page.

2025-03-25 16:32 UTC, wackerow requested changes
Solid work everyone! Thanks to @Qwerky7835 @CryptoDelirium @Shiva-Sai-ssb @JanetMo for helping with this... Apologies for delays so far.

Left a round of comments which I think will take this over the line. @CryptoDelirium would you be capable/interested in making some updates?

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-1-c-explanation": "A smart contract is a piece of code that can be executed automatically according to an 'if this then that' logic.",
Consider:

```suggestion
  "smart-contracts-1-c-explanation": "A smart contract is a piece of code that can be executed according to unchangeable 'if-this-then-that' logic.",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-1-d-label": "They are the rules behind the Ethereum Blockchain, developed together with lawyers to ensure legal compliance.",
```suggestion
  "smart-contracts-1-d-label": "They are the rules behind the Ethereum blockchain, developed together with lawyers to ensure legal compliance",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-2-a-explanation": "Banks require manual intervention and are structured as hierarchical entities, whereas a smart contract automatically executes without intervention.",
Again expressing caution around using "automatic" for smart contracts... They still must be told to "start" via a signed message and providing ETH as gas (computation fee)... it's the rest of the execution that is automatic:

```suggestion
  "smart-contracts-2-a-explanation": "Banks require manual execution and are structured as hierarchical entities, whereas smart contracts are executed predictable by computers with unchangeable rules.",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-2-b-explanation": "The vending machine will only dispense your desired product after all requirements are met - specific inputs guarantee predetermined outputs. This is similar to
Small suggestion:

```suggestion
  "smart-contracts-2-b-explanation": "The vending machine will only dispense your desired product after all requirements are met: specific inputs guarantee deterministic outputs. This is similar to the logic of smart contracts.",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-1-d-label": "They are the rules behind the Ethereum Blockchain, developed together with lawyers to ensure legal compliance.",
Love this answer btw haha

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-2-c-explanation": "smart contract code can be used for calculations, but is not limited to that. Rather, smart contracts are blockchain-based programs that follow an 'if this then
```suggestion
  "smart-contracts-2-c-explanation": "Smart contract code can be used for calculations, but is not limited to that. Rather, smart contracts are blockchain-based programs that follow 'if-this-then-that' logic.",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-3-prompt": "What is not one of the main characteristics of a smart contract?",
General quiz question suggestion, capitalize critical logic terms such as "NOT", and can simplify a touch:

```suggestion
  "smart-contracts-3-prompt": "Which is NOT a main characteristic of smart contracts?",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-5-d-explanation": "Ethereum co-founder Gavin Wood is known for coining the term web3. The term 'smart contract', however, was coined by Nick Szabo in 1994."
This feels much more like trivia than really adding to a users understanding of what smart contracts are or how they function... May consider removing entirely, but perhaps it's still additive... @konopkja thoughts on this one?

If we keep:

> which already has some basic smart contract functionalities

Would advocate we remove this... although there is technically some Turing-incomplete programmability here, at this level I see this as more likely to add confusion for users.

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-4-prompt": "What is not one of the applications of smart contracts?",
Similar to above:

```suggestion
  "smart-contracts-4-prompt": "Which is NOT an application of smart contracts?",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-4-b-explanation": "While protocol changes are enacted through a smart contract, their creation and definition are proposed through transparent online forums such as Github or Forum
Protocol changes are typically even lower in the stack than smart contracts... Although there are a few smart contracts these days that are used directly by the protocol (ie. deposit contract, and soon the withdrawal and compounding contracts from EIP-7251 and EIP-7002) BUT, generally protocol changes are implemented via the clients.

So.. technically "protocol changes" is still an application of smart contracts, but I think we can still use this.


```suggestion
  "smart-contracts-4-b-explanation": "While protocol changes can sometimes use smart contracts, their creation and definition are proposed through transparent online forums and implemented in client software.",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-4-c-label": "Non Fungible Assets",
```suggestion
  "smart-contracts-4-c-label": "Non-fungible assets",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-4-c-label": "Non Fungible Assets",
Or, since the explanation here used "NFT" consider just using "Non-fungible tokens"

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-4-c-label": "Non Fungible Assets",
Yeah, would consider spelling out and showing abbreviation for clarity, same with DAO below:

```suggestion
  "smart-contracts-4-c-label": "Non-fungible tokens (NFTs)",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-4-d-label": "DAOs",
```suggestion
  "smart-contracts-4-d-label": "Decentralized autonomous organizations (DAOs)",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-3-d-explanation": "A smart contract cannot be changed once created, it is guaranteed to execute according to the rules defined by its code.",
```suggestion
  "smart-contracts-3-d-explanation": "A smart contract cannot be changed once created—it is guaranteed to execute according to the rules defined by its code.",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-3-a-label": "Automatic execution",
Similar to other cautionary notes around using "automatic" for smart contracts:

```suggestion
  "smart-contracts-3-a-label": "Deterministic execution",
```

2025-03-25 16:32 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-3-a-explanation": "The main benefit of a smart contract is that it deterministically executes unambiguous code when certain conditions are met.",
> when certain conditions are met

A subtle but import point is how these still need to be poked.

I.e. a DAO vote goes up, people vote and it passes... to actually execute the results there needs to be some interaction by an account that can sign a message to authenticate and provide ETH for gas.... it doesn't just fire because the timer ended. Does that make sense?

Consider:

```suggestion
  "smart-contracts-3-a-explanation": "The main benefit of a smart contract is that it deterministically executes unambiguous code, without human interpretation or bias.",
```

2025-03-29 09:50 UTC, JanetMo commented
@wackerow Thanks for reviewing. From my side, feel free to implement the suggestions, sounds very good.

2025-03-31 10:50 UTC, CryptoDelirium commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-1-a-label": "Smart contracts are just like real (paper) contracts, but stored digitally on the blockchain to save the content securely.",
There is no legal weight behind smart contracts right? Maybe just stick to "digital contracts"?

2025-03-31 10:56 UTC, CryptoDelirium commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-5-d-explanation": "Ethereum co-founder Gavin Wood is known for coining the term web3. The term 'smart contract', however, was coined by Nick Szabo in 1994."
I see this as an intro into the most important figures who shaped crypto history so may be worth it from that perspective. 

If we are talking about the importance of smart contracts, perhaps we can go down the lines of "smart contracts opened unprecendented use cases for Blockchain technology" type of answers

2025-03-31 10:59 UTC, CryptoDelirium commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-1-c-explanation": "A smart contract is a piece of code that can be executed automatically according to an 'if this then that' logic.",
Maybe even shorter:

"A smart contract is a piece of immutable code, executed according to 'if-this-then-that' logic."

2025-03-31 11:03 UTC, CryptoDelirium commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-2-c-explanation": "smart contract code can be used for calculations, but is not limited to that. Rather, smart contracts are blockchain-based programs that follow an 'if this then
Even shorter:

Smart contract code are not limited to calculations. They are blockchain-based programs that follow 'if-this-then-that' logic.

2025-03-31 11:10 UTC, CryptoDelirium reviewed
I applied most of the changes. Some others I left comments and suggestions on.

2025-04-07 15:23 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-1-a-label": "Smart contracts are just like real (paper) contracts, but stored digitally on the blockchain to save the content securely.",
There is no legal weight by default, correct. This is a suggestion for an _incorrect_ answer choice though, not the correct answer.

2025-04-23 15:41 UTC, wackerow requested changes
Hey @CryptoDelirium! Left another round of comments, lemme know what you think here and we'll try to get it in soon.. thanks!

2025-04-23 15:41 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-1-c-explanation": "A smart contract is a piece of code that can be executed automatically according to an 'if this then that' logic.",
Sure... would err on the side of more concise.. "unchangeable" may be easier to understand than "immutable" though

2025-04-23 15:41 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-1-a-label": "Smart contracts are just like real (paper) contracts, but stored digitally on the blockchain to save the content securely.",
Would still suggest "legal contracts" here...

> "like real (paper) contracts"

Just noting that "real" feels ambiguous compared to "legal", and not all contracts need to be on paper either, ie verbal contracts

2025-04-23 15:41 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-1-c-label": "They are programs stored on the blockchain that follow an 'if this then that' logic, and are guaranteed to execute according to the rules defined by the code.",
Still a very long answer label... please shorten this up

2025-04-23 15:41 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-5-d-explanation": "Ethereum co-founder Gavin Wood is known for coining the term web3. The term 'smart contract', however, was coined by Nick Szabo in 1994."
Would strongly argue that who coined the term provides very little to the average user. My vote would be to remove this question... I would similarly prefer to drop the same question from the other "web3" quiz (out of scope for this PR, but a similar issue)

2025-04-26 12:46 UTC, JanetMo approved these changes
Hi @wackerow, thanks for your comments, we're fine with the suggested changes.

2025-07-23 20:02 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-4-d-label": "Decentralized autonomous organizations (DAOs)",
Going to patch this as well.. swapping DAO out for "insurance policy" since we don't mention DAOs on the page, but we do mention insurance.

2025-07-23 20:03 UTC, wackerow commented on src/intl/en/learn-quizzes.json
> +  "smart-contracts-4-d-label": "Decentralized autonomous organizations (DAOs)",
Actually, will use DEX

2025-07-23 20:18 UTC, wackerow approved these changes
made the updates discussed, thanks everyone! Pulling this in

2025-07-23 20:18 UTC, merged

2025-07-23 20:19 UTC, wackerow commented
@all-contributors please add @CryptoDelirium for content

2025-07-23 20:19 UTC, wackerow commented
@all-contributors please add @JanetMo for content