Migrate ActionCard.tsx to tailwind
ethereum/ethereum-org-website pull request #14244
Opened 2024-10-25 19:14 UTC by yun-chiao

## Description
- Wrapped the `ActionCard` inside `CentralActionCard` in `eth.tsx` with a `Box` to ensure parameters like `sx` are correctly passed down.
- Migrated `className` to Tailwind CSS.
- Replaced all components and types from `@chakra-ui/react`.

## Note

I did not replace `useColorModeValue` with the `useColorModeValue` from `@/hooks/useColorModeValue` because I encountered some strange issues.

For example:

```javascript
const descriptionColor = useColorModeValue(
  "lightmode",
  "darkmode"
)
```
When using descriptionColor as a className:

```jsx
<p className={`${descriptionColor}`}></p>
```

On the first render, it always gets `"darkmode"`, but when I `console.log(descriptionColor)`, it consistently returns `"lightmode"`.

After doing some debugging inside `@/hooks/useColorModeValue`, I suspect it is related to the `theme` being `null` on the initial render, which causes the conditional check to fail and return `"darkmode"`. However, I am unsure why `console.log(descriptionColor)` which would be "lightmode" and the actual `descriptionColor` applied to the CSS behave inconsistently.

## Snapshoot
### localhost
[
<img width="1457" alt="截圖 2024-10-26 上午3 10 05" src="https://github.com/user-attachments/assets/b3e864d8-9132-445d-90bb-fc2994b72e82">
<img width="1457" alt="截圖 2024-10-26 上午3 10 23" src="https://github.com/user-attachments/assets/6c5c10c0-8ead-4855-ab61-4f0345bd33cc">
](url)
### https://ethereum.org/
<img width="1457" alt="截圖 2024-10-26 上午3 10 58" src="https://github.com/user-attachments/assets/7c19d872-3d7b-4b27-abb2-8ec7e97328e8">
<img width="1457" alt="截圖 2024-10-26 上午3 10 53" src="https://github.com/user-attachments/assets/7fb01ccb-0736-43fa-98ae-7a9252a119d8">

## Related Issue
#13946

2024-10-31 11:42 UTC, pettinarip requested changes
@yun-chiao thanks for the PR. Left a reply about `useColorModeValue`. LMK what do you think

2024-10-31 11:42 UTC, pettinarip commented on src/components/ActionCard.tsx
> +  )
We should not need `useColorModeValue` for this case. We could do
```tsx
className="text-body opacity-65 dark:opacity-80"
```

2024-10-31 11:42 UTC, pettinarip commented on src/components/ActionCard.tsx
> +      className={`focus:bg-table-bg-hover m-4 flex flex-none shadow-table hover:scale-[1.02] hover:rounded hover:bg-background-highlight hover:shadow-table-box-hover hover:duration-100 focus:scale-[1
Lets use [the `cn` function](https://github.com/ethereum/ethereum-org-website/blob/dev/src/lib/utils/cn.ts)
```tsx
className={cn("...", className)}
```

2024-10-31 11:42 UTC, pettinarip commented on src/components/ActionCard.tsx
> +        className={`action-card-image-wrapper flex h-[260px] flex-row bg-gradient-to-r from-accent-a/10 to-accent-c/10 ${isBottom ? "items-end" : "items-center"} ${isRight ? "justify-end" : "justify-
Use `cn` function
```suggestion
        className={cn(
          "action-card-image-wrapper flex h-[260px] flex-row bg-gradient-to-r from-accent-a/10 to-accent-c/10 shadow-[inset_0px_-1px_0px_rgba(0,0,0,0.1)]",
          isBottom ? "items-end" : "items-center",
          isRight ? "justify-end" : "justify-center"
        )}
```

2024-10-31 11:42 UTC, pettinarip commented on src/pages/eth.tsx
> +    as={ActionCard}
👍🏼

2024-11-10 08:12 UTC, yun-chiao commented
> useColorModeValue

Hi @pettinarip ,

I've updated this PR, and here’s some information about the issue with `useColorModeValue`. Thanks!

I found an example that has been merged and is using `useColorModeValue`: `<EthVideo>`. When I'm in light mode and reload the page, the first render applies the dark mode setting instead of the light mode, as shown in the attached image. However, it behaves correctly when switching between modes.

If I add the following to `useColorModeValue`:

```javascript
if (resolvedTheme == null) {
  return "null_theme";
}
```

I then get `"null_theme"` in `src={src}`, but if I `console.log` related information in <EthVideo>, it returns the light mode variable as expected, e.g., "/images/ethereum-hero-light.mp4", with no trace of `"null_theme"` in the console. I find this behavior odd, as the displayed result in HTML and CSS differs from the variable output.

Thank you!

Snapshoot for `<EthVideo>`.
It should get the src = "/images/ethereum-hero-light.mp4" in the light mode.
<img width="1470" alt="截圖 2024-11-10 下午4 10 38" src="https://github.com/user-attachments/assets/e1dfa3a0-96cb-449c-82b9-362103fb3368">

2024-12-27 11:26 UTC, pettinarip commented
@yun-chiao uhmm good catch! yeah...looks like a bug. Thanks for letting me know, I'll take a look later.

2024-12-27 11:26 UTC, pettinarip approved these changes

2024-12-27 12:46 UTC, merged