Implemented a page for payments use-case
ethereum/ethereum-org-website pull request #14370
Opened 2024-11-21 16:27 UTC by MukulKolpe

## Description

Implemented a new page for the Ethereum Payments (`/payments`) use-case.

Content worked on here: https://github.com/ethereum/ethereum-org-website/issues/13653 by @BoluwatifeInferno.

Design and content of the page:
https://www.figma.com/design/PlJHPXisq7b5ual2DjrR9F/payments?node-id=12940-869&t=J998WMcKEFD6c0jn-1

## Related Issue

Resolves #14217

2024-12-13 15:26 UTC, konopkja commented
@MukulKolpe  do you think you can still look at this or should core devs take over here?

2024-12-15 00:28 UTC, MukulKolpe commented
> I wanted to review this but preview is broken

Thanks for pointing that out. It should be fixed now. Let me know what you think!

2024-12-15 00:32 UTC, MukulKolpe commented
> @MukulKolpe do you think you can still look at this or should core devs take over here?

For sure! Let me know if I've missed anything or if any adjustments are needed.

2024-12-15 10:11 UTC, konopkja commented
preview: https://deploy-preview-14370--ethereumorg.netlify.app/en/payments/

2024-12-16 12:44 UTC, konopkja commented
change request:

- [ ] max width 320px for image
- [ ] remove "ethereum in action" title and its one sentence


<img width="1022" alt="Screenshot 2024-12-16 at 13 44 17" src="https://github.com/user-attachments/assets/ea06da24-c434-4654-86f7-c216467545d4" />

2024-12-16 20:58 UTC, konopkja requested changes

2024-12-16 20:58 UTC, konopkja commented on public/content/payments/index.md
> +summaryPoint1: A world where money moves as freely as information.
```suggestion
summaryPoint1: A world where money moves as freely as information
summaryPoint2: Open and global, enabling borderless transactions for everyone
summaryPoint3: Payments received within a minute 


```

2024-12-18 04:52 UTC, corwintines approved these changes
Thanks @MukulKolpe

2024-12-18 04:52 UTC, merged