Migrated the Chakra-UI imports to Shadcn/Tailwind
ethereum/ethereum-org-website pull request #14508
Opened 2024-12-14 16:22 UTC by ashiskumar-1999

## Description
Migrated the necessary chakra-UI imports to Shadcn/TailwindCSS.

2024-12-30 13:24 UTC, pettinarip requested changes

2024-12-30 13:24 UTC, pettinarip commented on src/components/SideNav.tsx
> +import { Box } from "@chakra-ui/react"
This needs to be migrated too.

2025-01-06 15:06 UTC, pettinarip commented on src/components/SideNav.tsx
> +    <HStack className="w-full justify-between py-2 pe-4 ps-8 hover:bg-[ednBackground]">
```suggestion
    <HStack className="w-full justify-between py-2 pe-4 ps-8 hover:bg-background-highlight">
```

2025-01-06 15:06 UTC, pettinarip commented on src/components/SideNav.tsx
> +            <MdChevronRight className="h-6 w-6" color="secondary" />
```suggestion
            <MdChevronRight className="h-6 w-6" color="secondary" />
```
```suggestion
            <MdChevronRight className="h-6 w-6 text-body-medium" />
```

2025-01-06 15:06 UTC, pettinarip commented on src/components/SideNav.tsx
> +      className="sticky top-[4.75rem] pt-8 pb-16 h-[calc(100vh - 80px)] w-[calc((100% - 1448px) / 2 + 256px)] min-w-256 overflow-y-auto transition-transform duration-200 ease bg-[background.base] sha
```suggestion
      className="sticky top-[4.75rem] pt-8 pb-16 h-[calc(100vh - 80px)] w-[calc((100% - 1448px) / 2 + 256px)] min-w-256 overflow-y-auto transition-transform duration-200 ease bg-background shadow-[1px_0px_0px_rgba(0,0,0,0.1)] border-e border-e-border lg:block"
```

2025-01-17 13:30 UTC, pettinarip approved these changes
Gj @ashiskumar-1999

2025-01-17 14:43 UTC, merged

2025-01-17 16:01 UTC, ashiskumar-1999 commented
Thanks @pettinarip.👍
I'm about to finish the remaining two files in the Staking Components. Could you please assign me more files from the pages before it will be taken by anyone else?