Migrate filecontributors to shadcn
ethereum/ethereum-org-website pull request #14553
Opened 2024-12-27 12:38 UTC by plvzfq-rit

## Description

Migrated ```FileContributors.tsx``` from Chakra UI to Shadcn. Reutilized built-in Typescript components, e.g., ```Button```, ```InlineLink```, ```Modal```, ```Translation```, ```Flex```, ```VStack```, ```ListItem```, and ```UnorderedList```. Avatar left alone as per specification. Text also left alone for now since others seem to use it. Changes were done by using Tailwind classes to replace old Chakra UI parameters.

## Related Issue

#13946

2024-12-30 16:32 UTC, pettinarip requested changes
Nice job @plvzfq-rit

This is how I see the list in the [preview](https://deploy-preview-14553--ethereumorg.netlify.app/en/developers/docs/)
![image](https://github.com/user-attachments/assets/7375c780-4dad-433b-b202-cc42222a0726)

Seems that we need to set a min height to the container.

2024-12-31 01:05 UTC, plvzfq-rit commented on src/components/FileContributors.tsx
>  import { Button } from "@/components/Buttons"
Will change over+

2024-12-31 09:20 UTC, plvzfq-rit commented
Hi @pettinarip, happy new year.
I've changed the Button class from the old to the new. I also found out that the max sizing was wrong after looking at the generated source code in the original, so I upped it from ```max-h-3``` to ```max-h-64```. Should be all good now+

2024-12-31 11:14 UTC, pettinarip approved these changes
Thanks for those fixes @plvzfq-rit.

I've pushed a commit adding [`ScrollArea` from Shadcn](https://ui.shadcn.com/docs/components/scroll-area) to get a better looking scrolling and avoid potential overflows inside the modal.

2024-12-31 11:28 UTC, plvzfq-rit commented
Thanks as well @pettinarip!

2024-12-31 13:40 UTC, pettinarip approved these changes

2025-01-01 08:12 UTC, plvzfq-rit commented
By the by, I had some trouble with some of the CSS for hiding components at certain screen sizes. Turns out it was a Chrome issue.  Bypassed it through the code in this [StackOverflow poast](https://stackoverflow.com/questions/68981642/display-hidden-not-working-with-flex-in-tailwind). Thought I should put in some attribution+

2025-01-06 14:24 UTC, pettinarip commented
> By the by, I had some trouble with some of the CSS for hiding components at certain screen sizes. Turns out it was a Chrome issue. Bypassed it through the code in this [StackOverflow post](https://stackoverflow.com/questions/68981642/display-hidden-not-working-with-flex-in-tailwind). Thought I should put in some attribution+

Interesting. Thanks for sharing @plvzfq-rit

2025-01-06 14:24 UTC, merged