feat: add vyper.fun (wip)
ethereum/ethereum-org-website pull request #1534
Opened 2020-09-28 12:49 UTC by vasa-develop

License: MIT
Signed-off-by: Vaibhav Saini <vasa@dappkit.io>

## Description
This PR aims to add Vyper.fun (a game-based educational website for Vyper) to the "Interactive game tutorials" section of [learning-tools](https://ethereum.org/en/developers/learning-tools) page.

## Current Issue Faced

The website is breaking when run using `npm start` as the [`data`](https://github.com/vasa-develop/ethereum-org-website/blob/dev/src/pages-conditional/developers/learning-tools.js#L72) object receives an empty `vyperfun` object (which expects a [`childImageSharp`](https://github.com/vasa-develop/ethereum-org-website/blob/dev/src/pages-conditional/developers/learning-tools.js#L123) child object).

2020-09-28 13:43 UTC, ryancreatescopy requested changes

2020-09-28 13:43 UTC, ryancreatescopy commented on src/pages-conditional/developers/learning-tools.js
> +      image: data.vyper.childImageSharp.fixed,
I believe this should be `image: data.vyperfun.childImageSharp.fixed,`

2020-09-28 13:43 UTC, ryancreatescopy commented on src/intl/en.json
> +  "page-build-vyperfun-description": "Learn Vyper building your own Pokemon game.",
I believe this should be `Pokémon`

2020-09-28 15:23 UTC, vasa-develop commented
@ryancreatescopy Pushed the changes requested. But still, somehow the UI is breaking.

2020-10-01 12:26 UTC, vasa-develop commented
@ryancreatescopy Sorry for bugging you, but feel free to give it a look and merge this if it' all ok :smile:

2020-10-01 22:00 UTC, samajammin approved these changes
Thanks for this contribution @vasa-develop!

2020-10-01 22:01 UTC, merged

2020-10-01 22:01 UTC, samajammin commented
@all-contributors please add @vasa-develop for content.