Deposit address page [#1553]
ethereum/ethereum-org-website pull request #1554
Opened 2020-09-30 16:54 UTC by ryancreatescopy

## Description

Create a page that allows users to double check the deposit contract address for eth2 staking. 

THIS IS WIP AND A DUMMY ADDRESS – DON'T SEND ANYTHING TO THIS ADDRESS.

## Related Issue

#1553

2020-10-01 19:58 UTC, samajammin requested changes
A few TODOs (as expected) to update the address & URLs.

2020-10-01 19:58 UTC, samajammin commented on src/content/eth2/index.md
> +Looking to learn more about staking? Find the [staking smart contract address](/eth2/staking-address/).
@ryancreatescopy - FYI, I've added this link & copy to the main Eth2 page. I welcome your edits 😄

2020-10-01 19:58 UTC, samajammin commented on src/pages/eth2/staking-address.js
> +// TODO confirm/update
@ryancreatescopy FYI moved the address here & a function to "chunk" it so we only ever define the address in one place.

2020-10-01 19:58 UTC, samajammin commented on src/pages/eth2/staking-address.js
> +            {/* TODO add URL */}
TODO

2020-10-01 19:58 UTC, samajammin commented on src/pages/eth2/staking-address.js
> +            {/* TODO add URL */}
TODO

2020-10-01 19:58 UTC, samajammin commented on src/pages/eth2/staking-address.js
> +              {/* TODO add URL */}
TODO

2020-10-01 20:04 UTC, samajammin commented
@ryancreatescopy looks great! A couple things to note re: my updates:
- I moved the page, it's now located within the Eth2 directory (i.e. /eth2/staking-address/)
- I updated the `Button` component to `ButtonLink` as we discussed... you can safely ignore most of these file edits

One question - do we intend to create an /eth2/staking/ page in tandem with this release? I think we should provide a more in-depth resource on the how & why of staking. Our current content on the main Eth2 page (under "Proof of stake" is pretty sparse). If we do this, I'd probably move the address page (i.e. /eth2/staking/address/). LMK what our plans are around that.

2020-10-02 09:11 UTC, ryancreatescopy commented
> @ryancreatescopy looks great! A couple things to note re: my updates:
> 
> * I moved the page, it's now located within the Eth2 directory (i.e. /eth2/staking-address/)
> * I updated the `Button` component to `ButtonLink` as we discussed... you can safely ignore most of these file edits
> 
> One question - do we intend to create an /eth2/staking/ page in tandem with this release? I think we should provide a more in-depth resource on the how & why of staking. Our current content on the main Eth2 page (under "Proof of stake" is pretty sparse). If we do this, I'd probably move the address page (i.e. /eth2/staking/address/). LMK what our plans are around that.

I do intend to create a staking page – I'll start drafting this considering we wont be shipping this page for a little while. See a proposed structure here: https://www.notion.so/efdn/Scope-out-Eth2-v2-section-f8d938bae9064773a9f13c28f1c1ca41#572f96eb0cab41ffb8bd092681801790
I can also confirm that we do want a banner notification on the other ETH2 pages

2020-10-06 08:29 UTC, ryancreatescopy commented
@samajammin can we make the left column scrollable but the right column sticky so the check address component remains in view?

2020-10-13 08:34 UTC, ryancreatescopy commented
![image](https://user-images.githubusercontent.com/40891631/95836190-0d27b300-0d37-11eb-8177-0201d88fc4c5.png)

@samajammin The margin-bottom on the banner on mobile is a little tight to the top of the page. I reckon we need 2rem of margin.

2020-10-27 04:56 UTC, samajammin approved these changes
Merging this for the sake of the far-reaching style & component changes. I'll create a follow-up PR for deploying the page & updated address.

2020-10-27 04:57 UTC, merged

2020-10-27 05:04 UTC, samajammin commented
@ryancreatescopy @jjmstark - note the src/data/addresses.js file that now hosts the (dummy) contact address. That will be the file to keep a close eye on in future deploys.