Added Sydney's most active Ethereum dev community
ethereum/ethereum-org-website pull request #1584
Opened 2020-10-06 03:24 UTC by jzaki

The previous non-Ethereum link (replaced) was the product of a distinct shift away from the local Ethereum community.

## Description

## Related Issue

2020-10-06 19:35 UTC, samajammin requested changes
Thanks for the PR @jzaki! BokkyPooBah's Ethereum Workshop looks like a great group 👍 

My concern here is around replacing Web3 Sydney vs. just adding the new group. While I agree Web3 Sydney does not appear to be _specific_ to Ethereum, it does mention Ethereum (as the first protocol) & seems like a mission-aligned community. Do you have evidence that it's not an Ethereum community?

2020-10-06 21:22 UTC, jzaki commented
The incidents around the replaced group being spun out were, in a nutshell, controversial. But to avoid digging up past dirt, I will amend my pr to leave it there, and add the other meetup too. People will figure out where the conversation is happening 👍

2020-10-07 23:01 UTC, samajammin approved these changes

2020-10-07 23:01 UTC, merged

2020-10-07 23:02 UTC, samajammin commented
@all-contributors please add @jzaki for content.