[WIP] Add a new Waffle tutorial
ethereum/ethereum-org-website pull request #1676
Opened 2020-10-25 17:11 UTC by MiZiet

## Description

Add a new Hello World tutorial for Waffle.

2020-10-27 05:09 UTC, samajammin commented
Thanks for the submission @MiZiet! I've converted this PR to a draft. Please [mark it as ready for review](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review) when it's no longer a WIP.

2020-11-11 23:07 UTC, samajammin commented
Hey @MiZiet - checking in on this.

2020-11-20 19:34 UTC, samajammin commented
Hey @MiZiet - another nudge! We'd like to get this merged. Please let me know if/when this is ready to review. Thanks.

2020-11-23 07:53 UTC, MiZiet commented
Hey, sorry that it took me so long.

2020-11-25 16:34 UTC, samajammin requested changes
Thanks again for the submission @MiZiet. Given that Buidler is now Hardhat, would you please update the tutorial to reflect that?

2020-11-30 19:12 UTC, samajammin approved these changes
Thanks for making these updates! Approving w/ syntax tweaks.

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```bash
```

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```bash
```

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```bash
```

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```bash
```

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```bash
```

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```solidity
```

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```js
```

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```bash
```

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```js
```

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```bash
```

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```solidity
```

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```solidity
```

2020-11-30 19:12 UTC, samajammin commented on src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
> +```yml
```suggestion
```bash
```

2020-11-30 19:13 UTC, samajammin approved these changes

2020-11-30 19:13 UTC, merged

2020-11-30 19:14 UTC, samajammin commented
@all-contributors please add @MiZiet for content.