Glossary-to-docs linking [Fixed #1717]
ethereum/ethereum-org-website pull request #1724
Opened 2020-11-02 19:56 UTC by wackerow

## Description
- Added as many links as reasonably possible to other parts of ethereum.org website from terms in glossary (Most of these were to the developer docs pages for continued learning)
- Utilized 👉 emoji on links to other parts of ethereum.org website (differentiating from internal glossary # links, and external links)
- Standardized text for these links to "More about ____" for simplicity and cleaner UI/UX on mobile
- Also added term "token standard" with appropriate linking (ref: #1718)
- Refactored superscript text used in currency definition exponents. Removed unicode superscript, replaced with `<sup></sup>` for markdown interpretation. 

## Related Issue
Fixes #1717
Contributes to #1718

2020-11-03 09:04 UTC, ryancreatescopy approved these changes

2020-11-03 13:44 UTC, ryancreatescopy commented
![image](https://user-images.githubusercontent.com/40891631/97992150-34275100-1dda-11eb-9150-f44180609a03.png)

@wackerow I think I said in my review that it might look nice to eventually have even more differentiation between anchor links and links to other pages. This is what I had in mind. Could shortcut this by pulling in the page title and meta description to populate the content. 

Not a blocker to merging this PR, but just to show you what I mean.

2020-11-03 17:07 UTC, wackerow commented
@ryancreatescopy Oh that looks great!... I'll take a look at putting that together. I'll open a separate issue to track it so this can be merged/closed in the meantime.

2020-11-04 19:36 UTC, samajammin requested changes
Amazing! Thanks for this. 

Only issue: let's update these a tag links to use the markdown link syntax. See my comments in #1725 on the reasoning behind this (it makes it easier for translations).

2020-11-11 21:41 UTC, samajammin approved these changes
👏

2020-11-11 21:41 UTC, samajammin commented on src/content/glossary/index.md
> +[More about PoW<Emoji text=":point_right:" size={1} ml={`0.75rem`} />](/developers/docs/blocks/#proof-of-work-protocol)
```suggestion
[More about PoW<Emoji text=":point_right:" size={1} ml={`0.75rem`} />](/developers/docs/consensus-mechanisms/pow/)
```

2020-11-11 21:41 UTC, samajammin commented on src/content/glossary/index.md
> +[More about PoS<Emoji text=":point_right:" size={1} ml={`0.75rem`} />](/eth2/#proof-of-stake)
```suggestion
[More about PoS<Emoji text=":point_right:" size={1} ml={`0.75rem`} />](/developers/docs/consensus-mechanisms/pos/)
```

2020-11-11 21:41 UTC, samajammin commented on src/content/glossary/index.md
> +[More about mining<Emoji text=":point_right:" size={1} ml={`0.75rem`} />](/developers/docs/mining/)
```suggestion
[More about mining<Emoji text=":point_right:" size={1} ml={`0.75rem`} />](/developers/docs/consensus-mechanisms/pow/mining/)
```

2020-11-11 21:42 UTC, samajammin approved these changes

2020-11-11 21:42 UTC, merged