Fix renders twice on page load
ethereum/ethereum-org-website pull request #2108
Opened 2020-12-12 07:00 UTC by esteticalVE

## Description
 Created function for detecting and setting the right theme;
Resolved issue when component renders twice.
Layout was rendered twice because initial state in useState might be different from preferred by the user.
So the state changed and triggered second render;

2020-12-12 19:28 UTC, wackerow requested changes
Thanks for taking a look at this! I am no longer getting a duplicate render when `Layout` loads, however, this seems to be causing issues with the initial rendering of Dark vs Light mode:
![image](https://user-images.githubusercontent.com/54227730/101992981-b160a400-3c6b-11eb-8486-0f048995d456.png)
In the above you see portions of the site styled for light mode, and others styled for dark mode. This does not seem to show in when running in a dev environment, likely because of access to the "window" value that is not available during server side building for production. (btw, you can test a local "production build" by running `yarn start:static` which will run on port 9000, and you will likely see this same thing)
Not sure best way to fix this, but hope this helps a little if you can find a way to adjust it to fix the initial rendering. Thanks again for the help!

2020-12-12 19:28 UTC, wackerow commented on src/components/Layout.js
> +function isDarkThemeUtil(isUseEffect, setThemeCb) {
consider refactoring to arrow syntax to match codebase convention
ie: `const isDarkThemeUtil = (isUseEffect, setThemeCb) => { ... }`

2020-12-21 20:22 UTC, samajammin requested changes
Thanks for looking into this @esteticalVE!

I'm seeing the same issue as @wackerow in the preview deploy:
https://deploy-preview-2108--ethereumorg.netlify.app/en/

Please see if you can solve for that, otherwise close the PR. As you pointed out, the useEffect is causing the re-render so perhaps there is no way around it in order to adjust for the user's browser settings & to set the mode accordingly. I'm not sure but I'd certainly welcome solutions here! Thanks again.

2020-12-24 14:45 UTC, closed without merging

2020-12-24 14:48 UTC, esteticalVE commented
@wackerow @samajammin, thanks for feedback, i've closed this one, i will try to solve it once again, will open new PR