Update index.md
ethereum/ethereum-org-website pull request #2183
Opened 2020-12-25 13:49 UTC by taxmeifyoucan

Updated article, added links to new pages, updated database size overview numbers

2021-01-04 15:26 UTC, ryancreatescopy commented on src/content/developers/docs/nodes-and-clients/index.md
> +For general overview on running own Ethereum client instance, refer to [Spin up your own node article](/en/developers/docs/spin-up-your-node/).
Interested in running your own Ethereum client? Learn how to [spin up your own node](/en/developers/docs/spin-up-your-node/).

2021-01-04 15:27 UTC, ryancreatescopy commented on src/content/developers/docs/nodes-and-clients/index.md
> +Running your own node can be difficult and you don’t always need to run your own instance. In this case, you can use a third party API provider like [Infura](https://infura.io), [Alchemy](https://alc
We don't need to label the links as an article. 

For an overview of using these services, check out [nodes as a services](/en/developers/docs/nodes-and-clients/nodes-as-a-service/)

2021-01-04 15:28 UTC, ryancreatescopy requested changes
Couple of content tweaks, but thanks for updating @taxmeifyoucan !

2021-01-08 12:46 UTC, taxmeifyoucan commented
@ryancreatescopy thanks for reviewing! I tweaked the content and updated pictures with database size charts, changed Parity to Openethereum.

2021-01-17 06:22 UTC, wackerow requested changes
@taxmeifyoucan Just one small correction to "OpenEthereum", otherwise looking good! 👍 thanks for this!

2021-01-17 06:22 UTC, wackerow commented on src/content/developers/docs/nodes-and-clients/index.md
> +These charts show how storage requirements are always changing. For the most up-to-date data for Geth and Openethereum, see the [full sync data](https://etherscan.io/chartsync/chaindefault) and [arch
"Openethereum" -> "OpenEthereum"

2021-01-19 05:19 UTC, samajammin commented on src/content/developers/docs/nodes-and-clients/index.md
> +These charts show how storage requirements are always changing. For the most up-to-date data for Geth and Openethereum, see the [full sync data](https://etherscan.io/chartsync/chaindefault) and [arch
```suggestion
These charts show how storage requirements are always changing. For the most up-to-date data for Geth and OpenEthereum, see the [full sync data](https://etherscan.io/chartsync/chaindefault) and [archive sync data](https://etherscan.io/chartsync/chainarchive). 
```

2021-01-19 05:19 UTC, samajammin approved these changes
Thanks again!

2021-01-19 05:20 UTC, merged