Tutorial proposal called "Create and deploy a DeFi App"
ethereum/ethereum-org-website pull request #2194
Opened 2020-12-31 19:07 UTC by strykerin

Here is the tutorial I wrote about creating and deploying a DeFi app. It is a proposal to be published in the Tutorials section.

In this tutorial we will build a DeFi Application with solidity where users can deposit an ERC20 token to the smart contract and it will mint and transfer Farm Tokens to them. The users can later withdraw their ERC20 tokens by burning their Farm Token on smart contract and the ERC20 tokens will be transferred back to them.

2021-01-17 06:41 UTC, wackerow requested changes
@strykerin This is great! Thanks for putting this together, I enjoyed reading through it... just noted a couple small things to get it ready for the site. 👍

2021-01-17 06:41 UTC, wackerow commented on src/content/developers/tutorials/create-and-deploy-a-defi-app/index.md
> +![output of transferMyTokenToFarmToken.js](https://cdn-images-1.medium.com/max/2000/1*MoekE2QCw7vB98u5dl7ang.png)*output of transferMyTokenToFarmToken.js*
similar to above, consider bringing bold caption down two rows in markdown for readability

2021-01-17 06:41 UTC, wackerow commented on src/content/developers/tutorials/create-and-deploy-a-defi-app/index.md
> +![output of withdrawMyTokenFromTokenFarm.js](https://cdn-images-1.medium.com/max/2000/1*jHYlTFg0NgGbhASpsRvc0w.png)*output of withdrawMyTokenFromTokenFarm.js*
(same)

2021-01-17 06:41 UTC, wackerow commented on src/content/developers/tutorials/create-and-deploy-a-defi-app/index.md
> +## References
`{#references}`

2021-01-23 16:44 UTC, samajammin commented
Thanks for submitting this @strykerin! 

Great comments @wackerow - I agree with all them. I'll go ahead & merge this then add changes for the sake of speed.

2021-01-23 16:44 UTC, merged

2021-01-23 17:07 UTC, samajammin commented
@all-contributors please add @strykerin for content.