Added .env and POAP instructions to readme
ethereum/ethereum-org-website pull request #2288
Opened 2021-01-20 20:01 UTC by wackerow

## Description
- Adds some more descriptions to stack and examples for our conventions
- Adds step for setting up GitHub API Token in `.env` to local environment setup
- Introduces POAP section

2021-01-22 15:14 UTC, ryancreatescopy commented on README.md
> +> The Proof of Attendance Protocol is a dapp that distributes badges in the form of ERC-721 tokens to prove you participated in an event. More info on the dapp and the multiclient token can be found
> The Proof of Attendance Protocol is a dapp that distributes badges in the form of ERC-721 tokens to prove you participated in an event. [More on POAPs](https://www.poap.xyz/).

2021-01-22 15:15 UTC, ryancreatescopy requested changes

2021-01-22 15:15 UTC, ryancreatescopy commented on README.md
> +- This includes our dedicated supporters on Crowdin who contributed to our translation efforts
"merged into"

"This includes our dedicated translators on Crowdin."

2021-01-23 01:35 UTC, samajammin approved these changes
Looks great! Made 1 minor change.

2021-01-23 01:35 UTC, samajammin commented on README.md
> +- 👆 To claim your Contributor POAP, join our Discord server and paste a link to your contribution in the #POAP channel
```suggestion
- 👆 To claim your Contributor POAP, join our Discord server and paste a link to your contribution in the #contributing channel
```

2021-01-23 01:35 UTC, samajammin commented on README.md
> +- 👆 To claim your Contributor POAP, join our Discord server and paste a link to your contribution in the #POAP channel
Let's just use the existing #contributing channel

2021-01-23 01:36 UTC, merged