Change Dapps Features to use Shared Styled Card Component
ethereum/ethereum-org-website pull request #2365
Opened 2021-02-02 07:53 UTC by chase-manning

## Overview
This PR changes the Dapps Features section to use the shared StyledCard Component.  
It aims to further the design consistency of the site, improve performance and simplify the developer experience.

## Details
Previously the Dapps Features section looked like this:
![image](https://user-images.githubusercontent.com/53957795/106567447-b7517200-6596-11eb-864f-53b69fe2ad34.png)
It can be found on [this page](https://ethereum.org/en/dapps/) near the bottom.  
There are a few potential downsides to this design.  
The sheer and rotation animations on hover are not present anywhere else on the site and are unexpected.  
The color scheme, font sizing and icons sizes are also not aligned with the rest of the website.  
In other sections of the website, a standardised approach is used for card design.  

Here are some examples of other card sections throughout the website:
From [What is Ethereum](https://ethereum.org/en/what-is-ethereum/) Page:
![image](https://user-images.githubusercontent.com/53957795/106568346-0a77f480-6598-11eb-93b0-271bb3602dc1.png)
From [How to buy ETH](https://ethereum.org/en/get-eth/) Page:
![image](https://user-images.githubusercontent.com/53957795/106568427-27142c80-6598-11eb-93a4-b4ed43ed56e9.png)

The change in this PR is to change the features section to use this shared card design.  
After the change it now looks like this:
![image](https://user-images.githubusercontent.com/53957795/106568523-4612be80-6598-11eb-8f72-3630065a340d.png)

One additional benefit to this change is a smaller bundle size which means faster loading for the user.  
By using the shared style, we are able to remove the code for the old component as that was the only place it was used.

2021-02-02 21:07 UTC, samajammin commented
Thanks for the PR @chase-manning!

@ryancreatescopy what are your thoughts on this? I don't have a strong preference but I like the visual & interactive elements of the BoxGrid component. Gives the page a bit more life IMO.

2021-02-05 07:32 UTC, Kristiyan96 requested changes
Small change request

2021-02-05 07:32 UTC, Kristiyan96 commented on src/pages-conditional/dapps.js
> +            {features.map((card, idx) => {
```
features.map((card, idx) => (
                <StyledCard
                  key={idx}
                  emoji={card.emoji}
                  title={card.title}
                  description={card.description}
                />
)
```
No need for the return statement

2021-02-05 09:00 UTC, chase-manning commented on src/pages-conditional/dapps.js
> +            {features.map((card, idx) => {
Good spotting! Have just updated 😄

2021-02-12 09:08 UTC, ryancreatescopy commented
Hi @chase-manning thanks for digging into the codebase. This difference in style is quite deliberate however. I realise it may not be perfect but we're experimenting with more interactive ways to display content that's maybe not quite so relevant for everyone so people can dig into specific things they're interested in. More generally we wanted to explore some ways to diversify some of the layouts we've been using throughout the site. We don't want to use that standard card layout for everything! So I'm afraid we won't be merging this. 

For design changes like this I'd recommend discussing ideas in our discord before going ahead. We'd love to workshop design ideas with the community and don't want anyone to waste their time.

2021-02-12 09:08 UTC, closed without merging

2021-02-13 04:27 UTC, chase-manning commented
@ryancreatescopy Thanks Ryan! And no worries I had fun implementing it 😄

2021-02-13 04:27 UTC, chase-manning commented
@ryancreatescopy Thanks Ryan! And no worries I had fun implementing it 😄