Systematizes text styles [Fixes #2342]
ethereum/ethereum-org-website pull request #2382
Opened 2021-02-04 05:26 UTC by wackerow

## Description
Attempt at simplifying header tag styling across site. 
- This eliminates mixins and just adds h1-h5 styling directly to GlobalStyle in theme.js.
- This also eliminates the need for H1-H5 in the SharedStylesComponent, and instances have been removed.
- Some custom local styling had to be applied to a variety of pages, primarily with issues around the h1 and h2 headers.

@ryancreatescopy @samajammin Could use a hand auditing this. Ryan, curious to hear your thoughts on the subtle font-weight changes that you may notice here and there through this... lemme know what you think

## Related Issue
#2342

2021-02-05 07:29 UTC, Kristiyan96 requested changes
Inconsistent header styles, move them to a single file that defines all of them and import where needed.

2021-02-05 07:29 UTC, Kristiyan96 commented on src/components/Roadmap.js
> +      <h2>
Use the H2 you defined in src/components/CalloutBanner.js ?

2021-02-05 07:29 UTC, Kristiyan96 commented on src/pages-conditional/wallets/index.js
> +const H2 = styled.h2`
Why defining different H2 styles?

2021-02-22 22:10 UTC, samajammin approved these changes
Code LGTM! This doesn't get us all the way there in terms of unifying styles but it's a great 1st step.

@ryancreatescopy mind clicking around this preview PR & spot-checking that these changes didn't disrupt anything major?

2021-02-25 11:11 UTC, ryancreatescopy commented
Awesome, so have gone through this and made some tweaks. 

Some thoughts on how I think we should approach this moving forward.

1. The heading styles in the themes should define headings for use in Markdown as these can't be easily edited in a `.md` file. Thus the styling should aim to improve readability in markdown files.
2. We should create a Heading component for use in `.js` pages with less baked-in styling. My suggestion would be to define default sizing, weight, line-height and margin bottom (based on the theme.js headings in point 1). But we should be able to customise the component using props within components. There are so many variables: is this heading being used in a Content block, an InfoBanner, something else? I think we get the most user-friendly dev experience by importing the Heading component and customising to our needs. 
e.g. `<Heading level={2} marginTop="2rem">Example H2 heading with 32px of margin top</Heading>` – I think this is better than having to `const H2 = styled.h2....` etc in every page. 

What do you think?

2021-02-25 11:11 UTC, ryancreatescopy approved these changes

2021-02-25 11:13 UTC, ryancreatescopy approved these changes

2021-02-25 21:40 UTC, wackerow commented
@ryancreatescopy I like that layout and explanation. I'd be in favor of merging this PR, but keeping the original issue open and tackling this with a new PR.

2021-03-01 20:34 UTC, merged