Tutorial for testing a simple smart contract with Waffle
ethereum/ethereum-org-website pull request #2516
Opened 2021-03-01 20:22 UTC by ekowalsk

In this PR I add a new tutorial in developers/tutorials for testing a smart contract with Waffle

2021-03-03 22:39 UTC, samajammin commented on src/content/developers/tutorials/testing-ERC20-tokens-with-waffle/index.md
> +title: Testing ERC20 tokens with Waffle
```suggestion
title: Testing ERC-20 tokens with Waffle
```
Let's try to stick with a single convention: `ERC-20`

2021-03-03 22:40 UTC, samajammin commented on src/content/developers/tutorials/testing-ERC20-tokens-with-waffle/index.md
> +title: Testing ERC20 tokens with Waffle
Along with conventions, please keep the filename lowercase (i.e. `src/content/developers/tutorials/testing-erc-20-tokens-with-waffle/index.md`).

2021-03-03 22:40 UTC, samajammin commented on src/content/developers/tutorials/testing-ERC20-tokens-with-waffle/index.md
> +title: Testing ERC20 tokens with Waffle
Also please add `"erc-20"` as a tag to this tutorial 😄

2021-03-03 22:43 UTC, samajammin commented
Thanks for the PR @ekowalsk!

@wackerow please review when able.

2021-03-04 03:35 UTC, wackerow requested changes
@ekowalsk Thanks a lot for the PR! This looks great... no major changes, just some small semantic adjustments if you wouldn't mind touching them up =)

2021-03-04 03:35 UTC, wackerow commented on src/content/developers/tutorials/waffle-test-simple-smart-contract/index.md
> +During the tutorial we'll work on a simple smart contract example - EtherSplitter. It does not much apart from allowing anyone to send some Wei and split it evenly between two predefined receivers.\
Remove stray slash at the end

2021-03-04 03:35 UTC, wackerow commented on src/content/developers/tutorials/waffle-test-simple-smart-contract/index.md
> +The split function requires the number of Wei to be even, otherwise it will revert. For both receivers it performs a Wei transfer followed by emission of the Transfer event.
Been using convention of lowercase "wei" across the site (referencing the whitepaper)

2021-03-04 03:35 UTC, wackerow commented on src/content/developers/tutorials/waffle-test-simple-smart-contract/index.md
> +        require(msg.value % 2 == 0, 'Uneven Wei amount not allowed');
Ditto

2021-03-04 03:35 UTC, wackerow commented on src/content/developers/tutorials/waffle-test-simple-smart-contract/index.md
> +Testing with Waffle requires using Chai matchers and Mocha, so you need to [add](https://ethereum-waffle.readthedocs.io/en/latest/getting-started.html#writing-tests) them to your project. Update your
Single set of back-ticks should do around `"test"`

2021-03-04 03:35 UTC, wackerow commented on src/content/developers/tutorials/waffle-test-simple-smart-contract/index.md
> +If you want to [execute](https://ethereum-waffle.readthedocs.io/en/latest/getting-started.html#running-tests) your tests, just run ```yarn test``` .
Can use single back-ticks for the inline code snippet

2021-03-04 03:35 UTC, wackerow commented on src/content/developers/tutorials/waffle-test-simple-smart-contract/index.md
> +Now create the ``test`` directory and create the new file ``test\EtherSplitter.test.ts``.
Ditto

2021-03-04 03:35 UTC, wackerow commented on src/content/developers/tutorials/waffle-test-simple-smart-contract/index.md
> +First, we will check if the split method actually changes the balances of receivers' wallets. If we split 50 Wei from senders account, we would expect the balances of both receivers to increase by 25
Ditto on "wei" (throughout)

2021-03-04 03:35 UTC, wackerow commented on src/content/developers/tutorials/waffle-test-simple-smart-contract/index.md
> +The ``MockProvider`` comes up with a mock version of the blockchain. It also delivers mock wallets that will serve us for testing EtherSplitter contract. We can get up to ten wallets by calling ``get
Ditto on single back-ticks for inline code snippets (throughout)

2021-03-04 20:23 UTC, ekowalsk commented
Thank you for your reviews, I've applied all of your suggestions :)

2021-03-05 00:31 UTC, wackerow approved these changes
@ekowalsk Looks great, thanks again for the PR!

2021-03-08 22:27 UTC, merged

2021-03-08 22:27 UTC, samajammin commented
@all-contributors please add @ekowalsk for content.