Fixed the link to the JSON RPC interface
ethereum/ethereum-org-website pull request #2631
Opened 2021-03-14 17:16 UTC by qbzzt

The link in the page led to a 404 error instead of https://ethereum.org/en/developers/docs/apis/json-rpc/

## Related Issue

#2222

2021-03-14 20:52 UTC, jley81 approved these changes

2021-03-14 20:52 UTC, jley81 commented on src/content/developers/docs/programming-languages/index.md
> +you can use the [JSON-RPC interface](/en/developers/docs/apis/json-rpc/) to connect to the Ethereum network. Any programming
Well done

2021-03-15 15:26 UTC, wackerow requested changes
Nice, thanks for updating this. Just don't need the `/en` at the beginning. We can just use `/developers/docs/apis/json-rpc/` which will follow existing intl logic.

2021-03-15 15:58 UTC, samajammin commented on src/content/developers/docs/programming-languages/index.md
> +you can use the [JSON-RPC interface](/en/developers/docs/apis/json-rpc/) to connect to the Ethereum network. Any programming
```suggestion
you can use the [JSON-RPC interface](/developers/docs/apis/json-rpc/) to connect to the Ethereum network. Any programming 
```

2021-03-15 15:59 UTC, samajammin approved these changes
Thanks!

2021-03-15 15:59 UTC, merged