Tutorial on how to mint an NFT
ethereum/ethereum-org-website pull request #2653
Opened 2021-03-16 15:11 UTC by smudgil

This tutorial is part 2/3 of a series on minting an NFT.

This tutorial describes how to interact with an smart contract to mint an NFT using Web3.

2021-03-31 17:45 UTC, wackerow requested changes
Left more comments here, see review of #2652 first. Let us know if you have questions =)

2021-03-31 17:45 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft.md
> +This tutorial describes how to mint an NFT on the Ethereum blockchain using our smart contract and Web3. You should have already completed Part 1: How to Write & Deploy an NFT, prior to starting Part
Would add link here for `Part 1: How to Write & Deploy an NFT` to go to part 1 tutorial. Same with `Part 3`

2021-03-31 17:45 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft.md
> +[Beeple](https://www.wsj.com/articles/beeple-nft-fetches-record-breaking-69-million-in-christies-sale-11615477732): $69 Million
WSJ has a paywall, is there any link we could use that doesn't include a paywall?

2021-03-31 17:45 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft.md
> +“Minting a NFT” is the act of publishing a unique instance of your ERC721 token on the blockchain. Using our smart contract from Part 1 of this NFT tutorial series, let’s flex our web3 skills and min
Similar note to before about hyphenating ERC's for site convention, ie `ERC-721`

2021-03-31 17:45 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft.md
> +##
would remove this (L6)

Also, reminder to make sure custom ID headers are used throughout if the line starts with hash marks
ie:
`## Section name {#section-name}`

2021-03-31 17:45 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft.md
> +    npm install @alch/alchemy-web3
reminder that this site requires backticks to denote inline code, and triple backticks for code blocks, not just indentation (please update throughout)

2021-03-31 17:45 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft.md
> +![How to upload your image to Pinata](https://cdn-images-1.medium.com/max/2000/0*V_-3PGxnfsnLTGo4.gif)
(reminder to download external images and place into same folder as markdown file, then reference locally using `![alt text for gif](./file-name.gif)`)

2021-03-31 17:45 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft.md
> +1. Grab your PRIVATE_KEY* *and* *PUBLIC_KEY from the .env file.
This renders
![image](https://user-images.githubusercontent.com/54227730/113186055-066cf980-920c-11eb-8874-442aee84d676.png)
Was that intentional?
Typically we're using single underscore wrapping to denote italics, and double asterisk wrapping to denote bold, which must touch the content they're wrapping without a space.

2021-03-31 17:45 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft.md
> +1. Next, we’ll need to figure out the account nonce. The nonce specification is used to keep track of the number of transactions sent from your address— which we need for security purposes and to pre
We have local reference material for both of these external links. Can we change these to:
https://ethereum.org/en/glossary/#nonce
https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_gettransactioncount

2021-03-31 17:45 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft.md
> +And that’s it! You’ve now deployed AND minted with a NFT on the Ethereum blockchain 🤑
We use an `Emoji` component to standardize appearance of all Emoji's.. Just change this line to 
`And that’s it! You’ve now deployed AND minted with a NFT on the Ethereum blockchain <Emoji text=":money_mouth_face:" size={1} />`

2021-03-31 17:45 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft.md
> +Presumably, you’d like to be able to show off your NFT in your wallet — so be sure to check out Part 3: How to View Your NFT in Your Wallet!
Link this to 3rd part of tutorial (don't worry that it's in another PR)

2021-04-13 23:06 UTC, Finn-Developments approved these changes

2021-04-15 19:01 UTC, wackerow commented
@smudgil Hey! Just wanted to reach out and see if you intended on moving forward with this. Feel free to ask us any questions if you have them (here or on Discord)

2021-04-15 22:00 UTC, smudgil commented
Hey Paul! Thanks for following up! I do intend to move forward with this, just been super slammed at the moment. I'll get it done by early next week. Thanks a ton for your feedback 🙂
[https://my-email-signature.link/signature.gif?u=1100946&e=147596515&v=efcf5fc7612632f172580ac1c4ad3575550a04b239ef71a342268ad9baf9b047]
________________________________
From: Paul Wackerow ***@***.***>
Sent: Thursday, April 15, 2021 3:01 PM
To: ethereum/ethereum-org-website ***@***.***>
Cc: Sumi Pal Mudgil ***@***.***>; Mention ***@***.***>
Subject: Re: [ethereum/ethereum-org-website] Tutorial on how to mint an NFT (#2653)


@smudgil<https://github.com/smudgil> Hey! Just wanted to reach out and see if you intended on moving forward with this. Feel free to ask us any questions if you have them (here or on Discord)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ethereum/ethereum-org-website/pull/2653#issuecomment-820663037>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJDNA63YKYTBBPCYIVCW5BLTI4Z2PANCNFSM4ZIXVURA>.

2021-04-23 21:37 UTC, smudgil reviewed
updated files, would appreciate review!

2021-04-27 01:09 UTC, smudgil commented
Hey Paul! Pushed some edits near the end of last week, would appreciate feedback! Thanks 🙂
[https://my-email-signature.link/signature.gif?u=1100946&e=149622965&v=363a1ec6340dce7b48c2a22b72a5ddeb1c6577c1e88f95f615d9873f13799b0b]
________________________________
From: Sumi Pal Mudgil ***@***.***>
Sent: Thursday, April 15, 2021 6:00 PM
To: ethereum/ethereum-org-website ***@***.***>; ethereum/ethereum-org-website ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [ethereum/ethereum-org-website] Tutorial on how to mint an NFT (#2653)

Hey Paul! Thanks for following up! I do intend to move forward with this, just been super slammed at the moment. I'll get it done by early next week. Thanks a ton for your feedback 🙂
[https://my-email-signature.link/signature.gif?u=1100946&e=147596515&v=efcf5fc7612632f172580ac1c4ad3575550a04b239ef71a342268ad9baf9b047]
________________________________
From: Paul Wackerow ***@***.***>
Sent: Thursday, April 15, 2021 3:01 PM
To: ethereum/ethereum-org-website ***@***.***>
Cc: Sumi Pal Mudgil ***@***.***>; Mention ***@***.***>
Subject: Re: [ethereum/ethereum-org-website] Tutorial on how to mint an NFT (#2653)


@smudgil<https://github.com/smudgil> Hey! Just wanted to reach out and see if you intended on moving forward with this. Feel free to ask us any questions if you have them (here or on Discord)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ethereum/ethereum-org-website/pull/2653#issuecomment-820663037>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJDNA63YKYTBBPCYIVCW5BLTI4Z2PANCNFSM4ZIXVURA>.

2021-05-05 05:33 UTC, wackerow requested changes
@smudgil Appreciate the work you're doing on this, and we're getting super close! Few other things to clean up on the three PRs, looking forward to getting this merged =)

2021-05-05 05:33 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft/index.md
> +description: This tutorial describes how to mint an NFT on the Ethereum blockchain using our smart contract and Web3. You should have already completed [Part 1: How to Write & Deploy an NFT](/develop
Same as other two, trim down (metadata, not rendered)

2021-05-05 05:33 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft/index.md
>      const web3 = createAlchemyWeb3(API_URL);
Note, though the indented text will render as code, but we can take advantage of the syntax highlighting if we wrap these code blocks in triple-back-ticks as you've done in the others, put the programming language immediately after the opening back-ticks.  (same for code blocks below)

2021-05-05 05:33 UTC, wackerow commented on src/content/developers/tutorials/how-to-mint-an-nft/index.md
> + ```js
ah yes =) We should extend this formatting to the other blocks of code

2021-08-16 13:17 UTC, minimalsm approved these changes

2021-08-16 20:38 UTC, merged

2022-04-10 19:33 UTC, smudgil commented
Hey! Circling back a year later - though about a different tutorial - specifically the NFT Minter Tutorial<https://ethereum.org/en/developers/tutorials/nft-minter/>, which @nstrike2 claims to have authored on the Ethereum org's website and now on Twitter<https://ethereum.org/en/developers/tutorials/nft-minter/>.

I wrote this tutorial over a year ago while I was an interning at Alchemy. You can read it here on web3university<https://www.web3.university/article/nft-minter-tutorial-how-to-create-a-full-stack-dapp> and on the alchemy docs<https://docs.alchemy.com/alchemy/tutorials/nft-minter>. A quick look at the history of the git repo mentioned in the tutorial<https://github.com/alchemyplatform/nft-minter-tutorial/graphs/contributors> also illustrates that I wrote the code for it.

I would really appreciate it if someone could help me take credit for what's rightfully mine. Thank you so much and hope to hear from you soon.

Best regards,
Sumi Mudgil

________________________________
From: Paul Wackerow ***@***.***>
Sent: Wednesday, May 5, 2021 1:33 AM
To: ethereum/ethereum-org-website ***@***.***>
Cc: Sumi Pal Mudgil ***@***.***>; Mention ***@***.***>
Subject: Re: [ethereum/ethereum-org-website] Tutorial on how to mint an NFT (#2653)


@wackerow requested changes on this pull request.

@smudgil<https://github.com/smudgil> Appreciate the work you're doing on this, and we're getting super close! Few other things to clean up on the three PRs, looking forward to getting this merged =)

________________________________

In src/content/developers/tutorials/how-to-mint-an-nft/index.md<https://github.com/ethereum/ethereum-org-website/pull/2653#discussion_r626260031>:

> @@ -1,29 +1,33 @@

-

-# How to Mint an NFT (Part 2/3 of NFT Tutorial Series)

-

-This tutorial describes how to mint an NFT on the Ethereum blockchain using our smart contract and Web3. You should have already completed Part 1: How to Write & Deploy an NFT, prior to starting Part 2 below. In Part 3, we will explain how to view your freshly minted NFT on Metamask!

-

-##

-

-[Beeple](https://www.wsj.com/articles/beeple-nft-fetches-record-breaking-69-million-in-christies-sale-11615477732): $69 Million

+---

+title: How to Mint an NFT (Part 2/3 of NFT Tutorial Series)

+description: This tutorial describes how to mint an NFT on the Ethereum blockchain using our smart contract and Web3. You should have already completed [Part 1: How to Write & Deploy an NFT](/developers/tutorials/how-to-write-and-deploy-an-nft), prior to starting Part 2 below. In [Part 3, we will explain how to view your freshly minted NFT on Metamask](/developers/tutorials/how-to-view-nft-in-metamask/)!



Same as other two, trim down (metadata, not rendered)

________________________________

In src/content/developers/tutorials/how-to-mint-an-nft/index.md<https://github.com/ethereum/ethereum-org-website/pull/2653#discussion_r626261153>:

>      const { createAlchemyWeb3 } = ***@***.***/alchemy-web3");

     const web3 = createAlchemyWeb3(API_URL);



Note, though the indented text will render as code, but we can take advantage of the syntax highlighting if we wrap these code blocks in triple-back-ticks as you've done in the others, put the programming language immediately after the opening back-ticks. (same for code blocks below)

________________________________

In src/content/developers/tutorials/how-to-mint-an-nft/index.md<https://github.com/ethereum/ethereum-org-website/pull/2653#discussion_r626261395>:

> @@ -134,6 +138,7 @@ First, let’s define a function called mintNFT(tokenData) and create our transa



 Your mint-nft.js file should look like this now:



+ ```js



ah yes =) We should extend this formatting to the other blocks of code

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/ethereum/ethereum-org-website/pull/2653#pullrequestreview-651844186>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AJDNA6ZTJJYUM6KE2SFBCRLTMDKB5ANCNFSM4ZIXVURA>.

2022-04-10 20:38 UTC, nstrike2 commented
Hey @paulrberg, following up on this as well. My job while interning at Alchemy was just to put up the existing NFT Minter tutorial from our website on the Ethereum Foundation. After looking at the thread of comments a few months later on this PR, @smudgil is absolutely right — she is the rightful owner of this tutorial, and I had no clue!

I've gone ahead and taken down the Twitter post that Sumi linked, and in addition, I made a PR [here](https://github.com/ethereum/ethereum-org-website/pull/5990) with a request to change the top level name to Sumi's GitHub. Please see that this PR is merged, and Sumi becomes the official rightful owner here.

Once again, my sincerest apologies for my oversight here.

Thank you!!