Add visual demo to Accounts section
ethereum/ethereum-org-website pull request #2698
Opened 2021-03-21 20:31 UTC by 0xGabi

## Description

## Related Issue

2021-03-22 00:03 UTC, jley81 approved these changes

2021-03-23 03:02 UTC, wackerow requested changes
@0xGabi Thanks for posting these to extend the use of Austin's video explanations =) If you wouldn't mind just fixing up the links so they can be embedded we'll try to get this up soon. Thanks!

2021-03-23 05:10 UTC, 0xGabi commented on src/content/developers/docs/accounts/index.md
> +<iframe width="100%" height="315" src="https://www.youtube.com/watch?v=9LtBDy67Tho" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" al
Ops, good catch, thanks!

2021-03-23 18:12 UTC, wackerow approved these changes
@0xGabi looks good 👍 thanks again!

2021-03-23 18:12 UTC, merged

2021-03-23 18:12 UTC, wackerow commented
@all-contributors please add @0xGabi for content