Client-side GitHub API calls
ethereum/ethereum-org-website pull request #2713
Opened 2021-03-23 01:59 UTC by wackerow

## Description
- Pulls GitHub contributor information client side, for the tutorial and developer documents pages. 
- Should speed up build times and prevent hitting GitHub API rate limits which have been resulting in many failed Netlify builds.

## Related Issue
#2400 (Fixes?)

cc: @samajammin 🎉?

2021-03-31 21:51 UTC, wackerow commented
@samajammin Thoughts on giving this a try? Switched it over to Apollo so it's using GraphQL instead of REST. Seems to be running smoothly on Netlify and locally.

2021-04-02 00:41 UTC, samajammin commented on src/apollo.js
> +      Authorization: `Bearer ${GITHUB_TOKEN_READ_ONLY}`,
I believe we need to update this to a `GATSBY_...` ENV variable so it's accessible from the fronted. See my original PR here: https://github.com/ethereum/ethereum-org-website/pull/2296/files#diff-9bd41b9894ddb2787f97e601c440c1cf7b1018f8a52498fbec796bdc422efcf4

2021-04-02 00:42 UTC, samajammin requested changes
See my comment. Currently we're getting 401 unauthorized response, I believe because the `GITHUB_TOKEN_READ_ONLY` variable is not accessible from the client:

![Image 2021-04-01 at 5 39 40 PM](https://user-images.githubusercontent.com/8097623/113367682-8f218d80-9311-11eb-99ed-7b028be4bc2e.jpg)

2021-04-02 19:05 UTC, samajammin commented
Another thought - with the upgrade to Gatsby v3 (#2528), Gatsby add incremental builds by default:
https://www.gatsbyjs.com/docs/reference/release-notes/v3.0/#incremental-builds-in-oss

I'm curious if this will fix our API woes. I'm not clear on exactly how it works - would cache be preserved in Netlify for PRs into `dev`? Or does it build any new branch/fork PR from scratch?

2021-04-07 00:30 UTC, wackerow commented
@samajammin hm, still getting 401 with `GATSBY_GITHUB_TOKEN_READ_ONLY`... 
I'm not sure if Netlify would be able to share cache from another branch to its deploy preview builds. We'll find out soon though since Gatsby v3 changes were merged in... we'll see how new PRs do on builds.

2021-04-08 15:42 UTC, samajammin commented
@wackerow sorry I wasn't clear. We'd also need to add that `GATSBY_GITHUB_TOKEN_READ_ONLY` env variable for it to work 😄  - I've added it to Netlify & just ran a rebuild.

2021-04-08 15:43 UTC, samajammin commented
More context on the `GATSBY_` prefix for client side variables: https://www.gatsbyjs.com/docs/how-to/local-development/environment-variables/#client-side-javascript

2021-04-08 16:02 UTC, wackerow commented
@samajammin beautiful, looks like it's passing after 18 min. May be worth bringing this in and seeing how it affects our builds

2021-04-08 22:29 UTC, samajammin commented
Keep getting build failures in Netlify around the GH API (see #2802):
```
1:57:11 PM: Url path: /developers/local-environment/
1:57:11 PM: Plugin: none
1:57:11 PM: 
1:57:11 PM: 
1:57:11 PM:   FetchError: request to https://api.github.com/graphql failed, reason: Client n  etwork socket disconnected before secure TLS connection was established
1:57:11 PM:   
1:57:11 PM:   - index.js:1461 ClientRequest.<anonymous>
1:57:11 PM:     [repo]/[node-fetch]/lib/index.js:1461:11
1:57:11 PM:   
1:57:11 PM:   - destroy.js:92 emitErrorNT
1:57:11 PM:     internal/streams/destroy.js:92:8
1:57:11 PM:   
1:57:11 PM:   - destroy.js:60 emitErrorAndCloseNT
1:57:11 PM:     internal/streams/destroy.js:60:3
1:57:11 PM:   
1:57:11 PM:   - task_queues.js:84 processTicksAndRejections
1:57:11 PM:     internal/process/task_queues.js:84:21
1:57:11 PM:   
1:57:11 PM: 
1:57:11 PM: not finished run page queries - 2124.630s
1:57:11 PM: error Command failed with exit code 1.
```

Testing out removing those queries on build: https://github.com/ethereum/ethereum-org-website/pull/2713/commits/a7353f19eb1f951792f2b1ed4d3d6f90c9b545a6

We'll see if that fixes things...

2021-04-08 23:36 UTC, merged