ERC-721 Vyper Annotated Code
ethereum/ethereum-org-website pull request #2734
Opened 2021-03-26 18:56 UTC by qbzzt

## Description

The Vyper ERC-721 contract with commentary.

## Related Issue

#1785 requests this kind of article. This is the second one (the first one was ERC-20 and Solidity)

2021-04-07 00:16 UTC, wackerow commented
@qbzzt nice! Sorry for delays on this, trying to play some catch up as we're doing some planning. Will review soon but wanted to let you know it's not being ignored

2021-04-07 00:21 UTC, qbzzt commented
> @qbzzt nice! Sorry for delays on this, trying to play some catch up as we're doing some planning. Will review soon but wanted to let you know it's not being ignored

Thank you. I figured with the Berlin hardfork coming up everybody's busy.

2021-04-22 17:54 UTC, wackerow requested changes
@qbzzt Hey! Thanks for being so patient on this one... This looks great, just dropped a few semantic nit-picky adjustments and then we'll get this up.. thanks again!

2021-04-22 17:54 UTC, wackerow commented on src/content/developers/tutorials/erc721-vyper-annotated-code/index.md
> +title: "Vyper ERC-721 Contract Walk-Through"
`Walkthrough`

2021-04-22 17:54 UTC, wackerow commented on src/content/developers/tutorials/erc721-vyper-annotated-code/index.md
> +User and contract identities in Ethereum are represented by 160 bit addresses. These two variables map
hyphenate `160-bit`

2021-04-22 17:54 UTC, wackerow commented on src/content/developers/tutorials/erc721-vyper-annotated-code/index.md
> +and see the appropriate `Transfer`  events. We can use this variable to know when we have all the NFTs and don't
extra space after `Transfer`

2021-04-22 17:54 UTC, wackerow commented on src/content/developers/tutorials/erc721-vyper-annotated-code/index.md
> +type](https://vyper.readthedocs.io/en/latest/types.html). In this case the input parameter is `bytes32`, a 256 bit value
hyphenate `256-bit`, but keep `256 bits` in the next line... the subtleties =)

2021-04-22 17:54 UTC, wackerow commented on src/content/developers/tutorials/erc721-vyper-annotated-code/index.md
> +one of the most expensive operations the evm (Ethereum Virtual Machine) does (in terms of
`EVM`

2021-04-22 17:54 UTC, wackerow commented on src/content/developers/tutorials/erc721-vyper-annotated-code/index.md
> +For review, here are some of the most important ideas in this contract (in my opinion, yours is likely to vary):
`(in my opinion, yours is likely to vary)`
hah, don't be afraid to own it with confidence =) it's your post

2021-04-22 17:54 UTC, wackerow commented on src/content/developers/tutorials/erc721-vyper-annotated-code/index.md
> +---
Mind just changing the filename to hyphenate erc-721?
`/erc-721-vyper-annotated-code/index.md`

2021-04-22 18:43 UTC, qbzzt commented
> @qbzzt Hey! Thanks for being so patient on this one... This looks great, just dropped a few semantic nit-picky adjustments and then we'll get this up.. thanks again!

No problem. The changes have been done and committed, hopefully we're ready for publication

2021-04-22 19:01 UTC, wackerow approved these changes
@qbzzt 💪 Nice. Thanks for the touch-ups! Bringing it in 🎉

2021-04-22 19:01 UTC, merged