Added pros and contras
ethereum/ethereum-org-website pull request #2917
Opened 2021-04-23 14:18 UTC by kladkogex

Changed "company" to "project" everywhere. There are no companies in decentralized world.

Mentioned that for rollups the operator can influence ordering.

Mentioned that sidechains similar to rollups look and feel as ETH main net

## Description

## Related Issue

2021-04-27 02:52 UTC, wackerow requested changes
@kladkogex Hey thanks for submitting =) Noted a couple small changes

LGTM, @ryancreatescopy let me know if you have any thoughts on the wording here

2021-04-27 02:52 UTC, wackerow commented on src/content/developers/docs/layer-2-scaling/index.md
> +
can remove extra line

2021-04-27 02:52 UTC, wackerow commented on src/content/developers/docs/layer-2-scaling/index.md
> +- [EthHub on zk-rollups](https://docs.ethhub.io/ethereum-roadmap/layer-2-scaling/zk-rollups/)\
can remove this stray `\`

2021-04-27 02:52 UTC, wackerow commented on src/content/developers/docs/layer-2-scaling/index.md
> +Most layer 2 solutions are centered around a server or cluster of servers, each of which may be referred to as a node, validator, operator, sequencer, block producer, or similar term. Depending on th
in**v**ividuals -> in**d**ividuals

2021-04-27 13:31 UTC, kladkogex commented on src/content/developers/docs/layer-2-scaling/index.md
> +- [EthHub on zk-rollups](https://docs.ethhub.io/ethereum-roadmap/layer-2-scaling/zk-rollups/)\
OK

2021-04-27 13:31 UTC, kladkogex commented on src/content/developers/docs/layer-2-scaling/index.md
> +Most layer 2 solutions are centered around a server or cluster of servers, each of which may be referred to as a node, validator, operator, sequencer, block producer, or similar term. Depending on th
OK :)

2021-04-27 13:32 UTC, kladkogex commented on src/content/developers/docs/layer-2-scaling/index.md
> +
Ok :) Thanks

2021-05-05 03:13 UTC, wackerow commented
@kladkogex Just touching base, noticed you marked things as resolved but didn't see any commits... let me know if you're having any issues with GitHub or need any other help

2021-06-11 20:39 UTC, jaceppo approved these changes
guanlonghuang

2021-06-14 20:30 UTC, wackerow commented
@kladkogex What's the status on this?

2021-08-06 09:52 UTC, minimalsm commented
Cleaned this up as per your comments @wackerow but we have restructured this section into individual pages for each scaling solution. The merge conflicts require more wizardary than I feel comfortable attempting, is the easiest thing to do to open a new PR to make these changes in the corresponding, new pages?

2021-08-08 21:04 UTC, wackerow approved these changes
Well the merge/autoformatting/conflict clean up made a mess of this diff, but I simply merged the latest `dev` updates, removed the `/layer-2-scaling/` page and placed the changes into the `/scaling/`, `/scaling/layer-2-rollups/` and `/scaling/sidechains/`. 

Made very slight adjustments to the sidechain copy.

Should be good for a merge now after it builds 👍🏻

2021-08-10 13:46 UTC, minimalsm commented
Awesome! Thanks @wackerow for sorting conflicts and thanks @kladkogex for the PR ✌️

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

2021-08-10 13:47 UTC, minimalsm commented
@all-contributors please add @kladkogex for docs

2021-08-10 13:48 UTC, merged