Transaction fee calculation
ethereum/ethereum-org-website pull request #3133
Opened 2021-05-26 01:35 UTC by miiiguel

Correcting the formula for transaction fee to gasLimit times gasPrice

## Description

## Related Issue

2021-05-27 12:35 UTC, ryancreatescopy commented
Noticed something broken while reviewing the PR so added a fix to this PR.

Thanks @miiiguel for fixing this, but in my opinion this whole paragraph is actually redundant. It seems to re-explain something we've already explained higher up in a more accessible way. @samajammin @wackerow any thoughts on this?

2021-06-01 03:53 UTC, wackerow commented
@ryancreatescopy Ran with this a little and cleaned a few things up. I agree that paragraph had redundancy in there, and I tried to take it out. Cleaned up a bunch of other little semantic things, and also reordered the sections to flow better. 

Feedback welcome =)

2021-06-07 13:16 UTC, ryancreatescopy requested changes

2021-06-07 13:16 UTC, ryancreatescopy commented on src/content/developers/docs/gas/index.md
> +High gas fees are due to the popularity of Ethereum. Performing any operation on Ethereum requires consuming gas, and gas space is limited per block. This includes calculations, storing or manipulati
This last sentence is too complicated: 

If there's too much demand, users must offer a higher gas price to try and out-bid other users' transactions. A higher price can make it more likely that your transaction will get into the next block.

2021-06-07 13:16 UTC, ryancreatescopy commented on src/content/developers/docs/gas/index.md
> +Gas limit refers to the maximum amount of gas you are willing to consume on a transaction. A higher gas limit means more computational work can be done while interacting with [smart contracts](/devel
I think this paragraph is a bit confusing – specifically the second sentence... 

Try:

More complicated transactions, involving smart contracts, require more computational work so have a higher gas limit than a simple payment. A standard ETH transfer...

2021-06-07 13:16 UTC, ryancreatescopy commented
@wackerow thanks just a couple tweaks needed.

2021-06-07 13:30 UTC, merged

2021-06-07 13:31 UTC, wackerow commented
@all-contributors please add @miiiguel for content patch