Add "Fetch Price Data in Solidity Smart Contracts" tutorial
ethereum/ethereum-org-website pull request #3134
Opened 2021-05-26 03:02 UTC by kwsantiago

Added a "Fetch Price Data in Solidity Smart Contracts" tutorial.

2021-06-01 01:04 UTC, wackerow requested changes
@kwsantiago Thanks for submitting this! Gave it a once over, looks great, just some markdown and metadata related stuff to get this prepped. Ping when ready and we'll try to get this in =)

2021-06-01 01:04 UTC, wackerow commented on src/content/developers/tutorials/fetch-price-data-in-solidity-smart-contracts/index.md
> +</p>
Would just use markdown for this as well
```
![alternate text](src)
```

And by convention we've been keeping images for each tutorial directly in the same folder, ie `/fetch-price-data-in-solidity-smart-contracts/eth-usd.png` if you wouldn't mind relocating the file. 🙏🏻

2021-06-01 01:04 UTC, wackerow commented on src/content/developers/tutorials/fetch-price-data-in-solidity-smart-contracts/index.md
> +Once deployed, we simply need to execute the “getLatestPrice” function. The result should be that the function returns the latest price from the ETH/USD Aggregator contract, which can then be used on
note: Inline code names like `getLatestPrice` can be wrapped in single back-ticks to style as inline code for readability.

2021-06-01 01:40 UTC, kwsantiago reviewed
Sounds good, thank you for the suggestions as they were very helpful.

2021-08-23 13:39 UTC, minimalsm commented
@samajammin @wackerow Given that we are implementing third-party tutorials in #3630, this tutorial [already exists on Chainlink's website](https://blog.chain.link/fetch-current-crypto-price-data-solidity/) do you think its best we implement this as a third party tutorial instead? 

(I've opened a notion card around this question generally)

2021-08-23 21:37 UTC, minimalsm commented
Hey @kwsantiago, we're adding a feature to allow contributors to link to external tutorials within the next few weeks. Seeing as this tutorial already exists on Chainlink's website I'm going to close this out for now and add it as an external tutorial once this feature goes live. 😬

2021-08-23 21:37 UTC, closed without merging