Tellor Oracle Tutorial
ethereum/ethereum-org-website pull request #3360
Opened 2021-06-29 18:43 UTC by RaynHarr

Tutorial for getting set up with the Tellor oracle.

## Description
Submission for 'How to Set Up the Tellor Oracle' to be added to the developer tutorials page.

## Related Issue

2021-07-01 03:00 UTC, wackerow commented
@RaynHarr Hey, thanks a lot for the tutorial PR! Bear with us, will take a closer look within a week or two and get back to you with feedback 🙂

2021-07-07 22:56 UTC, wackerow requested changes
@RaynHarr Thanks again for posting this... noted a few small adjustments, but otherwise looked pretty good. 

I see it's labeled as beginning, just curious if we should include a bit more guidance as a beginner tutorial about how to go about using the Tellor functions listed. I feel this currently assumes a certain level of understanding, which is fine, but if there are pre-requisites maybe we should note those at the beginning and label this intermediate or advanced. 

Thoughts? Then we'll get this merged =)

2021-07-07 22:56 UTC, wackerow commented on src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md
> +tags: ["solidity", "smart contracts", "pricefeeds", "oracles"]
would use "price feeds"

2021-07-07 22:56 UTC, wackerow commented on src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md
> +Great! Now that you've got the tools ready, let's go through a simple excercise where we request the Bitcoin price:
- "exercise"
- lowercase "bitcoin" (for the currency)

2021-07-07 22:56 UTC, wackerow commented on src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md
> +    * @dev Retreive value from oracle based on requestId/timestamp
- "Retrieve" 
- (3 other instances of this typo noted below)

2021-07-07 22:56 UTC, wackerow commented on src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md
> +    * @param _requestId to looku p
"look up"

2021-07-07 22:56 UTC, wackerow commented on src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md
> +    * @dev Counts the number of values that have been submited for the request
"submitted"

2021-07-07 22:56 UTC, wackerow commented on src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md
> +<br>
Can remove `<br>` in the markdown

2021-07-14 13:56 UTC, RaynHarr commented
Hey Paul! 

Sorry I missed this, didn’t realize how fast you guys were! 

Absolutely, we’ll look at it today and get back. 

Thanks!

-Ryan

> On Jul 7, 2021, at 6:57 PM, Paul Wackerow ***@***.***> wrote:
> 
> ﻿
> @wackerow requested changes on this pull request.
> 
> @RaynHarr Thanks again for posting this... noted a few small adjustments, but otherwise looked pretty good.
> 
> I see it's labeled as beginning, just curious if we should include a bit more guidance as a beginner tutorial about how to go about using the Tellor functions listed. I feel this currently assumes a certain level of understanding, which is fine, but if there are pre-requisites maybe we should note those at the beginning and label this intermediate or advanced.
> 
> Thoughts? Then we'll get this merged =)
> 
> In src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md:
> 
> > @@ -0,0 +1,145 @@
> +---
> +title: How to Set Up Tellor as your Oracle
> +description: A guide to get started with integrating the Tellor oracle into your protocol
> +author: "Tellor"
> +lang: en
> +sidebar: true
> +tags: ["solidity", "smart contracts", "pricefeeds", "oracles"]
> would use "price feeds"
> 
> In src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md:
> 
> > +In this tutorial we'll go over:
> +* Setting up the initial toolkit you'll need to get up and running.
> +* Walk through a simple example.
> +* Provide basic functions that can be used for a more robust use of Tellor.
> +* List out testnet addresses of networks you currently can test Tellor on.
> +
> +
> +## UsingTellor
> +First thing you'll want to do is install the basic tools necessary for using Tellor as your oracle. Use [this package](https://github.com/tellor-io/usingtellor) to install the Tellor User Contracts to test the implementation of Tellor in your contracts:
> +
> +`npm install usingtellor`
> +
> +Once installed this will allow your contracts to inherit the functions from the contract 'UsingTellor'. 
> +
> +
> +Great! Now that you've got the tools ready, let's go through a simple excercise where we request the Bitcoin price:
> "exercise"
> lowercase "bitcoin" (for the currency)
> In src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md:
> 
> > +
> +    (_didGet, btcPrice, _timestamp) = getCurrentValue(btcRequestId);
> +  }
> +}
> +```
> +
> +
> +## Available Tellor Functions:
> +
> +Below is a group of basic functions that come with inheriting the UsingTellor contract. These will allow you to utilize Tellor in a more robust fashion than the example above.
> +
> +Children contracts have access to the following functions:
> +
> +```solidity
> +    /**
> +    * @dev Retreive value from oracle based on requestId/timestamp
> "Retrieve"
> (3 other instances of this typo noted below)
> In src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md:
> 
> > +Below is a group of basic functions that come with inheriting the UsingTellor contract. These will allow you to utilize Tellor in a more robust fashion than the example above.
> +
> +Children contracts have access to the following functions:
> +
> +```solidity
> +    /**
> +    * @dev Retreive value from oracle based on requestId/timestamp
> +    * @param _requestId being requested
> +    * @param _timestamp to retreive data/value from
> +    * @return uint value for requestId/timestamp submitted
> +    */
> +    function retrieveData(uint256 _requestId, uint256 _timestamp) public view returns(uint256);
> +
> +    /**
> +    * @dev Gets if the mined value for the specified requestId/_timestamp is currently under dispute
> +    * @param _requestId to looku p
> "look up"
> 
> In src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md:
> 
> > +    * @param _requestId being requested
> +    * @param _timestamp to retreive data/value from
> +    * @return uint value for requestId/timestamp submitted
> +    */
> +    function retrieveData(uint256 _requestId, uint256 _timestamp) public view returns(uint256);
> +
> +    /**
> +    * @dev Gets if the mined value for the specified requestId/_timestamp is currently under dispute
> +    * @param _requestId to looku p
> +    * @param _timestamp is the timestamp to look up miners for
> +    * @return bool true if requestId/timestamp is under dispute
> +    */
> +    function isInDispute(uint256 _requestId, uint256 _timestamp) public view returns(bool);
> +
> +    /**
> +    * @dev Counts the number of values that have been submited for the request
> "submitted"
> 
> In src/content/developers/tutorials/how-to-use-tellor-as-your-oracle/index.md:
> 
> > +```
> +## Looking to do some testing first? See the list below for our active testnet addresses:
> +
> +#### Addresses:
> +
> +Mainnet: [`0x88df592f8eb5d7bd38bfef7deb0fbc02cf3778a0`](https://etherscan.io/address/0x88df592f8eb5d7bd38bfef7deb0fbc02cf3778a0)
> +
> +Rinkeby: [`0x88df592f8eb5d7bd38bfef7deb0fbc02cf3778a0`](https://rinkeby.etherscan.io/address/0x20374E579832859f180536A69093A126Db1c8aE9#code)
> +
> +Kovan: [`0x20374E579832859f180536A69093A126Db1c8aE9`](https://kovan.etherscan.io/address/0x20374E579832859f180536A69093A126Db1c8aE9#code)
> +
> +Ropsten: [`0x20374E579832859f180536A69093A126Db1c8aE9`](https://ropsten.etherscan.io/address/0x20374E579832859f180536A69093A126Db1c8aE9#code)
> +
> +Goerli: [`0x20374E579832859f180536A69093A126Db1c8aE9`](https://goerli.etherscan.io/address/0x20374E579832859f180536A69093A126Db1c8aE9#code)
> +
> +<br>
> Can remove <br> in the markdown
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-07-15 20:10 UTC, RaynHarr commented
@wackerow Great points you brought up. In an attempt to keep it beginner-friendly, we went ahead and removed the extensive list of functions and gave a preliminary list of assumptions. Let me know if this works better, and if you think it's still wise to move it to intermediate, then that's cool with us too. Also, thanks for reminding me how to spell retrieved -_-

2021-07-30 01:56 UTC, wackerow approved these changes
@RaynHarr Looks good 👍🏻 Thanks for the updates, will get this pulled in

2021-07-30 01:56 UTC, merged

2021-07-30 01:57 UTC, wackerow commented
@all-contributors please add @RaynHarr for content

2021-07-31 13:36 UTC, RaynHarr commented
Woohoo! Thanks so much @wackerow and everyone! Much thanks to @tkernell as well for the guidance and collaboration.