dead links updated for scaling and rollups
ethereum/ethereum-org-website pull request #3394
Opened 2021-07-06 04:28 UTC by kwsorensen

Fixing broken links on pages.

## Description

I was looking into eth2 merge details and noticed there was broken links on a few pages.

## Related Issue
https://github.com/ethereum/ethereum-org-website/issues/3393

2021-07-07 17:12 UTC, kwsorensen commented
@corwintines @GeorgeTrotter  @jjmstark Can I get a review?

2021-07-07 19:55 UTC, wackerow requested changes
Hey @kwsorensen, thanks for helping update these! Left some notes, but in general I think the `/layer-2-scaling/ links should just be changed to `/scaling/layer-2-rollups/`. 

Also noted a youtube embed link that got screwed up at some point, and a header id (#rollups-and-sidechains) that doesn't exist, if you wouldn't mind touching these up.

2021-07-07 19:55 UTC, wackerow commented on src/content/translations/de/eth2/shard-chains/index.md
> +[Mehr zu Rollups](/developers/docs/scaling/layer-2-rollups/#rollups)
Not sure we need to direct to the #rollups header here. We already redirect `/docs/layer-2-scaling/` to `/docs/layer-2-rollups/` automatically, I would just stick with that for these links, ie:
```
[Mehr zu Rollups](/developers/docs/scaling/layer-2-rollups/)
```

2021-07-07 19:55 UTC, wackerow commented on src/content/translations/hr/eth2/shard-chains/index.md
> +Vitalik Buterin, u podcastu Bankless, predstavio je 3 potencijalne opcije o kojima vrijedi razgovarati. <iframe width="100%" height="315" src="/developers/docs/scaling/#layer-2-scaling" frameborder="
Looks like this was a bug previously, but the `src` here should be the YouTube embed link: https://www.youtube.com/embed/-R0j5AMUSzA?start=5841
```
Vitalik Buterin, u podcastu Bankless, predstavio je 3 potencijalne opcije o kojima vrijedi razgovarati. <iframe width="100%" height="315" src="https://www.youtube.com/embed/-R0j5AMUSzA?start=5841" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen mark="crwd-mark"></iframe>
```

2021-07-07 19:55 UTC, wackerow commented on src/content/translations/ro/history/index.md
> +- [EIP-197](https://eips.ethereum.org/EIPS/eip-197) – _adaugă curba eliptică și înmulțirea scalară pentru a permite [ZK-Snarks](/developers/docs/scaling/layer-2-rollups/#rollups-and-sidechains)._
`#rollups-and-sidechains` does not exist as a header link. The existing internal link of `#rollups` should be used here.

2021-07-07 19:55 UTC, wackerow commented on src/content/translations/ro/history/index.md
> +- A adăugat anumite metode de criptografie pentru a permite \[scalarea layer-ului 2\]((/developers/docs/scaling/#layer-2-scaling).
Similar to others, would change a;; `/layer-2-scaling/` to the main `scaling/layer-2-rollups` page:
```
/developers/docs/scaling/layer-2-rollups/
```

2021-07-07 19:55 UTC, wackerow commented on src/content/translations/ro/history/index.md
> +- [EIP-2028](https://eips.ethereum.org/EIPS/eip-2028) – _reduce costul CallData pentru a permite mai multe date în blocuri – bun pentru [scalarea Layer 2](/developers/docs/scaling/#layer-2-scaling)._
```
/developers/docs/scaling/layer-2-rollups/
```

2021-07-07 19:55 UTC, wackerow commented on src/content/translations/ro/history/index.md
> +- A făcut soluțiile de [scalare Layer 2](/developers/docs/scaling/#layer-2-scaling) bazate pe SNARK-uri și STARK-uri mai performante.
```
/developers/docs/scaling/layer-2-rollups/
```

2021-07-07 19:55 UTC, wackerow commented on src/content/translations/ro/eth2/shard-chains/index.md
> +[Mai multe despre rollup-uri](/developers/docs/scaling/layer-2-rollups/#rollups-and-sidechains)
```
/developers/docs/scaling/layer-2-rollups/
```

2021-07-07 19:55 UTC, wackerow commented on src/content/translations/ro/enterprise/index.md
> +[Nivelul 2](/developers/docs/scaling/#layer-2-scaling) este un set de tehnologii sau sisteme care rulează peste Ethereum (Nivelul 1), moștenesc proprietăți de securitate din Nivelul 1 și oferă o capa
```
/developers/docs/scaling/layer-2-rollups/
```

2021-07-13 16:17 UTC, kwsorensen commented
@wackerow I think your requests should be fixed.

2021-07-13 20:25 UTC, kwsorensen reviewed
I believe the changes you requested are satisfied.

2021-07-14 00:48 UTC, samajammin commented on src/content/translations/hi/eth2/shard-chains/index.md
> +[रोलअप के बारे में अधिक जानकारी](/developers/docs//docs/scaling/layer-2-rollups/#rollups)
```suggestion
[रोलअप के बारे में अधिक जानकारी](/developers/docs/docs/scaling/layer-2-rollups/#rollups)
```

2021-07-14 00:51 UTC, samajammin approved these changes
Thanks for the updates!

2021-07-14 00:51 UTC, merged

2021-07-14 00:51 UTC, samajammin commented
@all-contributors please add @kwsorensen for content.