Update index.md
ethereum/ethereum-org-website pull request #3444
Opened 2021-07-20 23:55 UTC by jbgwu

Edited for punctuation and a broken link.

## Description

## Related Issue

2021-07-30 02:38 UTC, wackerow requested changes
@jbgwu Thanks for posting =) Left a question about the link you swapped out, otherwise this looks good 👍🏻

2021-07-30 02:38 UTC, wackerow commented on src/content/developers/tutorials/erc-721-vyper-annotated-code/index.md
> +In this article we will analyze [Ryuya Nakamura's ERC-721 contract](https://github.com/vyperlang/vyper/blob/master/vyper/builtin_interfaces/ERC721.py).
Little confused, the original link is working for me and appears to be the contract being referenced. Could we revert this? Or am I missing something?

2021-08-05 20:12 UTC, minimalsm commented
Hey @jbgwu ✌️ Thanks for the PR. Agree with Paul that the original reference to the vyper file was the correct one so I've reverted that (feel free to comment if you think we've made a mistake). Appreciate the improvements you've made.

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!.

2021-08-05 20:12 UTC, minimalsm commented
@all-contributors please add @jbgwu for docs

2021-08-05 20:13 UTC, merged