Adding invitation to discord on feedback card
ethereum/ethereum-org-website pull request #3589
Opened 2021-08-09 21:18 UTC by ahmedprusevic

## Description

Added a discord invitation link on feedback card

## Related Issue

Resolves #3581

2021-08-09 22:23 UTC, wackerow requested changes
@ahmedprusevic Thanks for the PR! Couple things... 
- We use a component named "Link" for all of our links which can replace the anchor tag with 
`<Link to="https://discord.gg/rZz26QWfCg">Discord</Link>`. I would just put this inline within the `title` constant.
- Also, this now shows "Join our public Discord and get the answer you're looking for" even if they answered "Yes" to "Did this page help answer your question?" We should only show this invite text if the user answered "No"

We already pass in `isHelpful` to the `handleClick` function, which tells us what the user chose. We should add a state variable to store that, setting it to the `isHelpful` boolean in the `handleClick` function before `setFeedbackSubmitted`. Then update `title` to include a logic check for this result. Let me know if you need a hand!

2021-08-09 23:15 UTC, ahmedprusevic commented
> @ahmedprusevic Thanks for the PR! Couple things...
> 
> * We use a component named "Link" for all of our links which can replace the anchor tag with
>   `<Link to="https://discord.gg/rZz26QWfCg">Discord</Link>`. I would just put this inline within the `title` constant.
> * Also, this now shows "Join our public Discord and get the answer you're looking for" even if they answered "Yes" to "Did this page help answer your question?" We should only show this invite text if the user answered "No"
> 
> We already pass in `isHelpful` to the `handleClick` function, which tells us what the user chose. We should add a state variable to store that, setting it to the `isHelpful` boolean in the `handleClick` function before `setFeedbackSubmitted`. Then update `title` to include a logic check for this result. Let me know if you need a hand!

Solved, don't know if extra abstraction is needed with title or should it just be left as it is

2021-08-10 12:57 UTC, minimalsm commented on src/components/FeedbackCard.js
> +      and get the answer you're looking for
Suggested some punctuation for the negative feedback response - other than that LGTM 👍

```suggestion
      Join our public <Link to="https://discord.gg/rZz26QWfCg">Discord</Link>{" "}
      and get the answer you're looking for.
```

2021-08-11 12:22 UTC, minimalsm commented
LGTM and works as expected. Just checking you're good with merging this as it is @wackerow?

2021-08-12 22:43 UTC, wackerow approved these changes
@ahmedprusevic 👍🏻 Looks good! Thanks again for helping out!

2021-08-12 22:43 UTC, merged

2021-08-12 22:43 UTC, wackerow commented
@all-contributors please add @ahmedprusevic for code

2021-08-14 01:32 UTC, jley81 approved these changes

2021-08-17 07:18 UTC, samajammin commented
Woohoo! Thanks @ahmedprusevic!