Add ERC-777 developer docs
ethereum/ethereum-org-website pull request #3703
Opened 2021-08-24 17:28 UTC by il3ven

Added developer docs for ERC-777 token standard. There may be gaps in the docs. I am open to improving them.

## Related Issue
#3666

2021-08-25 10:34 UTC, minimalsm commented
Hey @il3ven, you've submitted this as a draft PR, just double checking that this is ready for review?

2021-08-25 11:01 UTC, il3ven commented
> Hey @il3ven, you've submitted this as a draft PR, just double checking that this is ready for review?

It is now ready for review. I had to format docs according to the writers template.

2021-08-30 15:16 UTC, minimalsm requested changes
Hey @il3ven ! Thanks for the work you've put into this. I've made some amendments, for now, to fix markdown mostly. I'll get to reviewing this properly later on today 😃

2021-08-30 15:16 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +[ERC-20](/developers/docs/standards/tokens/erc-20/)
```suggestion
To better understand this page, we recommend you first read about [ERC-20](/developers/docs/standards/tokens/erc-20/)
```

2021-08-30 15:16 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +## Body {#body}
```suggestion
```

2021-08-30 15:16 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +### Breaking down the definition {#breaking-down-the-definition}
```suggestion
## Breaking down the definition {#breaking-down-the-definition}
```

2021-08-30 15:16 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +### What improvements does ERC-777 propose over ERC-20? {#what-improvements-does-erc-777-propose-over-erc-20}
```suggestion
## What improvements does ERC-777 propose over ERC-20? {#-erc-777-vs-erc-20}
```

2021-08-30 15:16 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +#### Hooks {#hooks}
```suggestion
### Hooks {#hooks}
```

2021-08-30 15:16 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +##### Why are hooks great? {#why-are-hooks-great}
```suggestion
#### Why are hooks great? {#why-are-hooks-great}
```

2021-08-30 15:16 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +#### Decimals {#decimals}
```suggestion
### Decimals {#decimals}
```

2021-08-30 15:16 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +#### Backwards compatibility with ERC-20 {#backwards-compatibility-with-erc-20}
```suggestion
### Backwards compatibility with ERC-20 {#backwards-compatibility-with-erc-20}
```

2021-08-30 15:16 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +It means that ERC-777 contracts can be interacted with as if they were ERC-20 contracts.
```suggestion
ERC-777 contracts can be interacted with as if they were ERC-20 contracts.
```

2021-08-30 18:15 UTC, jley81 approved these changes

2021-09-15 09:54 UTC, minimalsm requested changes

2021-09-15 09:54 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +To better understand this page, we recommend you first read about [ERC-20](/developers/docs/standards/tokens/erc-20/)
```suggestion
To better understand this page, we recommend you first read about [ERC-20](/developers/docs/standards/tokens/erc-20/).
```

2021-09-15 09:54 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +
```suggestion
```

I'd remove this because it is already covered in the prerequisite section 🙂

2021-09-15 09:54 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +Hooks are a function described in a smart contract that will be called when tokens are sent or received. Essentially, smart contracts can react to incoming or outgoing tokens.
```suggestion
Hooks are a function described in the code of a smart contract. Hooks get called when tokens are sent or received through the contract. This allows a smart contract to react to incoming or outgoing tokens.
```

2021-09-15 09:54 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +3. Hooks can reject transactions.
```suggestion
1. Hook allow sending tokens to a contract and notifying the contract in a single transaction, unlike [ERC-20](https://eips.ethereum.org/EIPS/eip-20), which requires a double call (`approve`/`transferFrom`) to achieve this.
2. Contracts that have not registered hooks are incompatible with ERC-777. The sending contract will abort the transaction when the receiving contract has not registered a hook. This prevents accidental transfers to non-ERC-777 smart contracts.
3. Hooks can reject transactions.
```

2021-09-15 09:54 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-777/index.md
> +The standard also improves the confusion around `decimals` in ERC-20. Thus, making development a bit easier.
```suggestion
The standard also solves the confusion around `decimals` caused in ERC-20. This clarity improves the developer experience.
```

2021-09-15 09:56 UTC, minimalsm approved these changes

2021-09-15 09:57 UTC, minimalsm commented
@il3ven thanks for the work on this and all the PRs you've been putting in lately, the team really appreciate it! Bringing this in now ✌️

2021-09-15 09:58 UTC, merged