Translation Versions page
ethereum/ethereum-org-website pull request #3797
Opened 2021-09-02 15:40 UTC by minimalsm

## Description
Adds a page that explains what is in each translation version

2021-09-02 22:00 UTC, minimalsm commented
@lukassim can you have a look at this and let me know your thoughts 🙏 

https://deploy-preview-3797--ethereumorg.netlify.app/en/contributing/translation-program/translation-versions/

2021-09-07 20:25 UTC, wackerow requested changes
Couple small adjustments suggested and a question about listing all the pages in docs and tutorials. 👍🏻 lookin good though

2021-09-07 20:25 UTC, wackerow commented on src/content/contributing/translation-program/translation-versions/index.md
> +Language V2.0 translates high-impact, highly trafficed pages on ethereum.org and the navigation components.
```suggestion
Language V2.0 translates high-impact, highly trafficked pages on ethereum.org and the navigation components.
```

2021-09-07 20:25 UTC, wackerow commented on src/content/contributing/translation-program/translation-versions/index.md
> +- [What is Ether](/eth/)
```suggestion
- [What is ether](/eth/)
```

2021-09-07 20:25 UTC, wackerow commented on src/content/contributing/translation-program/translation-versions/index.md
> +Language V2.1 translates the majority of the developer docs and several less trafficed but important pages.
```suggestion
Language V2.1 translates the majority of the developer docs and several less trafficked but important pages.
```

2021-09-07 20:25 UTC, wackerow commented on src/content/contributing/translation-program/translation-versions/index.md
> +- [Validium](/developers/docs/scaling/validium/)
I'm fine with it either way, but any thoughts on simplifying this to just everything in "/developers/docs" is v2.1?

2021-09-07 20:25 UTC, wackerow commented on src/content/contributing/translation-program/translation-versions/index.md
> +- [How to use Manticore to find bugs in smart contracts](/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/)
Similar to above... should we consider just stating everything in "/developers/tutorials" is v2.2?

I suppose part of this depends on where newly listed tutorials and docs are going to be slotted for new content versions or not. If not, seems more dynamic and future proof to not explicitly list every page in these large folders.

2021-09-08 22:27 UTC, samajammin commented on src/content/contributing/translation-program/translation-versions/index.md
> +### Primary Pages {#primary}
There's a bunch missing: https://crowdin.com/project/ethereum-org/content/files

2021-09-08 22:46 UTC, samajammin approved these changes
Great idea & nice work on this @minimalsm!

Made some updates:
- Updated page from "Translation versions" to "Content versions"
- Added a brief overview section
- Added link from Translation Program page
- Added missing pages from v2.0
- Simplified lists to list "all docs pages" & "all tutorial pages"

I think this is ready to merge but feel free to make any edits you'd like first.

2021-09-08 23:43 UTC, corwintines approved these changes

2021-09-11 01:12 UTC, wackerow approved these changes

2021-09-14 22:08 UTC, minimalsm commented
Bringing this in for the deploy. Will make necessary changes in a patch deploy 👍

2021-09-14 22:08 UTC, merged