Add more explicit h2 font families
ethereum/ethereum-org-website pull request #3918
Opened 2021-09-16 11:34 UTC by minimalsm

## Description

We are not declaring explicit font families for most things using a monospace typeface unless the user has `SFMono-Regular` installed. Even on my iMac, the H2 was defaulting to `monospace` instead of `SFMono-Regular`

This was causing pages using monospace to 1. look a bit disconnected on most devices and 2. created issues with typographical hierarchy in some cases as H2s appeared to be smaller in height than H3s.

On this before screenshot notice how 'Development Modules' looks smaller than 'Foundational Topics' despite being the same font-size:
<img width="941" alt="Screenshot 2021-09-16 at 11 58 36" src="https://user-images.githubusercontent.com/62268199/133603999-55b7bd73-0b73-4a32-ad09-b497050884b0.png">

See after screenshot to see how this change fixes this.
<img width="904" alt="Screenshot 2021-09-16 at 11 58 25" src="https://user-images.githubusercontent.com/62268199/133604160-ba1c87ea-88e9-4e46-9d85-ab3d96656863.png">

Using BrowserStack I've tested this across windows and a few mobile devices and the change seems to be an improvement across all devices.

I re-used the monospace font-stack already used in our [layout CSS](https://github.com/ethereum/ethereum-org-website/search?q=Roboto+Mono)

Pretty sure this is the intended design as this is how it appears on @samajammin's screenshots [here](https://github.com/ethereum/ethereum-org-website/pull/2671#pullrequestreview-615891877).

*Should probably refactor this at some point so we aren't declaring the same fonts everywhere.*

2021-09-16 15:42 UTC, corwintines approved these changes
Looks good. Is there an issue created for the tech debt you mentioned?

2021-09-16 19:50 UTC, minimalsm commented
@corwintines not yet!

2021-09-17 08:47 UTC, minimalsm commented
This needs to be added to some H1s as well

- https://deploy-preview-3918--ethereumorg.netlify.app/en/developers/tutorials/
- https://deploy-preview-3918--ethereumorg.netlify.app/en/developers/learning-tools/
- https://deploy-preview-3918--ethereumorg.netlify.app/en/developers/local-environment/

<img width="852" alt="Screenshot 2021-09-17 at 09 46 39" src="https://user-images.githubusercontent.com/62268199/133753605-7d758bfc-653d-4422-b928-fd62fdf4ff09.png">
<img width="758" alt="Screenshot 2021-09-17 at 09 46 41" src="https://user-images.githubusercontent.com/62268199/133753612-08bd6d47-97e8-414a-b9b0-7856cadc0488.png">
<img width="953" alt="Screenshot 2021-09-17 at 09 46 44" src="https://user-images.githubusercontent.com/62268199/133753616-a38f75ed-9115-4453-bd11-a048e3dcbe2b.png">

2021-09-21 10:59 UTC, minimalsm commented
I've added the h1s using monospace to this PR also.

Issue created to refactor this in #3967 

cc: @corwintines

2021-09-22 02:48 UTC, wackerow requested changes
Thanks for doing this @minimalsm! Did a quick grep of the codebase and noticed there were a few more instances with `font-family: "SFMono-Regular", monospace;`

```log
7 results - 6 files

src/components/CallToContribute.js:
  62    color: ${(props) => props.theme.colors.text};
  63:   font-family: "SFMono-Regular", monospace;
  64  `

  66  const Title = styled.h2`
  67:   font-family: "SFMono-Regular", monospace;
  68    text-transform: uppercase;

src/components/CodeModal.js:
  68    text-transform: uppercase;
  69:   font-family: "SFMono-Regular", monospace;
  70  `

src/components/TutorialMetadata.js:
  65    text-overflow: ellipsis;
  66:   font-family: "SFMono-Regular", monospace;
  67    background: ${(props) => props.theme.colors.ednBackground};

src/pages/developers/index.js:
  71    font-weight: normal;
  72:   font-family: "SFMono-Regular", monospace;
  73    text-transform: uppercase;

src/pages/eth2/deposit-contract.js:
  113  const Address = styled.div`
  114:   font-family: "SFMono-Regular", monospace;
  115    border-radius: 2px;

src/styles/layout.css:
  101  samp {
  102:   font-family: "SFMono-Regular", monospace;
  103    font-size: 1em;
```

I feel like we should add the same series of font-families to these as well, thoughts?

2021-09-22 14:15 UTC, minimalsm commented
@wackerow fixed :)

2021-09-22 19:31 UTC, wackerow commented on src/components/CallToContribute.js
> +    "Liberation Mono", Menlo, Courier, monospace;
```suggestion
  font-family: "SFMono-Regular", Consolas, "Roboto Mono", "Droid Sans Mono",
    "Liberation Mono", Menlo, Courier, monospace;
```

![image](https://user-images.githubusercontent.com/54227730/134409369-000df1b3-c974-4c82-ae8d-9b3661253d0c.png)
@minimalsm were these skipped intentionally?

2021-09-22 19:37 UTC, wackerow commented on src/components/CallToContribute.js
> +    "Liberation Mono", Menlo, Courier, monospace;
Just pushed a patch for this =)

2021-09-22 19:38 UTC, wackerow approved these changes
💪🏻

2021-09-22 20:03 UTC, minimalsm commented
Thanks @wackerow 🙏

2021-09-22 20:04 UTC, merged