Add Translation Program mission and vision section
ethereum/ethereum-org-website pull request #4046
Opened 2021-09-27 14:11 UTC by lukassim

## Description

Added a section detailing the Translation Program mission and vision.
Added a section linking to the blog posts on the EF blog.

## Related Issue

#4036

2021-09-27 17:38 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +The Ethereum community is truly global and all-inclusive. However, as over 3/4 of the world’s population do not speak English, we want to provide them with content in their native language, in order
```suggestion
The Ethereum community strives to be truly global and all-inclusive. Given that over 3/4 of the world’s population do not speak English, we want to provide them with content in their native language, in order for ethereum.org to be the portal to Ethereum for the global community.
```

2021-09-27 17:40 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +To achieve this, our community of volunteer translators is working on translating the website and other Ethereum content into as many languages as possible.
I think this sentence could be brought into the paragraph above.

2021-09-27 17:41 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +- By providing translated versions of the website, visitors from all over the world can learn about Ethereum in their native language.
```suggestion
- Provide translated versions of the website to enable visitors from all over the world to learn about Ethereum in their native language.
```

2021-09-27 17:42 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +    - This helps to bridge language gaps and provides visitors with more inclusive and more generally understandable content.
```suggestion
    - Bridge language gaps and provide visitors with more inclusive and more generally understandable content.
```

2021-09-27 17:42 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +    - In addition, this facilitates the onboarding of more members to the global Ethereum community.
```suggestion
    - Facilitate the onboarding of more members to the global Ethereum community.
```

2021-09-27 17:42 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +- Translated content about Ethereum allows for easier and more inclusive sharing of information and knowledge.
```suggestion
- Allow for easier and more inclusive sharing of Ethereum information and knowledge.
```

2021-09-27 17:43 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +- By opening up the Translation Program to voluntary contributions, community members from all over the world have a chance to contribute to Ethereum and make their mark on the ecosystem.
```suggestion
- Open up the Translation Program to voluntary contributions to empower community members from all over the world to have a chance to contribute to Ethereum and make their mark on the ecosystem.
```

2021-09-27 17:44 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +- The Translation Program also allows us to identify and connect with numerous supporters and contributors, looking to get involved with Ethereum.
```suggestion
- Identify, connect with, and engage numerous supporters and contributors looking to get involved with Ethereum.
```

2021-09-27 17:44 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +- To translate essential content for members of the Ethereum community from as many countries and parts of the world as possible.
```suggestion
- Translate essential content for members of the Ethereum community from as many countries and parts of the world as possible.
```

2021-09-27 17:44 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +- To support the sharing of knowledge across languages with the aim of creating a better informed and educated Ethereum community.
```suggestion
- Support knowledge sharing across languages with the aim of creating a better informed and educated Ethereum community.
```

2021-09-27 17:44 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +- To increase Ethereum's inclusivity and accessibility by providing translated content and removing the language barriers that prevent non-English speakers from joining the ecosystem.
```suggestion
- Increase Ethereum's inclusivity and accessibility by providing translated content and removing the language barriers that prevent non-English speakers from joining the ecosystem.
```

2021-09-27 17:45 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +**Ethereum Foundation blog**
```suggestion
**Latest updates**
```

2021-09-27 17:45 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +To keep in touch with the latest updates about the Translation Program, you can follow the [Ethereum Foundation blog](https://blog.ethereum.org/).
```suggestion
To keep in touch with the latest Translation Program progress, you can follow the [Ethereum Foundation blog](https://blog.ethereum.org/).
```

2021-09-27 17:46 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +Our older posts are available below:
```suggestion
Our most recent posts are available below:
```

2021-09-27 17:46 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +- [Translation Program announcement](https://blog.ethereum.org/2019/08/20/translating-ethereum-for-our-global-community/)
```suggestion
- [August 2019 Translation Program launch](https://blog.ethereum.org/2019/08/20/translating-ethereum-for-our-global-community/)
```

2021-09-27 17:47 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +- [July 2020 post](https://blog.ethereum.org/2020/07/29/ethdotorg-translation-milestone/)
```suggestion
- [July 2020 milestones update](https://blog.ethereum.org/2020/07/29/ethdotorg-translation-milestone/)
```

2021-09-27 17:47 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +- [December 2020 post](https://blog.ethereum.org/2020/12/21/translation-program-milestones-updates-20/)
```suggestion
- [December 2020 milestones update](https://blog.ethereum.org/2020/12/21/translation-program-milestones-updates-20/)
```

2021-09-27 17:48 UTC, samajammin reviewed
Looks great! Made a bunch of minor suggestions, mostly updating to use a consistent active voice in the bullet points.

2021-09-27 17:48 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +## Translation Program mission and vision {#mission-and-vision}
```suggestion
## Mission and vision {#mission-and-vision}
```

2021-09-27 17:49 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +## Translation Program mission and vision {#mission-and-vision}
Should this be the top section on the page (i.e. in front of "How to translate" & "Resources")?

2021-09-27 18:57 UTC, wackerow requested changes
@lukassim Great start here! Made a few comments more related to wording/tone of what we're labeling "our mission," as it seems like it should be a bit more active.

Otherwise this looks great. Was trying to think of a way to squeeze in how Ethereum is something that stands to benefit these groups the most in many ways, and the option of leaving everything in English would exclude the majority of people who need this most, while enabling parts of society that are already fairly well off. Feel free to ignore or run with that thought =)

Nice job!

2021-09-27 18:57 UTC, wackerow commented on src/content/contributing/translation-program/index.md
> +- By opening up the Translation Program to voluntary contributions, community members from all over the world have a chance to contribute to Ethereum and make their mark on the ecosystem.
```suggestion
- Work with voluntary contributors and community members from all over the world to provide a chance for anyone to contribute to Ethereum and make their mark on the ecosystem.
```

2021-09-27 18:57 UTC, wackerow commented on src/content/contributing/translation-program/index.md
> +- The Translation Program also allows us to identify and connect with numerous supporters and contributors, looking to get involved with Ethereum.
```suggestion
- Identify and connect with supporters and contributors looking to get involved with Ethereum and help provide guidance.
```

2021-09-28 10:23 UTC, minimalsm requested changes
@lukassim looking awesome 🙌❤️ Made a few suggestions but feel free to drop anything you disagree with.

2021-09-28 10:23 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +The aim of the ethereum.org Translation Program is to make Ethereum accessible to everyone, regardless of their nationality and language, by translating the website and other Ethereum content into as
```suggestion
The ethereum.org Translation Program aims to make Ethereum accessible to everyone by translating ethereum.org and other Ethereum content into as many languages as possible.
```

2021-09-28 10:23 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +The aim of the ethereum.org Translation Program is to make Ethereum accessible to everyone, regardless of their nationality and language, by translating the website and other Ethereum content into as
>  regardless of their nationality and language

This is already implied

2021-09-28 10:23 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +- Provide translated versions of the website to empower visitors from all over the world to learn about Ethereum in their native language.
```suggestion
- Provide translated versions of the website to empower visitors worldwide to learn about Ethereum in their native language
```

2021-09-28 10:23 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +- Facilitate the onboarding of those who stand to benefit the most from Ethereum
> Facilitate the onboarding of those who stand to benefit the most from Ethereum

This seems a bit hand-wavy to me. Who benefits the most?

2021-09-28 10:23 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +- Allow for easier and more inclusive sharing of Ethereum information and knowledge.
```suggestion
- Allow for more accessible and more inclusive sharing of Ethereum information and knowledge
```

2021-09-28 10:23 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +- Open up the Translation Program to voluntary contributions to empower community members from all over the world to have a chance to contribute to Ethereum and make their mark on the ecosystem.
```suggestion
- Empower community members to contribute translations to Ethereum and make their mark on the ecosystem
```

> Open up the Translation Program to voluntary contribution

I think this is pretty well implied already

2021-09-28 10:23 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +- Identify and connect with supporters and contributors looking to get involved with Ethereum and help provide guidance.
```suggestion
- Identify, connect with, and provide guidance to passionate contributors looking to get involved in the ecosystem
```

2021-09-28 10:23 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +- Increase Ethereum's inclusivity and accessibility by providing translated content and removing the language barriers that prevent non-English speakers from joining the ecosystem.
```suggestion
- Increase Ethereum's inclusivity and accessibility by removing the language barriers preventing non-English speakers from joining the ecosystem
```

2021-09-28 10:23 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +- Support knowledge sharing across languages with the aim of creating a better informed and educated Ethereum community.
```suggestion
- Support knowledge sharing across languages to create a better informed and educated Ethereum community
```

2021-09-28 10:23 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +- Translate essential content for members of the Ethereum community from as many countries and parts of the world as possible.
> essential content

How do we define essential content?

2021-09-28 10:23 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +- [December 2020 milestones update](https://blog.ethereum.org/2020/12/21/translation-program-milestones-updates-20/)
```suggestion
To keep up-to-date with the latest Translation Program progress, you can follow the [Ethereum Foundation blog](https://blog.ethereum.org/):

- [December 2020 milestones update](https://blog.ethereum.org/2020/12/21/translation-program-milestones-updates-20/)
- [July 2020 milestones update](https://blog.ethereum.org/2020/07/29/ethdotorg-translation-milestone/)
- [August 2019 Translation Program launch](https://blog.ethereum.org/2019/08/20/translating-ethereum-for-our-global-community/)
```

IMO the updates should be in reverse chronological order (we already do this elsewhere)

<img width="1239" alt="Screenshot 2021-09-28 at 11 21 03" src="https://user-images.githubusercontent.com/62268199/135069513-b1332074-986f-4ab0-a93a-be6d3dc2e326.png">

> Our most recent posts are available below:

We can probably drop this, it's pretty implied / already has the law of proximity working for it.

2021-09-28 23:54 UTC, wackerow requested changes
This looks great @lukassim! After taking a look at it as the whole page, my vote would be to have this higher up on the page. 

Would personally suggest moving the Mission and Vision section up just above `#how-to-translate`, but splitting of the `Latest updates` as it's own Section and leaving it where it is. 

This way people are given a quick intro, then a passion-driven mission statement of _why_ this matters, then on to _how_ to be a part of it.

Loving it =) Nice job

2021-09-29 08:28 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +- Translate essential content for members of the Ethereum community from as many countries and parts of the world as possible.
On second read I'm okay with this being vague 👍

2021-09-29 16:06 UTC, wackerow approved these changes
💪🏻 🎉

2021-09-29 19:57 UTC, merged