Integrating Your Smart Contract with the Frontend (Part 4/4 of Hello World dApp Series)
ethereum/ethereum-org-website pull request #4279
Opened 2021-10-22 23:54 UTC by nstrike2

## Description

Added header tags for each of the titles as per request from @minimalsm. Please make sure to approve/merge [changes to Part 1/4](https://ethereum.org/en/developers/tutorials/hello-world-smart-contract/), [Part 2/4](https://github.com/ethereum/ethereum-org-website/pull/4280), and [Part 3/4](https://github.com/ethereum/ethereum-org-website/pull/4281) before approving/merging this one.

## Related Issue

Continuation of https://github.com/ethereum/ethereum-org-website/pull/4160, which has now been closed due to inaccessibility.

Related Issue: https://github.com/ethereum/ethereum-org-website/issues/4133

2021-11-24 00:05 UTC, nstrike2 commented
@minimalsm @corwintines @pettinarip @samajammin @wackerow Can we get this merged? If not, happy to change what needs to be changed to get this merged.

2021-12-16 09:19 UTC, nstrike2 commented
Hey @minimalsm , finished the changes for Part 4/4.

2021-12-16 11:41 UTC, minimalsm requested changes
Hey @nstrike2, same as part 2 just leaving some clean-up comments.

Can we ensure we have header-ids on any headings (and that they are supposed to be headings, there appear to be some random ones that aren't headings at all). And use our Emoji component [as per the style guide](https://ethereum.org/en/contributing/style-guide/#images) (if they are within code blocks just use them as normal)

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +title: 📱Integrating Your Smart Contract with the Frontend (Part 4/4 of Hello World dApp Series)
```suggestion
title: Integrating Your Smart Contract with the Frontend (Part 4/4 of Hello World dApp Series)
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +# 📱Integrating Your Smart Contract with the Frontend
```suggestion
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +🎉Woooo! You finally made it to the last part of this tutorial series: creating a full stack decentralized application \(dApp\) by connecting your Hello World smart contract to a frontend project and
```suggestion
🎉Woooo! You finally made it to the last part of this tutorial series: creating a full-stack decentralized application (dApp) by connecting your Hello World smart contract to a frontend project and interacting with it.

You'll need to have finished part 1 [creating and deploying a smart contract](https://docs.alchemy.com/alchemy/tutorials/hello-world-smart-contract), part 2 [interacting with your smart contract](https://docs.alchemy.com/alchemy/tutorials/hello-world-smart-contract/interacting-with-a-smart-contract), and part 3 [submitting your smart contract to Etherscan](https://docs.alchemy.com/alchemy/tutorials/hello-world-smart-contract/submitting-your-smart-contract-to-etherscan) before starting part 4 below.
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +## Step 1: Clone the starter files {#step-1-starter-files}
```suggestion
## Step 1: Clone the starter files {#starter-files}
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Don't know how to clone a repository? Check out [this guide](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository) from Github.
Let's assume if they got this far that they can clone a repo

```suggestion
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +## Step 2: Check out the starter files {#step-2-check-out-the-starter-files}
```suggestion
## Step 2: Check out the starter files {#check-out-the-starter-files}
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +Next, open your copy of `starter-files` to your favorite code editor \(at Alchemy, we we're big fans of [VSCode](https://code.visualstudio.com/download)\), and then navigate into your `src` folder.
Really don't think we need to give people code editor recommendations if they're this far into a web3 programming tutorial

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### **NOTE:** Make sure you're in the `starter-files` folder and not the `completed` folder!
I'm guessing this shouldn't be a heading?

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### The `HelloWorld.js` component
```suggestion
### The `HelloWorld.js` component {#hello-component}
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +At the top of this file, you'll notice we have several import statements that are necessary to get our project running, including the React library, useEffect and useState hooks, some items from the
```suggestion
At the top of this file, you'll notice we have several import statements that are necessary to get our project running, including the React library, useEffect and useState hooks, some items from the `./util/interact.js` (we'll describe them in more details soon!), and the Alchemy logo <Emoji text="🧙‍♂️" size={1} />
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +At the top of this file, you'll notice we have several import statements that are necessary to get our project running, including the React library, useEffect and useState hooks, some items from the
Please ensure any emojis are used as described in [the style guide](https://ethereum.org/en/contributing/style-guide/#images)

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Never heard of React state variables or state hooks? Check out [these](https://reactjs.org/docs/hooks-state.html) docs.
I don't think this should be a heading. Why don't we assume if they've read the intro about the React prerequisites that they can work this one out?

```suggestion
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +## Step 3: Read from your smart contract {#step-3-read-from-your-smart-contract}
```suggestion
## Step 3: Read from your smart contract {#read-from-your-smart-contract}
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +To get the project running, navigate to the root directory of the `starter-files` folder, and the run `npm install` in your terminal to install the dependencies of the project:
Technically they don't need to be at the root as long as no nested folder has a package.json file just FYI

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Establish an API connection to the Ethereum chain
```suggestion
### Establish an API connection to the Ethereum chain {#connect-to-ethereum}
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### If you skipped Part 3 of this tutorial, you can use the HelloWorld contract with address [0x6f3f635A9762B47954229Ea479b4541eAF402A6A](https://ropsten.etherscan.io/address/0x6f3f635a9762b47954229e
This shouldn't be a heading. I think assuming they've completed the tutorial as intended is fine here. We're covering too many edge cases (if you don't know React, if you don't know how to clone a repo, if you've not finished all tutorials, _if you aren't from planet Earth..._). I agree with trying to be inclusive and enabling users to complete the task but IMO it makes the tutorial less coherent and cluttered which will lead to lower completion rates.

```suggestion
If you skipped Part 3 of this tutorial, you can use the HelloWorld contract with address [0x6f3f635A9762B47954229Ea479b4541eAF402A6A](https://ropsten.etherscan.io/address/0x6f3f635a9762b47954229ea479b4541eaf402a6a#code). It's ABI can be found [here](https://ropsten.etherscan.io/address/0x6f3f635a9762b47954229ea479b4541eaf402a6a#code).
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Your contract-abi.json should be stored in your src folder.
Is this meant to be a heading? If so we need a header-id, if not can we remove the hashes

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Implementing `loadCurrentMessage` in your `interact.js` file
```suggestion
### Implementing `loadCurrentMessage` in your `interact.js` file {#implementing-load-current-message}
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +## Step 7: Make your own custom dApp 🚀
header-id

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Connect `updateMessage` to the `HelloWorld.js` frontend
header-id

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Signing our transaction
header-id

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### The `getCurrentWalletConnected` function
header-id

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Add the `connectWallet` function to your `HelloWorld.js` UI Component <a id="import-connect-wallet-pressed-into-minter-jss-connect-wallet-function"></a>
header-id and please remove link from title

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### The `connectWallet` function
header-id

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +## Step 5: Connect Metamask to your UI {#step-5-connect-metamask-to-your-UI}
```suggestion
## Step 5: Connect Metamask to your UI {#connect-metamask-to-your-UI}
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Check your Balance <a id="step-5-check-your-balance"></a>
header-id and remove link from title

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Add ether from a Faucet <a id="step-4-add-ether-from-a-faucet"></a>
header-id and remove link from title

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +## Step 4: Set up your Ethereum wallet {#step-4-create-an-instance-of-your-contract}
```suggestion
## Step 4: Set up your Ethereum wallet {#create-an-instance-of-your-contract}
```

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Implement `addSmartContractListener`
header-id

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Your UI should now reflect the message stored in the smart contract
header-id

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### How to get your contract ABI from Etherscan
header-id

2021-12-16 11:41 UTC, minimalsm commented on src/content/developers/tutorials/integrating-your-smart-contract-with-the-frontend/index.md
> +### Loading your Hello World smart contract
header-id

2021-12-21 08:19 UTC, nstrike2 commented
@minimalsm can we merge this? I'll be leaving Alchemy in 3 days to go back to school and then can't do much from here to continue on this after the holidays, so would love to have these be mutually beneficial to both you and us! Have made all the changes — should be ready to go.

2022-02-04 15:42 UTC, minimalsm commented
Closing as per [this comment](https://github.com/ethereum/ethereum-org-website/pull/4284#issuecomment-1030104270)

2022-02-04 15:42 UTC, closed without merging