Executing and Interacting with a Smart Contract (Part 2/4 of Hello World dApp Series)
ethereum/ethereum-org-website pull request #4280
Opened 2021-10-23 04:42 UTC by nstrike2

## Description

Added header tags for each of the titles as per request from @minimalsm. Please make sure to approve/merge [changes to Part 1/4](https://ethereum.org/en/developers/tutorials/hello-world-smart-contract/) to update its title before approving/merging this one.

## Related Issue

Continuation of https://github.com/ethereum/ethereum-org-website/pull/4158, which has now been closed due to inaccessibility.

Related Issue: https://github.com/ethereum/ethereum-org-website/issues/4068

2021-11-24 00:05 UTC, nstrike2 commented
@minimalsm @corwintines @pettinarip @samajammin @wackerow Can we get this merged? If not, happy to change what needs to be changed to get this merged.

2021-11-24 14:05 UTC, minimalsm commented on src/content/developers/tutorials/executing-and-interacting-with-a-smart-contract/index.md
> +# 💻 Executing and Interacting with a Smart Contract
We don't currently have support for using Emojis in headings (we use Twemoji to ensure emojis are consistent across browsers but it breaks the table of contents include them in headers). Can we remove them across these tutorials, please?

```suggestion
# Executing and Interacting with a Smart Contract
```

2021-11-24 14:07 UTC, minimalsm commented on src/content/developers/tutorials/executing-and-interacting-with-a-smart-contract/index.md
> +# 💻 Executing and Interacting with a Smart Contract
Also, could you please ensure all headers have header ids

e.g. `# Executing and Interacting with a Smart Contract {#executing-and-interacting}`

2021-11-24 14:14 UTC, minimalsm requested changes

2021-11-24 14:14 UTC, minimalsm commented on src/content/developers/tutorials/executing-and-interacting-with-a-smart-contract/index.md
> +## Part 2: Interact with your Smart Contract
Please add a header id here

2021-11-24 14:14 UTC, minimalsm commented on src/content/developers/tutorials/executing-and-interacting-with-a-smart-contract/index.md
> +**⏫ Step 7:** [Read the new message](./#step-7-read-the-new-message)
We already have a table of contents built into our tutorials page as a side panel, could we remove this please.

2021-11-24 14:14 UTC, minimalsm commented on src/content/developers/tutorials/executing-and-interacting-with-a-smart-contract/index.md
> +Inside your `scripts/`folder for the hardhat tutorial, or your home directory for the [Truffle tutorial](./#create-and-deploy-your-smart-contract-using-truffle), create a new file named `interact.js`
The link here doesn't do anything?

```suggestion
Inside your `scripts/`folder for the Hardhat tutorial, or your home directory for the Truffle tutorial, create a new file named `interact.js` add the following lines of code:
```

2021-11-24 14:14 UTC, minimalsm commented on src/content/developers/tutorials/executing-and-interacting-with-a-smart-contract/index.md
> +This guide assumes you already have an [Alchemy account](https://alchemy.com/?r=e68b2f77-7fc7-4ef7-8e9c-cdfea869b9b5), access to our [Dashboard](https://dashboard.alchemyapi.io/) and have gone throug
As discussed in the previous PR, we need to remove all tracking links as it conflicts with our privacy policy.

```suggestion
This guide assumes you already have an [Alchemy account](https://alchemy.com/), access to our [Dashboard](https://dashboard.alchemyapi.io/) and have gone through our [Hello World Smart Contract](https://docs.alchemy.com/alchemy/tutorials/hello-world-smart-contract) tutorial. 
```

2021-11-24 14:14 UTC, minimalsm commented on src/content/developers/tutorials/executing-and-interacting-with-a-smart-contract/index.md
> +And if you haven't already, you'll definitely need an Alchemy account to complete this tutorial as well as build anything on the blockchain. Sign up for a free account [here](https://alchemy.com/?a=e
```suggestion
And if you haven't already, you'll definitely need an Alchemy account to complete this tutorial as well as build anything on the blockchain. Sign up for a free account [here](https://alchemy.com/)!
```

2021-11-24 14:14 UTC, minimalsm commented on src/content/developers/tutorials/executing-and-interacting-with-a-smart-contract/index.md
> +Remember when we deployed our contract with the`initMessage = "Hello world!"`? We are now going to read that message stored in our smart contract and print it to the console.&#x20;
```suggestion
Remember when we deployed our contract with the`initMessage = "Hello world!"`? We are now going to read that message stored in our smart contract and print it to the console.
```

2021-11-24 14:14 UTC, minimalsm commented on src/content/developers/tutorials/executing-and-interacting-with-a-smart-contract/index.md
> +In JavaScript we use asynchronous functions to interact with networks. Check out this [article](https://blog.bitsrc.io/understanding-asynchronous-javascript-the-event-loop-74cd408419ff) to learn more
```suggestion
In JavaScript we use asynchronous functions to interact with networks. Check out this [article](https://blog.bitsrc.io/understanding-asynchronous-javascript-the-event-loop-74cd408419ff) to learn more about async functions.
```

2021-12-16 09:07 UTC, nstrike2 commented
Hey @minimalsm , finished the changes for Part 2/4.

2021-12-18 03:34 UTC, nstrike2 commented
@minimalsm wanted to follow up to get these all pushed!

2021-12-21 07:41 UTC, nstrike2 commented
@minimalsm can we merge this? I'll be leaving Alchemy in 3 days to go back to school and then can't do much from here to continue on this after the holidays, so would love to have these be mutually beneficial to both you and us! Have made all the changes — should be ready to go.

2022-02-04 15:41 UTC, minimalsm commented
Closing as per [this comment](https://github.com/ethereum/ethereum-org-website/pull/4284#issuecomment-1030104270)

2022-02-04 15:41 UTC, closed without merging