Submitting and Verifying your Smart Contract to Etherscan (Part 3/4 of Hello World dApp Series)
ethereum/ethereum-org-website pull request #4281
Opened 2021-10-23 06:17 UTC by nstrike2

## Description

Added header tags for each of the titles as per request from @minimalsm. Please make sure to approve/merge [changes to Part 1/4](https://ethereum.org/en/developers/tutorials/hello-world-smart-contract/) and [Part 2/4](https://github.com/ethereum/ethereum-org-website/pull/4280) before approving/merging this one.

## Related Issue

Continuation of https://github.com/ethereum/ethereum-org-website/pull/4159, which has now been closed due to inaccessibility.

Related Issue: https://github.com/ethereum/ethereum-org-website/issues/4092

2021-11-24 00:05 UTC, nstrike2 commented
@minimalsm @corwintines @pettinarip @samajammin @wackerow Can we get this merged? If not, happy to change what needs to be changed to get this merged.

2021-11-24 16:55 UTC, minimalsm requested changes

2021-12-16 09:19 UTC, nstrike2 commented
Hey @minimalsm , finished the changes for Part 3/4.

2021-12-16 10:12 UTC, minimalsm requested changes
Hey @nstrike2 thanks for getting changes in on these. Just doing another quick sweep on markdown/best practices and we can get to double-checking content 😀 thanks for your patience and persistence ❤️

2021-12-16 10:12 UTC, minimalsm commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +This guide assumes you already have an [Alchemy account](https://alchemy.com/?a=eth-org-etherscan), access to our [Dashboard](https://dashboard.alchemyapi.io/), have gone through our [Hello World Sma
This is a duplicate of the above

```suggestion
```

2021-12-16 10:12 UTC, minimalsm commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +### Step 1: Generate an API Key on your Etherscan account {#step-1-generate-an-api-key-on-your-etherscan-account}
```suggestion
### Step 1: Generate an API Key on your Etherscan account {#generate-an-api-key-on-your-etherscan-account}
```

2021-12-16 10:12 UTC, minimalsm commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +### Step 2: HardHat-deployed smart contracts {#step-2-hardhat-deployed-smart-contracts}
```suggestion
### Step 2: HardHat-deployed smart contracts {#hardhat-deployed-smart-contracts}
```

2021-12-16 10:12 UTC, minimalsm commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +#### Step 2.1 Install the [`hardhat-etherscan`](https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html) plugin {#step-2.1-install-the-hardhat-etherscan-plugin}
We can't link in headers

```suggestion
#### Step 2.1 Install hardhat-etherscan {#install-hardhat-etherscan}
```

2021-12-16 10:12 UTC, minimalsm commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +#### Step 2.2 Verify your smart contract on Etherscan! {#step-2.2-verify-your-smart-contract-on-etherscan}
```suggestion
#### Step 2.2 Verify your smart contract on Etherscan {#verify-your-smart-contract-on-etherscan}
```

2021-12-16 10:12 UTC, minimalsm commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +#### Step 3.2 Verify your smart contract on Etherscan! {#step-3.2-verify-your-smart-contract-on-etherscan}
```suggestion
#### Step 3.2 Verify your smart contract on Etherscan {#truffle-verify-your-smart-contract-on-etherscan}
```

2021-12-16 10:12 UTC, minimalsm commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +### Step 4: Check out your smart contract on Etherscan! {#step-4-check-out-your-smart-contract-on-etherscan!}
```suggestion
### Step 4: Check out your smart contract on Etherscan! {#check-out-your-smart-contract-on-etherscan!}
```

2021-12-16 10:12 UTC, minimalsm commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +![](https://gblobscdn.gitbook.com/assets%2F-MB17w56kk7ZnRMWdqOL%2F-MReibSVpLlOCa_Si494%2F-MRewuf9NzToMPg5WIln%2Fimage.png?alt=media&token=ca99b37e-6847-4b7a-8fef-371783f2e536)
We should host any images we include on ethereum.org so we're not relying on third parties for their availability ([Check out the style guide for an example](https://ethereum.org/en/contributing/style-guide/#images)). Could you upload this image in the local directory and reference it that way instead?

```suggestion
![](https://gblobscdn.gitbook.com/assets%2F-MB17w56kk7ZnRMWdqOL%2F-MReibSVpLlOCa_Si494%2F-MRewuf9NzToMPg5WIln%2Fimage.png?alt=media&token=ca99b37e-6847-4b7a-8fef-371783f2e536)
```

2021-12-16 10:12 UTC, minimalsm commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +#### Step 3.1: Install the `truffle-plugin-verify` plugin {#step-3.1-install-the-truffle-plugin-verify-plugin}
```suggestion
#### Step 3.1: Install the `truffle-plugin-verify` plugin {#install-the-truffle-plugin-verify-plugin}
```

2021-12-16 10:12 UTC, minimalsm commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +### Step 3: Truffle-deployed smart contracts {#step-3-truffle-deployed-smart-contracts}
```suggestion
### Step 3: Truffle-deployed smart contracts {#truffle-deployed-smart-contracts}
```

2021-12-16 10:12 UTC, minimalsm commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +Make sure your files are properly saved \(especially if you're in VSCode\) and your `.env` variables are properly configured.
```suggestion
Make sure your files are properly saved (especially if you're in VSCode) and your `.env` variables are properly configured.
```

2021-12-16 10:12 UTC, minimalsm commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +You should have completed part 1 [creating and deploying a smart contract](https://docs.alchemy.com/alchemy/tutorials/hello-world-smart-contract), and part 2 [interacting with your smart contract](ht
Note: we'll should probably change this to the ethereum.org version once this is live

2021-12-16 10:19 UTC, nstrike2 commented
> Note: we'll should probably change this to the ethereum.org version once this is live

Will do!

2021-12-16 10:19 UTC, nstrike2 commented
> Hey @nstrike2 thanks for getting changes in on these. Just doing another quick sweep on markdown/best practices and we can get to double-checking content 😀 thanks for your patience and persistence ❤️

You're the best @minimalsm 🙏 — just fixed your changes

2021-12-18 03:34 UTC, nstrike2 commented
@minimalsm wanted to follow up to get these all pushed!

2021-12-21 07:40 UTC, nstrike2 commented
@minimalsm can we merge this? I'll be leaving Alchemy in 3 days to go back to school and then can't do much from here to continue on this after the holidays, so would love to have these be mutually beneficial to both you and us! Have made all the changes — should be ready to go.

2021-12-30 14:56 UTC, nstrike2 commented
Following up @minimalsm !

2021-12-30 15:00 UTC, nstrike2 commented
> # [Gatsby Cloud](https://www.gatsbyjs.com) Build Report
> 🚩 Your build failed. [See the build logs here](https://gatsbyjs.com/dashboard/5e02f963-3fe5-4e37-a1e7-ac05f7753a86/sites/dc7c4340-a8e9-44ed-b7be-883c70d2f02d/builds/d1e39ff5-1376-4140-a916-485c609606d0/details)

@minimalsm not super sure why the build is failing, can't see the logs, as I don't have access (see screenshot) — would love some clarity here!

<img width="1254" alt="Screen Shot 2021-12-30 at 10 00 00 AM" src="https://user-images.githubusercontent.com/75461391/147762983-efd06020-33b4-4ac0-b958-baacf35c7312.png">

2022-02-03 06:59 UTC, sukruarc requested changes

2022-02-03 06:59 UTC, sukruarc commented on src/content/developers/tutorials/submitting-and-verifying-your-smart-contract-to-etherscan/index.md
> +Once you complete this tutorial, let us know how your experience was or if you have any feedback by tagging us on Twitter [@alchemyplatform](https://twitter.com/AlchemyPlatform)!
Eth

2022-02-04 15:42 UTC, minimalsm commented
Closing as per [this comment](https://github.com/ethereum/ethereum-org-website/pull/4284#issuecomment-1030104270)

2022-02-04 15:42 UTC, closed without merging