Add tutorial: NFT Minter tutorial
ethereum/ethereum-org-website pull request #4282
Opened 2021-10-23 06:53 UTC by nstrike2

As a Go-To-Market engineer at Alchemy, I am creating a tutorial on how to create a full-stack NFT Minter due to heavily popular demand as a PR to the Ethereum foundation, titled "📝 NFT Minter Tutorial: How to Create a Full Stack DApp".

Added header tags for each of the titles as per request from @minimalsm.

Thank you and let's go builders!!!

## Description

As a Go-To-Market engineer at Alchemy, I am creating a tutorial on how to create a full-stack NFT Minter due to heavily popular demand as a PR to the Ethereum foundation, titled "📝 NFT Minter Tutorial: How to Create a Full Stack DApp".

## Related Issue

Continuation of https://github.com/ethereum/ethereum-org-website/pull/4162, which has now been closed due to inaccessibility.

https://github.com/ethereum/ethereum-org-website/issues/4134

2021-11-24 00:05 UTC, nstrike2 commented
@minimalsm @corwintines @pettinarip @samajammin @wackerow Can we get this merged? If not, happy to change what needs to be changed to get this merged.

2021-11-24 02:02 UTC, samajammin commented
Thanks for the nudge - @corwintines or @minimalsm can you please review?

2021-11-24 15:03 UTC, minimalsm requested changes
Hey @nstrike2 thanks for the PR and sorry for the delay on this 😬🙏. I've left a quick first review to get the ball rolling ⚽️

I've left comments on the article itself but these are some general comments that are consistent across all of the tutorials you've posted. If we could resolve these we can get moving on these a lot faster.

- All headings must have header-ids
- Ethereum.org uses sentence casing for header names as a convention. Only the first word and proper nouns are capitalized. This applies to all markdown files on lines that begin with hashes (#).
- We can't use Emojis in headers as it causes issues with the table of contents
- We don't want a custom table of content's written into the content itself as we already have a sidebar component that handles this for us automatically
- Emojis should use the emoji component as [per our style guide](https://ethereum.org/en/contributing/style-guide/#images) to ensure consistency across devices and browsers
- All images must be saved locally (don't point to other websites). When adding an image to a page, the image should be downloaded and placed in the same folder as the markdown file. You can reference the image like this:`![alt text for image](./image.png)`

2021-12-16 09:50 UTC, nstrike2 commented on src/content/developers/tutorials/nft-minter/index.md
> +### Get your react project running
@minimalsm I don't need a header for a sub-bullet "Get your react project running" — I'm only using them for steps (e.g. Step 1, Step 2, etc.)

2021-12-16 09:55 UTC, nstrike2 commented
@minimalsm , at this point I've resolved all changes for this tutorial, and the hello world series (part 1/4, 2/4, 3/4, and 4/4). I hope we can close the loop here on all of them! Please let me know, as I'd love to get these all merged before the holidays.

2021-12-21 07:40 UTC, nstrike2 commented
@minimalsm can we merge this? I'll be leaving Alchemy in 3 days to go back to school and then can't do much from here to continue on this after the holidays, so would love to have these be mutually beneficial to both you and us! Have made all the changes — should be ready to go.

2022-02-28 13:39 UTC, minimalsm requested changes

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +## Step 0: Making NFTs 101 {#making-nfts-101}
```suggestion
## Making NFTs 101 {#making-nfts-101}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +### 1\) You publish an NFT smart contract on the Ethereum blockchain. Usually this is an [ERC-721](https://eips.ethereum.org/EIPS/eip-721) or [ERC-1155](https://eips.ethereum.org/EIPS/eip-1155) smart
```suggestion
### Publish an NFT smart contract on the Ethereum blockchain {#publish-nft}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +### 2\) You call the minting function on that NFT smart contract to mint the NFT. _Minting_ is simply the act of publishing a unique instance of your non fungible token on the blockchain.
```suggestion
### Call the minting function {#minting-function}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +Doing so should open [http://localhost:3000/](http://localhost:3000/) in your browser, where you'll see the frontend for our project. It should consist of 3 fields: a place to input a link to your NF
```suggestion
Doing so should open http://localhost:3000/ in your browser, where you'll see the frontend for our project. It should consist of 3 fields: a place to input a link to your NFT's asset, enter the name of your NFT, and provide a description.
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +### The `Minter.js` component
```suggestion
### The Minter.js component {#minter-js}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +### Download Metamask
```suggestion
### Download Metamask {#download-metamask}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +### The `getCurrentWalletConnected` function
```suggestion
### The getCurrentWalletConnected function {#get-current-wallet}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +## Step 5: NFT Metadata 101 {#nft-metadata-101}
```suggestion
## NFT Metadata 101 {#nft-metadata-101}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +* We could store it on the Ethereum blockchain; however, doing so would be SUPER expensive \(we're talking upwards of hundreds of dollars\) due to the nature of Ethereum. ❌
```suggestion
- We could store it on the Ethereum blockchain; however, doing so would be very expensive.
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +* We could store it on a centralized server, like AWS or Firebase. But that would defeat our decentralization ethos. ❌
```suggestion
- We could store it on a centralized server, like AWS or Firebase. But that would defeat our decentralization ethos.
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +* We could use IPFS, a decentralized protocol and peer-to-peer network for storing and sharing data in a distributed file system. As this protocol is decentralized and free, it is our best option! ✅
```suggestion
- We could use IPFS, a decentralized protocol and peer-to-peer network for storing and sharing data in a distributed file system. As this protocol is decentralized and free, it is our best option!
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +## Step 6: Use Pintata to pin your metadata to IPFS {#step-6-use-pinata-to-pin-your-metadata-to-IPFS}
```suggestion
## Use Pintata to pin your metadata to IPFS {#use-pinata-to-pin-your-metadata-to-IPFS}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +### Create your Pinata API key
```suggestion
### Create your Pinata API key {#create-pinata-api-key}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +### Implement `pinJSONToIPFS`
```suggestion
### Implement pinJSONToIPFS {#pin-json-to-ipfs}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +## Step 11: Take the blockchain world by storm {#take-the-blockchain-world-by-storm}
```suggestion
## Take the blockchain world by storm {#take-the-blockchain-world-by-storm}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +## Step 10: Deploy your NFT to a live website {#deploy-your-NFT}
```suggestion
## Deploy your NFT to a live website {#deploy-your-NFT}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +**NOTE:** The transactions sent through Metamask will use Metamask's default provider \(not necessarily your Alchemy endpoint\). If you'd like to send those transactions through Alchemy to unlock deb
```suggestion
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +And, as always, if you have any questions, we're here to help in the [Alchemy Discord](https://discord.gg/gWuC7zB). We can't wait to see how you apply the concepts from this tutorial to your future p
```suggestion
And, as always, if you have any questions, we're here to help in the [Alchemy Discord](https://discord.gg/gWuC7zB). We can't wait to see how you apply the concepts from this tutorial to your future projects! 
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +Once you complete this tutorial, let us know how your experience was or if you have any feedback by tagging us on Twitter [@alchemyplatform](https://twitter.com/AlchemyPlatform)!
```suggestion
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +## Step 9: Connect mintNFT to our Minter.js frontend {#connect-our-frontend}
```suggestion
## Connect mintNFT to our Minter.js frontend {#connect-our-frontend}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +## Step 8: Implement the mintNFT function {#step-8-implement-the-mintnft-function}
```suggestion
## Implement the mintNFT function {#implement-the-mintnft-function}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +Name your app \(we chose "My First NFT!"\), offer a short description, select “Staging” for the Environment \(used for your app bookkeeping\), and choose “Ropsten” for your network.
```suggestion
Name your app we chose "My First NFT!", offer a short description, select “Staging” for the Environment used for your app bookkeeping, and choose “Ropsten” for your network.
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +### The contract ABI
```suggestion
### The contract ABI {#contract-abi}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +## Step 7: Load your smart contract {#load-your-smart-contract}
```suggestion
## Load your smart contract {#load-your-smart-contract}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +Once you've added this code, try refreshing our browser window. The button should say that you're connected, and show a preview of your connected wallet's address - even after you refresh! 😅
```suggestion
Once you've added this code, try refreshing our browser window. The button should say that you're connected, and show a preview of your connected wallet's address - even after you refresh! 
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +You should see that the wallet button now reflects that your address is connected! Yasssss 🔥
```suggestion
You should see that the wallet button now reflects that your address is connected.
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +Now, let's save both files \(`Minter.js` and `interact.js`\) and test out our UI so far.
```suggestion
Now, let's save both files `Minter.js` and `interact.js` and test out our UI so far. 
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +Open your browser on the [http://localhost:3000/](http://localhost:3000/) page, and press the "Connect Wallet" button on the top right of the page.
```suggestion
Open your browser on the http://localhost:3000/ page, and press the "Connect Wallet" button on the top right of the page.
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +### The `connectWallet` function
```suggestion
### The `connectWallet` function {#connect-wallet-function}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +## Step 4: Connect Metamask to your UI {#connect-metamask-to-your-UI}
```suggestion
## Connect Metamask to your UI {#connect-metamask-to-your-UI}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +### Add ether from a Faucet <a id="step-4-add-ether-from-a-faucet"></a>
```suggestion
### Add ether from a Faucet {#add-ether-from-faucet}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +For this tutorial, we’ll use Metamask, a virtual wallet in the browser used to manage your Ethereum account address. If you want to understand more about how transactions on Ethereum work, check out
```suggestion
For this tutorial, we’ll use Metamask, a virtual wallet in the browser used to manage your Ethereum account address. If you want to understand more about how transactions on Ethereum work, check out [this page](/developers/docs/transactions/).
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +## Step 3: Set up your Ethereum wallet {#step-3-set-up-your-ethereum-wallet}
```suggestion
##: Set up your Ethereum wallet {#set-up-your-ethereum-wallet}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +## Step 1: Clone the starter files {#clone-the-starter-files}
```suggestion
## Clone the starter files {#clone-the-starter-files}
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +# 📝 NFT Minter Tutorial: How to Create a Full Stack DApp
```suggestion
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +* Connect to Metamask via your frontend project
```suggestion
- Connect to Metamask via your frontend project
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +* Sign transactions using Metamask
```suggestion
- Call smart contract methods from your frontend
- Sign transactions using Metamask
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +* `minter-starter-files` contains the starter files \(essentially the React UI\) for this project. In this tutorial, **we will be working in this directory**, as you learn how to bring this UI to lif
```suggestion
* `minter-starter-files` contains the starter files (essentially the React UI) for this project. In this tutorial, **we will be working in this directory**, as you learn how to bring this UI to life by connecting it to your Ethereum wallet and an NFT smart contract.
```

2022-02-28 13:39 UTC, minimalsm commented on src/content/developers/tutorials/nft-minter/index.md
> +Next open your copy of `minter-starter-files` in to your favorite code editor \(at Alchemy, we we're big fans of [VSCode](https://code.visualstudio.com/download)\), and then navigate into your `src`
```suggestion
Next, open your copy of `minter-starter-files` in your code editor, and then navigate into your `src` folder.
```

2022-02-28 14:17 UTC, minimalsm approved these changes

2022-02-28 14:18 UTC, merged