refactor(docs): move security page inside smart contract
ethereum/ethereum-org-website pull request #4383
Opened 2021-11-03 09:49 UTC by il3ven

## Description
- Moved the current [security page](https://ethereum.org/en/developers/docs/security/) into smart contracts.
- Updated links, description and id

The issue also mentioned `Upload changes to CrowdIn`. I am not sure if I need to do this.

## Related Issue

Fixes #4273

2021-11-03 10:08 UTC, minimalsm commented
Hey @il3ven thanks for the very comprehensive PR on this 🤩 Will get round to reviewing this properly today.

> The issue also mentioned Upload changes to CrowdIn. I am not sure if I need to do this.

Nope. Sorry, I should have been more clear. Uploading to CrowdIn is something the core team must do internally.

2021-11-04 16:57 UTC, samajammin commented on src/intl/en/page-developers-docs.json
> +  "docs-nav-smart-contract-security": "Smart Contract Security",
```suggestion
  "docs-nav-smart-contract-security": "Smart contract security",
```
Changing to sentence case for consistency w/ the rest of our links here.

2021-11-04 16:57 UTC, samajammin commented on src/intl/en/page-developers-docs.json
> +  "docs-nav-smart-contract-security-description": "Best practices for managing smart contract attacks and vulnerabilitie",
```suggestion
  "docs-nav-smart-contract-security-description": "Best practices for managing smart contract attacks and vulnerabilities",
```
Typo fix

2021-11-04 16:58 UTC, samajammin commented on src/intl/en/page-developers-index.json
> +  "page-developers-smart-contract-security-link": "Smart Contract Security",
```suggestion
  "page-developers-smart-contract-security-link": "Smart contract security",
```

2021-11-05 11:46 UTC, minimalsm requested changes

2021-11-05 11:46 UTC, minimalsm commented on src/content/contributing/translation-program/content-versions/index.md
> +- [Smart Contract Security](/developers/docs/smart-contracts/security/)
```suggestion
- [Smart contract security](/developers/docs/smart-contracts/security/)
```

2021-11-05 11:46 UTC, minimalsm commented on src/content/glossary/index.md
> +<DocLink to="/developers/docs/smart-contracts/security/" title="Smart Contract Security" />
```suggestion
<DocLink to="/developers/docs/smart-contracts/security/" title="Smart contract security" />
```

2021-11-05 11:46 UTC, minimalsm commented on src/content/glossary/index.md
> +<DocLink to="/developers/docs/smart-contracts/security/" title="Smart Contract Security" />
```suggestion
<DocLink to="/developers/docs/smart-contracts/security/" title="Smart contract security" />
```

2021-11-05 12:03 UTC, minimalsm approved these changes

2021-11-05 12:03 UTC, merged

2021-11-05 12:05 UTC, minimalsm commented
Updated relevant pages in CrowdIn, thanks for this @il3ven ❤️

This is also your 5th merged PR on the repo so you can claim some new POAPs too! Check [this discord message](https://discord.com/channels/714888181740339261/887696410567385138/894720659077345291) for context.