add skip link to main content button
ethereum/ethereum-org-website pull request #4570
Opened 2021-11-28 14:42 UTC by il3ven

## Description
I have added a banner on top of the page that is displayed when TAB is pressed. Pressing ENTER on the banner navigates to an element with `id=main-content`. Currently, I have added this *id* to 3 types of pages.
- Home Page (`src/pages/index.js`)
- Developer Documentation (`src/templates/docs.js`)
- Static Page (`src/templates/static.js`)

I want to get feedback on the implementation. If it is good then I can add *id* to more pages.

## Related Issue
Fixes #4425

2021-12-01 13:07 UTC, minimalsm commented
Hey @il3ven is this ready for review?

If so, please move it out of draft :-)

2021-12-09 16:39 UTC, minimalsm commented
@il3ven

2021-12-09 20:18 UTC, il3ven commented
> Hey @il3ven is this ready for review?
> 
> If so, please move it out of draft :-)

I marked it as a draft for an early feedback. Anyway, I have now completed the PR now and it is ready for review. Sorry, for the delay. I was working on something else.

2021-12-15 15:45 UTC, minimalsm requested changes
Thanks @il3ven, really great start on this.

I think we might be able to make this a little bit cleaner by targeting the `MainContent` in our [Layout.js file](https://github.com/ethereum/ethereum-org-website/blob/eb6e72418cc02bc442c606ad8aacdf21a01d9a7e/src/components/Layout.js#L153) instead of adding ids to every page. What do you think?

2021-12-20 18:27 UTC, samajammin requested changes
Awesome - thanks for this PR @il3ven! 

I agree with @minimalsm on this - I think we could add the `id` to an element with in the Layout component to make this update a bit cleaner.

2021-12-20 19:42 UTC, pettinarip requested changes
Loved this contribution @il3ven. I've added a minor comment.

2021-12-20 19:42 UTC, pettinarip commented on src/components/SkipTo.js
> +const SkipTo = ({ href_id }) => {
For consistency, let's use camelCase for props names: `hrefId`.

2021-12-20 20:04 UTC, minimalsm commented on src/components/SkipTo.js
> +const SkipTo = ({ href_id }) => {
Calling this component a SkipLink makes more semantic sense to me

```suggestion
const SkipLink = ({ href_id }) => {
```

2021-12-20 20:32 UTC, il3ven commented
You all are giving me more credit than I deserve. This is just a small PR. 😅 I have incorporated all your suggestions. This PR is ready to be merged.

2021-12-21 12:40 UTC, pettinarip approved these changes
lgtm!

2021-12-22 03:52 UTC, wackerow approved these changes
Looks good 😃  Just made the copy intl-ready. Bringing it in 💪🏻

2021-12-22 03:52 UTC, merged