Build translator acknowledgement page
ethereum/ethereum-org-website pull request #4571
Opened 2021-11-29 00:07 UTC by corwintines

## Description
Build out the Translation acknowledgement page, and contributor listing page. 

New Pages:
/contributing/translation-program/acknowledgements/
/contributing/translation-program/contributors/

2021-11-29 23:36 UTC, samajammin commented on src/components/TranslationLeaderboard.js
> +import monthData from "../data/translation_reports/month_data.json"
Minor nitpick & I don't believe this is actually stated anywhere but we've used dashes vs. underscores for directory & file names.

2021-11-29 23:41 UTC, samajammin commented on src/content/contributing/translation-program/index.md
> +  <a href="https://ethereum.org/en/contributing/translation-program/acknowledgements/">Translator Acknowledgements!</a>
I'm noticing we use this incorrectly elsewhere as well but this should use the Link component so we can use relative links here vs. hardcoding the production link. i.e.

`<Link to="contributing/translation-program/acknowledgements/">Translator Acknowledgements!</Link>`

2021-11-29 23:43 UTC, samajammin commented on src/intl/en/common.json
> +  "acknowledgements": "Acknowledgements",
Doesn't seem like we use this anywhere?

2021-11-29 23:50 UTC, samajammin commented
This looks a bit awkward. Let's chat through alternatives here:
![Image 2021-11-29 at 5 38 05 PM](https://user-images.githubusercontent.com/8097623/143960731-fea05c21-6a24-4c2b-9193-2c6b2eb95dd6.jpg)

2021-11-30 01:47 UTC, samajammin commented on src/intl/en/page-contributing-translation-program-acknowledgements.json
> +  "page-contributing-translation-program-acknowledgements-acknowledgement-page-title": "Acknowledgement Page",
"Acknowledgement Page" feels like a weird page title to me. Maybe something more "human", like "Acknowledging our contributors"?

2021-11-30 01:50 UTC, samajammin commented on src/components/TranslationLeaderboard.js
> +                    size={1.5}
The sizing here doesn't appear to be enforced - I'm seeing a range of sizes that looks to vary depending on the size of the `translated` number:
![Image 2021-11-29 at 7 47 00 PM](https://user-images.githubusercontent.com/8097623/143971050-52cce4e0-ae6a-454a-8999-0099f8097c66.jpg)

2021-11-30 01:54 UTC, samajammin commented on src/components/TranslationLeaderboard.js
> +                  <Emoji mr={"1rem"} text={emoji} />
These trophy emojis feel way too small - can we make them look similar to the bug bounty leaderboard?
![Image 2021-11-29 at 7 52 11 PM](https://user-images.githubusercontent.com/8097623/143971379-7cf4f3cf-a68f-4078-8ffd-1974721fd534.jpg)

2021-11-30 01:55 UTC, samajammin commented on src/components/TranslationLeaderboard.js
> +                  <Emoji mr={"1rem"} text={emoji} />
I know we're listing more results but in general I feel like this table could use a bit more breathing room, similar to size & spacing of the bug bounty leaderboard rows.

2021-11-30 01:58 UTC, samajammin commented on src/components/TranslationLeaderboard.js
> +const ButtonSecondaryStyled = styled(ButtonSecondary)`
I like the look of these buttons but they seem too close to the table & overall the spacing feels tight:
![Image 2021-11-29 at 7 56 09 PM](https://user-images.githubusercontent.com/8097623/143971845-f91361bd-b753-4bf2-ae52-76dc37d5853a.jpg)

I feel like we could work off existing elements, e.g. the pills of the dapps page:
![Image 2021-11-29 at 7 55 54 PM](https://user-images.githubusercontent.com/8097623/143971896-b01af833-c397-4193-b47a-6bb7b7858816.jpg)

2021-11-30 01:59 UTC, samajammin commented on src/components/TranslationLeaderboard.js
> +const ButtonSecondaryStyled = styled(ButtonSecondary)`
Really whenever possible I'd encourage us to re-use similar elements for consistency (& ideally sharing the styles in our code).

2021-11-30 04:57 UTC, corwintines commented on src/intl/en/common.json
> +  "acknowledgements": "Acknowledgements",
The breadcrumbs use this

2021-11-30 22:04 UTC, wackerow reviewed
This is looking awesome! Nice job @corwintines 🤩 Left a couple code suggestions... one is just fixing the alignment of text, the other is up to the collective, if we're down for larger avatars with the current layout.

Looking forward to getting this up!

2021-12-01 13:18 UTC, minimalsm commented
I like the increased size of the medal/trophy emojis but we should fix the alignment between emojis and regular numbers.

Current:
<img width="738" alt="Screenshot 2021-12-01 at 13 11 46" src="https://user-images.githubusercontent.com/62268199/144241187-08381183-854f-4b2c-ab19-613a4dc8d1dc.png">

Suggested:
<img width="734" alt="Screenshot 2021-12-01 at 13 15 56" src="https://user-images.githubusercontent.com/62268199/144241193-43f71bde-6690-4084-956c-1e8f07d4bac7.png">

2021-12-01 13:24 UTC, minimalsm commented
Given that the translation leaderboard is the main feature of this page I'm wondering if giving it more space on the page might make more sense. We could easily add the accompanying block of text below it.

<img width="1713" alt="Screenshot 2021-12-01 at 13 21 46" src="https://user-images.githubusercontent.com/62268199/144241986-4e0fbb00-5415-4bef-9183-295b0088fcac.png">

2021-12-02 05:36 UTC, samajammin commented
> Given that the translation leaderboard is the main feature of this page I'm wondering if giving it more space on the page might make more sense. We could easily add the accompanying block of text below it.

I agree with @minimalsm - we could easily consolidate that text and/or move it below.

2021-12-02 05:41 UTC, samajammin commented
Noticed some copy changes weren't displaying in the preview - just tried clearing the Netlify cache & redeploying.

2021-12-02 05:44 UTC, samajammin commented
I still think we should merge these callouts - let's quickly chat through copy tomorrow:
![Image 2021-12-01 at 9 42 58 PM](https://user-images.githubusercontent.com/8097623/144364754-4debc998-e09e-43e0-b129-c93d320475ce.jpg)

2021-12-02 05:47 UTC, samajammin requested changes
Looking great! I think it's just about there. Commented with couple change suggestions we can chat through tomorrow.

2021-12-02 13:47 UTC, minimalsm commented
> I like the increased size of the medal/trophy emojis but we should fix the alignment between emojis and regular numbers.
> 

Sorry, I don't think this was clear. I've tried to illustrate the problem better with the image below.

<img width="291" alt="Screenshot 2021-12-02 at 13 45 42" src="https://user-images.githubusercontent.com/62268199/144434164-947a7bd1-8170-40d1-85f8-7c6754aab24c.png">

2021-12-02 14:50 UTC, pettinarip reviewed
GJ! looking great @corwintines. I've added a couple of minor comments.

2021-12-02 14:50 UTC, pettinarip commented on src/pages/contributing/translation-program/contributors.js
> +    <Page>
Shouldn't we have a `PageMetadata` here as well? I've loaded the page and I don't see a title in the browser tab.

2021-12-02 14:50 UTC, pettinarip commented on src/pages/contributing/translation-program/contributors.js
> +              return <ListItem>{user}</ListItem>
Lets add a `key` here `<ListItem key={user}>{user}</ListItem>`

2021-12-02 17:14 UTC, pettinarip approved these changes

2021-12-02 19:11 UTC, Aivolt1 approved these changes

2021-12-03 00:46 UTC, samajammin requested changes
This looks terrific @corwintines!

Only a couple small mobile issues I'd like us to clean up before merging:

Not a great word wrap in the title on mobile. Perhaps we reduce the header size on mobile?
![95C61D6D-B20C-4F51-A839-1527F990540D_1_105_c](https://user-images.githubusercontent.com/8097623/144525547-4363dd27-56cb-430f-abb2-4a63578d766a.jpeg)

Image is cropped on mobile:
![B8A406EB-070C-40E6-A265-DCF348D5316F_1_105_c](https://user-images.githubusercontent.com/8097623/144525593-e5a0b6a0-1a4a-431b-be39-59290c94947b.jpeg)

2021-12-03 02:41 UTC, samajammin approved these changes
🎉

2021-12-03 02:41 UTC, merged