Mark link to ConsenSys as deprecated
ethereum/ethereum-org-website pull request #4573
Opened 2021-11-29 11:26 UTC by MatthieuScarset

## Description

The [repo by ConsenSys(https://github.com/ConsenSys/Tokens#deprecated) is marked as deprecated.

I think it's safer to tell readers about it before redirecting them to the EIP20 contract page directly. One might not necessarily think about verifying the main README file and would reuse/copy-paste EIP20.

2021-11-29 14:30 UTC, minimalsm commented
Hey @MatthieuScarset, thanks for the heads up on this 🤘

Curious for your input here: wouldn't it be better to remove it seeing as we have other, up to date and maintained implementations of ERC-20 already listed?

2021-11-30 10:56 UTC, MatthieuScarset commented
Yes I would understand if we prefer to remove the link completely 🚮

I simply marked it "deprecated" as it was worth it for me to go read the code and compare both contracts.

2021-12-01 04:11 UTC, corwintines commented
I definitely +1 to deprecating it and just removing the link in favor of the OpenZepplin contracts that are linked out to.

2021-12-01 12:54 UTC, minimalsm requested changes

2021-12-01 12:54 UTC, minimalsm commented on src/content/developers/docs/standards/tokens/erc-20/index.md
> +- [ConsenSys - ERC-20 Implementation](https://github.com/ConsenSys/Tokens/blob/master/contracts/eip20/EIP20.sol) (deprecated)
I'm definitely in favour of just removing it.

1. The page is primarily solving for users who want to know what ERC-20 is or want to know how to implement it. I don't think keeping this in solves for either user group.
2. Defaulting to remove deprecated/unmaintained software makes it easy to make the change across all translated languages on the site  (the alternative being that we queue up translations for adding a deprecated label across ~40 languages every time something is out of date)

```suggestion
```

2021-12-02 16:20 UTC, minimalsm commented
Cool :-) To get this merged quick but keep @MatthieuScarset as last edited author I'm going to merge this and throw up another PR to remove the deprecated software section.

2021-12-02 16:20 UTC, minimalsm commented
@MatthieuScarset thanks again for the PR ❤️🚀

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

2021-12-02 16:21 UTC, minimalsm commented
@all-contributors please add @MatthieuScarset for docs

2021-12-02 16:21 UTC, merged