Article to explain how to do Reverse Engineering on EVM contracts
ethereum/ethereum-org-website pull request #4581
Opened 2021-11-29 15:01 UTC by qbzzt

An article that explains how to do it, using commonly available tools, with either the opcodes or a decompiler.

2022-01-05 19:09 UTC, wackerow requested changes
@qbzzt This is great! Super advanced, but such a cool resource that I'm sure a lot of folks out there will appreciate having. Just left a couple small tweaks/suggestions, but otherwise this looks good to me. Thanks! 🎉

2022-01-05 19:09 UTC, wackerow commented on src/content/developers/tutorials/reverse-engineering-a-contract/index.md
> +To be able to understand this article you should already know the basics of the EVM, and be at least somewhat familiar with EVM assembler. [You read about about these topics here](https://medium.com/
```suggestion
To be able to understand this article you should already know the basics of the EVM, and be at least somewhat familiar with EVM assembler. [You can read about about these topics here](https://medium.com/mycrypto/the-ethereum-virtual-machine-how-does-it-work-9abac2b7c9e).
```

2022-01-05 19:09 UTC, wackerow commented on src/content/developers/tutorials/reverse-engineering-a-contract/index.md
> +This just is superflous, since we're going to the next opcode. This code isn't nearly as gas-efficient as it could be.
```suggestion
This jump is superfluous, since we're going to the next opcode. This code isn't nearly as gas-efficient as it could be.
```

2022-01-05 19:09 UTC, wackerow commented on src/content/developers/tutorials/reverse-engineering-a-contract/index.md
> +
```suggestion
```

2022-01-05 19:09 UTC, wackerow commented on src/content/developers/tutorials/reverse-engineering-a-contract/index.md
> +The transaction is reverted without any return data.
Felt this read a little funny... how about this:
```suggestion
It looks like this function takes at least 32 bytes (one word) of call data.

| Offset | Opcode | Stack |
| -: | - | - |  
| 19D | DUP1 | 0x00 0x00 0x04 CALLDATASIZE 0x0153 0xDA | 
| 19E	| DUP2 | 0x00 0x00 0x00 0x04 CALLDATASIZE 0x0153 0xDA |
| 19F	| REVERT  

If it doesn't get the call data the transaction is reverted without any return data.
```

2022-01-06 16:23 UTC, qbzzt commented
Thank you @wackerow , I committted all three suggestions - maybe I should stop writing when I'm tired, but if I do that I'll never get anything done.

2022-01-21 05:32 UTC, wackerow approved these changes
Thanks @qbzzt! Pullin it in =) 💪

2022-01-21 05:33 UTC, merged