fix: ethdubai new dates, add meetup too
ethereum/ethereum-org-website pull request #4646
Opened 2021-12-04 20:32 UTC by patcito

Small fix to ETHDubai conference date. Also add link to meetup.

2021-12-05 21:47 UTC, minimalsm approved these changes

2021-12-06 12:34 UTC, minimalsm requested changes
Hey @patcito, thanks for the PR ❤️🇦🇪 The emoji wasn't working properly, I think using `:united_arab_emirates:` instead of `:uae:` should fix it. 

Could you also move this entry to the bottom of the meetups list as [per our listing criteria here.](https://ethereum.org/en/contributing/adding-products/#product-ordering)

2021-12-06 12:34 UTC, minimalsm commented on src/components/MeetupList.js
> +  },
Emoji is broke. I _think_ this should fix it?

```suggestion
  {
    title: "DeFi Dubai",
    emoji: ":united_arab_emirates:",
    location: "Dubai",
    link: "https://www.meetup.com/DeFi-Dubai/",
  },
```

2021-12-06 12:38 UTC, minimalsm commented
FYI I've created an issue (#4657) to randomise the meetup list to give all meetups an equal opportunity at visibility :-)

2021-12-06 13:19 UTC, patcito commented
I've pushed the changes let me know if this works for you.

2021-12-07 11:52 UTC, minimalsm commented
Awesome, thank you. Merging now.

Remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳!

2021-12-07 11:52 UTC, minimalsm approved these changes

2021-12-07 11:52 UTC, minimalsm commented
@all-contributors please add @patcito for docs

2021-12-07 11:52 UTC, merged