Add PoS FAQ link
ethereum/ethereum-org-website pull request #4694
Opened 2021-12-08 21:02 UTC by samajammin

## Description

Add link to PoS FAQ

## Related Issue
None

2021-12-09 14:22 UTC, minimalsm requested changes

2021-12-09 14:22 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pos/index.md
> +- [Proof of Stake FAQ](https://vitalik.ca/general/2017/12/31/pos_faq.html)
```suggestion
- [Proof of Stake FAQ](https://vitalik.ca/general/2017/12/31/pos_faq.html) _Vitalik Buterin_
```

2021-12-09 14:22 UTC, minimalsm approved these changes

2021-12-10 05:30 UTC, corwintines approved these changes

2021-12-10 05:31 UTC, merged