update further reading to include A rollup-centric ethereum roadmap
ethereum/ethereum-org-website pull request #4754
Opened 2021-12-12 20:50 UTC by MiConnell

## Description
This PR adds a link to A rollup-centric ethereum roadmap, which is mentioned at the end of the video from the `More of a visual learner` section

## Related Issue

2021-12-13 02:46 UTC, wackerow approved these changes
Thanks @MiConnell! Just noting we do have this article linked on the `/en/eth2/shard-chain` shard chains page, but agree it provides value on this page as well.

2021-12-13 09:26 UTC, minimalsm requested changes
Thanks for the PR @MiConnell 💪 Just need a small tweak to enforce the convention we use when referring to article authors.

2021-12-13 09:26 UTC, minimalsm commented on src/content/developers/docs/scaling/index.md
> +- [A rollup-centric ethereum roadmap by Vitalik Buterin](https://ethereum-magicians.org/t/a-rollup-centric-ethereum-roadmap/4698)
```suggestion
- [A rollup-centric ethereum roadmap](https://ethereum-magicians.org/t/a-rollup-centric-ethereum-roadmap/4698) _Vitalik Buterin_
```

2021-12-13 17:45 UTC, minimalsm commented
[ ] - Note to self - add this to style guide

2021-12-14 13:13 UTC, minimalsm commented
Thanks for the changes! (I've added hopefully clearer guidance around this in #4773). Merging 🚀 Don't forget to claim [claim your POAP](https://ethereum.org/en/contributing/#poap) for 2021 if you haven't already 🥳!

2021-12-14 13:13 UTC, merged

2021-12-15 03:41 UTC, MiConnell commented
awesome, thank you!