Enable Gatsby functions in preview deploys
ethereum/ethereum-org-website pull request #4919
Opened 2021-12-29 17:01 UTC by pettinarip

[DO NOT MERGE]

## Description

Currently we have the Netlify functions working in the Netlify context/server. On the other hand, in our preview deploys context (Gatsby Cloud) they are not working. We need to integrate them. This PR addresses this issue.

- Added `api` folder to enable functions in gatsby cloud.

TODO:
- Test the functions in Netlify

2021-12-29 17:22 UTC, pettinarip commented
Last successful build: https://build-fb029333-c741-4c84-a19c-959909c87fa9.gtsb.io/en/

2022-01-26 16:20 UTC, minimalsm commented
@pettinarip the URL you've provided to test is re-directing to Gatsby cloud dashboard

On the deploy preview, the StatsBox is working 🎉🎉 The Roadmap isn't for me :( (returns a 500)

2022-01-28 00:53 UTC, samajammin commented
Homepage stats are working on 
https://ethereumorgwebsitedev01-pettinaripethereumorgwebsitefu.gtsb.io/en/contributing/translation-program
https://pettinarip-eth-org.netlify.app/en/
Thought I'm not seeing the API requests in browser network tab 🤔 

Translations endpoint is failing (500) for me on:
https://pettinarip-eth-org.netlify.app/en/contributing/translation-program/
![Image 2022-01-27 at 4 48 07 PM](https://user-images.githubusercontent.com/8097623/151467604-d52c9c76-16a9-4c2c-8653-e07f7ddba3c6.jpg)
Also failing on:
https://ethereumorgwebsitedev01-pettinaripethereumorgwebsitefu.gtsb.io/en/contributing/translation-program

Roadmap endpoint is failing (500) for me on:
https://ethereumorgwebsitedev01-pettinaripethereumorgwebsitefu.gtsb.io/en/about
https://pettinarip-eth-org.netlify.app/en/about/

2022-01-28 00:55 UTC, samajammin commented on src/api/etherscan.js
> +import { handler as lambda } from "../lambda/etherscan"
Glad to see we can re-use the code 😄

2022-01-28 23:52 UTC, wackerow commented
@samajammin It may be the cache functionality... it doesn't refetch every time you reload...
New private browser:
![image](https://user-images.githubusercontent.com/54227730/151636134-6cb4d00d-0aed-4138-9e0f-1e60d8be040d.png)
Then after refresh:
![image](https://user-images.githubusercontent.com/54227730/151636173-aaf8d7df-ee39-44a9-8a22-8bfd834a6834.png)

Also...
Getting the same on the `contributing/translation-program` pages, Status `500` but then the message shows 
```json
{"msg":"Request failed with status code 404"}
```
And on the `about` pages, status `500` and...
```json
{"msg": "Request failed with status code 401"}
```

2022-01-31 22:04 UTC, pettinarip commented
Hey sorry about that @samajammin and @wackerow. I forgot to add some env vars in my netlify account. Now everything should be working.

> Thought I'm not seeing the API requests in browser network tab

@samajammin you might need to test what Paul said. I see them in my browser 🤔

2022-02-02 01:43 UTC, samajammin requested changes
Looks close!

Everything I tested on https://pettinarip-eth-org.netlify.app/ appears to be working 👍 

The roadmap endpoint on https://ethereumorgwebsitedev01-pettinaripethereumorgwebsitefu.gtsb.io/en/about isn't working for me:
![Image 2022-02-01 at 5 40 23 PM](https://user-images.githubusercontent.com/8097623/152080319-ca9dd204-9a43-4547-a573-fb210bbb5e95.jpg)

Any idea why the 500 error? This response from the endpoint is:
```
{"msg":"Request failed with status code 401"}
```

2022-02-02 01:45 UTC, samajammin commented
@pettinarip the translations endpoint on https://ethereumorgwebsitedev01-pettinaripethereumorgwebsitefu.gtsb.io/en/contributing/translation-program/ is also still failing for me:
![Image 2022-02-01 at 5 44 28 PM](https://user-images.githubusercontent.com/8097623/152080520-1c37f42f-fa58-43f7-83bb-247a07515a12.jpg)

The response from the endpoint is:
```
{"msg":"Request failed with status code 404"}
```

2022-02-02 14:33 UTC, pettinarip commented
@samajammin yes, probably this is a bit tricky to test because we are using just 1 Gatsby Cloud site to test 2 different envs.

So, right now the GC site (`pettinarip-ethereum-org-website-dev`) is setup to be used in **Netlify context**.

If you want to test the preview deploys (**GC context**), you need to update the `GATSBY_FUNCTIONS_PATH` to be `/api`.

Let me know if this doesn't make sense to you and we can discuss it on a call.

2022-02-02 15:21 UTC, samajammin commented
Makes sense, so can't we set up this PR preview deploy to be the GC preview test (ie the GC dev project)? I suppose that was my assumption.

2022-02-23 15:41 UTC, samajammin commented
We're still waiting on Gatsby Cloud support for resolution here, correct @pettinarip? If so, could you please update this PR to a draft?

2022-02-28 17:43 UTC, samajammin commented
Marking as blocked - still waiting on a response from Gatsby Cloud.

2022-03-07 23:14 UTC, pettinarip commented
PR unblocked. Functions working in both envs now.

- Preview deploy: https://ethereumorgwebsitedev01-pettinaripethereumorgwebsitefu.gtsb.io/en/
- Netlify: https://pettinarip-eth-org.netlify.app/en/

2022-03-08 17:41 UTC, samajammin commented
@pettinarip all functions are giving me a 500 on https://pettinarip-eth-org.netlify.app/en/ - they're working for you?

2022-03-08 17:48 UTC, samajammin approved these changes
Working now!

2022-03-08 17:48 UTC, merged