Indonesian: Use Ethereum
ethereum/ethereum-org-website pull request #4962
Opened 2022-01-04 15:51 UTC by wackerow

## Description
Updates Indonesian (id) "Use Ethereum" content with latest from Crowdin

2022-01-04 22:38 UTC, corwintines reviewed
Just need to remove the markdown for the outdatedMarkdown files. Will push a commit up for that

2022-01-04 22:38 UTC, corwintines approved these changes

2022-01-05 13:46 UTC, minimalsm requested changes

2022-01-05 13:46 UTC, minimalsm commented on src/intl/id/page-eth2-index.json
> +  "eth2-client-trinity-logo-alt": "Logo Trinity",
```suggestion
```

2022-01-05 13:46 UTC, merged