Add section about office hours to TP page
ethereum/ethereum-org-website pull request #4998
Opened 2022-01-06 16:17 UTC by lukassim

## Description

Add a section and some details about office hours for translators to the translation program page.

2022-01-06 23:27 UTC, wackerow approved these changes

2022-01-07 14:01 UTC, minimalsm requested changes

2022-01-07 14:01 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +We will be holding office hours for translators on the second Wednesday of every month. These will be held in the #office-hours voice channel on our Discord, where you can also find the exact times a
```suggestion
We have office hours for translators on the second Wednesday of every month. These are held in the #office-hours voice channel on the [ethereum.org Discord](https://discord.gg/geKhWjtF), where you can also find the exact times and additional details.
```

2022-01-07 14:01 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +The purpose of the office hours is to allow our translators to ask questions about the translation process, provide feedback on the program, share their ideas, or just have a chat with us.
```suggestion
The purpose of office hours is to allow our translators to ask questions about the translation process, provide feedback on the program, share their ideas, or just have a chat with us.
```

2022-01-07 14:01 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +Participants can also learn more about the translation program, and get some information on how to become an ethereum.org translator.
```suggestion
Participants can also learn more about the translation program and get some information on becoming an ethereum.org translator.
```

2022-01-07 14:01 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +Finally, we want to use these calls to communicate recent developments in connection with the translation program, and share key tips and instructions with our contributors.
```suggestion
Finally, we want to use these calls to communicate recent developments with the translation program and share key tips and instructions with our contributors.
```

2022-01-07 14:01 UTC, minimalsm commented on src/content/contributing/translation-program/index.md
> +If you are an ethereum.org translator, or would like to become one, feel free to join us during one of these sessions.
```suggestion
If you are an ethereum.org translator or would like to become one, feel free to join us during one of these sessions.
```

2022-01-07 14:02 UTC, minimalsm commented
🚀🚀🚀

2022-01-07 14:02 UTC, merged