Fix overflow of text on /get-eth/ header
ethereum/ethereum-org-website pull request #5027
Opened 2022-01-08 11:54 UTC by minimalsm

## Description

Similar to #5011, fixes overflowing text on language with longer sentences.

- Added a max-width of 45 characters to each Subtitle
- Use the same colour on both subtitles (amused this was a mistake? can revert otherwise)
- Use rem over px (a11y)
- Small refactor to remove redundancy

## Related Issue
#5010

2022-01-09 04:47 UTC, corwintines approved these changes
LGTM 🚀

2022-01-09 16:56 UTC, wackerow requested changes
Just made a comment to double check the selector used to add the margin to the second subtitle, otherwise looks good 👍🏻

2022-01-09 16:56 UTC, wackerow commented on src/pages/get-eth.js
> +  }
Do we want this on the "second subtitle" (`&:nth-of-type(2)`), or do we want this on the _last_ subtitle (`&:last-of-type`)? Not sure we want to use `&:nth-last-of-type(2)`..

If we just want the margin to be on the last item:
```suggestion
  /* Add margin-bottom to the second subtitle */
  &:last-of-type {
    margin-bottom: 2rem;
  }
```

2022-01-10 17:06 UTC, minimalsm commented
The `&:last-of-type` selector selects the last HTML element (div), not the styled-component (Subtitle).

Thinking about that, this solution is tightly coupled to the order of components here. I've pushed a small refactor where we can use `mb` as a prop. If we don't want to do this, we should probably just create `SubtitleTwo` again.

2022-01-26 21:04 UTC, wackerow reviewed
lgtm =)

2022-01-26 21:04 UTC, merged