Adding Web3 University to developer bootcamps
ethereum/ethereum-org-website pull request #5031
Opened 2022-01-08 19:40 UTC by btandowsky

Adding Web3 University to the developer bootcamp page. I did this by 

1. Adding Web3 University to learning-tools.js 
2. Uploading a Web3 university image
3. Adding a description. 

Please let me know if there are any issues to the code! I am excited to contribute!

2022-01-09 17:01 UTC, wackerow commented on src/pages/developers/learning-tools.js
> +      ...learningToolImage
```suggestion
    }
    web3university: file(relativePath: { eq: "dev-tools/web3university.png" }) {
      ...learningToolImage
```

2022-01-09 17:01 UTC, wackerow approved these changes
@btandowsky Thanks for posting =) Looks good to me!

2022-01-10 23:37 UTC, btandowsky commented
> Hey @btandowsky thanks for the suggestion here 🙏
> 
> IMO this doesn't really fit into the developer bootcamp bucket. This seems like a curation/collection of valuable resources but I wouldn't say it has the kind of structured learning path we'd want to list this as a bootcamp. Definitely agree we should link out to this valuable resource _somewhere_ just not entirely sure where the best fit is. Our [/learn/](https://ethereum.org/en/learn/) page is an obvious one but I think we can do better. Any thoughts?


Thanks for getting back to me back to me @minimalsm . I am open to placing it in learn community guide and resources page under "In addition to the information on this page, there are many community-built resources worth exploring:" I would also like to add our awesome [discord](https://discord.gg/ZH5aXDgWEU) to the Online communities tab under chat rooms? What do you think?

2022-01-11 15:37 UTC, minimalsm commented
Yeah @btandowsky I think adding it as an online chatroom makes 💯. Feel free to add these changes to this PR, or open a new PR if you feel that is easier.

2022-01-11 19:09 UTC, btandowsky commented
> Yeah @btandowsky I think adding it as an online chatroom makes sense 💯. Feel free to add these changes to this PR, or open a new PR if you feel that is easier.

@minimalsm just updated, please let me know if this works! Summary of what I added.

1. Added Web3 University discord to online communities and Web3 University website building dAPPs sections under community
2. Added Alchemy discord to tooling.

2022-01-12 19:39 UTC, btandowsky commented
Hi team I wanted to check in and see if there were any questions with the updates? Please let me know!

2022-01-13 14:43 UTC, minimalsm requested changes
Hey @btandowsky, thanks for this 🙏

Just a few small changes and we can get this merged. Could you also remove the web3university.png image you added? As this is not a learning-tool the logo isn't required.

2022-01-13 14:43 UTC, minimalsm commented on src/intl/en/page-developers-learning-tools.json
> +  "page-learning-tools-web3university-logo-alt": "Web3 University logo"
```suggestion
```

2022-01-13 14:43 UTC, minimalsm commented on src/content/learn/index.md
> +- [Web3 University](https://www.web3.university) _A community driven online resource foused on teaching and learning Web3 development_
- Few typos/conventions
- Removed 'teaching and learning' as the sentence target was changing mid-sentence

```suggestion
- [Web3 University](https://www.web3.university) _A community-driven online resource focused on web3 development_
```

2022-01-13 14:43 UTC, minimalsm commented on src/content/community/online/index.md
> +<SocialListItem socialIcon="discord"><Link to="https://discord.gg/ZH5aXDgWEU">web3.university website team</Link> <i>- community focused on learning Web3 development </i></SocialListItem>
```suggestion
<SocialListItem socialIcon="discord"><Link to="https://discord.gg/ZH5aXDgWEU">Web3 University</Link> <i>- community focused on learning web3 development </i></SocialListItem>
```

2022-01-13 17:10 UTC, btandowsky commented
@minimalsm Thanks for all of the suggestions! Made all the commit suggestions and LFTM now! Please let me know if anything else is needed before merge!

2022-01-18 09:34 UTC, minimalsm commented on src/intl/en/page-developers-learning-tools.json
> +  "page-learning-tools-nftschool-logo-alt": "NFT school Logo",
```suggestion
```

2022-01-18 09:34 UTC, minimalsm commented
Thanks @btandowsky. Could you also remove the web3university.png image you added please 🙏?

2022-01-18 23:02 UTC, btandowsky commented
@minimalsm Thanks for all of the tips, just removed the final image by committing your suggestion. Are we good to merge?

2022-01-22 18:17 UTC, btandowsky commented
@minimalsm Just wanted to check and see if there were any blockers on my end before merge?

2022-01-24 18:56 UTC, minimalsm commented on src/intl/en/page-developers-learning-tools.json
>    "page-learning-tools-nftschool-description": "Explore what's going on with non-fungible tokens, or NFTs from the technical side.",
```suggestion
  "page-learning-tools-nftschool-description": "Explore what's going on with non-fungible tokens, or NFTs from the technical side.",
  "page-learning-tools-nftschool-logo-alt": "NFT school Logo"
```

2022-01-24 18:57 UTC, merged