added base fee
ethereum/ethereum-org-website pull request #5137
Opened 2022-01-18 09:04 UTC by zainabb12345

- Added "Base fee" in the glossary section

## Description

- Provided term's definition and link for better-detailed understanding

2022-01-18 14:42 UTC, minimalsm requested changes
Hey @zainabb12345, thanks for the PR 😀❤️

Looking good! I've just suggested a few changes based on current site conventions. If you could approve these I'll get this merged or you can let me know if you disagree on any.

2022-01-18 14:42 UTC, minimalsm commented on src/content/glossary/index.md
> +Every Block has a reserve price called the "base fee". It is the minimum fee a user pays to include a transaction in the next block. The base fee helps in making the transaction more predictable.
- Block shouldn't be capitalised mid-sentence
- We should link to block and gas definitions in the glossary
- I think we should drop the last sentence, we should only define base fee in the glossary, not explain why it was introduced.

```suggestion
Every [block](#block) has a reserve price known as the 'base fee'. It is the minimum [gas](#gas) fee a user must pay to include a transaction in the next block.
```

2022-01-18 14:42 UTC, minimalsm commented on src/content/glossary/index.md
> +  Gas & Fees
```suggestion
  Gas and fees
```

2022-01-18 15:38 UTC, zainabb12345 commented
> Hey @zainabb12345, thanks for the PR grinningheart
> 
> Looking good! I've just suggested a few changes based on current site conventions. If you could approve these I'll get this merged or you can let me know if you disagree on any.

Hey @minimalsm 
Thanks for the suggestions. I've accepted the suggestions, hope I did things right? 
Looking forward to do more contributions :grinning:

2022-01-19 12:27 UTC, minimalsm approved these changes

2022-01-19 12:28 UTC, minimalsm commented
Awesome, thanks @zainabb12345. Merging now 🚀

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳! We're currently working on our 2022 POAPs and they'll be released soon.

2022-01-19 12:28 UTC, minimalsm commented
@all-contributors please add @zainabb12345 for docs, ideas

2022-01-19 12:29 UTC, merged