Fix typos and mistranslations of Ethereum
ethereum/ethereum-org-website pull request #5155
Opened 2022-01-19 13:56 UTC by lukassim

## Description

Fix common typo in the spelling of Ethereum, specifically 'Etherum'.
This is the most common typo in the spelling of Ethereum, and has been reported as incorrect by other translators in these languages multiple times.

2022-01-19 15:43 UTC, wackerow requested changes
Looks good @lukassim, just noticed one spot where there were stashed changed that needed to be resolved. Left a code suggestion to correct it, and should be good other than that

2022-01-19 15:43 UTC, wackerow commented on src/content/translations/zh/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
> +>>>>>>> Stashed changes
```suggestion
2.  [创建 Metamask 帐户](https://metamask.io/)（或获取一个 Ethereum 地址）
3.  [按照这些步骤安装 NodeJs 和 NPM](https://medium.com/guides/alchemy-for-macs)
```

2022-01-19 15:47 UTC, lukassim commented
Great, thanks @wackerow!

2022-01-20 10:06 UTC, minimalsm approved these changes
LGTM! Let's hold off merging until the Eth2 rebrand is in as it'll introduce more conflicts.

2022-01-25 12:51 UTC, minimalsm commented
Merge conflict hell on this 😢

Would it maybe be quicker to throw up a fresh PR for this? @wackerow @corwintines

2022-01-28 23:15 UTC, wackerow approved these changes
Thanks @lukassim !

2022-01-28 23:23 UTC, merged