Add new upcoming events [Fixes #5221]
ethereum/ethereum-org-website pull request #5245
Opened 2022-01-27 12:34 UTC by vluna

## Description
- Add events from [the provided spreadsheet](https://docs.google.com/spreadsheets/d/1NEu_FCc1hnGAuRgPmbXXpf0h2lCrCOlMKbbFEqgkVDQ/htmlview)

## Related Issue
#5221

2022-01-27 14:35 UTC, minimalsm requested changes
Nice! Thanks @vluna.

A few thoughts:

If we don't have a description, we should write a simple one. 
e.g. ETHWarsaw is a hackathon in Warsaw, Poland, expected in Q4 2022.

I don't think we should link out to dead meetup.com meetings. Do they have an alternative? E.g. Twitter or if they are part of ETHGlobal we could just link there?

If something is TBD, we don't currently have a good way to show this and spanning the event across the whole quarter is confusing to users.
- We could remove ETHWarsaw, ETHKyiv, Liscon, EthLisbon, ETHBogota, DevCon until they get official dates IMO.
- We could refactor the component to better support this.

_Less of a priority but this list is super long now. I think we should paginate or add 'load more' functionality to reduce cognitive load here._

2022-01-28 00:52 UTC, vluna commented on src/data/community-events.json
> +    "title": "ETH SF",
Yup, it seems like it.

2022-01-28 04:05 UTC, vluna commented
@minimalsm Applied your suggestions. Let me know what you think.

2022-01-29 00:00 UTC, wackerow approved these changes
Aw yeah, great to see all these events getting listed. Thanks @vluna!

@minimalsm I think using `isSecondary` on that button would be more fitting, but we can debate that separately... gonna bring this in

2022-01-29 00:58 UTC, wackerow commented
Build is showing as failed because it ran out of memory:
```
Your Gatsby build's memory consumption exceeded the limits allowed in your plan. For more details, see https://gatsby.dev/memory.
```

I cleared cache and rebuilt it and it worked fine, just doesn't seem to be updating here.

2022-01-29 00:58 UTC, merged