feat: add chat links (gitter/matrix) for ethereum-solidity
ethereum/ethereum-org-website pull request #5322
Opened 2022-02-03 13:32 UTC by ErikBjare

Adds chat links for ethereum-solidity.

## Description

Not sure if `gitter` and `matrix` are valid `socialIcon` options. Should perhaps be changed to `webpage`.

## Related Issue

Fixes #4753

2022-02-03 13:33 UTC, ErikBjare commented on src/content/community/online/index.md
> +<SocialListItem socialIcon="gitter"><Link to="gitter.im/ethereum/solidity">Solidity Gitter</Link> <i>- chat for solidity development (Gitter)</i></SocialListItem>
```suggestion
<SocialListItem socialIcon="website"><Link to="gitter.im/ethereum/solidity">Solidity Gitter</Link> <i>- chat for solidity development (Gitter)</i></SocialListItem>
```

2022-02-03 13:33 UTC, ErikBjare commented on src/content/community/online/index.md
> +<SocialListItem socialIcon="matrix"><Link to="matrix.to/#/#ethereum_solidity:gitter.im">Solidity Gitter</Link> <i>- chat for solidity development (Matrix)</i></SocialListItem>
```suggestion
<SocialListItem socialIcon="website"><Link to="matrix.to/#/#ethereum_solidity:gitter.im">Solidity Gitter</Link> <i>- chat for solidity development (Matrix)</i></SocialListItem>
```

2022-02-03 13:33 UTC, ErikBjare commented on src/content/community/online/index.md
> +
```suggestion
```

2022-02-04 10:33 UTC, minimalsm requested changes
Thanks for the PR @ErikBjare 

Made a tiny change to fix the social icon :-) just waiting on this building and I think we're good to merge.

2022-02-04 10:33 UTC, minimalsm commented on src/content/community/online/index.md
> +<SocialListItem socialIcon="website"><Link to="gitter.im/ethereum/solidity">Solidity Gitter</Link> <i>- chat for solidity development (Gitter)</i></SocialListItem>
I think you're trying to add the globe 🌐? We use `webpage` for the socialIcon id.

```suggestion
<SocialListItem socialIcon="webpage"><Link to="gitter.im/ethereum/solidity">Solidity Gitter</Link> <i>- chat for solidity development (Gitter)</i></SocialListItem>
```

2022-02-04 10:33 UTC, minimalsm commented on src/content/community/online/index.md
> +<SocialListItem socialIcon="website"><Link to="matrix.to/#/#ethereum_solidity:gitter.im">Solidity Matrix</Link> <i>- chat for solidity development (Matrix)</i></SocialListItem>
```suggestion
<SocialListItem socialIcon="webpage"><Link to="matrix.to/#/#ethereum_solidity:gitter.im">Solidity Matrix</Link> <i>- chat for solidity development (Matrix)</i></SocialListItem>
```

2022-02-04 10:33 UTC, minimalsm approved these changes

2022-02-04 12:19 UTC, minimalsm commented
Thanks for the PR @ErikBjare 🤘

Be sure to [[join the discord](https://discord.gg/CetY6Y4)](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [[claim your POAP](https://ethereum.org/en/contributing/#poap)](https://ethereum.org/en/contributing/#poap) also 🥳! We're currently working on our 2022 POAPs and they'll be released soon.

2022-02-04 12:20 UTC, minimalsm commented
@all-contributors please add @ErikBjare for docs, code

2022-02-04 12:20 UTC, merged