add warnings for env file instructions
ethereum/ethereum-org-website pull request #5363
Opened 2022-02-08 13:47 UTC by Dentrax

Signed-off-by: Furkan <furkan.turkal@trendyol.com>

## Description

This PR adds an important security warning message for the `.env` file creation steps. Accidentally committing `.env` file  to a git repo is a mistake. Adding some warning messages, so devs don't forget.

## Related Issue

2022-02-10 13:52 UTC, minimalsm requested changes
Hey @Dentrax, I think this is an awesome idea. I had similar concerns when reviewing a tutorial a few days ago.

Made a suggestion to use slightly stronger language (are exposing secrets vs might be exposing secrets) and to let users know to use a gitignore file.

2022-02-10 13:52 UTC, minimalsm commented on src/content/developers/tutorials/hello-world-smart-contract/index.md
> +  Don't commit `.env`: Please make sure to never share or expose your `.env` file with anyone as you can compromise your secrets in doing so. If you are using version control, ensure that you will ne
I'd use stronger language here. 

Also backticks won't work inside HTML. Added <pre> tags instead.

```suggestion
Don't commit <pre>.env</pre>! Please make sure never to share or expose your <pre>.env</pre> file with anyone, as you are compromising your secrets in doing so. If you are using version control, add your <pre>.env</pre> to a <a href="https://git-scm.com/docs/gitignore">gitignore</a> file.
```

2022-02-10 13:52 UTC, minimalsm commented on src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
> +  Don't commit `.env`: Please make sure to never share or expose your `.env` file with anyone as you can compromise your secrets in doing so. If you are using version control, ensure that you will ne
```suggestion
Don't commit <pre>.env</pre>! Please make sure never to share or expose your <pre>.env</pre> file with anyone, as you are compromising your secrets in doing so. If you are using version control, add your <pre>.env</pre> to a <a href="https://git-scm.com/docs/gitignore">gitignore</a> file.
```

2022-02-10 13:52 UTC, minimalsm commented on src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
> +  Don't commit `.env`: Please make sure to never share or expose your `.env` file with anyone as you can compromise your secrets in doing so. If you are using version control, ensure that you will ne
```suggestion
Don't commit <pre>.env</pre>! Please make sure never to share or expose your <pre>.env</pre> file with anyone, as you are compromising your secrets in doing so. If you are using version control, add your <pre>.env</pre> to a <a href="https://git-scm.com/docs/gitignore">gitignore</a> file.
```

2022-02-10 13:59 UTC, Dentrax commented
Thank you for reviews, @minimalsm! 🙏 

Is there somewhere that I forgot to add this warning? Should I squash my commits?

2022-02-22 11:45 UTC, minimalsm requested changes
TIL `<pre>` tags split across multiple lines 😅

<img width="970" alt="Screenshot 2022-02-22 at 11 45 26" src="https://user-images.githubusercontent.com/62268199/155125936-fdcf4e48-0c9a-46f1-9a96-3e581733d69e.png">

2022-02-22 11:45 UTC, minimalsm commented on src/content/developers/tutorials/hello-world-smart-contract/index.md
> +Don't commit <pre>.env</pre>! Please make sure never to share or expose your <pre>.env</pre> file with anyone, as you are compromising your secrets in doing so. If you are using version control, add
```suggestion
Don't commit <code>.env</code>! Please make sure never to share or expose your <code>.env</code> file with anyone, as you are compromising your secrets in doing so. If you are using version control, add your <code>.env</code> to a <a href="https://git-scm.com/docs/gitignore">gitignore</a> file.
```

2022-02-22 11:45 UTC, minimalsm commented on src/content/developers/tutorials/how-to-write-and-deploy-an-nft/index.md
> +Don't commit <pre>.env</pre>! Please make sure never to share or expose your <pre>.env</pre> file with anyone, as you are compromising your secrets in doing so. If you are using version control, add
```suggestion
Don't commit <code>.env</code>! Please make sure never to share or expose your <code>.env</code> file with anyone, as you are compromising your secrets in doing so. If you are using version control, add your <code>.env</code> to a <a href="https://git-scm.com/docs/gitignore">gitignore</a> file.
```

2022-02-22 11:45 UTC, minimalsm commented on src/content/developers/tutorials/sending-transactions-using-web3-and-alchemy/index.md
> +Don't commit <pre>.env</pre>! Please make sure never to share or expose your <pre>.env</pre> file with anyone, as you are compromising your secrets in doing so. If you are using version control, add
```suggestion
Don't commit <code>.env</code>! Please make sure never to share or expose your <code>.env</code> file with anyone, as you are compromising your secrets in doing so. If you are using version control, add your <code>.env</code> to a <a href="https://git-scm.com/docs/gitignore">gitignore</a> file.
```

2022-02-22 11:46 UTC, minimalsm commented
> Is there somewhere that I forgot to add this warning? Should I squash my commits?

@Dentrax nope, this is fine as is, thanks. Just waiting on this building to make sure I fixed the bug I introduced and I'll merge this 🚀🚀🚀🚀

2022-02-22 12:15 UTC, minimalsm commented
Fixed, thanks again @Dentrax 

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And remember to [claim your POAP](https://ethereum.org/en/contributing/#poap) also 🥳! We're currently working on our 2022 POAPs and they'll be released soon.

2022-02-22 12:15 UTC, minimalsm approved these changes

2022-02-22 12:16 UTC, merged