Add Discord redirect
ethereum/ethereum-org-website pull request #5650
Opened 2022-03-11 11:14 UTC by minimalsm

## Description

- Redirects from https://ethereum.org/discord to discord invite link.

## Related Issue
None

2022-03-14 20:54 UTC, wackerow requested changes
Awesome!
To your question about providing one for the language paths, I think we should, since otherwise it's easy for someone to just add `discord` to `https://ethereum.org/en/` and they will hit a 404.

Otherwise it worked great, we should consider other shortcut URLs that could be helpful for people.

2022-03-14 20:54 UTC, wackerow commented on redirects.json
> +  },
```suggestion
  {
    "fromPath": "/discord",
    "toPath": "https://discord.gg/rZz26QWfCg"
  },
  {
    "fromPath": "/*/discord",
    "toPath": "https://discord.gg/rZz26QWfCg"
  },
```

2022-03-15 11:59 UTC, minimalsm commented
@wackerow ethereum.org/crowdin might be useful?

also, can't merge. can you slap an approval on this @wackerow ❤️

2022-03-15 15:43 UTC, wackerow approved these changes

2022-03-15 15:43 UTC, merged