improved breadcrumbs
ethereum/ethereum-org-website pull request #5881
Opened 2022-04-01 19:59 UTC by kum9748ar

## Description
Improved breadcrumbs

## Related Issue
[Breadcrumbs a11y improvements](https://github.com/ethereum/ethereum-org-website/issues/5791#)

2022-04-04 13:09 UTC, minimalsm requested changes
Thanks for the PR @kum9748ar 💪

Looks like the styling has changed (see screenshot below). Could you amend this so that the style is the same as we currently have?

**Changes proposed:**
<img width="1104" alt="Screenshot 2022-04-04 at 14 05 40" src="https://user-images.githubusercontent.com/62268199/161550414-242791ce-cd8f-48d3-a2d4-1dcb57977ed5.png">

**Current styling:**
<img width="1188" alt="Screenshot 2022-04-04 at 14 05 44" src="https://user-images.githubusercontent.com/62268199/161550421-519566a8-6be3-4041-ad39-7f5092ce572d.png">

2022-04-04 16:32 UTC, pettinarip requested changes
Hi @kum9748ar, left a couple of things there to fix. Check out the screenshot shared by @minimalsm and make sure to keep the current styling.

2022-04-04 16:32 UTC, pettinarip commented on src/components/Breadcrumbs.js
> +          <ol>
`ol` should not be here. It should be wrapping all the crumbs.

2022-04-04 17:54 UTC, kum9748ar commented
@pettinarip @minimalsm thanks for your feedback I will fix them

2022-04-11 16:13 UTC, kum9748ar commented
Should I close this pull request ?

2022-04-11 16:14 UTC, pettinarip approved these changes
Looks good! 💪🏼 ty @kum9748ar

2022-04-11 16:15 UTC, minimalsm commented
Oops. Accidently didn't add the styling to the slash, which is giving us a different line height than production.

2022-04-11 16:20 UTC, kum9748ar commented
@minimalsm thanks for fixing and helping me out

2022-04-11 17:12 UTC, minimalsm approved these changes
All fixed!

[![Image from Gyazo](https://i.gyazo.com/f2966aadc9e382ff0fa5288f6686de55.gif)](https://gyazo.com/f2966aadc9e382ff0fa5288f6686de55)

Merging, thanks @kum9748ar ❤️

2022-04-11 17:12 UTC, merged