migrate Ethereum history page from ethdocs.org
ethereum/ethereum-org-website pull request #5935
Opened 2022-04-07 14:51 UTC by jmcook1186

## Description

Ethereum history from inception to first production network (homestead) is added to the history page on ethereum.org. The text is migrated from ethdocs.org with only minor typographic changes. Removed/updated dead links.

Also embedded image of Vitalik's announcement of Ethereum genesis on bitcointalk.org.

## Related Issue

#5731

2022-04-11 12:40 UTC, minimalsm commented
Hey @jmcook1186,

I support adding these details, but I think we have a separation of concerns problem here. I believe the best approach is to separate these into two pages:

1. the history of Ethereum (i.e. a story-driven narrative)
2. the network upgrades history (i.e. the current history page)

There will obviously be some crossover with this approach, but I think this is best when we consider the discussion we had around fleshing out this story-driven narrative and translating it to provide a free, approachable resource for all to learn Ethereum's story so far.

What do you think?

2022-05-05 20:24 UTC, wackerow requested changes
@jmcook1186 Loving these PR's of yours, great work! I like the new breakdown where the story is separated a bit from the strict upgrade timeline. 

Need to get an easier link to jump to the `/network-upgrades/` subpage. Otherwise left a handful of small semantic adjustments, and suggestions on removing some dead links from the design rationale page.
After that I think this is good to go =)

2022-05-05 20:24 UTC, wackerow commented on src/content/history/design-rationale/index.md
> +RLP ("recursive length prefix") encoding is the main serialization format used in Ethereum, and is used everywhere - for blocks, transactions, account state data and wire protocol messages. RLP is fo
Similar to above, we may want to pull this until we have the `data-structures` PR merged (or at least make sure we're set on the path name first, then aim to merge these together)
```suggestion
RLP ("recursive length prefix") encoding is the main serialization format used in Ethereum, and is used everywhere - for blocks, transactions, account state data and wire protocol messages.
```

2022-05-05 20:24 UTC, wackerow commented on src/content/history/design-rationale/index.md
> +There is also a bloom in the block header, which is the OR of all of the blooms for the transactions in the block. The purpose of this construction is to make the Ethereum protocol light-client frien
Broken link from migration... link back to ethdocs.org? Remove link? Not sure we have a great alternative to link to within the repo on light clients, so may err on the side of just removing this. 
```suggestion
There is also a bloom in the block header, which is the OR of all of the blooms for the transactions in the block. The purpose of this construction is to make the Ethereum protocol light-client friendly in as many ways as possible.
```

2022-05-05 20:24 UTC, wackerow commented on src/content/history/design-rationale/index.md
> +- **12 second block time**: 12 seconds was chosen as a time that is as fast as possible, but is at the same time substantially longer than network latency. A [2013 paper](http://www.tik.ee.ethz.ch/fi
Dead link
```suggestion
- **12 second block time**: 12 seconds was chosen as a time that is as fast as possible, but is at the same time substantially longer than network latency. A 2013 paper by Decker and Wattenhofer in Zurich measures Bitcoin network latency, and determines that 12.6 seconds is the time it takes for a new block to propagate to 95% of nodes; however, the paper also points out that the bulk of the propagation time is proportional to block size, and thus in a faster currency we can expect the propagation time to be drastically reduced. The constant portion of the propagation interval is about 2 seconds; however, for safety we assume that blocks take 12 seconds to propagate in our analysis.
```

2022-05-06 12:26 UTC, minimalsm commented on src/content/history/index.md
> +title: Upgrade Timeline
```suggestion
title: Ethereum's upgrade timeline
```

2022-05-06 12:26 UTC, minimalsm commented on src/content/history/index.md
> +# Upgrade Timeline
```suggestion
# Ethereum's upgrade timeline {#upgrade-timeline}
```

2022-05-06 12:30 UTC, minimalsm commented
@jmcook1186 I've moved the network upgrade's timeline back to (/history/) and moved the new page to (/history/story-of-ethereum/) for now. We link out to /history/ a lot across the site which would break those links and we'd also have to change translated versions of ethereum.org to match, as well as update our translation management software mid update, which might confuse our reviewers.

Support the change of structure overall, but let's get the content in first and change the architecture when the timing is more optimal.

2022-05-12 12:04 UTC, minimalsm commented
Closing for now until we get a better sense of what we want to do here and if we want to do it.

2022-05-12 12:04 UTC, closed without merging