Typo Update index.md
ethereum/ethereum-org-website pull request #6346
Opened 2022-05-16 14:57 UTC by graz-network

Typo and negativ form uncomplete
 
-- Typo : "dur" changed in "sur"

-- "Ethereum n'a été conçu pour cela"  changed by : "Ethereum n'a pas été conçu pour cela"

2022-05-16 19:44 UTC, SuperDelphi requested changes
It's almost all good. Since we agreed upon the usage of "gaz" instead of "carburant", we could change the "carburant" occurrence here. (SuperDelphi#2468 on Discord)

2022-05-16 20:31 UTC, minimalsm commented on src/content/translations/fr/developers/docs/storage/index.md
> +Ethereum lui-même peut être utilisé comme un système de stockage décentralisé, c'est d'ailleurs déjà le cas concernant le stockage de code compris dans tous les contrats intelligent. Cependant, lorsq
```suggestion
Ethereum lui-même peut être utilisé comme un système de stockage décentralisé, c'est d'ailleurs déjà le cas concernant le stockage de code compris dans tous les contrats intelligent. Cependant, lorsqu'il s'agit de grandes quantités de données, Ethereum n'a pas été conçu pour cela. La chaîne ne cesse de croître, mais au moment d'écrire ces lignes, la chaîne Ethereum est d'environ 500 Go à 1 To ([selon le client](https://etherscan.io/chartsync/chaindefault)), et chaque nœud du réseau doit être en mesure de stocker toutes les données. Si la chaîne devait s'étendre à de grandes quantités de données (disons 5 To par exemple), il serait impossible pour tous les nœuds de continuer à fonctionner. En outre, le coût du déploiement d'une telle quantité de données sur le réseau principal serait prohibitif en raison des frais de [gaz](/developers/docs/gas).
```

2022-06-06 12:32 UTC, minimalsm approved these changes

2022-06-06 12:32 UTC, minimalsm commented
Thanks @graz-network 

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

2022-06-06 12:33 UTC, minimalsm commented
@all-contributors please add @graz-network for docs, translation

2022-06-06 12:33 UTC, merged