Layer 2 translation
ethereum/ethereum-org-website pull request #6440
Opened 2022-05-24 00:58 UTC by corwintines

## Description
- Set layer 2 page up for translation

2022-05-26 17:57 UTC, wackerow commented on src/pages/layer-2.js
> +        title: translateMessageId("layer-2-tools-l2beat-title", intl),
Typically we do not set product names up for translation. Some of these names, like "L2 Fees" I suppose are debatable, but many of these I would assume would remain untranslated, such as L2BEAT, Zepper, Zerion, etc.
<img width="331" alt="image" src="https://user-images.githubusercontent.com/54227730/170547401-1de1709e-452c-441e-8b9e-10135396b9bf.png">
Would suggest we revert these six strings.

2022-05-30 14:47 UTC, minimalsm requested changes
Nice 😎💪

Left some comments on some small things that we missed adding to translations.

2022-05-30 14:47 UTC, minimalsm commented on src/pages/layer-2.js
>          <ul>
We should translate the further reading section

<img width="1054" alt="Screenshot 2022-05-30 at 15 39 42" src="https://user-images.githubusercontent.com/62268199/171015581-4550f0d4-deb4-4d66-b9ae-a81a44a1f7ba.png">

2022-05-30 14:47 UTC, minimalsm commented on src/pages/layer-2.js
>              <ProductList
We should queue up this JSON file for translation too.

<img width="1334" alt="Screenshot 2022-05-30 at 15 39 35" src="https://user-images.githubusercontent.com/62268199/171015500-1f75f5c6-3eb7-4f48-b4fd-6ef887211517.png">

2022-05-30 14:47 UTC, minimalsm commented on src/pages/layer-2.js
>        },
Oops missed this one 

<img width="324" alt="Screenshot 2022-05-30 at 15 39 54" src="https://user-images.githubusercontent.com/62268199/171015942-9784362f-f4be-48d0-834b-772c171c3fd8.png">

2022-05-30 14:47 UTC, minimalsm commented on src/intl/en/page-layer-2.json
> +  "layer-2-hero-alt-text": "Layer 2 diagram",
```suggestion
  "layer-2-hero-alt-text": "Illustration of transactions being rolled up on Layer 2 and posted to Ethereum Mainnet",
```

2022-06-02 13:51 UTC, minimalsm approved these changes

2022-06-02 13:51 UTC, merged