added patrick mega course & a few others
ethereum/ethereum-org-website pull request #6482
Opened 2022-05-27 12:06 UTC by PatrickAlphaC

Added a few more courses, including the mega 32 hour long course in javascript!

## Related Issue

https://github.com/ethereum/ethereum-org-website/issues/6481

2022-05-30 11:18 UTC, minimalsm requested changes
Thanks for the PR @PatrickAlphaC, just a few comments to remove some deadspace and remove some extra newly added tags (we're overflowing in tags and need to explore a new solution 😅)

2022-05-30 11:18 UTC, minimalsm commented on src/data/externalTutorials.json
> +    "title": "How to Connect your Smart Contracts to Metamask | Full Stack Web3",
```suggestion
    "title": "How to Connect your Smart Contracts to Metamask",
```

2022-05-30 11:18 UTC, minimalsm commented on src/data/externalTutorials.json
> +    "description": "Using Compound and Openzeppelin as a basis, we build a 100% on-chain DAO using an ERC20 governance token for votes.  ",
```suggestion
    "description": "Using Compound and Openzeppelin as a basis, we build a 100% on-chain DAO using an ERC20 governance token for votes.",
```

2022-05-30 11:18 UTC, minimalsm commented on src/data/externalTutorials.json
> +    "description": "We build a minimal foundry project using a staking application. Showing you how to work with foundry.  ",
```suggestion
    "description": "We build a minimal Foundry project using a staking application to show you how to work with Foundry.",
```

2022-05-30 11:18 UTC, minimalsm commented on src/data/externalTutorials.json
> +    "description": "We learn exactly how web3 / blockchain / smart contract applications work in the front end using HTML and Javascript. We then go through 6 different ways you can connect your Meta
```suggestion
    "description": "We learn exactly how web3 / blockchain / smart contract applications work in the front end using HTML and Javascript. We then go through 6 different ways you can connect your Metamask, Phantom, or other blockchain wallet address to your front end. We’ll look at popular Nextjs / React packages to make your development lifecycle 100 times easier.",
```

2022-05-30 11:19 UTC, minimalsm approved these changes

2022-05-30 11:19 UTC, merged

2022-05-31 21:53 UTC, PatrickAlphaC commented
Love it!

Thanks for your work here!