Feat/convert ts d files
ethereum/ethereum-org-website pull request #6548
Opened 2022-06-02 22:30 UTC by vdusart

Moving to TS

## Related Issue
Conversion to TS according to #6392

2022-06-03 17:07 UTC, pettinarip requested changes
Hey @vdusart Thanks for the work here. I left a couple of comments to improve the definitions and others to follow conventions. Gj 💪🏼

2022-06-03 17:07 UTC, pettinarip commented on overrides.d.ts
> +}
I think this is fine but I don't love it. I encourage you to define it a bit better (not using `any` and define it for each yaml file).

```ts
declare module "*developer-docs-links.yaml" {
  export interface DeveloperDocsLink {
    id: string
    to: string
    path: string
    description: string
    items: Array<DeveloperDocsLink>
  }
  const content: Array<DeveloperDocsLink>
  export default content
}

// then in DocsNav.tsx  you can use it like this
import docLinks, { DeveloperDocsLink } from "../data/developer-docs-links.yaml"
....
const getDocs = (links: Array<DeveloperDocsLink>): void => {
```

2022-06-03 17:07 UTC, pettinarip commented on src/components/DocsNav.tsx
>    const getDocs = (links) => {
(take a look at my other comment about defining the yaml file)

2022-06-03 21:40 UTC, vdusart commented
Ok @pettinarip, I corrected all your comments, thanks for that. I will try to apply all of them for the next ones :wink:

2022-06-07 15:03 UTC, merged

2022-06-07 15:04 UTC, pettinarip commented
@all-contributors please add @vdusart for code