refactor: migrate listed components to typescript
ethereum/ethereum-org-website pull request #6909
Opened 2022-07-04 16:37 UTC by didoshotev

## Description

migrate listed components:
src/components/PageHero.js
src/components/SkipLink.js

In PageHero content prop, I have set it to any, since I don't see any TS interface for this type of data. This can be changed once we have defined interface.

Please let me know, if you want to separate `SkipLinkAnchor` into different file, as there are 2 components in the same file (SkipLink) currently.

## Related Issue

Refs: #6392

2022-07-12 17:03 UTC, pettinarip requested changes
Thanks for the PR @didoshotev! left one comment.

2022-07-12 17:03 UTC, pettinarip commented on src/components/PageHero.tsx
>    const { buttons, title, header, subtitle, image, alt } = content
For now, we could add the content interface in this file with this structure. Could be something like:
```ts
interface IButton {
  path: string
  pathId: string
}

interface IContent {
  buttons?: Array<IButton>
  title: string
  header: string
  subtitle: string
  image: string
  alt: string
}
```

2022-07-16 15:15 UTC, didoshotev commented
@pettinarip I have made the requested changes and pulled the new changes from dev. Let me know if something else needs to be added for this PR.

2022-07-16 18:43 UTC, pettinarip approved these changes
Thanks @didoshotev. I've pushed a few minor things but overall it looks great! thanks for applying the suggestions.

2022-07-16 21:16 UTC, merged