post-merge updates: pow/mining
ethereum/ethereum-org-website pull request #7109
Opened 2022-07-18 10:41 UTC by jmcook1186

## Description
updates `developers/docs/consensus-mechanisms/pow/mining/index.md` for post-merge 

## Related Issue
 #7075

2022-07-25 12:52 UTC, wackerow requested changes
@jmcook1186 Few suggestions, otherwise looks good =)

2022-07-25 12:52 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +   Proof-of-work is no longer Ethereum's consensus mechanism, meaning mining has been switched off. Instead, Ethereum is secured by validators who stake ETH. You can start staking your ETH today. Rea
```suggestion
   Proof-of-work is no longer underlying Ethereum's consensus mechanism, meaning mining has been switched off. Instead, Ethereum is secured by validators who stake ETH. You can start staking your ETH today. Read more on <a href="/upgrades/merge/">The Merge</a>, <a href="/developers/docs/consensus-mechanisms/pos/">proof-of-stake</a> and <a href="/staking/">staking</a>. This page is for historical interest!  
```

2022-07-25 12:52 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +
```suggestion
```

2022-07-25 12:52 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +The word mining originates in the context of the gold analogy for crypto currencies. Gold or precious metals are scarce, so are digital tokens, and the only way to increase the total volume in a proo
```suggestion
The word mining originates in the context of the gold analogy for cryptocurrencies. Gold or precious metals are scarce, so are digital tokens, and the only way to increase the total volume in a proof-of-work system is through mining. In proof-of-work Ethereum, the only mode of issuance was via mining. Unlike gold or precious metals however, Ethereum mining was also the way to secure the network by creating, verifying, publishing and propagating blocks in the blockchain.
```

Just a note here that it's not just miners who secure the network by "verifying" and "propagating" blocks, as all nodes contribute to this.

2022-07-25 12:52 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +Mining is the lifeblood of proof-of-work. Ethereum miners - computers running software - used their time and computation power to process transactions and produce blocks.
```suggestion
Mining is the lifeblood of any proof-of-work blockchain. Ethereum miners - computers running software - used their time and computation power to process transactions and produce blocks prior to the transition to proof-of-stake.
```

2022-07-25 12:52 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +Anyone could mine on the Ethereum network using their computer. However, not everyone could mine ether (ETH) profitably. In most cases, miners had to purchase dedicated computer hardware. The average
Just a suggestion.. "could" sounds more like a theoretical present tense. 
```suggestion
Anyone was previously able to mine on the Ethereum network using their computer. However, not everyone could mine ether (ETH) profitably. In most cases, miners had to purchase dedicated computer hardware, and have access to inexpensive energy sources. The average computer was unlikely to earn enough block rewards to cover the associated costs of mining.
```

2022-07-25 12:52 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +- If you were mining in a pool, mining pools typically charge a flat % fee of each block generated by the pool
```suggestion
- If you were mining in a pool, these pools typically charged a flat % fee of each block generated by the pool
```

2022-07-25 12:52 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +Ethereum Mainnet onyl ever used one mining algorithm - ['Ethash'](/developers/docs/consensus-mechanisms/pow/mining/mining-algorithms/ethash). This was a successor to an original R&D algorithm known a
```suggestion
Ethereum Mainnet only ever used one mining algorithm - ['Ethash'](/developers/docs/consensus-mechanisms/pow/mining/mining-algorithms/ethash). This was a successor to an original R&D algorithm known as ['Dagger-Hashamoto'](/developers/docs/consensus-mechanisms/pow/mining/mining-algorithms/dagger-hashamoto).
```

2022-07-25 12:52 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +The algorithm is based around the provision of a large, transient, randomly generated dataset which forms a [Directed Acyclic Graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph) (the Dagger-
```suggestion
The algorithm is based around the provision of a large, transient, randomly generated dataset which forms a [Directed Acyclic Graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph) (the Dagger part), with miners attempting to solve a particular constraint on it, partly determined through a block’s header-hash. This has high memory-access bandwidth requirements but could be run using a modest processor, making it GPU-friendly but resistant to the type of ASIC-driven hardware arms race that could pose a centralization risk (more on [problems with ASICS](https://www.investopedia.com/investing/why-centralized-crypto-mining-growing-problem/)). ASICs for Ethereum mining were eventually developed, but the majority of mining on Ethereum was nevertheless done using GPUs.
```

2022-08-01 12:26 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +   Proof-of-work is no longer underlying Ethereum's consensus mechanism, meaning mining has been switched off. Instead, Ethereum is secured by validators who stake ETH. You can start staking your ETH
```suggestion

   Proof-of-work is no longer underlying Ethereum's consensus mechanism, meaning mining has been switched off. Instead, Ethereum is secured by validators who stake ETH. You can start staking your ETH today. Read more on [The Merge](/upgrades/merge/), [proof-of-stake](/developers/docs/consensus-mechanisms/pos/), and [staking](/staking/). This page is for historical interest.
   
```

2022-08-01 12:27 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +   Proof-of-work is no longer underlying Ethereum's consensus mechanism, meaning mining has been switched off. Instead, Ethereum is secured by validators who stake ETH. You can start staking your ETH
Added spaces either side so we can use markdown syntax instead of HTML here.

2022-08-01 12:29 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +The algorithm is based around the provision of a large, transient, randomly generated dataset which forms a [Directed Acyclic Graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph) (the Dagger
Can we just remove this section @jmcook1186? 

The only nice thing I'd like to keep **somewhere** is the problem with ASICS information, though if it doesn't already, I think that can be covered in the mining algorithms page.

2022-08-08 09:33 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +The algorithm is based around the provision of a large, transient, randomly generated dataset which forms a [Directed Acyclic Graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph) (the Dagger
```suggestion
```

2022-08-08 09:34 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
>  More information on these mining algorithms is available at our [mining algorithms page](/developers/docs/consensus-mechanisms/pow/mining-algorithms/).
```suggestion

[More on mining algorithms](/developers/docs/consensus-mechanisms/pow/mining-algorithms/).
```

2022-08-08 09:34 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +Ethereum Mainnet only ever used one mining algorithm - ['Ethash'](/developers/docs/consensus-mechanisms/pow/mining/mining-algorithms/ethash). This was a successor to an original R&D algorithm known a
```suggestion
Ethereum Mainnet only ever used one mining algorithm - ['Ethash'](/developers/docs/consensus-mechanisms/pow/mining/mining-algorithms/ethash). Ethhash was the successor to an original R&D algorithm known as ['Dagger-Hashamoto'](/developers/docs/consensus-mechanisms/pow/mining/mining-algorithms/dagger-hashamoto).
```

2022-08-08 09:37 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
> +The algorithm is based around the provision of a large, transient, randomly generated dataset which forms a [Directed Acyclic Graph](https://en.wikipedia.org/wiki/Directed_acyclic_graph) (the Dagger
Coming back to this, I feel the same way. I've removed it and [created a card to add it to the mining algorithms page.](https://www.notion.so/efdn/Add-information-about-the-problem-with-ASICS-to-mining-algorithms-page-45985053907a4a50a2049e941c9c5cba)

2022-08-08 09:37 UTC, minimalsm approved these changes
Nice work :]

2022-08-08 09:37 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pow/mining/index.md
>  description: An explanation of how mining works in Ethereum and how it helps keep Ethereum secure and decentralized.
```suggestion
description: An explanation of how mining worked on Ethereum.
```

2022-08-08 09:38 UTC, merged