post-merge updates: staking content
ethereum/ethereum-org-website pull request #7115
Opened 2022-07-18 12:46 UTC by jmcook1186

## Description

updates staking content ready for post-merge

## Related Issue

#7105

2022-07-25 13:22 UTC, wackerow requested changes
@jmcook1186 Couple suggestions, one of which required (need to remove that lonely closing tag). Otherwise looks good!

2022-07-25 13:22 UTC, wackerow commented on src/content/staking/pools/index.md
> +Alternatively, pools that utilize an ERC-20 liquidity token allow users to trade this token in the open market, effectively allowing you to "withdraw" without actually removing ETH from the staking c
Just a thought
```suggestion
Alternatively, pools that utilize an ERC-20 liquidity token allow users to trade this token in the open market, allowing you to sell your staking position, effectively "withdrawing" without actually removing ETH from the staking contract.
```

2022-07-25 13:22 UTC, wackerow commented on src/content/staking/saas/index.md
<img width="342" alt="image" src="https://user-images.githubusercontent.com/54227730/180784812-e0e92580-f685-450b-8ed5-42f4b8b1af4f.png">

Ended up with an extra closing tag here

```suggestion
```

2022-07-25 13:22 UTC, wackerow commented on src/content/staking/solo/index.md
> +    Withdrawing staked ETH or rewards from a validator balance is not yet supported. Support for withdrawals are planned for the Shanghai upgrade. You should anticipate your ETH being locked for at l
Just a thought to infer that this upgrade is coming next
```suggestion
    Withdrawing staked ETH or rewards from a validator balance is not yet supported. Support for withdrawals are planned for the upcoming Shanghai upgrade. You should anticipate your ETH being locked for at least one-to-two years. After the Shanghai upgrade you will be able to freely withdraw portions or all of your stake if you wish.
```

2022-08-01 12:32 UTC, minimalsm commented on src/content/staking/pools/index.md
> +Currently, withdrawing funds from an Ethereum validator is not possible, which limits the ability to actually <em>redeem</em> your liquidity token for the ETH rewards locked in the consensus layer.
```suggestion

Currently, withdrawing funds from an Ethereum validator is not possible, which limits the ability to actually _redeem_ your liquidity token for the ETH rewards locked in the consensus layer.

```

2022-08-01 12:33 UTC, minimalsm commented on src/content/staking/solo/index.md
> +A <em>validator</em> is a virtual entity that lives on Ethereum and participates in the consensus of the Ethereum protocol. Validators are represented by a balance, public key, and other properties.
```suggestion

A _validator_ is a virtual entity that lives on Ethereum and participates in the consensus of the Ethereum protocol. Validators are represented by a balance, public key, and other properties. A <em>validator client</em> is the software that acts on behalf of the validator by holding and using its private key. A single validator client can hold many key pairs, controlling many validators.

```

2022-08-01 12:34 UTC, minimalsm approved these changes

2022-08-01 12:34 UTC, merged