update intro to ether page
ethereum/ethereum-org-website pull request #7141
Opened 2022-07-20 09:37 UTC by jmcook1186

## Description

updates `developers/docs/intro-to-ether/index.md` for post-merge 

## Related Issue

#7105

2022-07-25 16:09 UTC, wackerow approved these changes
@jmcook1186 LGTM! Just committed a couple tiny typo fixes

2022-07-25 16:09 UTC, wackerow commented on src/content/developers/docs/intro-to-ethereum/index.md
> +Ethereum uses a proof-of-stake based consensus mechanism. This means that anyone who wants to add new blocks to the chain must stake at least 32 ETH into the deposit contract and run validator softwa
```suggestion
Ethereum uses a proof-of-stake based consensus mechanism. This means that anyone who wants to add new blocks to the chain must stake at least 32 ETH into the deposit contract and run validator software. They then have a chance of being randomly selected to propose blocks that other validators check and add to the blockchain. In this model there is usually only one chain, but network latency and dishonest behavior can cause multiple blocks to exist at the same position near the head of the chain. To resolve this, a fork-choice algorithm selects one canonical set of blocks. The blocks selected are the ones that form the heaviest possible chain, where 'heavy' refers to the number of validators that have endorsed the blocks (weighted by the ETH they have staked). There is a system of rewards and penalties that strongly incentivize participants to be honest and online as much as possible.
```

2022-07-25 16:09 UTC, wackerow commented on src/content/developers/docs/intro-to-ethereum/index.md
> +Ethereum is a blockchain with a computer embedded in it. It serves as the foundation for building apps and organizations is a decentralized, permissionless, censorship resistant way.
```suggestion
Ethereum is a blockchain with a computer embedded in it. It serves as the foundation for building apps and organizations in a decentralized, permissionless, censorship resistant way.
```

2022-07-25 16:09 UTC, wackerow commented on src/content/developers/docs/intro-to-ethereum/index.md
> +ETH is also used to provide crypto-economic security to the network, in three main ways: 1) it is used as a means to reward validators who propose blocks or call out dishonest behaviour by other vali
```suggestion
ETH is also used to provide crypto-economic security to the network, in three main ways: 1) it is used as a means to reward validators who propose blocks or call out dishonest behavior by other validators; 2) It is staked by validators, acting as collateral against dishonest behavior—if validators attempt to misbehave their ETH can be destroyed; 3) it is used to weight 'votes' for newly proposed blocks, feeding into the fork-choice part of the consensus mechanism.
```

2022-07-27 14:29 UTC, minimalsm requested changes

2022-07-27 14:29 UTC, minimalsm commented on src/content/developers/docs/intro-to-ethereum/index.md
> +Ethereum uses a proof-of-stake based consensus mechanism. This means that anyone who wants to add new blocks to the chain must stake at least 32 ETH into the deposit contract and run validator softwa
```suggestion
Ethereum uses a [proof-of-stake-based consensus mechanism](/developers/docs/consensus-mechanisms/pos). Anyone who wants to add new blocks to the chain must stake at least 32 ETH into the deposit contract and run validator software. They then can be randomly selected to propose blocks that other validators check and add to the blockchain. In this model, there is usually only one chain, but network latency and dishonest behavior can cause multiple blocks to exist at the same position near the head of the chain. To resolve this, a fork-choice algorithm selects one canonical set of blocks. The blocks selected are the ones that form the heaviest possible chain, where 'heavy' refers to the number of validators that have endorsed the blocks (weighted by the ETH they have staked). There is a system of rewards and penalties that strongly incentivize participants to be honest and online as much as possible.
```

2022-07-27 14:29 UTC, minimalsm commented on src/content/developers/docs/intro-to-ethereum/index.md
> +More on [proof-of-stake](/developers/docs/consensus-mechanisms/pos).
```suggestion
```

2022-07-27 14:29 UTC, minimalsm commented on src/content/developers/docs/intro-to-ethereum/index.md
> +Ethereum is a blockchain with a computer embedded in it. It serves as the foundation for building apps and organizations in a decentralized, permissionless, censorship resistant way.
```suggestion
Ethereum is a blockchain with a computer embedded in it. It is the foundation for building apps and organizations in a decentralized, permissionless, censorship-resistant way.
```

2022-07-27 14:29 UTC, minimalsm commented on src/content/developers/docs/intro-to-ethereum/index.md
> +ETH is also used to provide crypto-economic security to the network, in three main ways: 1) it is used as a means to reward validators who propose blocks or call out dishonest behavior by other valid
```suggestion
ETH is also used to provide crypto-economic security to the network in three main ways: 1) it is used as a means to reward validators who propose blocks or call out dishonest behavior by other validators; 2) It is staked by validators, acting as collateral against dishonest behavior—if validators attempt to misbehave their ETH can be destroyed; 3) it is used to weight 'votes' for newly proposed blocks, feeding into the fork-choice part of the consensus mechanism.
```

2022-07-27 14:29 UTC, minimalsm commented on src/content/developers/docs/intro-to-ethereum/index.md
> +Any participant who broadcasts a transaction request must also offer some amount of ETH to the network as a bounty. This bounty will be awarded to whoever eventually does the work of verifying the tr
```suggestion
Any participant who broadcasts a transaction request must also offer some amount of ETH to the network as a bounty. The network will award this bounty to whoever eventually does the work of verifying the transaction, executing it, committing it to the blockchain, and broadcasting it to the network.
```

2022-07-27 14:30 UTC, minimalsm commented on src/content/developers/docs/intro-to-ethereum/index.md
> +Ethereum uses a [proof-of-stake-based consensus mechanism](/developers/docs/consensus-mechanisms/pos). Anyone who wants to add new blocks to the chain must stake at least 32 ETH into the deposit cont
```suggestion
Ethereum uses a [proof-of-stake-based consensus mechanism](/developers/docs/consensus-mechanisms/pos/). Anyone who wants to add new blocks to the chain must stake at least 32 ETH into the deposit contract and run validator software. They then can be randomly selected to propose blocks that other validators check and add to the blockchain. In this model, there is usually only one chain, but network latency and dishonest behavior can cause multiple blocks to exist at the same position near the head of the chain. To resolve this, a fork-choice algorithm selects one canonical set of blocks. The blocks selected are the ones that form the heaviest possible chain, where 'heavy' refers to the number of validators that have endorsed the blocks (weighted by the ETH they have staked). There is a system of rewards and penalties that strongly incentivize participants to be honest and online as much as possible.
```

2022-07-27 14:35 UTC, minimalsm approved these changes
Nice :-)

I think we should remove the videos (at least Austin's, which heavily refers to proof-of-work). Happy to split that discussion off into a more general 'what do we do with external resources' discussion at some point soon. [I've made a Notion card here to capture that work.](https://www.notion.so/efdn/Evaluate-external-resources-used-on-ethereum-org-15fffa1bc7ff45eaacfe0885b53245fb)

2022-07-27 14:35 UTC, merged

2022-07-27 14:51 UTC, minimalsm commented on src/content/developers/docs/intro-to-ethereum/index.md
> +ETH is also used to provide crypto-economic security to the network in three main ways: 1) it is used as a means to reward validators who propose blocks or call out dishonest behavior by other valida
Let's use an actual ordered list (`<ol> <li>`) here instead of listing in text.