post-merge updates: intro to ether page
ethereum/ethereum-org-website pull request #7154
Opened 2022-07-21 10:06 UTC by jmcook1186

## Description

updates `developers/docs/intro-to-ether/index.md` ready for post-merge

## Related Issue

#7105

2022-07-25 18:30 UTC, wackerow requested changes
@jmcook1186 Left a comment...

Also, I'm assuming it wasn't intentional to include changes to the `data/translation-reports/**/*.json` files—any chance we can revert these?

2022-07-25 18:30 UTC, wackerow commented on src/content/developers/docs/intro-to-ether/index.md
> +Ether is minted in each slot (every 12 seconds). The total amount issued depends on the number of validators and how much ether they have staked. This total issuance is divided equally among validato
> Ether is minted in each slot (every 12 seconds). 

Would push back on this a bit. Correct me if I'm wrong, but ether isn't necessarily minted each "slot"... Each slot is an opportunity for a block, but is not guaranteed (ie, block proposer is offline), and IIRC, attestation rewards are not credited to the validator balance until the epoch checkpoint.

Perhaps:
```suggestion
Ether is minted as a reward for each block proposed, and also at every epoch checkpoint for other validator activity related to reaching consensus. The total amount issued depends on the number of validators and how much ether they have staked. This total issuance is divided equally among validators in the ideal case that all validators are honest and online, but in reality it varies based on validator performance. About 1/8 of the total issuance goes to the block proposer, the remainder is distributed across the other validators. Block proposers also receive tips from transaction fees and MEV related income but these come from recycled ether, not fresh issuance.
```

Not sure if we should get into block/slot timing in this section, any thoughts?

2022-07-26 08:52 UTC, jmcook1186 commented
incorporated your suggestion and reverted changes to `/intl` in forced push.

2022-08-01 10:42 UTC, minimalsm commented on src/content/developers/docs/intro-to-ether/index.md
> +Ether is minted as a reward for each block proposed, and also at every epoch checkpoint for other validator activity related to reaching consensus. The total amount issued depends on the number of va
```suggestion
Ether is minted as a reward for each block proposed and at every epoch checkpoint for other validator activity related to reaching consensus. The total amount issued depends on the number of validators and how much ether they have staked. This total issuance is divided equally among validators in the ideal case that all validators are honest and online, but in reality, it varies based on validator performance. About 1/8 of the total issuance goes to the block proposer; the remainder is distributed across the other validators. Block proposers also receive tips from transaction fees and MEV-related income, but these come from recycled ether, not new issuance.
```

2022-08-01 10:43 UTC, minimalsm approved these changes

2022-08-01 10:43 UTC, merged