add page on attestations to pos section
ethereum/ethereum-org-website pull request #7155
Opened 2022-07-21 14:52 UTC by jmcook1186

## Description

Adds page on attestations to `developers/docs/consensus-mechanisms/pos`.
Uses kb.beaconchain attestation page as base but pretty heavily modified, including new diagram.

## Related Issue

#2277

2022-07-25 20:45 UTC, wackerow reviewed
❤️ love to see this =) 

Committed a couple small adjustments during my first quick pass... 

Our nice new image =) Love this, but two concerns, 1) translations and 2) dark mode. 

<img width="608" alt="image" src="https://user-images.githubusercontent.com/54227730/180869696-b98797ee-d9c2-448c-8f74-435f3175e23c.png">

The later is a blocker, but I'm sure can easily be fixed... is this in Figma? @nloureiro was this you?

Will try to consider options for intl support here in the meantime

2022-07-26 08:44 UTC, jmcook1186 commented
damn, dark mode ofc. I whipped that image up bc I thought the one in the original page was a bit scrappy for e.org. @nloureiro can you help make this e.org compatible?

2022-07-27 15:21 UTC, nloureiro commented
> damn, dark mode ofc. I whipped that image up bc I thought the one in the original page was a bit scrappy for e.org. @nloureiro can you help make this e.org compatible?

Yes, I can try.

What is the page? Is it this one? https://ethereumorgwebsitedev01-jcbeaconchainattestations.gtsb.io/en/developers/docs/consensus-mechanisms/pos

For translation, @wackerow any idea? should we make this diagram a component with text in html and the rest svg?

2022-08-01 22:58 UTC, wackerow commented
@nloureiro https://ethereumorgwebsitedev01-jcbeaconchainattestations.gtsb.io/en/developers/docs/consensus-mechanisms/pos/attestations

As for translations, this is a similar problem that plagues our developer docs... I think we should consider this as a separate initiative (possibly a future epic cc: @samajammin) to fix all of these images that use embedded English. In the meantime, if we just keep the Figma you use handy, we can always re-export without text in the future.

2022-08-08 09:49 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pos/attestations/index.md
> +### Aggregated Attestation {#aggregated-attestation}
```suggestion
### Aggregated attestation {#aggregated-attestation}
```

2022-08-08 09:50 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pos/attestations/index.md
> +### Attestation Inclusion Lifecycle {#attestation-inclusion-lifecycle}
Please use sentence case for titles :-)

```suggestion
### Attestation inclusion lifecycle {#attestation-inclusion-lifecycle}
```

2022-08-08 09:50 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pos/attestations/index.md
> +## What is an attestation? {#what-is-an-attestation}
Can we add pre-requisites here

2022-08-08 09:55 UTC, minimalsm commented on src/content/developers/docs/consensus-mechanisms/pos/attestations/index.md
> +description: A description of attestations on PoS Ethereum.
```suggestion
description: A description of attestations on proof-of-stake Ethereum.
```

2022-08-08 09:56 UTC, minimalsm requested changes
This has been hanging around for a while.

To get this merged quickly, could I suggest:

- We add a non-transparent background to the image for now
- We create a card to revisit the image (probably as an epic?)
- We add a pre-requisites section

2022-08-08 20:29 UTC, minimalsm approved these changes

2022-08-08 20:29 UTC, merged