Change the checkbox to radio on the profile chooser box
ethereum/ethereum-org-website pull request #7159
Opened 2022-07-21 20:43 UTC by nloureiro

We got a suggestion from "RomoPuma" (if you have a Github profile, please add it) on discord (https://discord.com/channels/714888181740339261/951053072258453574/999409307953143932)to change The checkboxes on the personas box to radio-style buttons.

Here are some screenshots of the change.

![Screen Shot 2022-07-21 09 42 19 PM](https://user-images.githubusercontent.com/1120748/180311678-c24a28f9-df1a-4536-a832-ed1416ddff3f.png)

![Screen Shot 2022-07-21 09 42 09 PM](https://user-images.githubusercontent.com/1120748/180311702-a2b19b04-5567-4c08-b70d-6ca606072748.png)

2022-07-21 21:30 UTC, filtelescu commented
RomoPuma here (also updated my 'about me' on Discord as a verification) -- Looks great! 

I noticed there's a slight animation time between states on the deploy (when selecting 'New to crypto' for example), not sure if that's supposed to be there or not considering on live the transition is instant. 

Super dope :)

2022-07-22 07:35 UTC, nloureiro commented
> 

yes. actually was on purpose. I think it improves awareness of the "different" radio button. I think the only downside of this change is awareness. You were right, this is a radio button behavior but in a different look/style/appearance. The check mark would try to make it more obvious. with the animation, I'm trying to gain a bit of the sense that something happen without removing the focus or usability.

I can reduce the time, it's a 1,5s transition.

2022-07-22 09:57 UTC, filtelescu commented
Understandable, you're definitely right that the check mark makes the selection more obvious. I do think reducing the time _slightly_ could help keep it consistent with the snappiness of the rest of the interface while still acting as a clear indicator. 

The best of both worlds 😎

2022-07-22 21:39 UTC, corwintines commented
I'm going to do some playing around to bring this in as an actual radio input instead of CSS styling if that's ok @nloureiro

2022-07-29 13:28 UTC, minimalsm requested changes
Nice :-) agree with the change on the design here 💯

The implementation currently does not allow screen readers to select/unselect or know what is selected from the profiles. To fix this, I think we should break these styles out of the h3 and into a radio button-styled component. What do you think?

2022-08-01 22:59 UTC, corwintines commented
@minimalsm I think this should fix up the regression in screen reader functionality. @nloureiro @filtelescu any feedback welcome as well.

2022-08-09 23:45 UTC, samajammin approved these changes
LGTM! Though I'd like @minimalsm to confirm he doesn't see any issues w/ screen readers.

2022-08-15 08:58 UTC, minimalsm approved these changes
Sorry for blocking :-)

2022-08-15 08:58 UTC, merged

2022-08-15 08:59 UTC, minimalsm commented
For context, this was some discussion behind the scenes:

- Not blocking this PR but wanted to highlight we’re doing something unusual with radio buttons here
    - A radio button typically can only be selected, and after one radio button has been selected, another must be selected to unselect the previous (the default state of none selected cannot be re-achieved)
    - In the current implementation, only one option can be chosen, but we also deselect it (so it essentially behaves kinda like a checkbox, kinda like a radio button)
    - This might be a headache if we decide to implement Chakra’s Checkbox component