Update types of wallets section of wallets page
ethereum/ethereum-org-website pull request #7320
Opened 2022-08-05 21:15 UTC by corwintines

## Description
- Update title `Types of wallet` to `Types of wallet interfaces`
    - Context on this, thought it was worth differentiating that these are the types of ways to interface with an account. Types of wallets to me is more Private key, smart contract, MPC. Not necessarily the device which this is providing information on.
- Add a short description
- Add Brower Extensions as a type of wallet interface.

2022-08-09 23:26 UTC, samajammin commented on src/intl/en/page-wallets.json
> +  "page-wallets-types": "Types of wallet interfaces",
Hmmm so what is a "wallet" vs. what is a "wallet interface"? This now confuses me a bit.

2022-08-09 23:28 UTC, samajammin commented on src/intl/en/page-wallets.json
> +  "page-wallets-types": "Types of wallet interfaces",
To me these are still "types of wallets". Not convinced we should introduce yet more jargon.

2022-08-09 23:30 UTC, samajammin commented on src/intl/en/page-wallets.json
> +  "page-wallets-web-browser": "Browser wallets let you interact with your account directly in the browser",
```suggestion
  "page-wallets-web-browser": "Browser wallets are web applications that let you interact with your account directly in the browser",
```

2022-08-09 23:30 UTC, samajammin commented on src/intl/en/page-wallets.json
> +  "page-wallets-types": "Types of wallet interfaces",
```suggestion
  "page-wallets-types": "Types of wallets",
```

2022-08-09 23:30 UTC, samajammin requested changes
Suggested a couple changes. Curious what other folks think here.

2022-08-10 02:27 UTC, konopkja commented
> ## Description
> * Update title `Types of wallet` to `Types of wallet interfaces`
>   
>   * Context on this, thought it was worth differentiating that these are the types of ways to interface with an account. Types of wallets to me is more Private key, smart contract, MPC. Not necessarily the device which this is providing information on.
> * Add a short description
> * Add Brower Extensions as a type of wallet interface.

this assumes others also have this background knowledge about smart contract, private key etc. I agree with Sam here, that this level of detail maybe unnecessary to differentiate.

2022-08-10 22:51 UTC, corwintines commented
Thanks for the input @samajammin @konopkja . Brought in the change requests. I think this should be good now!

2022-08-12 22:16 UTC, samajammin approved these changes

2022-08-12 22:16 UTC, merged