post-merge updates: data and analytics page
ethereum/ethereum-org-website pull request #7481
Opened 2022-08-18 09:24 UTC by jmcook1186

## Description

updates data and analytics page for post-merge. Adds Dune Analytics and client diversity dashboards, removes "miners" from text

## Related Issue

#7075

2022-08-19 08:33 UTC, minimalsm commented on src/content/developers/docs/data-and-analytics/index.md
> +Client diversity is important for the overall health of the Ethereum network because it provides resilience to bugs and exploits. There are now several cl;eint diversity dashboards including [clientd
```suggestion
[Client diversity](/developers/docs/nodes-and-clients/client-diversity/) is important for the overall health of the Ethereum network because it provides resilience to bugs and exploits. There are now several client diversity dashboards including [clientdiversity.org](https://clientdiversity.org/), [rated.network](rated.network), [pool.invis.cloud](pool.invis.cloud), [slashed.info](slahed.info) and [Ethernodes](https://ethernodes.org/).
```

2022-08-19 08:34 UTC, minimalsm commented on src/content/developers/docs/data-and-analytics/index.md
> +Client diversity is important for the overall health of the Ethereum network because it provides resilience to bugs and exploits. There are now several cl;eint diversity dashboards including [clientd
Might we want this as an actual list vs an in-sentence list? Not a requirement, just an idea.

2022-08-19 08:36 UTC, minimalsm requested changes

2022-08-19 08:36 UTC, minimalsm commented on src/content/developers/docs/data-and-analytics/index.md
> +## Dune analytics
```suggestion
## Dune analytics {#dune-analytics}
```

2022-08-19 08:36 UTC, minimalsm commented on src/content/developers/docs/data-and-analytics/index.md
> +[Dune analytics](https://docs.dune.com/) aggregates blockchain data into SQL databases that can be queried and used to create visualizations and dashboards.
We had a contributor submit an in-depth description of Dune analytics this week [in this PR](https://github.com/ethereum/ethereum-org-website/pull/7448/files). Do we think the in-depth description is better? (Or does it read like an ad?)

2022-08-19 08:36 UTC, minimalsm commented on src/content/developers/docs/data-and-analytics/index.md
> +- [Beaconcha.in beacon chaion explorer](beaconcha.in)
```suggestion
- [Beaconcha.in beacon chain explorer](beaconcha.in)
```

2022-08-22 11:52 UTC, jmcook1186 commented on src/content/developers/docs/data-and-analytics/index.md
> +[Dune analytics](https://docs.dune.com/) aggregates blockchain data into SQL databases that can be queried and used to create visualizations and dashboards.
I prefer their version

2022-08-30 23:37 UTC, wackerow approved these changes
Merged in changed from dev and cleared the conflicts using the Dune Analytics section from the other PR.

2022-08-30 23:37 UTC, merged