add page on pos rewards and penalties
ethereum/ethereum-org-website pull request #7541
Opened 2022-08-23 13:14 UTC by jmcook1186

## Description

Adds a page on rewards and penalties in proof-of-stake ethereum as part of kb.beaconchain migration.
Pinging @wackerow for review and suggest possibly getting someone from consensus dev group to look too.

## Related Issue
#2277

2022-08-23 14:18 UTC, jmcook1186 commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +The `base_reward` is also modified by the `inclusion_delay` which rewards prompt attestations. If the delay between block proposal and attestation is >= 1 slot, the attestor receives the full 7/8 _ `
```suggestion
The `base_reward` is also modified by the `inclusion_delay` which rewards prompt attestations. If the delay between block proposal and attestation is >= 1 slot, the attestor receives the full 7/8 * `base_reward`. For each additional missed slot, the denominator is increased by 8, meaning that the reward for a delay of two slots is scaled by 7/16, for three slots it is 7/24, for four slots it is 7/32 (or, put another way, `7/8 * base_reward * 1/k`where`k` = number of slots separating block and attestation). 32 is the maximum inclusion delay denominator that can be applied. This means the slower the attestation, the smaller the reward.
```

2022-09-01 03:05 UTC, wackerow requested changes
@jmcook1186 This is really great, nice job here! This will be a very nice resource to have on the page.

I left comments for round one, but clearly I'm going to need to peak at those sources myself at the bottom to get a refresher and circle back.

2022-09-01 03:05 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +\__[\_https://benjaminion.xyz/eth2-annotated-spec/phase0/beacon-chain/_](https://benjaminion.xyz/eth2-annotated-spec/phase0/beacon-chain/)
```suggestion
_[https://consensys.net/blog/codefi/rewards-and-penalties-on-ethereum-20-phase-0/](https://consensys.net/blog/codefi/rewards-and-penalties-on-ethereum-20-phase-0/)_
_[https://benjaminion.xyz/eth2-annotated-spec/phase0/beacon-chain/](https://benjaminion.xyz/eth2-annotated-spec/phase0/beacon-chain/)_
```

2022-09-01 03:05 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +
```suggestion
[Eth2 Slashing Prevention Tips](https://medium.com/prysmatic-labs/eth2-slashing-prevention-tips-f6faa5025f50)

```
This is getting slightly dated, but still a nice writeup by Raul with Prysm about slashing we could consider adding.

2022-09-01 03:05 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +The reward, penalty and slashing design of the Beacon Chain encourages individual validators to behave correctly. However, from these design choices emerges a system that strongly incentivizes equal
An inactivity leak occurred with the Medalla testnet... nice to have, but a note about how this was encountered in testing and did ultimately allow the chain to finalize again could maybe be nice.

2022-09-01 13:41 UTC, jmcook1186 commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +There are also some actions that are very difficult to do accidentally and signify some malicious intent, such as proposing multiple blocks for the same slot or attesting to multiple blocks for the s
ah ok, my mistake - I was going off altair spec I think.
```suggestion
There are also some actions that are very difficult to do accidentally and signify some malicious intent, such as proposing multiple blocks for the same slot or attesting to multiple blocks for the same slot. These are “slashable” behaviors that result in the validator having some amount of ether (up to 1 ETH) burned before the validator is removed from the network, which takes 36 days. The slashed validator’s ether slowly drains away across the exit period, but on Day 18 they receive a “correlation penalty” which is larger when more validators are slashed around the same time. The Beacon Chain’s incentive structure therefore pays for honesty and punishes bad actors.
```

2022-09-01 14:04 UTC, jmcook1186 commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +There are two primary roles for a validator: 1) checking new blocks and “attesting” to them if they are valid, 2) proposing new blocks when selected at random from the total validator pool. If the va
yea we can.
```suggestion
There are two primary roles for a validator: 1) checking new blocks and “attesting” to them if they are valid, 2) proposing new blocks when selected at random from the total validator pool. If the validator fails to do either of these tasks when asked they miss out on an ether payout. Validators are also sometimes tasked with signature aggregation and participating in sync committees.
```

2022-09-01 14:08 UTC, jmcook1186 commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +The `base_reward` for each validator is then also multiplied by the `participation_rate` which is the fraction of all active validators that participate consistently with each other. So, if all valid
I think not, as it;s not the final reward that's being calculated, it's an adjustment to the `base_reward` specifically. Agree that `==` is incorrect as it should indicate an assignment not an equality.
```suggestion
The `base_reward` for each validator is then also multiplied by the `participation_rate` which is the fraction of all active validators that participate consistently with each other. So, if all validators attest identically, `base_reward`=`base_reward`, if 10% of validators fail to participate or do so differently to the majority `base_reward` = `base_reward * 0.9`. This ensures there is no benefit to attacking other validators.
```

2022-09-01 14:11 UTC, jmcook1186 commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +| correct           | correct           | correct           | 3 _ `base_reward` _ `participation_rate` | 0                  | `base_reward` \* 7/8 | (3 _ `base_reward` _ `participation_rate`) + `base
```suggestion
| ----------------- | ----------------- | ----------------- | ---------------------------------------- | ------------------ | -------------------- | ----------------------------------------------------------------- |
| incorrect/missing | incorrect/missing | incorrect/missing | 0                                        | 3 * `base_reward` | 0                    | -3 * `base_reward`                                               |
| correct           | incorrect/missing | incorrect/missing | `base_reward` * `participation_rate`    | 2 * `base_reward` | `base_reward` * 7/8 | `base_reward` _ `participation_rate` - 9/8 _ `base_reward`        |
| correct           | correct           | incorrect/missing | 2 _ `base_reward` _ `participation_rate` | `base_reward`      | `base_reward` * 7/8 | (2 _ `base_reward` _ `participation_rate`) - 1/8 * `base_reward` |
| correct           | correct           | correct           | 3 _ `base_reward` _ `participation_rate` | 0                  | `base_reward` * 7/8 | (3 _ `base_reward` _ `participation_rate`) + `base_reward` * 7/8 |
```

2022-09-01 14:24 UTC, jmcook1186 commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +- You vote correctly and gets included in the next slot: you get 31/8 \* `base_reward`
I think it is 8/8 * 3 * `base_reward` for source, target and head votes, plus 7/8 * `base_reward` = 31/8.

I'm not 100% sure this is right, but it is consistent with the kb.beaconchain info.

2022-09-01 14:52 UTC, jmcook1186 commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +If these actions are detected, the validator is slashed. This means that 1/64th of their staked ether (up to a maximum of 0.5 ether) is immediately burned, then a 36 day removal period begins. During
```suggestion
If these actions are detected, the validator is slashed. This means that 1/32 of their staked ether (up to a maximum of 1 ether) is immediately burned, then a 36 day removal period begins. During this removal period the validators stake gradually bleeds away. At the mid-point (Day 18) an additional penalty is applied whose magnitude scales with the total staked ether of all slashed validators in the 36 days prior to slashing event. This means that when more validators are slashed, the magnitude of the slash increases. The maximum slash is the full effective balance of all slashed validators (i.e. if there are lots of validators being slashed they could lose their entire stake). On the other hand, a single, isolated slashing event only burns a small portion of the validator's stake. This midpoint penalty that scales with the number of slashed validators is called the "correlation penalty".
```

2022-09-01 22:49 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +The `base_reward` for each validator is then also multiplied by the `participation_rate` which is the fraction of all active validators that participate consistently with each other. So, if all valid
Ok.. the assignment operand makes more sense, but could we not use another name as the intermediate value here to prevent confusion?

2022-09-01 22:59 UTC, wackerow commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +| correct           | correct           | correct           | 3 _ `base_reward` _ `participation_rate` | 0                  | `base_reward` \* 7/8 | (3 _ `base_reward` _ `participation_rate`) + `base
<img width="1517" alt="image" src="https://user-images.githubusercontent.com/54227730/188025893-343fb66b-31ee-45e4-9ee9-5acbe57628a0.png">

- Adds header ID to header
- Using `vote_reward` and `inclusion_reward` to make it more clear these are separate rewards, and being explicit about how the result is the `vote_reward` + `inclusion_reward` - `penalty`
- Moves `inclusion_reward` column to the left to consolidate rewards together
- Simplifies the "results" mathematically, and arranges them all with the `base_reward` multiplier at the end

(same as screenshot above)
```suggestion
### Attestation scenarios {#attestation-scenarios}

Assuming attestations are timely (included in the very next block, inclusion distance of 1) the following table describes the attestation rewards for four scenarios:

| `source`          | `target`          | `head`            | `vote_reward`                              | `inclusion_reward`   | `penalty`          | Result (`vote_reward` + `inclusion_reward` - `penalty`) |
| ----------------- | ----------------- | ----------------- | ------------------------------------------ | -------------------- | ------------------ | ------------------------------------------------------- |
| incorrect/missing | incorrect/missing | incorrect/missing | 0                                          | 0                    | 3 \* `base_reward` |                                    - 3 \* `base_reward` |
| correct           | incorrect/missing | incorrect/missing | 1 \* `base_reward` \* `participation_rate` | 7/8 \* `base_reward` | 2 \* `base_reward` |           (`participation_rate` - 9/8) \* `base_reward` |
| correct           | correct           | incorrect/missing | 2 \* `base_reward` \* `participation_rate` | 7/8 \* `base_reward` | 1 \* `base_reward` |      (2 \* `participation_rate` - 1/8) \* `base_reward` |
| correct           | correct           | correct           | 3 \* `base_reward` \* `participation_rate` | 7/8 \* `base_reward` | 0                  |      (3 \* `participation_rate` + 7/8) \* `base_reward` |
```

2022-09-02 08:26 UTC, jmcook1186 commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +The `base_reward` for each validator is then also multiplied by the `participation_rate` which is the fraction of all active validators that participate consistently with each other. So, if all valid
ok, how about just being really explicit about it:
```suggestion
The `base_reward` for each validator is then also multiplied by the `participation_rate` which is the fraction of all active validators that participate consistently with each other. So, if all validators attest identically, `updated_base_reward` =`base_reward`, if 10% of validators fail to participate or do so differently to the majority `updated_base_reward` = `base_reward * 0.9`. This ensures there is no benefit to attacking other validators.
```

2022-09-06 11:04 UTC, jmcook1186 commented on src/content/developers/docs/consensus-mechanisms/pos/rewards-and-penalties/index.md
> +If the Beacon Chain has gone more than four epochs without finalizing, an emergency protocol called the "inactivity leak" is activated. The ultimate aim of the inactivity leak is to create the condit
```suggestion
If the Beacon Chain has gone more than four epochs without finalizing, an emergency protocol called the "inactivity leak" is activated. The ultimate aim of the inactivity leak is to create the conditions required for the chain to recover finality. As explained above, finality requires a 2/3 majority of the total staked ether to agree on source and target checkpoints. If validators representing more than 1/3 of the total validators go offline or fail to submit correct attestations then it is not possible for a 2/3 supermajority to finalize checkpoints. The inactivity leak lets the stake belonging to the inactive validators gradually bleed away until they control less than 1/3 of the total stake, allowing the remaining active validators finalize the chain. However large the pool of inactive validators, the remaining active validators will eventually control >2/3 of the stake. The loss of stake is a strong incentive for inactive validators to reactivate as soon as possible! An inactivity leak scenario was encountered on the Medalla testnet when < 66% of active validators were able to come to consensus on the current head of the blockchain. The inactivity leak was activated and finality was eventually regained!
```

2022-09-12 09:24 UTC, wackerow approved these changes
@jmcook1186 🎉 🥳

2022-09-12 09:24 UTC, merged