Added Avado as solo staking tool
ethereum/ethereum-org-website pull request #7636
Opened 2022-08-31 14:01 UTC by heeckhau

Added Avado as solo staking solution

## Description

Avado is the easiest hardware solution for home staking

## Related Issue

https://github.com/ethereum/ethereum-org-website/issues/6340

2022-09-05 07:41 UTC, heeckhau commented
@pettinarip Anything I can do to make progress here? I don't have a Vercel account

2022-09-05 12:22 UTC, minimalsm commented
Hey @heeckhau, thanks for the PR. You don't need to worry about the Vercel message. We'll try to review this very soon.

2022-09-22 18:31 UTC, corwintines commented
@wackerow do you have a moment to review this?

2022-09-22 19:25 UTC, wackerow requested changes
@heeckhau Hey, left a couple questions and suggestions, let me know your thoughts and I think we can get this in!

2022-09-22 19:25 UTC, wackerow commented on src/data/staking-products.json
> +      "name": "AVADO",
Curious if there would be opposition to making this title case consistent with the others?
```suggestion
      "name": "Avado",
```

2022-09-22 19:25 UTC, wackerow commented on src/data/staking-products.json
> +      "minEth": 16,
Good to see support for Rocket Pool... 
I know this isn't fully utilized on the front-end yet, but similar to the Rocket Pool entry we should include the additional deposit requirements in the JSON here.
```suggestion
      "minEth": 16,
      "additionalStake": "10",
      "additionalStakeUnit": "% RPL",
```

2022-09-22 19:25 UTC, wackerow commented on src/data/staking-products.json
> +      "platforms": ["Linux", "macOS", "Windows", "Browser"],
My understanding is the Avado interface is accessed through a browser, and not as stand-along executable (similar to DAppNode above). Am I incorrect?
```suggestion
      "platforms": ["Browser"],
```

2022-09-23 07:41 UTC, heeckhau commented
@wackerow Thanks a lot for the suggestions. I have applied the improvements.

2022-10-10 22:17 UTC, corwintines commented on src/data/staking-products.json
> +      "name": "AVADO",
```suggestion
      "name": "Avado",
```
Just changing this to be consistent

2022-10-10 22:19 UTC, corwintines commented on src/data/staking-products.json
> +      "platforms": ["Linux", "macOS", "Windows", "Browser"],
```suggestion
      "platforms": ["Browser"],
```

Changing this for consistency as well

2022-10-10 22:19 UTC, corwintines commented on src/data/staking-products.json
> +      "minEth": 16,
```suggestion
      "minEth": 16,
      "additionalStake": "10",
      "additionalStakeUnit": "% RPL",
```

Here as well

2022-10-10 22:22 UTC, corwintines approved these changes
Thanks, @heeckhau!

2022-10-10 22:22 UTC, merged