refactor `EthVideo.tsx` component with chakra UI
ethereum/ethereum-org-website pull request #7785
Opened 2022-09-10 16:12 UTC by MahendraBishnoi29

## Description
Migrate `EthVideo.tsx` component to Chakra.

Includes refactor of `div` component.

## Related Issue
#6374

2022-09-12 16:20 UTC, pettinarip requested changes
@MahendraBishnoi29 thanks for the PR.

For some reason, I don't see the video. You can check that in the preview deploy generated here https://ethereumorgwebsitedev01-mahendrabishnoi29ethereum00379.gtsb.io/en/eth

![image](https://user-images.githubusercontent.com/468158/189704844-647d07fd-ac42-4028-9ab8-d4e70e7a644f.png)

You can compare it with the production version. https://ethereum.org/en/eth/

I think it is because of how the parent container is positioned. I would recommend avoiding using AspectRatio in this case since I don't see an easy solution. One thing we could do here is to wrap the video tag with a Box and use the same styles we had.

```tsx
<Box as="video" ....>
```

2022-09-12 16:26 UTC, pettinarip commented on src/components/EthVideo.tsx
> +import { AspectRatio } from "@chakra-ui/react"
import order
```suggestion
import { AspectRatio } from "@chakra-ui/react"

import darkVideo from "../assets/ethereum-hero-dark.mp4"
import lightVideo from "../assets/ethereum-hero-light.mp4"

```

2022-09-13 01:59 UTC, MahendraBishnoi29 commented
> @MahendraBishnoi29 thanks for the PR.
> 
> For some reason, I don't see the video. You can check that in the preview deploy generated here https://ethereumorgwebsitedev01-mahendrabishnoi29ethereum00379.gtsb.io/en/eth
> 
> ![image](https://user-images.githubusercontent.com/468158/189704844-647d07fd-ac42-4028-9ab8-d4e70e7a644f.png)
> 
> You can compare it with the production version. https://ethereum.org/en/eth/
> 
> I think it is because of how the parent container is positioned. I would recommend avoiding using AspectRatio in this case since I don't see an easy solution. One thing we could do here is to wrap the video tag with a Box and use the same styles we had.
> 
> ```tsx
> <Box as="video" ....>
> ```

alright lemme fix it.

2022-09-13 02:45 UTC, MahendraBishnoi29 commented
@pettinarip I did your suggested changes have a look. 🛠

2022-09-14 17:35 UTC, pettinarip approved these changes
🚀 thanks @MahendraBishnoi29 

@MahendraBishnoi29 be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

2022-09-14 17:35 UTC, merged

2022-09-14 17:36 UTC, pettinarip commented
@all-contributors please add @MahendraBishnoi29 for code