SpeedRunEthereum typo fix
ethereum/ethereum-org-website pull request #7907
Opened 2022-09-18 16:10 UTC by hursittarcan

## Description
* Fixed a small typo. 

## Related Issue
* Not related to an open issue.

2022-09-19 10:31 UTC, minimalsm reviewed
Hey @hursittarcan, thanks for the PR.

What reference are you using for the naming of this? It isn't very clear from https://speedrunethereum.com/, but I can see that in the page title, they separate it as 'Speed Run Ethereum' (see screenshot below). Unfortunately, as with many things in this space, the naming convention here might be a bit shakey 😆 

<img width="366" alt="Screenshot 2022-09-19 at 12 30 07" src="https://user-images.githubusercontent.com/62268199/190998868-8492d7bc-6c83-4fe7-9dc2-b36066f55100.png">

I'm noticing that we also use inconsistent naming on the card for this:

<img width="385" alt="Screenshot 2022-09-19 at 12 30 58" src="https://user-images.githubusercontent.com/62268199/190999052-84d467da-af87-4ca4-93e1-307e0dde6bb4.png">

2022-09-19 10:35 UTC, minimalsm commented
@hursittarcan I've pinged @austintgriffith (the creator) to advise here 😀 thanks for catching this inconsistency.

2022-09-29 02:03 UTC, corwintines requested changes
I think we should fix any spelling that is `SpeedRunEthereum` to `Speed Run Ethereum` since their repo spells it [Speed Run Ethereum](https://github.com/moonshotcollective/scaffold-directory).

@minimalism have you heard back yet?

@minimalism @hursittarcan let me know if you think otherwise, but if not ill merge this in tomorrow.

2022-10-04 03:26 UTC, corwintines approved these changes

2022-10-04 03:26 UTC, merged