Migrate InfoBanner to Chakra
ethereum/ethereum-org-website pull request #7929
Opened 2022-09-20 04:19 UTC by ImMiguelP

## Description

- Migrates `InfoBanner` component from `emotion` to `chakra-ui`

## Related Issue

#6374

2022-09-21 21:12 UTC, pettinarip requested changes
Looking good @ImMiguelP left a few comments. Thanks for the PR

2022-09-21 21:12 UTC, pettinarip commented on src/components/InfoBanner.tsx
> +      direction={{ sm: "column" }}
This should be
```suggestion
      direction={{ base: "column", sm: "row" }}
```

2022-09-21 21:12 UTC, pettinarip commented on src/components/InfoBanner.tsx
> +      alignItems="center"
```suggestion
      align="center"
```

2022-09-21 21:12 UTC, pettinarip commented on src/components/InfoBanner.tsx
> +      borderRadius={0.5}
```suggestion
      borderRadius="sm"
```

2022-09-21 21:12 UTC, pettinarip commented on src/components/InfoBanner.tsx
>        {...props}
nice

2022-09-21 21:12 UTC, pettinarip commented on src/components/InfoBanner.tsx
> +          mr={{base : 6, sm: 0}}
```suggestion
          mr={{base : 0, sm: 6}}
```

2022-09-21 21:12 UTC, pettinarip commented on src/components/InfoBanner.tsx
> +          mb={{ sm: 2 }}
```suggestion
          mb={{ base: 2, sm: 0 }}
```

2022-09-21 21:12 UTC, pettinarip commented on src/components/InfoBanner.tsx
> +          alignSelf={{ sm: "flex-start" }}
```suggestion
          alignSelf={{ base: "flex-start", sm: "auto" }}
```

2022-09-21 21:12 UTC, pettinarip commented on src/components/InfoBanner.tsx
> +        display={{ base: shouldSpaceBetween ? "flex" : "block", sm: "block" }}
```suggestion
        display={{ base: "block", sm: shouldSpaceBetween ? "flex" : "block" }}
```

2022-09-22 04:32 UTC, ImMiguelP commented
> Looking good @ImMiguelP left a few comments. Thanks for the PR

Thank you @pettinarip here goes the updated files with the correct changes

2022-09-23 13:53 UTC, pettinarip approved these changes
Awesome @ImMiguelP! Thanks for the PR!

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

2022-09-23 13:53 UTC, merged

2022-09-23 13:53 UTC, pettinarip commented
@all-contributors please add @ImMiguelP for code