SectionNav refactor to ChakraUI
ethereum/ethereum-org-website pull request #7978
Opened 2022-09-23 00:42 UTC by Master7130

## Description

Converted SectionNav.tsx from styled-components to ChakraUI

## Related Issue

#6374

2022-09-23 01:56 UTC, Master7130 commented
The letter spacing for the heading was previously 0.04rem but ChakraUI doesn't have a default value for that. The closest one was "wider" which is 0.05rem. Is that close enough or should I manually set it to 0.04rem?

2022-09-26 14:07 UTC, pettinarip requested changes
Good job @Master7130. Left a few comments 👍🏼

2022-09-26 14:07 UTC, pettinarip commented on src/components/SectionNav.tsx
> +    display="flex"
```suggestion
```

2022-09-26 14:07 UTC, pettinarip commented on src/components/SectionNav.tsx
> +    flexDirection="column"
```suggestion
    direction="column"
```

2022-09-26 14:07 UTC, pettinarip commented on src/components/SectionNav.tsx
> +    justifyContent="space-between"
```suggestion
    justify="space-between"
```

2022-09-26 14:07 UTC, pettinarip commented on src/components/SectionNav.tsx
> +    borderRadius="2xl"
```suggestion
    borderRadius="base"
```

2022-09-26 14:07 UTC, pettinarip commented on src/components/SectionNav.tsx
> +    <Flex display="flex" alignItems="flex-start">
```suggestion
    <Flex align="flex-start">
```

2022-09-26 17:28 UTC, Master7130 commented
I noticed that some of your suggestions were to change the style names from longer names like justifyContent to justify. Is using the shorthand form a best practice?

2022-09-28 14:48 UTC, pettinarip commented
> I noticed that some of your suggestions were to change the style names from longer names like justifyContent to justify. Is using the shorthand form a best practice?

Good question. It is (at least try) to maintain as much consistency as possible in the code base. Since by using [`Flex`](https://chakra-ui.com/docs/components/flex/usage#usage) you benefit from these shorthand props, we tend to use them to keep it more concise.

2022-09-29 16:38 UTC, Master7130 commented
@pettinarip The build is failing here but it's succeeding locally. Can you rerun the build check?

2022-09-29 20:38 UTC, pettinarip approved these changes
🚀

2022-09-29 20:39 UTC, merged