Migrate UpgradeBannerNotification.tsx to chakra
ethereum/ethereum-org-website pull request #8189
Opened 2022-10-06 07:01 UTC by Mahmadabid

## The component has been migrated to chakra UI.
## The emotion styled component has been removed from the file

2022-10-12 15:16 UTC, pettinarip requested changes
Thanks for the PR @Mahmadabid 💪🏼

2022-10-13 11:11 UTC, Mahmadabid commented on src/components/UpgradeBannerNotification.tsx
> +import Emoji from "src/components/Emoji"
Fixed import

2022-10-13 11:12 UTC, Mahmadabid commented on src/components/UpgradeBannerNotification.tsx
> +import { chakra, Center } from "@chakra-ui/react"
Import order is changed

2022-10-13 11:12 UTC, Mahmadabid commented on src/components/UpgradeBannerNotification.tsx
> +const StyledBannerNotification = chakra(BannerNotification)
Removed Chakra wrap from Chakra components

2022-10-13 11:12 UTC, Mahmadabid commented on src/components/UpgradeBannerNotification.tsx
> +const StyledEmoji = chakra(Emoji)
Removed Chakra wrap from Chakra components

2022-10-13 11:13 UTC, Mahmadabid commented on src/components/UpgradeBannerNotification.tsx
> +  <StyledBannerNotification display="flex" justifyContent="center" shouldShow>
Removed flex

2022-10-13 11:14 UTC, Mahmadabid commented on src/components/UpgradeBannerNotification.tsx
> +    <StyledEmoji text=":megaphone:"  alignSelf="center" mr="1rem" flexShrink="0"/>
Changed according to Chakra scale system

2022-10-25 12:59 UTC, pettinarip approved these changes
Thanks for the PR @Mahmadabid I've pushed a few tiny styles fixes. The rest looks great.

2022-10-25 14:24 UTC, merged

2022-10-25 14:24 UTC, pettinarip commented
@Mahmadabid be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

2022-10-25 14:24 UTC, pettinarip commented
@all-contributors please add @Mahmadabid for code