[UI] Stablecoin Box Grid: migrate component to chakra UI (Need help in centering cash emoji)
ethereum/ethereum-org-website pull request #8201
Opened 2022-10-07 14:45 UTC by shariqanwar20

## Description
The component has been migrated to chakra UI
The emotion styled component has been removed from the code

-  **Facing issue in centering Cash Emoji when screen size is decreased**

- Each emotion component is replaced with inline style attributes using chakra UI
- Media queries have been handled using breakpoints in chakra

### Before
![Screenshot (9)](https://user-images.githubusercontent.com/61353122/194579357-ec1ed0e5-3f30-4202-a0fa-725e016d1d19.png)
![Screenshot (10)](https://user-images.githubusercontent.com/61353122/194579700-35ce15c0-0c08-4977-b831-f1702499dac4.png)
![Screenshot (8)](https://user-images.githubusercontent.com/61353122/194579507-9b3679e5-9448-49da-b476-f20b66decc1e.png)

### After
![Screenshot (12)](https://user-images.githubusercontent.com/61353122/194580720-e7cc1328-d6e3-432c-b2ca-b090010c4083.png)
![Screenshot (11)](https://user-images.githubusercontent.com/61353122/194579924-fe698157-5676-4c0b-94d9-c30f53e90095.png)
![Screenshot (8)](https://user-images.githubusercontent.com/61353122/194579490-6665d2b3-b60d-443d-85d2-4353f2b9adfa.png)

## Related Issue

Refs: #6374

2022-10-23 04:15 UTC, TylerAPfledderer requested changes
Hey @shariqanwar20! Nice work! I had a chance to look through your PR and left some comments. 😃 

I think there are many spots where reusable child components should be recreated (Like what was originally labeled `Subtitle`, `Row`, `Column`, etc. to make sure the code is DRY. 😸

2022-10-23 04:15 UTC, TylerAPfledderer commented on src/components/StablecoinBoxGrid.tsx
> +                  <Text
Also should be a `Heading` with an `h4` similar to previous

2022-10-23 04:15 UTC, TylerAPfledderer commented on src/components/StablecoinBoxGrid.tsx
> +                  <Text
Also should be a `Heading` with an `h4` similar to previous

2022-10-23 04:15 UTC, TylerAPfledderer commented on src/components/StablecoinBoxGrid.tsx
> +              <Text
Also should be a `Heading` with an `h4` similar to previous

2022-10-23 04:15 UTC, TylerAPfledderer commented on src/components/StablecoinBoxGrid.tsx
> +      margin={0}
Should be `margin="4rem 0"` to have the vertical spacing around the container.

2022-10-24 14:25 UTC, pettinarip requested changes
Good job @shariqanwar20

2022-10-31 07:18 UTC, shariqanwar20 commented
@pettinarip @TylerAPfledderer Thanks for the feedback. I will start working on the changes right away

2022-10-31 15:19 UTC, pettinarip approved these changes
Thanks @shariqanwar20! I've pushed some minor fixes but overall this looks great.

Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

2022-10-31 16:36 UTC, merged

2022-10-31 16:37 UTC, pettinarip commented
@all-contributors please add @shariqanwar20 for code