accounts: remove example using deprecated namespace
ethereum/ethereum-org-website pull request #8395
Opened 2022-10-28 13:34 UTC by jmcook1186

## Description

The example on the accounts page uses Geth's `personal` namespace which is going to be deprecated very soon. Thi change swaps it out for a more future-proof alternative (although it might need updating again if more of geth's account tools get deprecated later on).

2022-10-28 16:30 UTC, ligi requested changes
Small nit - otherwise LGTM
not 100% happy with `example` also - but happier than with `code-snippet` (as it is not really code)

2022-10-28 16:30 UTC, ligi commented on src/content/developers/docs/accounts/index.md
> +The following code snippet shows how to use a signing tool called [Clef](https://geth.ethereum.org/docs/clef/introduction) to generate a new account. Clef is an account management and signing tool th
```suggestion
The following example shows how to use a signing tool called [Clef](https://geth.ethereum.org/docs/clef/introduction) to generate a new account. Clef is an account management and signing tool that comes bundled with the Ethereum client, [Geth](https://geth.ethereum.org). The `clef newaccount` command creates a new key pair and saves them in an encrypted keystore.
```

2022-10-28 20:06 UTC, wackerow approved these changes
💪

2022-10-30 14:05 UTC, jmcook1186 commented on src/content/developers/docs/accounts/index.md
> +WARN [10-28|16:19:09.306] Please backup your key file      path=/home/.ethereum/keystore/UTC--2022-10-28T15-19-08.000825927Z--5e97870f263700f46aa00d967821199b9bc5a120
```suggestion
WARN [10-28|16:19:09.306] Please backup your key file      path=/home/user/go-ethereum/data/keystore/UTC--2022-10-28T15-19-08.000825927Z--5e97870f263700f46aa00d967821199b9bc5a120
```

2022-11-03 15:31 UTC, corwintines approved these changes

2022-11-03 15:31 UTC, merged