fix: inconsistent page layout in docs [Fixes: #8364]
ethereum/ethereum-org-website pull request #8415
Opened 2022-10-31 06:12 UTC by amit-ksh

Added the `width` property to the `Content` component which allows the component to adjust according to screen width.

https://user-images.githubusercontent.com/91947037/198942663-941b57ec-aa93-4a24-aba2-ac8b51870814.mp4

## Related Issue
Fixes #8364

2023-02-16 22:55 UTC, corwintines requested changes
Hey @amit-ksh. 

Thanks for opening this. I noticed this doesn't quite fit the solution that @nloureiro proposed here: https://github.com/ethereum/ethereum-org-website/issues/8364#issuecomment-1316844297

Let me know if you have any questions :)

2023-02-17 10:33 UTC, amit-ksh commented
Hey @corwintines! can you please check this issue also #8373, it might be related

2023-02-17 11:47 UTC, nloureiro commented
As far as I could check, this is aligned with the Design system.
I made some comments in the code, but my big question is more about having hardcoded values in the component. Should we have this in a variable? might need to be re-used in other situation in the future and should not be inside a component

2023-06-13 20:10 UTC, corwintines commented
@amit-ksh if you have a moment, could you resolve the conflicts here?

2023-06-14 16:34 UTC, amit-ksh commented
Hey @corwintines, I try to fix the merge conflict, could please check if I did it correctly or not, first I'm doing this.

2023-09-21 21:32 UTC, wackerow commented on docs/ds-implementation.md
> +└── // Any other files as applicable (utils, child components, useHook, etc.)
```suggestion
    └── ComponentA/
        ├── index.tsx
        ├── ComponentA.stories.tsx
        └── // Any other files as applicable (utils, child components, useHook, etc.)
```

2023-09-21 21:35 UTC, wackerow reviewed
@amit-ksh sorry for delays! Circled back and was taking a look here... I merged in `dev` and cleared the conflicts...

@nloureiro, if you get a moment take a peak here and let us know if this is still needed...  if so, and if it builds properly, I think we can pull this in.

2023-09-22 09:42 UTC, nloureiro commented
I have been reviewing this. Can I propose 2 small changes?

1 . The table of contents still bounces left/right depending on the content. It needs to justify to left on the flex
2. The content is, in fact, 768px but includes the padding. My goal is to have a max-width for the text lines itself. on the dev tools, I simulate something like `max-width: calc( 48rem + var(--eth-space-16) + var(--eth-space-16));` but not sure how the code is set up to solve this in a good way.

I made some notes on these screenshots to help illustrate these 2 points.
![Screen Shot 2023-09-22 10 33 19 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/8211d3c4-ded8-46f5-8910-a8746b86d9b9)

![Screen Shot 2023-09-22 10 33 27 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/871dba9d-ea3b-46af-abde-c4c3ae074b25)


@amit-ksh If I'm not clear on any of these please reach out, Thank you for your help :)

2023-09-22 13:43 UTC, amit-ksh commented
@nloureiro @wackerow my university exams are about to start, so, I will watch this after 5th October

2023-10-14 07:25 UTC, amit-ksh commented
Hey @nloureiro, here's my solution for the changes you requested: 

1. I believe the `TableOfContent` is not bouncing but the width values are different. It is happening because the width can vary from 12rem(min-width) to 16rem(max-width). If the width of **TableOfContent** should be the same for all the pages then, we can do that by setting the width to some fixed value. 
2. And for setting the max-width just for the content we can use this `box-sizing: content-box`. This will not include the padding and applies the width size to content only.

2024-03-22 15:28 UTC, wackerow commented
Hey @amit-ksh, appreciate the efforts here!... recently have merged a fix for this in #12460 so going to close this out. Apologies we weren't able to get this in 🙏

2024-03-22 15:28 UTC, closed without merging