Refactor `SkipLink.tsx` component to use ChakraUI
ethereum/ethereum-org-website pull request #8602
Opened 2022-11-16 08:44 UTC by MahendraBishnoi29

## Description
Refactored `SkipLink.tsx` component with Chakra UI

## Related Issue
#6374

2022-11-23 20:38 UTC, pettinarip requested changes
Looking good @MahendraBishnoi29 I've just added some minor requests.

2022-11-23 20:38 UTC, pettinarip commented on src/components/SkipLink.tsx
> +        ml=".5rem"
```suggestion
        ml="2"
```

2022-11-23 20:38 UTC, pettinarip commented on src/components/SkipLink.tsx
> +        lineHeight="2rem"
https://chakra-ui.com/docs/styled-system/theme#typography
```suggestion
        lineHeight="taller"
```

2022-11-23 20:38 UTC, pettinarip commented on src/components/SkipLink.tsx
> +import { Box, Link } from "@chakra-ui/react"
Let use the custom `Link` component from `src/components/Link`

2022-11-23 20:38 UTC, pettinarip commented on src/components/SkipLink.tsx
> +        top="-3rem"
```suggestion
        top="-12"
```

2022-11-26 09:21 UTC, MahendraBishnoi29 commented
@pettinarip is everything ok now?

2022-11-28 17:24 UTC, pettinarip approved these changes
lgtm! thanks @MahendraBishnoi29 💪🏼

2022-11-28 17:24 UTC, merged