Refactor: Migrate `StakingProductsCardGrid` to Chakra
ethereum/ethereum-org-website pull request #8679
Opened 2022-11-20 06:30 UTC by TylerAPfledderer

## Description
Migrate the `StakingProductsCardGrid` component to Chakra UI

>Side Note: This PR also fixes broken styling present in the current production.

## Related Issue
#8632

2022-11-21 15:26 UTC, pettinarip requested changes
This looks great @TylerAPfledderer! left a comment.

2022-11-22 01:20 UTC, TylerAPfledderer commented on src/components/Staking/StakingProductsCardGrid.tsx
> +        <Heading fontSize="2xl" color="white" fontWeight="normal">
Got it. Agreed, I can see a possible quick alteration with the grid to overcome this text wrapping, but it's definitely better with it's own PR and design team input.

2022-11-22 01:25 UTC, TylerAPfledderer commented on src/components/Staking/StakingProductsCardGrid.tsx
> +        <Heading fontSize="2xl" color="white" fontWeight="normal">
Change of font weight was not intended to fix the header height. I removed the `fontWeight` prop.

2022-11-22 14:45 UTC, pettinarip approved these changes
LGTM! thanks @TylerAPfledderer

2022-11-22 14:46 UTC, merged