Refactor: Migrate `StakingHierarchy` to Chakra
ethereum/ethereum-org-website pull request #8686
Opened 2022-11-21 04:02 UTC by TylerAPfledderer

## Description

Migrate the `StakingHierarchy` component to Chakra.

Also includes updating the glyph icons to have `currentColor` as their fill values.

## Related Issue
#8632

2022-11-28 21:10 UTC, pettinarip requested changes
Looking good @TylerAPfledderer 

Just a few things I see comparing it with the prod version:

- small gap between sections
![image](https://user-images.githubusercontent.com/468158/204381462-ca9d410d-3a9d-465a-8daf-02c498030bfe.png)

- eth icons are too small on small resolutions
![image](https://user-images.githubusercontent.com/468158/204381563-59ffb6cf-0ba9-4bfd-9a94-78e6c0641e89.png)

This is in prod:
![image](https://user-images.githubusercontent.com/468158/204381648-9650269f-3d4d-4591-bce1-2e516762622e.png)

2022-12-01 15:30 UTC, TylerAPfledderer commented
@pettinarip yikes! We have browser inconsistencies here. I definitely see this in Chrome, but the styling works as expected in Firefox.

2022-12-02 17:44 UTC, pettinarip reviewed
Thanks for the fixes @TylerAPfledderer.

I wouldn't say this is a blocker but I still see a small gap between the line and the eth logos. Probably it is related to the `VStack` but I see you set it as `gap={0}` in the `md` breakpoint, so I'm not sure what is going on.

![image](https://user-images.githubusercontent.com/468158/205353314-e3cf028b-6f53-4b2b-88f5-4df514165d7e.png)

2022-12-02 18:02 UTC, TylerAPfledderer commented on src/components/Staking/StakingHierarchy.tsx
> -  .gold {
I will add it back in and add a comment above it stating that markdown files use this classname

2022-12-02 18:06 UTC, Fqc301033 approved these changes

2022-12-02 21:45 UTC, TylerAPfledderer commented
> Thanks for the fixes @TylerAPfledderer.
> 
> I wouldn't say this is a blocker but I still see a small gap between the line and the eth logos. Probably it is related to the `VStack` but I see you set it as `gap={0}` in the `md` breakpoint, so I'm not sure what is going on.
> 
> ![image](https://user-images.githubusercontent.com/468158/205353314-e3cf028b-6f53-4b2b-88f5-4df514165d7e.png)

With `VStack` I am supposed to use the `spacing` prop and not the `gap` prop (renders the "owl" selector to create margins). So even with `gap` margin still existed. 🤦🏼 

For context and example, if `spacing={2}`, then the following selector and property gets rendered for every sibling after the first:
```css
.css-tnhm38 > :not(style) ~ :not(style) {
  margin-top: 0.5rem;
}
```

`gap` would only really work if you were using the `Flex` component, say, or any component that doesn't do the above selector rendering under the hood.

2022-12-02 21:47 UTC, TylerAPfledderer commented
@pettinarip should be good to go now! 😄

2022-12-05 21:53 UTC, pettinarip commented
Oh got it. makes sense now :)

2022-12-05 21:54 UTC, pettinarip approved these changes
lgtm!

2022-12-05 21:54 UTC, merged