Edit text
ethereum/ethereum-org-website pull request #8732
Opened 2022-11-24 14:24 UTC by TimDaub

- superseeds #8727

I edited the text to make it more readable. I didn't make any changes to the actual content, just copyediting.

2022-11-28 13:38 UTC, minimalsm commented
Thanks for the PR @TimDaub 👍 

@jmcook1186 any chance you could a look at this when you've got some time. no rush :)

2022-11-28 14:00 UTC, jmcook1186 commented on src/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md
> +But radix tries have one major limitation: they are inefficient. If you want to store one `(path, value)` binding where the path, like in Ethereum, is 64 characters long (the number of nibbles in `by
```suggestion
Radix tries have one major limitation: they are inefficient. If you want to store one `(path, value)` binding where the path, like in Ethereum, is 64 characters long (the number of nibbles in `bytes32`), we will need over a kilobyte of extra space to store one level per character, and each lookup or delete will take the full 64 steps. The Patricia trie introduced in the following solves this issue.
```

2022-11-28 14:04 UTC, jmcook1186 requested changes
Thanks - this page needed refining - just one tiny suggestion, but otherwise approve.

2023-01-16 22:56 UTC, corwintines commented on src/content/developers/docs/data-structures-and-encoding/patricia-merkle-trie/index.md
> +We'll refer to an atomic unit of a radix tree (e.g. a single hex character, or 4 bit binary number) as a "nibble".  While traversing a path one nibble at a time, as described above, nodes can maximal
```suggestion
We'll refer to an atomic unit of a radix tree (e.g. a single hex character, or 4 bit binary number) as a "nibble".  While traversing a path one nibble at a time, as described above, nodes can maximally refer to 16 children but include a `value` element. We, hence, represent them as array with length. We call these 17-element arrays "branch nodes".
```

2023-01-16 22:57 UTC, corwintines approved these changes
Thanks @TimDaub!

2023-01-16 22:58 UTC, merged