Refactor/migrate bug bounty cards to chakra UI [Relates to #6374]
ethereum/ethereum-org-website pull request #8739
Opened 2022-11-25 19:12 UTC by Marcelixoo

## Description

This PR implements the BugBountyCards component using ChakraUI.

Below you can find screenshots of the component rendered before/after the changes side-by-side and in different states.

### Dark mode: Large screens
1. Current versions
![Screenshot 2022-11-25 at 19 58 01](https://user-images.githubusercontent.com/29285152/204043029-e72ba158-ed3e-43a7-b8f6-c154e16152a5.png)
ion

2. After changes
![Screenshot 2022-11-25 at 19 58 07](https://user-images.githubusercontent.com/29285152/204043045-e1cff6f2-d27a-4b8e-b6d8-88ceddcf72e7.png)

### Light mode: Large screens
1. Current version
![Screenshot 2022-11-25 at 19 58 28](https://user-images.githubusercontent.com/29285152/204043060-9b23bccc-b23b-440d-b5cc-10f2c4b48f37.png)

2. After changes
![Screenshot 2022-11-25 at 19 58 19](https://user-images.githubusercontent.com/29285152/204043071-e8164dba-4bae-4958-a876-96381263b959.png)

### Light mode: Medium screens
1. Current version
![Screenshot 2022-11-25 at 19 58 45](https://user-images.githubusercontent.com/29285152/204043201-a8bcdf43-078a-4271-a6ba-b7fc2ff3658b.png)

2. After changes
![Screenshot 2022-11-25 at 19 58 50](https://user-images.githubusercontent.com/29285152/204043208-a9238fb3-55a3-4edc-a898-2c588af21504.png)

### Light mode: Small screens
1. Current version
![Screenshot 2022-11-25 at 19 59 06](https://user-images.githubusercontent.com/29285152/204043216-de260402-ec64-412e-b492-f9ac3983465b.png)

2. After changes
![Screenshot 2022-11-25 at 19 59 14](https://user-images.githubusercontent.com/29285152/204043224-8f4d7553-10f2-41de-b8c7-3ad32296b69f.png)

## Related Issue
#6374

2022-11-26 14:27 UTC, Marcelixoo commented
FYI, I've checked the deployment preview and it looks pretty solid there as well 👍🏼

2022-12-05 23:14 UTC, pettinarip requested changes
Looks great overall, nice job @Marcelixoo. I've left a few minor comments.

2022-12-05 23:14 UTC, pettinarip commented on src/components/BugBountyCards.tsx
> +        "box-shadow": "var(--eth-shadows-tableBoxHover)",
```suggestion
        boxShadow: "tableBoxHover",
```

2022-12-16 22:06 UTC, Marcelixoo commented on src/components/BugBountyCards.tsx
> +      boxShadow="var(--eth-colors-tableBoxShadow)"
Thanks, @pettinarip! I think I've addressed all comments on this thread.

Could you give it a second look?

2022-12-22 19:21 UTC, pettinarip approved these changes
Nicee! @Marcelixoo thanks. LGTM 🚀

2022-12-22 19:22 UTC, pettinarip commented
Be sure to [join the discord](https://discord.gg/CetY6Y4) if you are interested in contributing further to the project or have any questions for the team. And we've just released our 2022 POAPs so remember to [claim yours](https://ethereum.org/en/contributing/#poap) also 🥳!

2022-12-22 19:22 UTC, merged

2022-12-22 19:22 UTC, pettinarip commented
@all-contributors please add @Marcelixoo for code