added support for svg download from assets [Fixes #8026]
ethereum/ethereum-org-website pull request #8891
Opened 2022-12-14 22:01 UTC by kaspi90

## Description

## Related Issue

2022-12-20 20:10 UTC, Inatiye33 approved these changes

2023-01-18 14:24 UTC, pettinarip requested changes
Thanks for the PR @kaspi90 

This svg doesn't have a download button. Wondering if we need to add it there as well.
cc @konopkja 
![image](https://user-images.githubusercontent.com/468158/213195092-de6bbd8a-1b23-4609-a834-bf601e9e059f.png)

When I downloaded the "ETH diamond (glyph)" and the "ETH diamond (color)" svgs, I got this error when I tried to open them on the browser:
![image](https://user-images.githubusercontent.com/468158/213195572-31010c04-301e-4453-a75f-6e9d010a8803.png)
Looking at the svg code it seems that we are injecting an `<image id="_Image1" width="64">` tag inside it. I think that is not what we want. We should have `<path>`s instead.

2023-01-18 14:24 UTC, pettinarip commented on src/components/AssetDownload.tsx
> +import theme from "../@chakra-ui/gatsby-plugin/theme"
Some of these imports aren't used. Lets remove them.

And external lib imports should be imported at the top of the file (along with the react, react-dom import).

2023-01-18 14:24 UTC, pettinarip commented on src/components/AssetDownload.tsx
> +    const index = svgRendered.indexOf("<svg ") + 5
Curious to understand why we need that extra `5` in this index.

2023-01-18 14:45 UTC, konopkja commented
> 

i think merge related artwork was supposed to be temporary? what do you think @nloureiro

2023-02-13 19:51 UTC, corwintines commented
2 things to follow up with from grooming:
- We will move the merge images into the historical section of this page
- Instead of png and svg each having their own image, we will instead just show 1 image and have a button for each image type

2023-05-13 15:10 UTC, pettinarip commented
@konopkja this is ready for review. [Preview](https://ethereumorgwebsitedev01-kaspi90ethereumorgwebsitesvgas.gatsbyjs.io/en/assets/)

2023-05-15 11:46 UTC, konopkja commented
@pettinarip  buttons look good

Question: can we make something about the preview picture sizes? :D 

<img width="1497" alt="Screenshot 2023-05-15 at 20 44 49" src="https://github.com/ethereum/ethereum-org-website/assets/100724231/f7a92b8e-4e20-4b26-b31c-5624d83e6f53">

2023-05-15 18:06 UTC, nhsz commented
> Preview

checking previous comments, should merge images move to the historial section? @pettinarip @corwintines

2023-05-15 18:06 UTC, nhsz commented
> 2 things to follow up with from grooming:
> 
> * We will move the merge images into the historical section of this page
> * Instead of png and svg each having their own image, we will instead just show 1 image and have a button for each image type

checking previous comments, should merge images move to the historial section? @pettinarip @corwintines

2023-05-16 21:26 UTC, pettinarip commented
Goood point @nhsz. I'll refresh my mind with those requirements and will get back to you.

2023-05-16 21:56 UTC, pettinarip commented
Done @konopkja @nhsz. I've moved the panda images under the historical images section.

2023-05-30 19:00 UTC, corwintines approved these changes

2023-05-30 19:00 UTC, merged