migrate `TranslationBannerLegal` to Chakra
ethereum/ethereum-org-website pull request #8962
Opened 2022-12-21 07:22 UTC by amit-ksh

## Description

Migrate the `TranslationBannerLegal` component from emotion to Chakra.

### Can you check the hover style of the `Don't Show Again` button, it differs from the original one.

### Original Style vs Current Style
![hover Style](https://user-images.githubusercontent.com/91947037/208843280-3f3b4780-efca-41e5-a933-9f2c14f23b2a.png)

## Related Issue

#8632

2022-12-23 17:51 UTC, pettinarip requested changes
@amit-ksh thanks man, this is looking great. I left a couple of small change requests.

2022-12-23 17:51 UTC, pettinarip commented on src/components/TranslationBannerLegal.tsx
> +              }}
You can remove these styles. The default Button is going to render the `solid` variant with the correct color scheme. You can see the details [here](https://github.com/ethereum/ethereum-org-website/blob/dev/src/%40chakra-ui/gatsby-plugin/components/Button.ts).

```suggestion
            <Button
```

2022-12-23 17:51 UTC, pettinarip commented on src/components/TranslationBannerLegal.tsx
> +} from "@chakra-ui/react"
import order. Can you put this import on the top of the file? below the react import

2022-12-23 17:51 UTC, pettinarip commented on src/components/TranslationBannerLegal.tsx
> +        borderRadius="2px"
```suggestion
        borderRadius="sm"
```

2022-12-23 17:51 UTC, pettinarip commented on src/components/TranslationBannerLegal.tsx
> +          base: `-4px 10px 0px ${text} 10%`,
nice 👍🏼

2022-12-24 09:05 UTC, amit-ksh commented on src/components/TranslationBannerLegal.tsx
> +          base: `-4px 10px 0px ${text} 10%`,
Thanks!

2023-01-05 19:34 UTC, merged