Feat/convert translation leaderboard to chakra
ethereum/ethereum-org-website pull request #9058
Opened 2023-01-04 21:25 UTC by vdusart

## Description

Convert `TranslationLeaderboard.tsx` file to Chakra

## Related Issue
Close: #8640
Epic: #8632

2023-01-17 23:18 UTC, pettinarip requested changes
Great job @vdusart. I've tested it and the component is working fine.

I've left a few small issues and an idea to refactor the buttons we are showing that I think are worth implementing.

2023-01-17 23:18 UTC, pettinarip commented on src/components/TranslationLeaderboard.tsx
> +          mb="px"
```suggestion
          mb="1px"
```

2023-01-17 23:18 UTC, pettinarip commented on src/components/TranslationLeaderboard.tsx
> +                mb="px"
```suggestion
                mb="1px"
```

2023-01-17 23:18 UTC, pettinarip commented on src/components/TranslationLeaderboard.tsx
> +        >
This should be a button. I know it was not a button before but I think we should fix this. I'd understand if you don't want to do that on this PR. I could create a new issue to tackle that refactor, up to you. LMK what do you think.

2023-01-17 23:18 UTC, pettinarip commented on src/components/TranslationLeaderboard.tsx
> +        >
And we could share these styles with the ones we are using on the `RadioCard`.

I have in mind this:
```tsx
const Button = (props) => {
  return (
    <ChakraButton
      borderRadius="2rem"
      borderWidth="1px"
      borderStyle="solid"
      borderColor="text"
      ...
      ...props
    />
  )
}

// on the RadioCard component
const RadioCard = () => {
  ...
  
  return (
    <Button
      as="label"
      {...checkbox}
      ...
  )
}
```

2023-01-18 18:55 UTC, vdusart commented
Ok @pettinarip,
I just implemented the changes you proposed, tell me what you think about it :smile:

2023-01-25 13:38 UTC, pettinarip approved these changes
Thanks @vdusart lgtm!

2023-01-25 13:39 UTC, merged