Convert Asset Icons to Chakra UI
ethereum/ethereum-org-website pull request #9093
Opened 2023-01-06 17:49 UTC by TylerAPfledderer

## Description

## Related Issue
Closes #9048

2023-01-08 03:12 UTC, hoanglamcoin approved these changes

2023-01-12 12:06 UTC, nloureiro commented
@TylerAPfledderer can you help me understand a little more this?

Do you want to port all the SVG icons to the chakra icon component?
https://chakra-ui.com/docs/components/icon

I'm asking because, in the Design system plan, we aim to build a new ethereum.org icon family somewhere in the future. Something open source and web3 packed.

Would this issue be the beginning?

2023-01-12 15:12 UTC, peetzweg commented
Uff that was probably a lot of work 👍 

IMHO I think it a bit weird copying the svg code into the tsx files. Isn't the bundler able to import svg files directly and just pass this as the `path` prop for `createIcon()`?

Feels hard to maintain in the future if the actual SVG is hardcoded in a tsx file. No vector tool can open `.tsx` files to edit it.

Furthermore the svg code could maybe use some optimization with something like [scour](https://github.com/scour-project/scour) to reduce precision to save on file size.

2023-01-14 02:33 UTC, TylerAPfledderer commented
@nloureiro 
> Do you want to port all the SVG icons to the chakra icon component?
https://chakra-ui.com/docs/components/icon

That is the intention here. 

This proposed change did not take into account a new set of SVGs with the intended purpose you describe. I was not aware of that goal, and would like to know more about what you mean in the new collection being web3 packed. 😄 

---

@peetzweg
> IMHO I think it a bit weird copying the svg code into the tsx files. Isn't the bundler able to import svg files directly and just pass this as the path prop for createIcon()?

The `path` prop is meant for the internal elements of the svg, as by default it creates the svg element. So importing the SVG to the function that way would render a nested svg

The `createIcon()` function makes the svg directly supercharged with Chakra, so you can supply Chakra style props and theming on it. This also eliminates the need to use a parent element in some cases to style it via descendant selecting, say.

Indeed, you can instead pass the svg file to Chakra's `Icon` component via the `as` prop and be able to style that way. `createIcon` could give you a little more control in how you can alter the styling of the internals. 

I would use `Icon` to handle third-party icons, and `createIcon()` for internal icons.

As far as management, I come from a standpoint of not having designed SVGs. I would think that the process here would be to create the svgs, send them to an app like SVGOmg to optimize the code, transfer the code setup to `createIcon()`, test in the environment (like with Storybook since that is going to used going forward), and if there is any issue revisit the SVG file rinse and repeat as needed!

The expectation then is that the original svg assets are saved if changes need to be addressed in the design. Though I am open to understanding if this would not be an expected or desirable process; I'm all for getting a better idea of the workflow! 😃 🤘🏼

2023-01-16 11:27 UTC, nloureiro commented
> 

@TylerAPfledderer this goal is more a collateral of the Design system.

Having an open-source design system allows us to give others the ability to work on top of our work.

The icons are the best example of a small part of the design system that can be used separably, and with that in mind, I have been building the idea of creating an ethereum.org icon family.

It would be based on the design style we use on ethereum.org and can be updated and transformed by the community for their own projects.

On top of the normal icons, we could have more web3 icons that most icon families don't have, like the ones I did for the find my wallet page.

![Screen Shot 2023-01-16 09 56 59 AM](https://user-images.githubusercontent.com/1120748/212667520-c31e0474-1e8f-4832-8d47-9ff3844b90a9.png)

Does it help? In the way that you are thinking of converting the SVG to an icon?

2023-01-19 01:10 UTC, TylerAPfledderer commented
@nloureiro thank you for elaborating!

In that case, the new library you looking to building should be treated like 3rd-party icons and use the `Icon` component instead with the `as` prop.
```tsx
<Icon as={SomeIcon} {...stylePropsHere} />
``` 
> We can still use the Chakra theme config to handle any base styles if need be!

This way -- barring other usage that would prevent you from doing this -- the SVGs might need to be optimized so there is no need to drill down to the internal elements via a descendant selector to alter colors, unless there is an edge case or if an SVG might have some small animations going on. (I've only seen one or two instances where this was occurring so maybe this a non-issue 😄 )

2023-01-19 11:03 UTC, nloureiro commented
> @nloureiro thank you for elaborating!
> 
> In that case, the new library you looking to building should be treated like 3rd-party icons and use the `Icon` component instead with the `as` prop.
> 
> ```tsx
> <Icon as={SomeIcon} {...stylePropsHere} />
> ```
> 
>  > We can still use the Chakra theme config to handle any base styles if need be!
> 
> This way -- barring other usage that would prevent you from doing this -- the SVGs might need to be optimized so there is no need to drill down to the internal elements via a descendant selector to alter colors, unless there is an edge case or if an SVG might have some small animations going on. (I've only seen one or two instances where this was occurring so maybe this a non-issue 😄 )


Ok, got it. Makes sense to use it as a 3rd party 'icon'

Question: having this in mind, does it make sense to keep this issue open? Should we start the new icons collection with this svg's? or am I seeing wrong and we will add this later when implementing the Design system

2023-01-20 17:34 UTC, TylerAPfledderer commented
I have no objection to closing this PR and the respective issue.

I'd like to know what @pettinarip thinks about next steps here. 😁

2023-01-24 15:14 UTC, pettinarip requested changes
Thanks a lot for the time and effort you have put on this @TylerAPfledderer 

I've only found a small issue on the staking page.

======

@nloureiro and I talked about this yesterday and we've decided to include these changes since they will be part of the transition over to the icons font in the near future.

Once we have the font, we'll start deprecating these icons and removing them. In the meanwhile, we can benefit from these newly wrapped icons :)

> Should the naming of these new files not include Glyph?

As we are going to remove these icons at some point, I wouldn't mind doing that at this moment. I think its fine for now.

2023-01-24 17:52 UTC, TylerAPfledderer commented on src/components/icons/staking/StakingGlyphCloudIcon.tsx
> +})
This is coming from the `StakingHeirarchy` component and it's child component `Glyph` where the `md` was setting`boxSize` to `initial` which overrides the original width/height set from the icons themselves. Had to explicitly set the value to `50px` here.

2023-01-24 17:52 UTC, TylerAPfledderer commented
@pettinarip we should be good here! A couple of merge conflicts that were resolved. (Still had some trouble handling them properly!)

I'll leave alone the file names with `Glyph`.

2023-01-24 22:08 UTC, pettinarip approved these changes
Niceee 🚀

2023-01-25 20:58 UTC, wackerow approved these changes
Phew, that's a lot of SVGs, nice work @TylerAPfledderer!

I do think I would be nice to remove some of the redundant naming like "glyph" and "icon", and maybe placing those items into a folder labeled as such instead (ie /glyphs/Decentralization). But, rather than complicating this PR further I would suggest we address that separately if we want to do that. This looks good to go from my perspective.

Will just make note that for the /assets page, any SVG's we want to host we'll need to have a publicly available static `.svg` file for folks to download since these won't be available.

2023-01-25 23:45 UTC, pettinarip commented
> Will just make note that for the /assets page, any SVG's we want to host we'll need to have a publicly available static .svg file for folks to download since these won't be available.

Agreed. Just to let you know, the svgs that lives under `src/assets/assets` are still in there, those were not deleted or modified. Those svgs are the ones being consumed in the `/assets` page. This is related to this PR #8891 where we are adding new svgs to be downloaded.

2023-01-30 19:39 UTC, corwintines approved these changes
Nice one @TylerAPfledderer. I just merged dev to fix some conflicts, but this is good to go 🎉

2023-01-30 19:39 UTC, merged