Migrate the `BoxGrid` component to Chakra
ethereum/ethereum-org-website pull request #9094
Opened 2023-01-06 18:12 UTC by soheil555

## Description

Migrate the `BoxGrid` component to Chakra

## Related Issue
#8632

2023-01-08 01:02 UTC, TylerAPfledderer requested changes
Hey @soheil555! Nice work here. 🤘🏼 

For you and @pettinarip, I've provided some thoughts with using `SimpleGrid` to keep from flipping between grid and flexbox, along with tricks to simplify the code. Wondering from both of you if these suggested changes improve readability. 😄

2023-01-08 12:47 UTC, soheil555 commented
Hey @TylerAPfledderer 
Awesome suggestions!
Thank you so much.

2023-01-18 12:44 UTC, pettinarip commented on src/components/BoxGrid.tsx
> +    >
This totally simplifies the component overall. Nice suggestion!

2023-01-18 12:47 UTC, pettinarip requested changes
Thanks @soheil555, the component is working perfectly for me 💯 

Would like to see the `SimpleGrid` implementation here if that is possible.

Thanks @TylerAPfledderer for the suggestions and review 💪🏼

2023-01-18 18:28 UTC, pettinarip approved these changes
🚢

2023-01-18 18:28 UTC, merged