developers/networks: update current network plans
ethereum/ethereum-org-website pull request #9191
Opened 2023-01-16 13:22 UTC by q9f

removed kovan and ropsten

deprecated goerli

emphasized sepolia

2023-01-19 17:39 UTC, Pandapip1 requested changes

2023-01-19 17:39 UTC, Pandapip1 commented on src/content/developers/docs/networks/index.md
> +The two public testnets which client developers are maintaining post-merge are Goerli and Sepolia. The Goerli network is targeting protocol developers to test network upgrades and stakers to test run
How about swapping the order?
```suggestion
The two public testnets that client developers are currently maintaining are Sepolia and Goerli. Sepolia is a network for contract and application developers to test their applications. The Goerli network lets protocol developers test network upgrades, and lets stakers test running validators.
```

2023-01-19 17:39 UTC, Pandapip1 commented on src/content/developers/docs/networks/index.md
> +**Faucets**:
```suggestion
##### Faucets
```
Using bold for headings is an antipattern

2023-01-19 17:39 UTC, Pandapip1 commented on src/content/developers/docs/networks/index.md
> +**Resources**:
```suggestion
##### Resources
```
Using bold for headings is an antipattern

2023-01-19 17:39 UTC, Pandapip1 commented on src/content/developers/docs/networks/index.md
> +**Resources**:
```suggestion
##### Resources
```
Using bold for headings is an antipattern

2023-01-19 17:39 UTC, Pandapip1 commented on src/content/developers/docs/networks/index.md
> +**Faucets**:
```suggestion
##### Faucets
```
Using bold for headings is an antipattern

2023-01-19 17:39 UTC, Pandapip1 commented on src/content/developers/docs/networks/index.md
> +**Faucets**:
```suggestion
##### Faucets
```
Using bold for headings is an antipattern

2023-01-19 17:39 UTC, Pandapip1 commented on src/content/developers/docs/networks/index.md
> +**Faucets**:
```suggestion
##### Faucets
```
Using bold for headings is an antipattern

2023-01-19 17:39 UTC, Pandapip1 commented on src/content/developers/docs/networks/index.md
> +**Faucets**:
```suggestion
##### Faucets
```
Using bold for headings is an antipattern

2023-01-21 01:43 UTC, Pandapip1 approved these changes
LGTM.

2023-02-02 22:58 UTC, corwintines commented on src/content/developers/docs/networks/index.md
> +Most testnets started by using a permissioned proof-of-authority consensus mechanism. This means a small number of nodes are chosen to validate transactions and create new blocks – staking their iden
```suggestion
Most testnets started by using a permissioned proof-of-authority consensus mechanism. This means a small number of nodes are chosen to validate transactions and create new blocks – staking their identity in the process. Alternatively, some testnets feature an open proof-of-stake consensus mechanism where everyone can test running a validator, just like Ethereum Mainnet.
```

2023-02-02 23:20 UTC, corwintines approved these changes
Thanks for these updates @q9f!

2023-02-02 23:20 UTC, merged