Migrate `ShardChainsList.tsx` to Chakra
ethereum/ethereum-org-website pull request #9238
Opened 2023-01-19 04:15 UTC by MahendraBishnoi29

## Description
Migrate `ShardChainsList.tsx` to Chakra

## Related Issue
#8632

2023-01-20 04:12 UTC, TylerAPfledderer requested changes
Hi @MahendraBishnoi29! Tiny changes here, then it should be good!

2023-01-20 04:12 UTC, TylerAPfledderer commented on src/components/ShardChainsList.tsx
> +    <Box as="div" mb="4rem">
Same as the `MergeArticleList` migration PR, `Box` renders `div` by default.
```suggestion
    <Box mb="4rem">
```

2023-01-20 04:12 UTC, TylerAPfledderer commented on src/components/ShardChainsList.tsx
> +import { Box } from "@chakra-ui/react"
Import order

2023-01-20 06:07 UTC, MahendraBishnoi29 commented
> Hi @MahendraBishnoi29! Tiny changes here, then it should be good!

thank you for fixing my small mistakes @TylerAPfledderer 🚀

2023-01-25 13:54 UTC, pettinarip approved these changes
🚀 🚀 🚀 🚀

2023-01-25 13:54 UTC, merged