fix the translate page button not showing the text
ethereum/ethereum-org-website pull request #9315
Opened 2023-01-26 13:45 UTC by MrJithil

## Description

## Related Issue

2023-01-27 13:26 UTC, pettinarip requested changes
I think this issue is an issue from the `ButtonLink` component. The `ButtonLink` component is a Link but is styled as a Button. Having said that, a Button styled component should not have an `active` style or state.

So, I think the correct way to fix this problem is to override the `activeStyles` from the `ButtonLink` component, making all the `ButtonLink`s the same.

LMK what do you think.

@corwintines this is related to the problem we saw on the guides PR.

2023-01-28 00:49 UTC, MrJithil commented
> I think this issue is an issue from the `ButtonLink` component. The `ButtonLink` component is a Link but is styled as a Button. Having said that, a Button styled component should not have an `active` style or state.
> 
> So, I think the correct way to fix this problem is to override the `activeStyles` from the `ButtonLink` component, making all the `ButtonLink`s the same.
> 
> LMK what do you think.
> 
> @corwintines this is related to the problem we saw on the guides PR.

There are many instance of `ButtonLink` all are working well. So, removing the `activeStyle` from the `Link` may introduce many changes. To test and ensure all these instance is hard task.

2023-01-30 20:23 UTC, corwintines commented
Thanks so much @MrJithil!

2023-01-30 20:24 UTC, corwintines commented
@all-contributors can you add @MrJithil for code

2023-01-30 20:27 UTC, merged