migrate assets to chakra UI
ethereum/ethereum-org-website pull request #9406
Opened 2023-02-06 02:48 UTC by MrJithil

Migrating the assets to Chakra UI
## Description
There are some margin difference of Hero Container. I am not sure, whether we need to customise it each page, or we are following the new Chakra design. Please comment after checking the PR website deployment. 

## Related Issue
#9353

2023-02-15 23:10 UTC, pettinarip requested changes
Thanks for the PR @MrJithil 💪🏼 

> There are some margin difference of Hero Container. I am not sure, whether we need to customise it each page, or we are following the new Chakra design. Please comment after checking the PR website deployment.

What we try to achieve at this stage is to just migrate the existing emotion components to Chakra components, keeping the same styles we had. So, in theory, we should see the exact same page we currently have in production (same styles).

Later, when we implement our new Design System, our plan is to consolidate a lot of these repeated components that we have across different layouts/pages.

2023-02-15 23:10 UTC, pettinarip commented on src/pages/assets.tsx
> +    <Flex direction={"column"} width="full">
To follow conventions, lets not wrap the value if it is a string literal (this applies also to the rest of the changes).
```suggestion
    <Flex direction="column" width="full">
```

2023-02-15 23:10 UTC, pettinarip commented on src/pages/assets.tsx
> +      <Box padding={"1rem 2rem"}>
To follow conventions, lets use as much as we can, chakra values. You can see them [here](https://chakra-ui.com/docs/styled-system/theme#spacing).
```suggestion
      <Box py={4} px={8}>
```

2023-02-15 23:10 UTC, pettinarip commented on src/pages/assets.tsx
> +        <Flex direction={"column"} margin="2rem 0rem">
```suggestion
        <Flex direction="column" my={8}>
```

2023-02-15 23:10 UTC, pettinarip commented on src/pages/assets.tsx
> +              as={GatsbyImage}
```suggestion
              as={GatsbyImage}
              image={getImage(assetPageHeroImage)!}
```

2023-02-15 23:10 UTC, pettinarip commented on src/pages/assets.tsx
> +          <Flex>
`Row` has more styles that are missing here for mobile responsiveness.

2023-03-01 19:12 UTC, pettinarip approved these changes
Thanks @MrJithil 

I've unified the `Row` components and add some missing styles on the headings.

2023-03-07 15:59 UTC, merged

2023-04-19 05:51 UTC, JithilNCA commented
Thank You.