Fix ETH.STORE URL
ethereum/ethereum-org-website pull request #9457
Opened 2023-02-09 16:20 UTC by Buttaa

We just added ETHSTORE to beaconcha.in. This PR forwards the user to the correct subpage :)

2023-02-09 17:32 UTC, Fqc301033 approved these changes

2023-02-09 17:32 UTC, Fqc301033 approved these changes

2023-02-09 18:51 UTC, wackerow approved these changes

2023-02-13 00:34 UTC, wackerow requested changes
@Buttaa As I look at this again, I'm not sure we need to link out to two different places for eth.store... We were splitting this before when the beaconcha.in/ethstore page wasn't ready yet.

I think we should just update this to just show ETH.STORE (or Beaconcha.in ETH.STORE) and link to the new URL, removing the github link. 

We can keep the `isEthStore` check here, and if true use the ETH.STORE label/link, and if not use the regalar Beaconcha.in label/link. How does that sound?

2023-02-14 19:57 UTC, wackerow approved these changes
Per our chat @Buttaa, updated to simplify this so there is only one link to the new beaconcha.in/ethstore page. Good to go from my end!

2023-03-20 12:22 UTC, merged