Fetch validatorscount from latest epoch endpoint
ethereum/ethereum-org-website pull request #9458
Opened 2023-02-09 20:11 UTC by wackerow

## Description
Currently out "total validator count" calculates an estimate based on the total effective balance, which under estimates the total validator count. The https://beaconcha.in/api/v1/epoch/latest enpoint offers `validatorscount` which fetches the actual number of validators who are active on the network (not exited or pending).

This will make the reading consistent with the Launchpad and Beaconcha.in pages, eliminate the bug where there are decimals being presented, and provide more accuracy.

Old:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/54227730/217925979-6457202f-c331-4a99-8acf-152416feeb4a.png">

New:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/54227730/217925887-234eb766-b86f-4317-866c-c8f869a1adc6.png">

2023-03-09 18:46 UTC, wackerow commented
Parallel PR open at https://github.com/ethereum/staking-launchpad/pull/602

2023-03-14 15:30 UTC, pettinarip requested changes
Looks good. One minor request to follow conventions.

2023-03-14 15:30 UTC, pettinarip commented on src/components/Staking/StakingStatsBox.tsx
> +        interface EthStoreResponse {
Define the types/interfaces outside of the component's scope.

2023-03-17 16:50 UTC, corwintines approved these changes

2023-03-17 16:50 UTC, merged