Migrated the `Bug-bounty.tsx` to Chakra components
ethereum/ethereum-org-website pull request #9475
Opened 2023-02-11 11:09 UTC by Seek4samurai

Migrated the `Bug-bounty.tsx` to Chakra components. `Emotes`, replaced `src/components/SharedStyledComponents`, and other inner components.

## Related Issue 
[Migrate pages & templates issue](https://github.com/ethereum/ethereum-org-website/issues/9353)

2023-02-11 11:11 UTC, Seek4samurai commented
Please add the `Chakra-migration` label.

2023-02-16 18:29 UTC, pettinarip requested changes
This is great @Seek4samurai, thanks for the work done here.

As a general note and for convention matters, we try to follow the following rules:
- not use of curly brackets if the value is a string
- [nice-to-have] usage of shorthand versions of the props (instead of `padding` use `p`)
- [nice-to-have] usage of chakra values as much as we can (for example, for spacing values you can check [this doc](https://chakra-ui.com/docs/styled-system/theme#spacing))

```tsx
// from this
<Box padding={"1rem 2rem"} width={"100%"}>

// to this
<Box py={4} px={8} w="full">
```

2023-02-16 18:29 UTC, pettinarip commented on src/pages/bug-bounty.tsx
> +  <Box display={"flex"} flexWrap={"wrap"} marginLeft={"2rem -1rem 3rem -1rem"}>
```suggestion
  <Box display={"flex"} flexWrap={"wrap"} margin={"2rem -1rem 3rem -1rem"}>
```

2023-02-16 18:29 UTC, pettinarip commented on src/pages/bug-bounty.tsx
> +          <Text marginBottom={"0rem"}>
```suggestion
          <Text mb={0}>
```

2023-02-16 18:29 UTC, pettinarip commented on src/pages/bug-bounty.tsx
> +import { Box, Center, Heading, Text } from "@chakra-ui/react"
import order

Lets put 3rd party imports at the top of the import list, along with the `"gatsby"` or `"react"` imports.

2023-02-17 05:46 UTC, Seek4samurai commented
Hi @pettinarip, I've updated the codebase and branch as well. Please check.

2023-03-01 20:48 UTC, pettinarip approved these changes
Hey @Seek4samurai thanks for all the work done here. Also thanks for doing those changes I requested :)

I've added a few more refactors to use more Chakra components where we were not using and fix a few minor style issues.

2023-03-07 16:19 UTC, merged