Chakra/wallets.tsx
ethereum/ethereum-org-website pull request #9500
Opened 2023-02-16 06:45 UTC by ameeetgaikwad

## Description

refactored the wallets.tsx file

## Related Issue
 #9353

2023-03-02 13:21 UTC, pettinarip requested changes
Thanks for the PR @ameeetgaikwad 

The overall result looks good but there are a few things we would like to add on this migration. Like deprecating the components from `SharedStyledComponents`.

Then, there are a few spacing differences I see, comparing it with the production version, that would be nice to cover as well.

Current implementation:
![image](https://user-images.githubusercontent.com/468158/222439483-d660883f-1a26-48c0-ad61-c5a998428ab9.png)

Production (how it should be):
![image](https://user-images.githubusercontent.com/468158/222439864-4ce773da-ad68-41b3-85e6-9db83841bbf3.png)

2023-03-04 17:01 UTC, ameeetgaikwad commented on src/pages-conditional/wallets.tsx
>  } from "../components/SharedStyledComponents"
so I should refactor `SharedStyledComponents` first?

2023-03-07 20:25 UTC, ameeetgaikwad commented on src/pages-conditional/wallets.tsx
>  } from "../components/SharedStyledComponents"
I removed the `RightColumn` and fixed the margins. Lemme know if it works or now. 

After this, I should replace these `SharedStyledComponents`  right?

2023-04-20 18:40 UTC, pettinarip approved these changes

2023-04-20 19:29 UTC, merged