[roadmap epic]: move upgrades pages
ethereum/ethereum-org-website pull request #9815
Opened 2023-03-28 15:40 UTC by jmcook1186

## Description

deletes:
`upgrades/index.md`
`upgrades/get_involved`

moves:
`upgrades/beacon-chain` --> `roadmap/beacon-chain`
`upgrades/merge` --> `roadmap/merge`
`upgrades/merge/issuance` --> `roadmap/merge/issuance`

adds appropriate redirects to `redirects.json`

## Related Issue

#9242

2023-03-29 14:56 UTC, pettinarip requested changes
One thing I notice here is that we should also move the md files for the other languages as well.

For example, in the Spanish version we will have 2 pages for the merge:
- [/es/upgrades/merge/](https://ethereumorgwebsitedev01-moveupgradespages.gatsbyjs.io/es/upgrades/merge/) - should be deleted
- [/es/roadmap/merge/](https://ethereumorgwebsitedev01-moveupgradespages.gatsbyjs.io/es/roadmap/merge/) - this one is the one we want but is not getting translated because the other one exists

I can help you making these changes @jmcook1186 (not only for Spanish but for all the other langs that have a md file for these pages).

Will let you know when its ready.

2023-03-31 08:41 UTC, jmcook1186 commented on redirects.json
> +    "fromPath": /upgrades/sharding/",
```suggestion
    "fromPath": /upgrades/sharding",
```

2023-03-31 08:42 UTC, jmcook1186 commented
yea the sharding page should be deleted from all languages, and redirected to `roadmap/danksharding`.
I'll add the redirect now.

2023-03-31 22:47 UTC, pettinarip approved these changes
Ok, I've modified the redirects a bit.

Now, per each page we are moving, I've added:
- A redirect from the root path to the English path - e.g. `/upgrades/merge` => `/en/roadmap/merge`
- A redirect to catch when the user specify the language in the path (Netlify only) - e.g. `/[lang]/upgrades/merge` => `/[lang]/roadmap/merge`

Then, I've also updated all the rest of md files (non English) to represent the same naming and structure we have for English.

2023-04-04 19:30 UTC, corwintines approved these changes

2023-04-04 19:48 UTC, merged