added taiko to the Projects working on zkEVMs
ethereum/ethereum-org-website pull request #9825
Opened 2023-03-28 22:42 UTC by seunbayo

## Description
added taiko to the Projects working on zkEVMs

## Related Issue

2023-03-31 07:45 UTC, seunbayo commented
@corwintines

2023-04-04 13:02 UTC, seunbayo commented
@jmcook1186  can you review it?

2023-04-05 14:50 UTC, corwintines requested changes
Thanks @seunbayo!

https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=feature+%3Asparkles%3A%2Ccontent+%3Afountain_pen%3A&template=suggest_layer2.yaml&title=Suggest+a+Layer+2

Need an issue to go with this listing for a layer 2. Can you fill out the above issue template for layer 2 products? After that, just link the issue in this PR. 

I've converted this to draft for now until this is done. After you link the PR, feel free to take this out of draft.

2023-04-06 22:45 UTC, d1onys1us commented on src/content/developers/docs/scaling/zk-rollups/index.md
> +- **[Taiko](https://taiko.xyz)** - _Taiko is building a fully decentralized, Ethereum-equivalent ZK-rollup._
```suggestion
- **[Taiko](https://taiko.xyz)** - _Taiko is a fully decentralized, Ethereum-equivalent ZK Rollup._
```

2023-04-06 22:59 UTC, d1onys1us commented
> Thanks @seunbayo!
> 
> https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=feature+%3Asparkles%3A%2Ccontent+%3Afountain_pen%3A&template=suggest_layer2.yaml&title=Suggest+a+Layer+2
> 
> Need an issue to go with this listing for a layer 2. Can you fill out the above issue template for layer 2 products? After that, just link the issue in this PR.
> 
> I've converted this to draft for now until this is done. After you link the PR, feel free to take this out of draft.

hey @corwintines and @seunbayo , I have filled out the form here! https://github.com/ethereum/ethereum-org-website/issues/9919

Thank you and please let me know how I can help or if anything else needs to be done.

2023-04-10 09:21 UTC, d1onys1us commented
hey @corwintines are there any changes still requested or is this good to go now? thank you :)

2023-04-10 09:22 UTC, d1onys1us approved these changes

2023-04-17 04:20 UTC, d1onys1us commented
hello @corwintines, just a friendly poke. i want to know is there anything else we need to do to merge the PR? we did create the issue, and we are on l2beat. thank you.

2023-04-20 17:47 UTC, closed without merging