Fix broken PageHero buttons on the Layer2 page
ethereum/ethereum-org-website pull request #9980
Opened 2023-04-17 18:38 UTC by pettinarip

## Description

- Fixes id attr on page's headers
- Fixes hidden overflow on PageHero buttons

The last fix covers the visual issue when you hover or focus the buttons.
![image](https://user-images.githubusercontent.com/468158/232579690-c07f79c1-8d21-4664-babb-94d601ed3205.png)
Now:
![image](https://user-images.githubusercontent.com/468158/232580376-899ec352-886d-49c5-a820-b5fa632bf9d5.png)

2023-04-25 17:23 UTC, nhsz requested changes
Thanks, asking for a small change

2023-04-25 17:23 UTC, nhsz commented on src/pages/layer-2.tsx
> +}: BoxProps & {
```
{
  children: ReactNode
  isLightGrayBg?: boolean
}
```

should be defined as an interface

2023-05-02 17:20 UTC, wackerow commented on src/pages/layer-2.tsx
> +}) => (
```suggestion
interface ContentBoxProps extends BoxProps {
  isLightGrayBg?: boolean
}
const ContentBox: React.FC<ContentBoxProps> = ({ isLightGrayBg, ...rest }) => (
```

2023-05-04 21:35 UTC, pettinarip commented on src/pages/layer-2.tsx
> +}: BoxProps & {
Agreed

2023-05-04 21:36 UTC, pettinarip commented on src/pages/layer-2.tsx
> +}) => (
Thanks!

2023-05-04 21:40 UTC, nhsz approved these changes
LGTM!

2023-05-04 22:14 UTC, corwintines approved these changes

2023-05-04 22:44 UTC, merged